feat: make it easy to get OPerationMetadata from Operation
influxdata/influxdb_iox pull request #1059
Opened 2021-03-26 21:07 UTC by NGA-TRAN

Closes #1001

Implement an own struct to return the right metadata for an operation.

@alamb Because I am not sure I am understand your implementation proposal, I commented out the old code but  keep them here until you confirm

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-03-27 12:57 UTC, alamb reviewed
Thanks for looking at this @NGA-TRAN !

2021-03-27 12:57 UTC, alamb commented on influxdb_iox_client/src/client/operations.rs
> +    pub async fn operation_metadata(&mut self, id: usize) -> management::OperationMetadata {
Rather than a new API just to fetch metadata, what would you think about returning a `ClientOperation` instead of an `Operation` in the other methods

So something like
```
    pub async fn list_operations(&mut self) -> Result<Vec<ClientOperation>> {
```

Rather than
```
    pub async fn list_operations(&mut self) -> Result<Vec<Operation>> {
```

?

2021-03-27 12:57 UTC, alamb commented on influxdb_iox_client/src/client/operations.rs
> +    pub fn new(operation: generated_types::Operation) -> Self {
Rather than `panic` perhaps this could return a `Result` with possible error.

Perhaps like
```
    pub fn try_new(operation: generated_types::Operation) -> Result<Self> {
```

2021-03-27 12:57 UTC, alamb commented on tests/end_to_end_cases/operations_api.rs
> +    let meta = operations_client.operation_metadata(id).await;
Here is the API i was hoping for:

```suggestion
    let meta = operations_client
        .get_operation(id)
        .operation_metadata(id)
        .await
        .metadata();
```

2021-03-29 19:07 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/operations.rs
> +    pub async fn operation_metadata(&mut self, id: usize) -> management::OperationMetadata {
@alamb I have added list_client_operations for what you mean because the list_operations still needs for something else but let know what you think

2021-03-29 19:07 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/operations.rs
> +    pub fn new(operation: generated_types::Operation) -> Self {
Addressed

2021-03-29 19:08 UTC, NGA-TRAN commented on tests/end_to_end_cases/operations_api.rs
> +    let meta = operations_client.operation_metadata(id).await;
Addressed

2021-03-29 19:08 UTC, NGA-TRAN commented
@alamb  I have addressed your comments. Can you have a look?

2021-03-29 19:28 UTC, carols10cents commented on influxdb_iox_client/src/client/operations.rs
> +        ClientOperation::try_new(operation).unwrap()
Should this function return `Result` too, and propagate errors it might encounter rather than panicking? So:

```suggestion
    pub async fn client_operation(&mut self, id: usize) -> Result<ClientOperation> {
        let operation = self.get_operation(id).await?;
        ClientOperation::try_new(operation)
```

2021-03-29 19:50 UTC, carols10cents requested changes
A few suggestions around returning errors rather than panicking :)

2021-03-29 19:50 UTC, carols10cents commented on influxdb_iox_client/src/client/operations.rs
> +            .map(|o| ClientOperation::try_new(o).unwrap())
So this will panic if any of these `ClientOperation::try_new` calls fail... is that what we want to happen? Or should `list_client_operations` return an `Err` if any one of these fail? Or should this `collect` all of the `Ok`s and `Err`s here and return `Result<Vec<Result<ClientOperation>>>`?

2021-03-29 20:25 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/operations.rs
> +            .map(|o| ClientOperation::try_new(o).unwrap())
@alamb what do you think. So far I only see this one use in tests but I think it will be used to list system information in the future. Maybe the last option is the best?

2021-03-29 20:25 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/operations.rs
> +        ClientOperation::try_new(operation).unwrap()
Ye, I think we should propagate the errors

2021-03-30 11:28 UTC, alamb approved these changes
I think it is looking good -- once we have cleaned up the last `unwrap()` I think it is good to go . Thanks @NGA-TRAN

2021-03-30 11:28 UTC, alamb commented on influxdb_iox_client/src/client/operations.rs
> +            .map(|o| ClientOperation::try_new(o).unwrap())
I think`list_client_operations` should return `Result<Vec<ClientOperation>>` and return an `Err` if any of the conversions fail. I don't expect such an error to happen regularly (it would most likely happen if the client and server versions were not compatible), and if it did it will likely apply to either *all* the responses or *none*. 

So I think that would end up looking like:

```
 pub async fn list_client_operations(&mut self) -> Result<Vec<ClientOperation>> {
        Ok(self
            .inner
            .list_operations(ListOperationsRequest::default())
            .await
            .map_err(Error::ServerError)?
            .into_inner()
            .operations
            .into_iter()
            .map(|o| ClientOperation::try_new(o))
            .collect()
```

2021-03-30 11:28 UTC, alamb commented on influxdb_iox_client/src/client/operations.rs
> +#[derive(Debug, Clone)]//, Serialize)]
I am not sure if we meant to leave in `//, Serialize`

2021-03-30 11:28 UTC, alamb commented on influxdb_iox_client/src/client/operations.rs
> +    pub async fn list_client_operations(&mut self) -> Result<Vec<ClientOperation>> {
Given you can get an `Operation` from a `ClientOperation` via `ClientOperation::operation()` I think it would be possible to combine `list_operations()` and `list_client_operations()`

Though we can perhaps do that as a follow on PR

2021-03-30 14:20 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/operations.rs
> +            .map(|o| ClientOperation::try_new(o).unwrap())
@alamb Your code suggestion will return Result<Vec<Result<ClientOperation>>> which is different from your text suggestion Result<Vec<ClientOperation>>.Do you mean the former or latter?

2021-03-30 14:51 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/operations.rs
> +            .map(|o| ClientOperation::try_new(o).unwrap())
I am making it  `Result<Vec<Result<ClientOperation>>>` and will change it to  `Result<Vec<<ClientOperation>>` later if that is what we want

2021-03-30 15:14 UTC, alamb commented on influxdb_iox_client/src/client/operations.rs
> +            .map(|o| ClientOperation::try_new(o).unwrap())
I think `Result<Vec<<ClientOperation>>` is what we want

2021-03-30 17:00 UTC, closed without merging

2021-03-30 17:09 UTC, NGA-TRAN commented
I have closed this one without merging it. All the work is in the new PR #1078