feat: Add support for labels API to influxdb_client
influxdata/influxdb_iox pull request #1070
Opened 2021-03-30 03:48 UTC by jeivardan

Implemented the following for labels API

- List all Labels
- Retrieve a label by ID
- Create a Label
- Update a Label
- Delete a Label

Added necessary models, examples and test.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-03-30 09:29 UTC, e-dard submitted a review, later dismissed
Thanks so much for this @jeivardan. I had a few suggestions for you.

2021-03-30 09:29 UTC, e-dard commented
@jeivardan has signed the CLA.

2021-03-30 11:27 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    pub async fn find_labels(&self) -> Result<LabelsResponse, RequestError> {
Yeah using `labels(&self)` is more appropriate, will change that.

2021-03-30 11:30 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +        let mock_server = mock("GET", format!("/api/v2/labels/{}", label_id).as_str())
Will do :)

2021-03-30 11:31 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    async fn find_labels() -> Result {
Can you please give me an example

2021-03-31 04:39 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    async fn find_labels() -> Result {
I've followed the discussion in #998

2021-04-01 14:44 UTC, carols10cents requested changes
Some small comment corrections, and I think we should support optionally listing labels by organization. Thanks!

2021-04-01 14:44 UTC, carols10cents commented on influxdb2_client/src/api/label.rs
> +    pub async fn labels(&self) -> Result<LabelsResponse, RequestError> {
This `labels` method doesn't take any parameters, but the [API docs](https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetLabels) say this route optionally takes an org id.

[The Go client provides multiple functions for listing labels](https://github.com/influxdata/influxdb-client-go/blob/7469a6aac6e56bf7d44590c659a1d4dbc46970aa/api/labels.go#L53-L76) - `GetLabels` that doesn't have any params, `FindLabelsByOrgId` that always takes an org id param (I don't think `FindLabelsByOrg` is relevant to this client right now), and those call an internal `getLabels` function that optionally takes params. I think I like that structure, what do you think? Could you please add a `labels_by_org` method and a private method that both `labels` and `labels_by_org` share?

2021-04-01 14:44 UTC, carols10cents commented on influxdb2_client/src/models/label.rs
> +    /// Organisation name
I don't think this `name` parameter is the organization name, [I think it's the label name](https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostLabels)? I could be wrong though.

```suggestion
    /// Label name
```

2021-04-01 14:44 UTC, carols10cents commented on influxdb2_client/src/models/label.rs
> +    /// Key/Value pairs associated with properties.
I think this is supposed to say:

```suggestion
    /// Key/Value pairs associated with this label.
```

2021-04-01 14:44 UTC, carols10cents commented on influxdb2_client/src/models/label.rs
> +    /// Key/Value pairs associated with properties.
Same here:

```suggestion
    /// Key/Value pairs associated with this label.
```

2021-04-03 07:10 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    pub async fn labels(&self) -> Result<LabelsResponse, RequestError> {
I too came across this while testing this API, I thought of adding it after getting some reviews and totally forgot about that.
I will add `labels_by_org` method and a private method that both labels and `labels_by_org` share.

2021-04-03 07:13 UTC, jeivardan commented on influxdb2_client/src/models/label.rs
> +    /// Key/Value pairs associated with properties.
Yeah! I'll change that

2021-04-03 07:14 UTC, jeivardan commented on influxdb2_client/src/models/label.rs
> +    /// Organisation name
It is Label name, I'll fix it

2021-04-05 13:56 UTC, carols10cents commented on influxdb2_client/src/api/label.rs
> +    async fn find_labels() -> Result {
This is actually a discussion we've had internally but haven't written down anywhere, and the codebase is definitely not internally consistent right now.

What @e-dard means is rather than using `?` in tests, use `expect` or `unwrap` and not return `Result`.

I will bring this up in our team meeting today and let you know which way we're going.

2021-04-05 13:58 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    async fn find_labels() -> Result {
Okay :)

2021-04-05 15:09 UTC, carols10cents commented on influxdb2_client/src/api/label.rs
> +    }
Ok, we decided in our meeting today that we're going to standardize on test functions not returning anything and using `expect` or `unwrap` in tests rather than `?`. So for example, this test should instead be:

```suggestion
    #[tokio::test]
    async fn labels() {
        let token = "some-token";

        let mock_server = mock("GET", format!("{}?orgID=", BASE_PATH).as_str())
            .match_header("Authorization", format!("Token {}", token).as_str())
            .create();

        let client = Client::new(&mockito::server_url(), token);

        let _result = client.labels().await;

        mock_server.assert();
    }
```

(there actually aren't any uses of `?` in these tests currently)

Please update this PR accordingly and then I'll take another look at it. I will take care of adding this convention to docs/style_guide.md and work on making the whole codebase consistent-- no need for you to go back and change past tests, just tests in this and future PRs :)

2021-04-05 15:13 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    }
okay will do that :)

2021-04-05 15:27 UTC, aakashhemadri commented on influxdb2_client/src/api/label.rs
> +    }
@carols10cents I was going to start working on a possible refactor, from data_point, write, errors splitting them into seperate files, possibly updating docs with examples -- and making sure there is a provision for having separate api versions (to accomadate v1.8 later on, if possible). Shall I drop that?

2021-04-05 18:47 UTC, carols10cents commented on influxdb2_client/src/api/label.rs
> +    }
@aakashhemadri I just [opened a PR](https://github.com/influxdata/influxdb_iox/pull/1120) with everything I was planning on doing regarding making the codebase consistent with regards to test function return types, so I'd wait til that gets merged in before starting any big reorganizing.

> I was going to start working on a possible refactor, from data_point, write, errors splitting them into seperate files, possibly updating docs with examples

That all sounds fine!

> making sure there is a provision for having separate api versions (to accomadate v1.8 later on, if possible).

We're actually not interested in having 1.8 support in this crate, given that it's called `influxdb*2*_client` :)

2021-04-05 23:19 UTC, aakashhemadri commented on influxdb2_client/src/api/label.rs
> +    }
Okayyy

2021-04-09 04:40 UTC, jeivardan commented
@carols10cents I've modified the test functions and committed, but circleci is throwing some erros in `check-flatbuffers` [circleci-error](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/4500/workflows/7bcf2c63-763a-41ae-90cb-daf3bb0e9add/jobs/9786/parallel-runs/0/steps/0-102).

2021-04-09 15:01 UTC, shepmaster commented
> some erros in `check-flatbuffers`

Yeah, that shouldn't be related to what you are doing. I think once #1164 is merged that should help avoid the problem.

2021-04-12 15:13 UTC, carols10cents requested changes
I think we should use `Option` in the private labels function rather than the special value of `""`. Could you make that change please?

2021-04-12 15:13 UTC, carols10cents commented on influxdb2_client/src/api/label.rs
> +    async fn get_labels(&self, org_id: &str) -> Result<LabelsResponse, RequestError> {
Actually I think this function should have this signature:

```suggestion
    async fn get_labels(&self, org_id: Option<&str>) -> Result<LabelsResponse, RequestError> {
```

and then `labels` should call `self.get_labels(None)` and `labels_by_org` should call `self.get_labels(Some(org_id))`. Then the `query` should only be added to the request if needed, rather than potentially sending `orgID=`.

2021-04-12 15:22 UTC, jeivardan commented on influxdb2_client/src/api/label.rs
> +    async fn get_labels(&self, org_id: &str) -> Result<LabelsResponse, RequestError> {
Sure, I'll do that!

2021-04-14 17:22 UTC, carols10cents approved these changes
Looks great now, thank you!!

2021-04-14 18:00 UTC, merged