feat: Add support for Query API to influxdb_client
influxdata/influxdb_iox pull request #1076
Opened 2021-03-30 15:48 UTC by aakashhemadri

POST /query/ast
GET   /query/suggestions
GET   /query/suggestions/{name}
POST /query/analyze
POST /query

Implemented all query APIs, needed models, tests, and examples

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-04-01 20:30 UTC, carols10cents requested changes
I found a few things I'd like to see fixed; there might be more but I keep getting pulled away to other things and I don't want to forget to submit this :) So I might have more comments next round....

2021-04-01 20:30 UTC, carols10cents commented on influxdb2_client/src/models/ast/dialect.rs
> +pub struct Dialect {
Hm, there are some fields in the spec that aren't here-- are they not supported by InfluxDB (I'm not sure)? I don't see `doubleQuote`, `encoding`, `headerRowCount`, `lineTerminators`, among others...?

2021-04-02 05:11 UTC, aakashhemadri commented on influxdb2_client/src/api/query.rs
> +//! Initate and start onboarding process of InfluxDB server.
Sure! 😅

2021-04-02 05:23 UTC, aakashhemadri commented on influxdb2_client/src/api/query.rs
> +        org_id: &str,
You are right as to both being optional, I have also looked into the C# Client, Seems to be the same as Go, just org being used. I will make this change once you give me confirmation

2021-04-02 05:25 UTC, aakashhemadri commented on influxdb2_client/src/models/ast/call_expression.rs
> +    pub arguments: Option<Vec<crate::models::ast::Expression>>,
Ah I missed this file altogether 😅

2021-04-02 05:43 UTC, aakashhemadri commented on influxdb2_client/src/api/query.rs
> +                serde_json::to_string(&query.unwrap_or_else(|| Query::new("".to_string())))
Ah your fix is cleaner :)

2021-04-02 06:06 UTC, aakashhemadri commented on influxdb2_client/src/models/ast/dialect.rs
> +pub struct Dialect {
Ah not sure about this, This is what the swagger spec generated, I assumed it was correct. Can you point me to the specification itself? I did find [this..](https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/) but can't seem to find anything else.

2021-04-05 13:40 UTC, carols10cents commented on influxdb2_client/src/api/query.rs
> +        org_id: &str,
Yes, please!

2021-04-05 13:41 UTC, carols10cents commented on influxdb2_client/src/models/ast/dialect.rs
> +pub struct Dialect {
Oh the spec is at the link in the doc comment: https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#dialect-descriptions

If this is what the Influx swagger generates though, that's fine then.

2021-04-05 15:41 UTC, carols10cents requested changes
This is getting close! Just a few more tiny little picky changes. Thanks!

2021-04-05 15:41 UTC, carols10cents commented on influxdb2_client/src/models/ast/dict_item.rs
> +    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
This rename isn't needed

2021-04-05 15:41 UTC, carols10cents commented on influxdb2_client/src/models/ast/dict_item.rs
> +    #[serde(rename = "val", skip_serializing_if = "Option::is_none")]
This rename isn't needed

2021-04-05 15:41 UTC, carols10cents commented on influxdb2_client/src/models/ast/expression.rs
> +    pub test: Option<Box<crate::models::ast::Expression>>,
I got used to reading:

```
/// Doc comment
#[annotations]
pub field: ...
```

but this one is:

```
#[annotations]
/// Doc comment
pub field: ...
```

Is there any reason for the difference or could this be made consistent with the other fields?

2021-04-05 15:41 UTC, carols10cents commented on influxdb2_client/src/models/ast/expression.rs
> +    pub call: Option<crate::models::ast::CallExpression>,
Same ordering inconsistency here

2021-04-05 15:41 UTC, carols10cents commented on influxdb2_client/src/models/query.rs
> +    /// Specifies the time that should be reported as \"now\" in the query.
Do these double quotes really need to be escaped in this doc comment? I'm guessing that was something the swagger code generator did... could you remove the escaping please?

2021-04-06 10:15 UTC, aakashhemadri commented on influxdb2_client/src/models/ast/expression.rs
> +    pub test: Option<Box<crate::models::ast::Expression>>,
Ah no just an error on my end

2021-04-08 18:52 UTC, carols10cents approved these changes
This looks great now, thank you!!

2021-04-08 18:53 UTC, merged

2021-04-08 18:57 UTC, alamb commented
Thanks @aakashhemadri !