feat: Add support for health API to influxdb_client
influxdata/influxdb_iox pull request #1172
Opened 2021-04-12 09:12 UTC by jeivardan

Get the health of an influxdb instance

Signed-off-by: jeivardan <jeivardanvenkatesh@gmail.com>

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-04-12 16:48 UTC, carols10cents requested changes
A few tiny comments. There are also integration tests now in `influxdb2_client/tests/` (I've only added some for `setup` so far); could you please create `influxdb2_client/tests/health.rs` and add at least one integration test in there please? Thanks!

2021-04-12 16:48 UTC, carols10cents commented on influxdb2_client/src/models/health.rs
> +    /// Name of the infludb instance
Not sure if this typo came from the swagger definition or not, but we should fix it in either case:

```suggestion
    /// Name of the influxdb instance
```

2021-04-12 16:48 UTC, carols10cents commented on influxdb2_client/src/models/health.rs
> +    pub status: Option<Status>,
Should `status` have `#[serde(skip_serializing_if = "Option::is_none")]` on it? Or should it be `pub status: Status` rather than an `Option`, if it will always be present?

2021-04-13 05:10 UTC, jeivardan commented on influxdb2_client/src/models/health.rs
> +    /// Name of the infludb instance
It was my mistake, I'll fix it

2021-04-13 05:11 UTC, jeivardan commented on influxdb2_client/src/models/health.rs
> +    pub status: Option<Status>,
Just now saw the API docs, status is a mandatory filed.

2021-04-13 06:08 UTC, jeivardan commented on influxdb2_client/src/models/health.rs
> +    /// Name of the infludb instance
I'll add integration test too!

2021-04-13 06:30 UTC, jeivardan commented on influxdb2_client/src/models/health.rs
> +    pub status: Option<Status>,
In order  to use Default trait in `HealthCheck` ,  I need to make my own default for the enum status since Default is not implemented for `Status`. What do you think I should return the default value? Pass or Fail?

2021-04-14 09:03 UTC, jeivardan commented on influxdb2_client/src/models/health.rs
> +    pub status: Option<Status>,
For now I've made the default value as Pass

2021-04-14 17:31 UTC, carols10cents requested changes
Two more small changes I'd like to see. Almost there!

2021-04-14 17:31 UTC, carols10cents commented on influxdb2_client/tests/health.rs
> +    client.health().await?;
Could you please add an assertion on the value that `health` returns? For example, it should have `status` with value `Status::Pass`, right?

2021-04-14 17:31 UTC, carols10cents commented on influxdb2_client/src/models/health.rs
> +            ..Default::default()
Hm, given that this is currently the only usage of `HealthCheck::default` (I think?), and that `Status` doesn't have a clear default (and `status`'s default doesn't get used in this `new` function anyway), I think in this case it would be better to not have `HealthCheck` or `Status` implement `Default`. That will make this line slightly more annoying, but not by much:

```suggestion
            message: None,
            checks: Vec::new(),
            version: None,
            commit: None,
```

Could you make that change please?

2021-04-14 18:50 UTC, jeivardan commented on influxdb2_client/tests/health.rs
> +    client.health().await?;
Yeah! 
I'll update that

2021-04-19 17:43 UTC, carols10cents approved these changes
Looks great! I made one small change -- `influxdb2_client::models::Status::Pass` implements `PartialEq` and `Debug`, so the health integration test can use `assert_eq!` rather than `assert!(matches!())` -- but otherwise, this is ready to be merged! Thank you!!

2021-04-19 18:28 UTC, merged