feat: Run query plans on the database wide executor as well
influxdata/influxdb_iox pull request #1210
Opened 2021-04-14 14:38 UTC by alamb

Follow on to https://github.com/influxdata/influxdb_iox/pull/1198 and closes https://github.com/influxdata/conductor/issues/244 where running CPU heavy queries can cause IOx to stop responding to health check queries.

# Rationale:
Some queries can take a long time to plan (e.g. some of the "metadata" queries that touch actual data"), and we would liek these queries not to prevent other API requests from being serviced.

# Changes:

- [x] Add new `Planner` structure in `influxdb_ioxd` which handles creating plans on the query execution thread pool
- [x] Update influxdb_ioxd handlers to use `Planner` rather than `SQLQueryPlanner` or `InfluxRPCPlanner` directly
- [x] Audit use of InfluxRPCPlanner and SQLPlanner in the `influxdb_ioxd` code

# Discussion

While the `Planner` structure is somewhat repetitive, wrapping the underlying `query::frontend` planners, this design has the benefit of keeping all the async / threading out of the core planning logic and isolated to the `influxdb_ioxd` module, where it is needed.

This structure should also make switching to a dedicated thread pool just for planning, if we ever want to, relatively straightforward

# Questions / Future work

I don't really have a good testing story for this PR other than "on production". I thought of tracking how many tasks got run on the dedicated executor and writing some tests to makes sure queries are planned there but I thought that would likely be brittle (the numbers of tasks would change based on changes to the underlying planners, etc) and not add sufficient testing to be worth the effort.

It seems what we really need is a system level stress test showing api responses aren't held up by query planning or execution. This is probably something we need a higher level test harness / system but I don't think we are at the point of the project to invest yet. So I am "testing on my machine" and calling it good!

As mentioned above, we also considered planning queries using a threadpool dedicated only to queries. This would ensure that some queries (e.g. metadata queries like SHOW TAG KEYS) that are often run without a DataFusion plan and are used to drive the UI could respond without waiting for slower queries to finish. Given the way tokio / DataFusion work, if we plan using the same pool as we execute on, the plans will back up behind any currently executing queries, which doesn't sound good)

In an ideal world, we would have some sort of IOx scheduler that would have a list of queries to run and only start them based on our own application logic. This would have to include some sort of periodic yield to the scheduler as well. Some day (TM)

2021-04-14 14:38 UTC, alamb commented on src/influxdb_ioxd/http.rs
> +    let executor = db.executor();
This is basically the pattern repeated throughout this PR (switch to use `Planner`)

2021-04-14 14:39 UTC, alamb commented on query/src/frontend/influxrpc.rs
> -    pub fn read_group_plan<C>(
Drive by fix: these did not need to be `pub`

2021-04-14 14:40 UTC, alamb commented on src/influxdb_ioxd/rpc/flight.rs
> +use super::super::planner::Planner;
Its not just a planner, it is a super super planner

2021-04-15 09:27 UTC, crepererum requested changes
I also agree that we need a proper stress test at some point, but that needs some design as well to balance off the implementation effort and maintenance overhead with the actual use. So I also agree that we need to postpone that.

Overall the change looks good, just some minor style / doc issues.

2021-04-15 09:27 UTC, crepererum commented on query/src/exec.rs
> +    /// This means among other things that
So what does that mean?

2021-04-15 09:27 UTC, crepererum commented on query/src/exec.rs
>      JoinError { source: ExecutorError },
Now explanation for the JOIN error does not mention the word "join" at all. That smells like loads of confusion during a debugging session.

2021-04-15 09:27 UTC, crepererum commented on src/influxdb_ioxd/planner.rs
> +/// Query planning was, at time of writing, a single threaded
This paragraph and the next one should be module-level. They have nothing to do with the actual `Planner` struct.

2021-04-15 09:27 UTC, crepererum commented on src/influxdb_ioxd/planner.rs
> +        self.exec
This pattern is basically repeated for every single function. Should probably be a declarative macro to lower maintenance burden.

2021-04-15 11:06 UTC, alamb commented on query/src/exec.rs
>      JoinError { source: ExecutorError },
I was worried that `Join` might be confused with SQL Join. I will make this error clearer.

2021-04-15 11:09 UTC, alamb commented on query/src/exec.rs
> +    /// This means among other things that
... that I am losing my mind 🥁 
Will remove

2021-04-15 11:12 UTC, alamb commented on src/influxdb_ioxd/planner.rs
> +/// Query planning was, at time of writing, a single threaded
I believe you are correct that the paragraph apply to everything in the module. However, my rationale is that since the `Planner` struct is the only real logic in this module they are very similar. In addition, I wanted to leave the comments as close to the code as possible, to maximize the chance they were seen.

I will remove the confusing and redundant last paragraph.

2021-04-15 11:17 UTC, alamb commented on src/influxdb_ioxd/planner.rs
> +        self.exec
There are three things that vary from call to call:
1.  The underlying planner struct - `SQLQueryPlanner` or `InfluxRPCPlanner`
2. The  name of the underlying planner function to call
3.  The parameters that the function needs

I agree that the repetition isn't great, but  I am not sure how to make make a single macro that covers all the cases that isn't complicated enough that any benefits to maintain the code are lost. 

If you have some ideas of how to structure this I would love to give them a try

2021-04-15 11:18 UTC, alamb commented
@crepererum Thanks for the comments! I believe I have addressed them all now. Can you take another look at this PR when you get a chance?

2021-04-15 11:38 UTC, crepererum commented on src/influxdb_ioxd/planner.rs
> +        self.exec
OK, agreed. Let's leave it as it is :)

2021-04-15 11:40 UTC, crepererum approved these changes

2021-04-15 11:57 UTC, merged