feat: wire up catalog preservation write path
influxdata/influxdb_iox pull request #1482
Opened 2021-05-12 08:42 UTC by crepererum

Required a bit of refactoring:

- Extract some observability tools from db into its own file.
- Move some observability helpers into catalog.
- Add an extra layer between DB an catalog which is the "preserved
  catalog" wrapper. This is required to make the ownership model
  somewhat sane, because during the read operations the "preserved
  catalog" is going to act on the in-mem catalog.
- Move "parquet file written" logic into catalog, so we have a single
  place where new parquet files are announced. For now this only works
  for chunks that are already known (i.e. the writing->written
  transation when coming from read buffer), however in the next PR this
  will be extended to also handle totally new parquet files during
  transaction playback.

**NOTE: This does NOT include the read path yet!**

For #1382 .

2021-05-12 08:43 UTC, crepererum commented on server/src/db.rs
> +                ("partition", "1970-01-01T00"),
@tustvold I don't really understand why that worked before, because the `str`s have to have a static lifetime.

2021-05-12 08:49 UTC, crepererum commented on server/src/db/catalog.rs
> +    fn add(
this code here was just moved from `write_chunk_to_object_store` which formally did multiple things:

1. set chunk state to "writing"
2. do the actual parquet write
3. book the "written" state into the catalog

The last part was moved into this function.

2021-05-12 08:52 UTC, crepererum commented on server/src/db/observability.rs
> +use std::sync::Arc;
The code in this file was just moved from `db.rs`, no functional change happened/intended.

2021-05-12 08:57 UTC, tustvold commented on server/src/db/catalog.rs
> +    fn add(
@alamb has previously expressed reticence about pushing lifecycle logic into the catalog, and I'm somewhat inclined to agree with him. The catalog is the accounting mechanism, not the thing that should be initiating the actual motion...

2021-05-12 08:59 UTC, crepererum commented on server/src/db/catalog.rs
> +    fn add(
Well it's technically not part of the catalog, it's part of the interface that binds the catalog to the preservation layer.

2021-05-12 13:41 UTC, alamb commented
I plan to review this this afternoon US EST time (in 4-5 hours time)

2021-05-12 17:02 UTC, alamb approved these changes
I reviewed this PR carefully. I have several stylistic and code organization change suggestions, but nothing in my mind that would prevent this PR from being merged as is.

Clearly I thought the comments were important otherwise I wouldn't have spent time writing them up :) But I want to be clear they are not required from my perspective.

2021-05-12 17:02 UTC, alamb commented on server/src/db/catalog.rs
> +
It seems to me the integration logic in this file is untested at the moment 

I know the PR description says "Also end-to-end tests (write + DB restart + read) will be added with the read-path" but I wonder if there is any value to creating some sort of "create a db, move a chunk to parquet, and then verify that the catalog has been persisted" type test before doing full on end-to-end coverage

It might make problems easier to diagnose (aka a more targeted test would fail rather than an end to end one)

2021-05-12 20:30 UTC, carols10cents reviewed
A few questions and thoughts

2021-05-12 20:30 UTC, carols10cents commented on server/src/db/observability.rs
> +        db_name: String,
Same here, I think it'd be nicer if this `db_name` was `&str` or `impl Into<String>`

2021-05-12 20:30 UTC, carols10cents commented on server/src/db/catalog.rs
> +        let storage = Storage::new(Arc::clone(&object_store), server_id, db_name.to_string());
Yes, while reading through this PR, my thought was "what if we decide the directories on object storage need to be `[server id]/iox/[db-name]` or something?" That is, the knowledge of the semantics of the object store directory structure now appears to be spread out in multiple places. Fixing that might be a bigger refactoring than this PR should do, though, I'm not sure, but this PR probably shouldn't add another place this knowledge lives.

2021-05-12 20:30 UTC, carols10cents commented on server/src/db/catalog.rs
> +        let parquet_chunk = Arc::clone(&Arc::new(parquet_chunk));
I realize you moved this line the way it was in server/src/db.rs, but... do you know why this line is creating a new `Arc`, not holding onto it, and then immediately cloning it...? I don't know of a reason why this can't be:

```suggestion
        let parquet_chunk = Arc::new(parquet_chunk);
```

2021-05-12 20:30 UTC, carols10cents commented on server/src/db/catalog.rs
> +        chunk.set_written_to_object_store(parquet_chunk).unwrap();
In its old location, this line returned an error, and now it `unwrap`s... is that intentional and desired?

2021-05-13 20:02 UTC, NGA-TRAN requested changes
My 2 main concerns about this PR:
1. As pointed out in my 3 detailed comments, I strongly oppose:
     . Using parse_location to get back metadata which will cause backward compatibility and bug-prone.
     . Moving parquet chunk created in from db.rs to catalog.rs. The code is less clean and will need to use parse_location which will cause the problem above.
     . The use of DirAndFileName. We should keep it a general Path.
2. The changes in metrics should be in different PR and I do see with the commit of #1488, there will be a huge conflict with this.

2021-05-17 07:12 UTC, crepererum commented on server/src/db/catalog.rs
> +    fn add(
So the main reason the parquet code cannot stay where it currently lives (at least not in the same method) is that we need to have to have a code-path to "replay" transaction later when we read a catalog from store. And I don't want do duplicate the two paths. There shall be one and only one section that registers "here is a new known parquet-sources chunk".

2021-05-17 09:42 UTC, crepererum commented on parquet_file/src/catalog.rs
> +    /// - return a pointer to self (e.g. using an )
fixed

2021-05-17 09:49 UTC, crepererum commented on parquet_file/src/catalog.rs
>      fn handle_action(
added docs

2021-05-17 10:03 UTC, crepererum commented on parquet_file/src/catalog.rs
> +pub struct TestCatalogState {
done

2021-05-17 10:03 UTC, crepererum commented on parquet_file/src/storage.rs
> +        // TODO: make this work w/o cloning the byte vector
file a ticket and added a commit, this is for later

2021-05-17 10:04 UTC, crepererum commented on server/src/db.rs
> +        let mut paths_and_metadata = vec![];
not relevant anymore

2021-05-17 10:05 UTC, crepererum commented on parquet_file/src/catalog.rs
> +    fn new(catalog_inner: &PreservedCatalogInner<S>) -> Self {
also added a small comment

2021-05-17 10:05 UTC, crepererum commented on parquet_file/src/catalog.rs
> +    inner: RwLock<PreservedCatalogInner<S>>,
done

2021-05-17 10:05 UTC, crepererum commented on parquet_file/src/catalog.rs
>      /// Open a new transaction.
done

2021-05-17 10:29 UTC, crepererum commented on server/src/db/observability.rs
> +        db_name: String,
not relevant anymore

2021-05-17 10:30 UTC, crepererum commented on server/src/db/catalog.rs
> +        chunk.set_written_to_object_store(parquet_chunk).unwrap();
fixed in the new patch design

2021-05-17 10:33 UTC, crepererum commented on parquet_file/src/catalog.rs
> +        db_name: String,
done

2021-05-17 10:33 UTC, crepererum commented on server/src/db.rs
> -                ReadBufferChunkTimestampError {
done

2021-05-17 10:33 UTC, crepererum commented on server/src/db/catalog.rs
> +        let parquet_chunk = Arc::clone(&Arc::new(parquet_chunk));
done

2021-05-17 12:03 UTC, crepererum commented on server/src/db/catalog.rs
> +
Added a test.

2021-05-17 12:05 UTC, crepererum commented on server/src/db/catalog.rs
> +        let storage = Storage::new(Arc::clone(&object_store), server_id, db_name.to_string());
This is now tracked under #1506, so this will be solved in a follow-up PR.

2021-05-17 12:51 UTC, alamb commented on server/src/db/catalog.rs
> +    fn add(
What about adding a level of indirection?

For example, rather than having the code for creating chunks live in the catalog state itself, perhaps you could pass a callback into the catalog such as `on_parquet_creation` and have `Db` provide an appropriate implementation

2021-05-17 13:45 UTC, crepererum commented on server/src/db/catalog.rs
> +    fn add(
I have to think about that, but honestly I'm not a big fan of callbacks since they are very prone to deadlocking and "what is actually going on here?!". So I would rather prefer a type hierarchy that somewhat reflects the mutation direction.

2021-05-17 14:03 UTC, alamb commented on server/src/db/catalog.rs
> +    fn add(
I agree it is a style preference for sure

2021-05-17 16:22 UTC, alamb approved these changes
FWIW @tustvold @NGA-TRAN and @crepererum and I had a good discussion about how to make the encoding of chunk lifecycle clearer and support better the local parquet file (re https://github.com/influxdata/influxdb_iox/issues/1400).

I think the consensus is to merge this PR in and then refactor how the states are encoded which will address most/all of the concerns from @NGA-TRAN  and myself

2021-05-17 17:47 UTC, NGA-TRAN approved these changes
We have discussed and agree on what have to do next recorded in comments and a few newly opened tickets

2021-05-17 18:01 UTC, merged