ci: verify gpg signatures of dependencies in CI
influxdata/influxdb_iox pull request #1609
Opened 2021-06-02 14:37 UTC by pierwill

Verify signatures of bazel and influxdb2.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).

2021-06-02 19:33 UTC, alamb approved these changes
Looks like a nice change to me -- thank you @pierwill

2021-06-02 19:33 UTC, alamb commented
Any comments @jacobmarble ?

2021-06-03 07:22 UTC, crepererum requested changes
`curl` (esp. during key import) should probably hardened a bit.

2021-06-03 07:22 UTC, crepererum commented on docker/Dockerfile.ci
> +RUN curl https://bazel.build/bazel-release.pub.gpg | gpg --import - \
```suggestion
RUN curl --proto '=https' --tlsv1.2 -sSf https://bazel.build/bazel-release.pub.gpg | gpg --import - \
```

To ensure:

- use HTTPS for real
- enforce a sufficient TLS version
- silent mode
- show errors if they occur
- fail on HTTP errors

Taken from https://rustup.rs/ . Similar change should be applied to all `curl` invocations.

2021-06-03 15:19 UTC, pierwill commented
git history's gotten a little weird. 😬

2021-06-03 15:52 UTC, crepererum approved these changes

2021-06-03 16:06 UTC, alamb commented
> git history's gotten a little weird. 😬
No worries -- we'll squash it all together

2021-06-03 16:15 UTC, alamb approved these changes
I tested this locally and it seems to work great. Thanks @pierwill

2021-06-03 16:20 UTC, merged