feat: Implement LayeredTracing
influxdata/influxdb_iox pull request #1681
Opened 2021-06-10 16:39 UTC by mkmik

__Rationale__

We currently use the `tracing` framework to output to both log outputs (e.g. stdout for k8s) and distributed tracing collectors (e.g. opentelemetry jaeger).

However, due to a limitation in the `tracing` SDK, we can only have one "filter" level that applies
to both logs and tracing outputs. This is unpractical because tracing collectors are designed
to receive high verbosity data (which will be then sampled within the opentelemetry library),
while logs generally are limited to the DEBUG level on production.

This PR adds a `FilteredLayer` tracing subscriber layer, that wraps a subscriber layer with a independent
filter, which can filter events goint to the wrapper subscriber layer more agressively than the global layer.

This will allow us to emit logs at INFO or DEBUG level while passing all events to opentelemetry at TRACE
level (and opentelemetry SDK will then sample the events so that only a small part will be sent to the
ot collector)

__Note__

This PR just implements the `FilteredLayer` and a test. Another PR will integrate this with
our log/tracing setup code.

2021-06-10 16:55 UTC, tustvold reviewed
Why do we want trace verbosity level for distributed tracing? I fear this will enable a large number of callsites with significant performance implications?

I'd imagine we'd use `info` spans for the stuff we'd want sent to jaeger? And possibly strip out everything below info in release builds (I believe this is what linkerd-proxy does). See [here](https://docs.rs/tracing/0.1.26/tracing/level_filters/index.html#compile-time-filters)

2021-06-10 21:41 UTC, alamb approved these changes
I think this looks good -- I think the fact there is a difference between `tracing`  and the level `trace!` makes this conversation quite confusing.

Having the ability for one stream to emit at one "level" and then tap a second stream with a more restrictive filter makes all sorts of sense to me 👍

2021-06-10 21:41 UTC, alamb commented on Cargo.toml
> +delegate = "0.5.1"
oh no! More packages! (this brings in 2 new dependencies it seems)

2021-06-10 21:41 UTC, alamb commented on src/commands/layered_tracing.rs
> +    delegate! {
I suggest we do some small copy/paste transgression here to avoid the dependency (and even longer compile times)

2021-06-10 21:41 UTC, alamb commented on Cargo.toml
> +tracing-appender = "0.1.2"
Is this one used at all? I didn't see it referenced anywhere in the code

2021-06-10 21:41 UTC, alamb commented on src/commands/layered_tracing.rs
> +        let (log_file, log_file_path) = NamedTempFile::new().expect("temp file").into_parts();
This is a very cool test --send info/error to one stream and trace/info/error to another

2021-06-10 21:51 UTC, mkmik commented on src/commands/layered_tracing.rs
> +    delegate! {
ok, I actually started with manually delegating code then "cleaned up" with the macro :-)

2021-06-10 21:58 UTC, mkmik commented on Cargo.toml
> +tracing-appender = "0.1.2"
yes, it's used in the tests

```
 let (log_file_writer, _log_guard) = tracing_appender::non_blocking(log_file);
```

opentelemetry is quite complicated. You don't pass a "writer" to it, no no; you pass a writer factory (MakeWriter).
So you cannot just pass a `&Vec<[u8]>` and call it a day; you have to plumb a shared Writer into something that can be returned multiple times by a `Fn` ... that's what `tracing_appender` does.

2021-06-10 22:04 UTC, alamb commented on Cargo.toml
> +tracing-appender = "0.1.2"
![image](https://user-images.githubusercontent.com/490673/121603081-3c053e80-ca16-11eb-83dd-47c5ee58dcb6.png)

2021-06-10 22:15 UTC, mkmik commented on src/commands/layered_tracing.rs
> +    delegate! {
done

2021-06-10 22:19 UTC, alamb commented on src/commands/layered_tracing.rs
> +    delegate! {
thank you

2021-06-10 22:37 UTC, jacobmarble requested changes

2021-06-10 22:37 UTC, jacobmarble commented on src/commands/layered_tracing.rs
> +                EnvFilter::new("info"),
When I swap the values "info" and "debug", the test fails only at line 136, but I would expect line 128 to also fail. This suggests that filters are not both receiving the same stream of trace events, but that one is filtering the other.

2021-06-10 22:38 UTC, mkmik commented on src/commands/layered_tracing.rs
> +    }
@jacobmarble btw, I noticed that these functions are not even called in my tests.

Not sure if we really need to delegate enything other than `on_event`. I'm too lazy right now to actually read all the docs and understand what those callbacks are for. Do you know?

2021-06-10 22:43 UTC, mkmik commented on src/commands/layered_tracing.rs
> +                EnvFilter::new("info"),
yes, that's how this particular test has been set up; if you want two completely independent subscribers you need to use two `FilteredLayer` (which is likely how this will be used in `tracing.rs`)

Do you think I should adapt the test to showcase that?

2021-06-10 22:54 UTC, jacobmarble commented on src/commands/layered_tracing.rs
> +    }
For delegating, the `inner` implementation should filter its own `on_event`, so it could be simply delegated.

2021-06-10 22:56 UTC, jacobmarble commented on src/commands/layered_tracing.rs
> +                EnvFilter::new("info"),
Yes, that would illustrate the goal that this is trying to reach.

2021-06-10 23:07 UTC, mkmik commented on src/commands/layered_tracing.rs
> +    }
can you please rephrase, I don't understand

2021-06-10 23:13 UTC, jacobmarble commented
Related https://github.com/tokio-rs/tracing/issues/597

2021-06-10 23:16 UTC, jacobmarble commented on src/commands/layered_tracing.rs
> +    }
Yes. Any implementation of `Layer.on_event` should filter its input. This covers situations where the callback is registered as "maybe" so that the Layer can decide whether to filter when the event is emitted.

So, just delegate it like the other methods.

2021-06-10 23:32 UTC, mkmik commented on src/commands/layered_tracing.rs
> +    }
I'm still confused; are you suggesting that we should chain the filter onto `inner` and then just delegate everything except `register_callsite` and `enabled` ?

2021-06-11 00:00 UTC, mkmik commented on src/commands/layered_tracing.rs
> +    }
An `on_event` implementation doesn't have to do it's own filtering. `tracing` won't call `on_event` if the subscriber declares its not interested in the event either by returning `Interest::never()` from `register_callsite` or by returning `false` to the call to `enabled`.

The wrapper has to do its own filtering.

2021-06-11 00:00 UTC, mkmik commented
> Related [tokio-rs/tracing#597](https://github.com/tokio-rs/tracing/issues/597)

Thanks for the link.

One of the solutions there (https://github.com/tokio-rs/tracing/issues/597#issuecomment-814507031) shows how to do the filtering explicitly by metadata level.

This PR instead delegates the checking to an EnvFilter which can apply more complex filters, like applying different levels for different rust modules.

2021-06-11 00:00 UTC, mkmik commented on src/commands/layered_tracing.rs
> +                EnvFilter::new("info"),
done PTAL

2021-06-11 00:10 UTC, mkmik commented on src/commands/layered_tracing.rs
> +            inner: delegate.and_then(filter),
@jacobmarble I found  this other trick: by chaining the filter to the delegate, I can get rid of the phantomdata and I simplify the call to `enabled`, since now the delegate itself knows when it's enabled.

2021-06-11 00:51 UTC, mkmik commented
hmm it seems that the test is still flaky despite the calls to `.flush()`

```
---- commands::layered_tracing::tests::test_independent stdout ----
thread 'commands::layered_tracing::tests::test_independent' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `["{\"timestamp\":\"\",\"level\":\"ERROR\",\"fields\":{\"message\":\"foo\"}}", "{\"timestamp\":\"\",\"level\":\"INFO\",\"fields\":{\"message\":\"bar\"}}"]`', src/commands/layered_tracing.rs:170:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2021-06-11 00:58 UTC, mkmik commented
turns out we call `tracing::subscriber::set_global_default(subscriber)?;` during e2e tests, which conflicts with testing the subcribers here

2021-06-11 02:43 UTC, mkmik commented on Cargo.toml
> +tracing-appender = "0.1.2"
ok, I traded the `tracing_appender` for `synchronized-writer` to make the test actually deterministic.

2021-06-11 02:43 UTC, mkmik commented
ok, the test was failing because the writer I was using used a background thread. Switched to a synchronized writer into a vec<u8> and simplified the test a bit.

2021-06-11 08:48 UTC, e-dard commented
This is very cool. Not going to review as you have had so much good feedback already 👍

2021-06-11 14:19 UTC, merged