test: Add a test that hitting the soft limit does not drop all chunks
influxdata/influxdb_iox pull request #1705
Opened 2021-06-11 20:49 UTC by alamb

Re https://github.com/influxdata/influxdb_iox/issues/1698 (which I thought was a bug by inspection, but seems to be fine after some testing). builds on https://github.com/influxdata/influxdb_iox/pull/1701 so draft until that is merged.

The theory was when the soft buffer limit is hit, the life cycle
manager was dropping too many chunks. However, I could not replicate this behavior but the test I prepared I thought was valuable from a "document the end to end behavior" perspective

2021-06-11 20:51 UTC, alamb commented on server/src/db/lifecycle.rs
> +            let mut chunks = chunks.into_iter();
@tustvold  and I theorized this could be the solution to the (non existent) problem, so I figured I would at least make the change 🤷

2021-06-14 18:20 UTC, carols10cents requested changes
A few little nits about comments.

I'm also concerned about the logic of this test, but it might be my lack of understanding of how unloading chunks works. Here's what I think this test is doing:

- Set a soft limit that can accommodate 10 chunks
- Write 10 chunks and validate they're all in the read buffer and object storage
- Change the soft limit to be lower
- Check until 4 are in object storage and 6 are in the read buffer and object storage

The title of this PR says "add a test that hitting the soft limit does not drop all chunks", and in the description you said you expected this test to fail-- if chunks are evicted one at a time, however (or in some number other than all atomically), I can totally see how this could happen:

- 10 chunks in read buffer
- Lower limit
- 1 chunk evicted, 9 remain: assertion fails
- 2 chunks evicted, 8 remain: assertion fails
- 3 chunks evicted, 7 remain: assertion fails
- 4 chunks evicted, 6 remain: assertion passes and the test stops! But if the assertion wasn't there, then...
- 5 chunks evicted, 5 remain
- ..etc..
- 10 chunks evicted, 0 remain -- there's the bug.

Soooo you might have a good ol' Heisenbug on your hand? Or I could be missing something :)

2021-06-14 18:20 UTC, carols10cents commented on tests/end_to_end_cases/persistence.rs
> +    // Ensure ensure that 10 chunks have been persisted
Really really sure? ;)

```suggestion
    // Ensure that 10 chunks have been persisted
```

2021-06-14 18:20 UTC, carols10cents commented on tests/end_to_end_cases/persistence.rs
> +    // Ensure ensure that only the chunks needed to hit the soft limit
Here too :)

```suggestion
    // Ensure that only the chunks needed to hit the soft limit
```

2021-06-14 18:20 UTC, carols10cents commented on tests/end_to_end_cases/persistence.rs
> +    // make sure that at least one is in object store
I don't really understand this comment... I don't see any logic here about "at least one", and sometimes there are going to be chunks in object storage and sometimes there aren't, because the `ChunkStorage` states are passed in? Is this outdated?

2021-06-14 18:36 UTC, alamb commented
> The title of this PR says "add a test that hitting the soft limit does not drop all chunks", and in the description you said you expected this test to fail-- if chunks are evicted one at a time, however (or in some number other than all atomically), I can totally see how this could happen:


That is an (amazing) observation @carols10cents. Thank you -- 🤔  given how the lifecycle manager is currently structured, I am not sure how (short of putting a hard sleep in this test) I can know when the lifecycle manager is in steady state (aka will not make any other changes given no new data). 

I think @tustvold is thinking about restructuring the lifecycle manager imminently -- I wonder if he has any thoughts about how we might 'wait for lifecycle manager to be in steady state'?

2021-06-14 18:36 UTC, alamb commented
Putting this back into draft mode until we sort out @carols10cents 's concerns

2021-06-14 18:37 UTC, alamb commented on tests/end_to_end_cases/persistence.rs
> +    // make sure that at least one is in object store
```suggestion
```

2021-06-14 18:37 UTC, alamb commented on tests/end_to_end_cases/persistence.rs
> +    // make sure that at least one is in object store
You are right -- this is some copy/pasta

2021-06-15 10:51 UTC, alamb commented
Closing subject to more thought

2021-06-15 10:51 UTC, closed without merging