feat: Add persistence windows ingestion tracking
influxdata/influxdb_iox pull request #1724
Opened 2021-06-14 21:22 UTC by pauldix

This adds a new module, persistence_windows, to the mutable buffer crate. Later PRs will add this into the mutable buffer chunk where it can be used to track when the lifecycle for persistence should be triggered.

2021-06-15 09:10 UTC, crepererum requested changes
Functionality-wise this should be OK, just some stylistic questions.

2021-06-15 09:10 UTC, crepererum commented on mutable_buffer/src/persistence_windows.rs
> +        let second_start = Utc::now();
```suggestion
        let second_start = start_time + chrono::Duration::microseconds(1);
```

No need to actually sleep here.

2021-06-15 09:10 UTC, crepererum commented on mutable_buffer/src/persistence_windows.rs
> +        received_at: Instant,
Also after reading the code, do I understand this correctly that `{min,max}_time` and `received_at` are somehow different timelines, i.e. that they don't have any relation at all and never interact with each other? That might at least be worth a comment in the docs.

2021-06-15 09:10 UTC, crepererum commented on mutable_buffer/src/persistence_windows.rs
> +    fn flush_persistable_keeps_open_and_closed() {
I'm having a bit of a hard time to read the test, esp. since modifications (e.g. adding windows, rotating, flushing) and actual checks are so interleaved. Some code comments could help, like:

1. here are the windows that we create
2. call rotate
3. now the following should hold (and why, e.g. why is the row count 2?)
4. we flush
5. now the following should hold (and why)

2021-06-15 10:49 UTC, alamb approved these changes
I think this is a good start and is mergeable as is (ideally with some of the comments addressed) and then we can improve the logic in subsequent PRs

2021-06-15 10:49 UTC, alamb commented on mutable_buffer/src/persistence_windows.rs
> +    pub fn t_flush(&self) -> Option<DateTime<Utc>> {
```suggestion
    pub fn max_persistable_timestamp(&self) -> Option<DateTime<Utc>> {
```

Maybe for explicitness?

2021-06-15 10:49 UTC, alamb commented on mutable_buffer/src/persistence_windows.rs
> +    created_at: Instant,
If possible, documenting as `///` doc comments how these fields should be interpreted would be helpful to me as well. I think @crepererum mentioned this above as well.

As I understand t, `created_at` is a measure of the wallclock time that the windows were created whereas `min_time` and `max_time` are the min and max timestamps in the data itself.

It would also help readability to explain how to interpret the `sequence_numbers` field (aka what does the `u32` key represent and what do each of the tuple values represent)

2021-06-15 10:49 UTC, alamb commented on mutable_buffer/src/persistence_windows.rs
> +    // Updates the window the the passed in range. This function assumes that sequence numbers
I probably missed it but I am slightly confused about the difference between a `sequence_id` and a `sequence_number`

2021-06-15 10:49 UTC, alamb commented on mutable_buffer/src/persistence_windows.rs
> +        std::thread::sleep(Duration::new(0, 1_000));
If you call `sleep` in the test, it means the tests will take at least 2 seconds to pass. Since the test seems to be about time arithmetic, would you think about doing something like 

```rust
        let start_time = Utc::now();
        let second_start = start_time + chrono::Duration::seconds(1);
        let first_end = start_time + + chrono::Duration::seconds(2);
...
```
which would make the tests themselves run a lot faster


In playground form: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=da525b915b03bae106493d6446e2a698

2021-06-15 22:53 UTC, pauldix commented on mutable_buffer/src/persistence_windows.rs
> +    // Updates the window the the passed in range. This function assumes that sequence numbers
`sequencer_id` which will map to a Kafka partition (or some future sequencer). I'll add some comments about the sequencer and sequence numbers.

2021-06-16 15:59 UTC, pauldix commented on mutable_buffer/src/persistence_windows.rs
> +    /// should clone all persistence windows and call this method before checking on persistable_age
I need to talk through this a bit with @tustvold. The original idea is that the lifecycle planner would clone them all and use rotate to determine which partition to select. Then once it's done that, it would grab a write lock on the partition and call rotate on the live window and use whatever value is there.

2021-06-16 17:49 UTC, tustvold commented on mutable_buffer/src/persistence_windows.rs
> +        while i != self.closed.len() {
I think the closed windows should be in order of arrival time, which makes me think `closed` could be a `Dequeue` and this efficiently pop stuff off the front.

2021-06-16 17:50 UTC, tustvold commented on mutable_buffer/src/persistence_windows.rs
> +    // The server time when this window was created. Used to determine how long data in this
`///` doc comments should be preferred

2021-06-16 17:50 UTC, tustvold commented on mutable_buffer/src/persistence_windows.rs
> +    // Updates the window with the passed in range. This function assumes that sequence numbers
Doc comments

2021-06-16 18:05 UTC, tustvold commented on mutable_buffer/src/persistence_windows.rs
> +    pub fn rotate(&mut self, now: Instant) {
It's a pretty minor thing, but it might save some headaches if we assert that this method is always called with increasing `Instant`.

2021-06-16 18:06 UTC, tustvold commented on mutable_buffer/src/persistence_windows.rs
> +            Some(n) => n.max = sequence.number,
Could maybe add an assert that the new sequence number is larger than the previous

2021-06-16 18:07 UTC, tustvold commented on mutable_buffer/src/persistence_windows.rs
> +                Some(n) => n.max = other_n.max,
Could also assert here

2021-06-16 18:14 UTC, tustvold approved these changes
Some minor nits, and I'd possibly make the datastructure a bit more defensive about panicking if it receives out of order Instant's and/or sequence numbers. Just thinking that if something does go bad in the ingest path, it'd be good to know :sweat_smile:

2021-06-16 19:18 UTC, pauldix commented on mutable_buffer/src/persistence_windows.rs
> +    // The server time when this window was created. Used to determine how long data in this
even though this struct isn't public?

2021-06-16 19:22 UTC, pauldix commented on mutable_buffer/src/persistence_windows.rs
> +    pub fn rotate(&mut self, now: Instant) {
Which would cause a panic? I assume the same effect is achieved because the comparisons against our `created_at` instants use `duration_since` which will panic if the passed in `now` is not greater than.

2021-06-16 20:19 UTC, merged