feat: Write entries to Kafka
influxdata/influxdb_iox pull request #1743
Opened 2021-06-16 18:54 UTC by carols10cents

Depends on #1675, not ready to merge yet.

2021-06-21 22:15 UTC, alamb approved these changes
Looks pretty amazing to me -- the fact you have figured out `ci/circleci: test_kafka_integration` is pretty awesome

https://circleci.com/gh/influxdata/influxdb_iox/31451?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2021-06-21 22:15 UTC, alamb commented on tests/end_to_end_cases/write_buffer.rs
> +    assert_eq!(partition_writes.len(), 2);
this is pretty cool 

The only thing I can think that might make this better would be to somehow check the contents of the write -- but since the test's primary purpose is to ensure the plumbing is hooked up this is probably fine for now

2021-06-21 22:15 UTC, alamb commented on query_tests/src/pruning.rs
> +    write_lp(db, "cpu bar=1 10").await;
It is amusing to me that these functions go from `async` to non `async` and then back to `async` --I am not trying to be snide, just observing

2021-06-21 22:15 UTC, alamb commented on server/src/db.rs
> +                let _ = write_buffer
I think @pauldix  has been thinking about changes in this area FYI

2021-06-22 09:35 UTC, crepererum requested changes

2021-06-22 09:35 UTC, crepererum commented on server/src/config.rs
> +        let write_buffer = match rules.write_buffer_connection_string.as_ref() {
That's a good question. A similar question exists for the object store (where we currently do NOT check anything at startup). So ideally _somewhere_ we have the ability to fail, but I also think that `commit_db` here is not a good spot. Currently all pre-validation logic resides in `server::init` that also somewhat drives the state machine and error tracking. I think `commit_db`should accept a pre-made `KafkaBuffer` that is constructed in `server::init`. For now I would put it after the catalog loading around here:

https://github.com/influxdata/influxdb_iox/blob/01b0fdabb7ffe9c88ed7167cebb86fdd2b771830/server/src/init.rs#L329

I will later come back to that part then and move it to a proper FSM.

2021-06-23 14:46 UTC, carols10cents commented on server/Cargo.toml
> +rdkafka = "0.26.0" # TODO: Put behind a feature?
On further thought, it probably doesn't make sense to make this a feature unless we want to have IOx binaries that aren't capable of connecting to Kafka. I was mostly thinking about compile times if you're not working on Kafka-related functionality... What do you think?

2021-06-23 14:51 UTC, mkmik commented on server/Cargo.toml
> +rdkafka = "0.26.0" # TODO: Put behind a feature?
I don't think we'll cut different flavours of the binary.

2021-06-23 15:14 UTC, carols10cents commented on server/src/config.rs
> +        let write_buffer = match rules.write_buffer_connection_string.as_ref() {
Hm so I'm not sure that `server::init` is the right place for this-- It *looks* like `server::init` assumes that all databases that have object stores will have the same object store, but my understanding was that each database could potentially be pointing to a different Kafka instance? And the server won't necessarily know the address of the Kafka instance if the server starts up with no databases, then it's asked to create a database with a connection string in its rules?

2021-06-23 15:32 UTC, carols10cents commented on server/src/config.rs
> +        let write_buffer = match rules.write_buffer_connection_string.as_ref() {
Clarified with Marco in chat-- `server::init` is for when the server is creating databases on startup, [`server::create_database`](https://github.com/influxdata/influxdb_iox/blob/01b0fdabb7ffe9c88ed7167cebb86fdd2b771830/server/src/lib.rs#L500) is where this change needs to happen for creating a database because of a gRPC request.

2021-06-23 17:59 UTC, carols10cents commented
@crepererum Ok, I've moved the write buffer creation out of the database committing, so I think this is ready for a re-review!

2021-06-24 07:22 UTC, crepererum approved these changes
Looks good, esp. thanks for the cleanup around the DB init code :+1:

2021-06-24 07:22 UTC, crepererum commented on server/src/db.rs
> +#[derive(Debug)]
:tada:

2021-06-24 12:50 UTC, merged