feat: make lifecycle partition-aware
influxdata/influxdb_iox pull request #1767
Opened 2021-06-21 13:33 UTC by tustvold

The first step of making the lifecycle policy partition-aware, follows the pattern established in #1753

2021-06-21 13:34 UTC, tustvold commented on lifecycle/src/lib.rs
> +impl std::fmt::Display for ChunkLifecycleAction {
Rather than converting to a string in the error, it seems nicer to just propagate the actual variant

2021-06-21 13:36 UTC, tustvold commented on server/src/db.rs
> +                        // TODO: Should this really be infallible?
This was a strange thing that turned up whilst making this PR. The current logic is such that it won't create files only to immediately delete them, but it will still try to drop the chunks it didn't create. I'm not sure what the desired behaviour is here, so I've opted to preserve what it was doing before.

FYI @crepererum

2021-06-21 13:42 UTC, tustvold commented on lifecycle/src/policy.rs
> +                    match LockablePartition::chunk(&partition, candidate.chunk_id) {
Something is a bit funny about the error handling here, it feels a bit silly to have to pre-validate before calling a method that does the same validation. As more of the partition-based lifecycle comes together it might become more clear how best to handle this, perhaps a lifecycle defined error enumeration or something :thinking:

2021-06-21 15:15 UTC, alamb commented
I plan to review this later today

2021-06-21 17:24 UTC, alamb approved these changes
I like this PR -- very cool.

2021-06-21 17:24 UTC, alamb commented on server/src/db.rs
> +        partition.write().drop_chunk(chunk_id)?;
in case anyone else is wondering, the "is there an outstanding lifecycle action" was moved into `partiton.rs`

2021-06-21 17:24 UTC, alamb commented on server/src/db.rs
> +                        // TODO: Should this really be infallible?
It seems to me that the new code is better (in that it won't end up leaving a newly created, empty partition, in the catalog. 

I don't understand the "infallable" comment -- this situation can happen if two transactions are racing to drop the chunk, right?

2021-06-21 17:24 UTC, alamb commented on lifecycle/src/policy.rs
> +        sort_free_candidates(&mut candidates);
It took me a while to understand why you chose to split the "determine candidates" and "do action" logic,  as doing so has introduced a lock gap *I think*.  

Is it correct to say that this PR also changes the lifecycle logic so that  as we are nearing the limits, we preferentially try and drop data that has already been persisted, and only then (if allowed via `drop_non_persisted`) move on to dropping non persisted data? If so, perhaps that could be clarified in a comment somewhere

BTW by "lock gap" I mean state of the chunks change between when the code makes a decision (under lock), releases the lock, and then actually does the work (again under lock). For example, a lifecycle action starts between the time the check if `chunk.lifecycle_action().is_some` and the actual drop. However, you appear to have handled all those cases; 

I am not sure if that is what you are talking about with "funny with error handling" but having to re-check pre-conditions after a lock gap is pretty standard.

2021-06-21 17:24 UTC, alamb commented on lifecycle/src/policy.rs
> +                                        "unexpected storage"
it is more like "lock gap" I think

2021-06-21 17:24 UTC, alamb commented on lifecycle/src/policy.rs
> +    fn check_memory(&mut self, soft_limit: usize, drop_non_persisted: bool) {
```suggestion
    fn check_memory_and_drop_chunks(&mut self, soft_limit: usize, drop_non_persisted: bool) {
```

Or maybe
```suggestion
    fn enforce_memory_limit(&mut self, soft_limit: usize, drop_non_persisted: bool) {
```

I am just thinking `check_memory` makes it sound like the code is just checking the limits, but in reality it is also attempting to free up memory as well

2021-06-21 17:25 UTC, alamb commented
I think we should also call out the improvements in the policy enforcement algorithm in the comments too

2021-06-21 17:31 UTC, tustvold commented on server/src/db.rs
> +                        // TODO: Should this really be infallible?
> I don't understand the "infallable" comment -- this situation can happen if two transactions are racing to drop the chunk, right?

The preserved catalog's logic should prevent transactions from racing with each other, so normally you wouldn't expect this to be possible. However, the logic in the transaction will won't create chunks only for them to be deleted, but will still drop what it didn't create - so this method **can** return an "expected error". The comment was more whether we are potentially masking a transaction isolation bug, by having such expected errors

2021-06-21 17:32 UTC, tustvold commented on server/src/db.rs
> +        partition.write().drop_chunk(chunk_id)?;
Oh sorry - should have highlighted that

2021-06-21 17:34 UTC, tustvold commented on lifecycle/src/policy.rs
> +        sort_free_candidates(&mut candidates);
> lock gap I think.

Yeah, I wanted to avoid holding upgradeable read locks on all the droppable chunks across the entire database, only to then drop a subset.

> I am not sure if that is what you are talking about with "funny with error handling" but having to re-check pre-conditions after a lock gap is pretty standard.

I was referring to how this method re-checks, and then the lifecycle action (e.g `LockableChunk::unload_read_buffer`) checks again. It doesn't impact correctness, just verbosity

2021-06-22 08:32 UTC, tustvold commented on lifecycle/src/policy.rs
> +    fn check_memory(&mut self, soft_limit: usize, drop_non_persisted: bool) {
I went with `maybe_free_memory`

2021-06-22 08:48 UTC, crepererum commented on server/src/db/catalog/partition.rs
> +                Ok(occupied.remove())
@tustvold sorry for being a bit late to the party, but you probably shoudn't just remove chunks that are persisted here. There's a read buffer attached that you can drop, but now the in-mem catalog and the preserved catalog our out-of-sync.

2021-06-22 08:52 UTC, crepererum requested changes
We should have a chat about the dropping, I think.

2021-06-22 08:54 UTC, tustvold commented on server/src/db/catalog/partition.rs
> +                Ok(occupied.remove())
I'll add a check for this case :+1:

2021-06-22 08:58 UTC, crepererum approved these changes
Clarified w/ @tustvold that this only drops unpersisted chunks.

2021-06-22 09:24 UTC, merged