fix: Use layered tracing
influxdata/influxdb_iox pull request #1796
Opened 2021-06-24 14:06 UTC by mkmik

2021-06-24 15:09 UTC, alamb reviewed
Can you remind me how I would test this (so that I can see logging at one level of verbosity and tracing at another)?

2021-06-24 15:09 UTC, alamb commented on trogging/src/lib.rs
> +                    .and_then(log_format_full)
this is cool

2021-06-24 15:10 UTC, alamb approved these changes
I think the code looks to do what it says, and since you are going to be the one configuring it / debugging it I kind of think "testing in production" is the best way here.

FYI @jacobmarble

2021-06-24 15:12 UTC, mkmik commented
> Can you remind me how I would test this (so that I can see logging at one level of verbosity and tracing at another)?

added an example (commands + my output) in the commit description

2021-06-24 15:14 UTC, tustvold requested changes

2021-06-24 15:14 UTC, tustvold commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
If I'm not mistaken this will enable every callsite, as FilteredLayer does not implement `Layer::enabled` can we at the very least enable a base level filter

2021-06-24 15:16 UTC, e-dard approved these changes
LGTM modulo @tustvold's comment.

2021-06-24 15:17 UTC, alamb commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
What changes are you suggesting?

2021-06-24 15:18 UTC, mkmik commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
is it really that expensive though?

I mean, once a callsite is disabled, it goes in a cache, and the cache is consulted anyway for every event. Is the event filter impl that much slower than an access in hashmap? perhaps; should we postpone the judgement if the profiler shows that we're wasting time evaluating the EnvFilter?

2021-06-24 15:22 UTC, mkmik commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
I think @tustvold  is suggesting to add a layered to the outer chain that implements
```
pub fn enabled(&self, metadata: &Metadata<'_>) -> bool {
  if metadata is in the very chatty hyper/tokio/h2 modules {
    return false;
  } 
}
```

2021-06-24 15:48 UTC, tustvold commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
This is based off my experience with adding access logging to [linkerd-proxy](https://github.com/linkerd/linkerd2-proxy/pull/601) and the concern one of the authors of tokio-tracing has about the performance of unnecessarily enabled callsites. This functionality exists for a reason.

> I mean, once a callsite is disabled, it goes in a cache, and the cache is consulted anyway for every event. Is the event filter impl that much slower than an access in hashmap?

At the very least you are adding a number of lock acquisitions to every callsite, which for futures is every time they are polled. I'm fairly certain this doesn't occur if the span is disabled. Also if memory serves most values will be formatted to strings before determination of whether the data matches filters - so you're adding a load of string allocations and formatting operations as well.

> should we postpone the judgement if the profiler shows that we're wasting time evaluating the EnvFilter?

I'd imagine it would be very hard to visalize this, as the crate is aggressively inlined. It would effectively just make codepaths slower, you wouldn't necessarily see it obviously spending time in tracing. You'd see it spending time in std::fmt and waiting on locks.

> What changes are you suggesting?

I was kind of thinking you'd add a default filter of `info`, but tbh you could also just use a [compile time filter](https://docs.rs/tracing/0.1.26/tracing/level_filters/index.html#compile-time-filters) and keep it simple

2021-06-24 16:06 UTC, mkmik commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
> This is based off my experience with adding access logging to linkerd-proxy 

my guess is that linkerd-proxy is dominated by network traffic; we're likely going to have other things eating the cpu.

> I'd imagine it would be very hard to visalize this, as the crate is aggressively inlined.
since dwarf info is used to compute the backtraces (and from the lowlevel structs I was exploring I'm sure that multiple function names can be returned for the same instruction pointer) I would expect this function to show up in the flamegraph

> I was kind of thinking you'd add a default filter of info, but tbh you could also just use a compile time filter and keep it simple

do you mean a default filter of info that drops all debug/trace calls globally or just filtering out the chatty hyper and friends?

As for the compile time filter, that's global right? We currently have `release_max_level_debug` which I plan to raise to `release_max_level_trace`.

2021-06-24 16:28 UTC, tustvold commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
> my guess is that linkerd-proxy is dominated by network traffic; we're likely going to have other things eating the cpu.

True, but burning CPU just because we can seems a bit silly :laughing: 

> As for the compile time filter, that's global right? We currently have release_max_level_debug which I plan to raise to release_max_level_trace.

Isn't trace even more verbose than debug?

2021-06-25 09:28 UTC, crepererum commented
@mkmik I think GitHub misinterpreted you "fix ..." comment in #1804.

2021-06-25 09:30 UTC, mkmik commented
Oh GH, you dummy, I get it that PRs are just issues for you, but beware your leaky abstractions because that's certainly not the right way to fix a PR!

2021-06-25 23:47 UTC, mkmik commented on trogging/src/lib.rs
> +            .with(FilteredLayer::new(
ok, implemented the "union filter", so that now this  PR passes the test we added in https://github.com/influxdata/influxdb_iox/pull/1804, which, IIUC, basically encoded your objection.

PTAL

2021-06-28 12:41 UTC, tustvold commented on trogging/src/layered_tracing.rs
> +    /// A None filter doesn't really mean "I want this event", nor it means "I want to filter this event out";
Given it's a `Vec`, why not just not add a filter to the list in such a case?

2021-06-28 12:44 UTC, tustvold commented on trogging/src/layered_tracing.rs
> +            .map(|i| match i {
`.any` might be more idiomatic and would short-circuit

2021-06-28 12:44 UTC, tustvold approved these changes
Some minor nits, would be nice to have a test of the UnionFilter also

2021-06-28 16:29 UTC, mkmik commented on trogging/src/layered_tracing.rs
> +            .map(|i| match i {
much better; thanks

2021-06-28 16:30 UTC, mkmik commented on trogging/src/layered_tracing.rs
> +    /// A None filter doesn't really mean "I want this event", nor it means "I want to filter this event out";
explained why the constructor has to keep an option, but filtered out the nones in the constructor so we don't have to do it again in at runtime

2021-06-28 16:45 UTC, merged