feat: integrate tokens into some potentially harmful API calls
influxdata/influxdb_iox pull request #1843
Opened 2021-06-30 07:36 UTC by crepererum

Closes #1746.

Tokens are generated via HMAC, so we don't need to store them all over the place.

2021-06-30 08:14 UTC, mkmik commented on src/influxdb_ioxd/rpc/management.rs
> +            .wipe_preserved_catalog(db_name, token)
wouldn't it be simpler to have `wipe_preserved_catalog` require a token (not an Option) and have the
API layer here just do something like:

```
if token.is_empty() {
    let token = self.server.preserved_catalog_token();
    info!(%token, ".....");
}

let tracker = self.
    .server
    .wipe_preserved_catalog(db_name)
.....
}
```

2021-06-30 08:16 UTC, crepererum commented on src/influxdb_ioxd/rpc/management.rs
> +            .wipe_preserved_catalog(db_name, token)
We could move this whole thing into the API layer, I don't mind.

2021-06-30 08:18 UTC, mkmik commented on token_challenge/src/hmac.rs
> +/// | `drop@table=my_table`           | Database is missing (might drop same table from another database) |
I wonder if we could simplify this further by making the token checking happen at the management API side only.
That way we could just hmac the serialized `request` and avoid risking forgetting some important parameters.

2021-06-30 08:50 UTC, crepererum commented on src/influxdb_ioxd/rpc/management.rs
> +            .wipe_preserved_catalog(db_name, token)
done

2021-06-30 09:03 UTC, mkmik commented on token_challenge/src/hmac.rs
> +        token_bytes.extend_from_slice(&mac_bytes);
in this case I'm ok with the kind manual encoding, but only because the tokens are valid only for the lifetime of a server. Otherwise in cases like this we should use an schema evolution resistent encoding, like (binary) protobuf.

2021-06-30 09:07 UTC, mkmik commented on src/influxdb_ioxd/rpc/management.rs
> +    fn check_token(&self, scope: &str, description: &str, token: String) -> Result<(), Status> {
"token" sounds too generic. cannot think of a better name though; ideally something that conveys what is for?
Perhaps some as explicit as "fat_finger_protection_token"? (and elsewhere)

2021-06-30 09:09 UTC, mkmik commented on src/influxdb_ioxd/rpc/management.rs
> +            &format!("wipe_preserved_catalog@db={}", db_name),
cool; now all we need to do is to render the `WipePreservedCatalogRequest` into a string (either as json or base64 binary encoded protobuf) and I'm happy :-)

2021-06-30 09:27 UTC, crepererum commented on token_challenge/src/hmac.rs
> +/// | `drop@table=my_table`           | Database is missing (might drop same table from another database) |
done

2021-06-30 09:29 UTC, crepererum commented on token_challenge/src/hmac.rs
> +        token_bytes.extend_from_slice(&mac_bytes);
I would have used some proper token (like JWT or PASETO) that have all this tiny features. However they tend to produce very long tokens and are polluted with features that we don't need here. So I'm sticking to the good old handmade HMAC.

2021-06-30 09:30 UTC, crepererum commented on src/influxdb_ioxd/rpc/management.rs
> +            &format!("wipe_preserved_catalog@db={}", db_name),
done (although the building of the description is not automated, but IMHO that's ok)

2021-06-30 10:03 UTC, crepererum commented on src/influxdb_ioxd/rpc/management.rs
> +    fn check_token(&self, scope: &str, description: &str, token: String) -> Result<(), Status> {
done

2021-06-30 10:23 UTC, mkmik commented on src/influxdb_ioxd/rpc/management.rs
> +        let (token, request_message) = f_token(request_message.clone());
yeah, it would have been easier if the token had to be passed via headers

2021-06-30 10:24 UTC, mkmik approved these changes
LGTM

2021-06-30 13:09 UTC, alamb reviewed
The idea is cool. As someone who is often stuck waiting on compilation, I do wonder how much extra value using HMAC for a "extra safety feature" gives us over a "pick a random string as token" type implementation

2021-06-30 13:09 UTC, alamb commented on docs/server_startup.md
> +Use that token and trigger the action again. This double check will hopefully prevent one or the other fat-fingered
👍

2021-06-30 13:26 UTC, mkmik commented
> gives us over a "pick a random string as token" type implementation

random strings that are still tied to a given operation require state right?

If it's about reusing the same random string across operations then this would only prevent fat fingering across deployments (e.g. staging vs production), which is still a good idea; This is stronger: it allows us to avoid accidentally replaying an operation even against the same database on the same server.

2021-06-30 13:32 UTC, mkmik commented
> > gives us over a "pick a random string as token" type implementation
> 
> random strings that are still tied to a given operation require state right?
> 
> If it's about reusing the same random string across operations then this would only prevent fat fingering across deployments (e.g. staging vs production), which is still a good idea; This is stronger: it allows us to avoid accidentally replaying an operation even against the same database on the same server.

Perhaps you meant just a hmac of the timestamp so we prevent accidentally replaying a command from the shell history?

2021-06-30 13:50 UTC, crepererum commented
> As someone who is often stuck waiting on compilation, I do wonder how much extra value using HMAC for a "extra safety feature" gives us over a "pick a random string as token" type implementation

If you pick a random string, you have to store it somewhere. So the API layer (or some helper that it is using) needs to store them, including some timestamp. And then if you wanna support multiple tokens to be active in parallel, you need multiple storage locations.... and in the end, you're managing a token store. Or: don't store anything at all. IMHO the HMAC impl is also quite thin and could easily be reused in other places in case we need it.

2021-06-30 13:52 UTC, crepererum commented
Regarding replay: within the validity time window, you can replay tokens (currently that window is set to 60s). If you leave that window, the token is invalid. I think that's a relatively safe protection against fat-finger-shell-history-scrollback.

2021-06-30 20:15 UTC, pauldix requested changes
Are we sure this is the right thing to do? The API needs to support deleting a database (and thus deleting the catalog). Which means doing so without having to go into the server logs. I'd prefer to have some intermediate state where something is marked as deleted and would thus not respond to writes or queries. It could then later get reaped/deleted for real after some cooldown period (like a few days). This would give an operator a period of time to "undo".

Separately, we need to add support for some basic authentication (likely via JWT tokens). It feels like that would be the correct place to do something a bit more sophisticated. But the plan even for that is kind of an all or nothing approach. You either have access to the management API (and thus dropping databases) or you don't.

2021-06-30 20:20 UTC, mkmik commented
This is only for low level disaster recovery API; a database delete operation should not require this. (This is also partially a reason why I preferred this check to happen at the management API layer for the wipe catalog call, instead of being part of internals that could accidentally end up being called by other high level operations)

2021-06-30 20:34 UTC, alamb commented
> Perhaps you meant just a hmac of the timestamp so we prevent accidentally replaying a command from the shell history?

I was mostly trying to come up with some way to avoid two new dependencies (our dependency chain is already quite distinguished). I thought HMAC was used when there were cryptographic considerations -- so what I was really trying to say was "can we use one of our many existing libraries rather than bringing in a new one"

2021-06-30 21:00 UTC, mkmik commented
Yes it's not about security. A weaker hash can be used instead (e.g. timestamp++sha256(timestamp++scope++secret) )

2021-07-01 07:52 UTC, crepererum commented
The thing though is: an HMAC is something that everyone recognizes. Using some self-built hash construction will leave every future developer wondering "what exactly did they do here?". So I would always use primitives that are established. And TBH I refuse to believe that these two mini-crates are the big issue in our dependency chain.

2021-07-01 08:49 UTC, mkmik commented
> The thing though is: an HMAC is something that everyone recognizes. Using some self-built hash construction will leave every future developer wondering "what exactly did they do here?". So I would always use primitives that are established. And TBH I refuse to believe that these two mini-crates are the big issue in our dependency chain.

What I proposed above is also very well known, it's called a MAC (https://en.wikipedia.org/wiki/Message_authentication_code); putting the key after the message means it's not collision resistant (while putting it at the beginning makes it subject to length extension attacks); HMAC solves that and other problems, which are irrelevant here (one could even argue that having a too strong crypto here could let some users accidentally rely on this crate for things it's not designed for, at least according to its crate doc).

That said, I see we're using a `hmac` library in our codebase:
```
[[package]]
name = "hmac"
version = "0.10.1"
```

not sure what the `crypto-mac` offers on top of that.

----

I think what @alamb is trying to do here (and elsewhere) is to provide a counter-pressure to avoid ending up with too many dependencies, non of which is per-se a big issue, but the accumulation of them is or could become.

I'm in two minds about that. On one hand, a lot of unit tests would be cleaner if we could use https://docs.rs/indoc/1.0.3/indoc/;  it's a small crate. On the other hand, it's not technically necessary (multiline strings will just be a bit more ugly).

----

It's quite possible that the cost of the code in this PR is actually greater than the cost of adding the dependency itself.
A possible approach would thus be to drastically simplify this PR, slightly reducing the fat-finger protection to what likely matters most: making sure that the manual admin command is delivered to the intended server.

Perhaps something as simple as this would be good enough in practice at the cost of much much less code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3bacfaee5afa1de265cdd6c60510d392

2021-07-01 10:44 UTC, alamb commented
> I think what @alamb is trying to do here (and elsewhere) is to provide a counter-pressure to avoid ending up with too many dependencies, non of which is per-se a big issue, but the accumulation of them is or could become.


Yes, this is correct. I don't really care about any individual dependency or two but since the number of dependencies seems to be a one way function (almost always up and never down) over time, we have accumulated 523 dependencies somehow (?!?!?!). 

Over time, IOx is getting saltier: Like the Dead Sea where water comes in but not out and the salt accumulates. I am just trying to slow that process don

2021-07-01 10:48 UTC, alamb commented
Another approach, if we are trying to avoid fat fingering but not require log access, would be to return the required token in the error message itself. Something like

```#
./influxdb_iox catalog wipe
ERROR: Wiping catalog is destructive. If you are sure you want to wipe the catalog of database <DBNAME> please include token <SomeTokenHere>

./influxdb_iox catalog wipe --token=<SomeTokenHere>
OK -- catalog wiped
```

Depending on what we are trying to prevent, simply creating some random number at startup (maybe changing it on success ful wipe) might be sufficient

2021-07-01 11:01 UTC, crepererum commented
> Another approach, if we are trying to avoid fat fingering but not require log access, would be to return the required token in the error message itself. 

Then you don't prevent "acting on prod while you think you're on staging" which @mkmik was concerned about.

2021-07-01 11:17 UTC, crepererum commented
> I see we're using a `hmac` library in our codebase ... not sure what the `crypto-mac` offers on top of that.

That's exactly the lib I'm using here. New versions of `hmac` depend on `crypto-mac`, it's just that we're currently (indirectly) depending on an old version that doesn't have that dependency

2021-07-01 12:10 UTC, mkmik commented
> > I see we're using a `hmac` library in our codebase ... not sure what the `crypto-mac` offers on top of that.
> 
> That's exactly the lib I'm using here. New versions of `hmac` depend on `crypto-mac`, it's just that we're currently (indirectly) depending on an old version that doesn't have that dependency

Oh sorry, I misread the cargo.lock and didn't look further.

2021-07-02 20:31 UTC, shepmaster commented
> Oh sorry, I misread the cargo.lock and didn't look further.

One tool that is useful in this world is `cargo tree`. For example, to see where `crypto-mac` comes from:

```
% cargo tree -i crypto-mac
crypto-mac v0.10.0
└── hmac v0.10.1
    └── rusoto_signature v0.46.0
```

> we have accumulated 523 dependencies somehow (?!?!?!).

One low(er) hanging branch is to investigate duplicate dependencies:

```
% cargo tree -d
```

If the team wants to reduce that, one solution is to enhance our dependencies to have compatible version ranges. It's unfortunately very common for crate maintainers to bump the version of a dependency without allowing for older versions. (e.g. they go from `foo = "0.1"` to `foo = "0.2"` when they could have also said `foo = ">= 0.1; < 0.3"`). Doubly-unfortunate, many maintainers don't test their crates with their minimum supported versions.

Another path to reduce dependencies is to default to `default-features = false`. I've started doing this by default in all my projects, but it's certainly not the common process.

2021-07-02 20:45 UTC, shepmaster commented on src/influxdb_ioxd/rpc/management.rs
> +                std::mem::swap(&mut token, &mut request_message.fatfinger_token);
This looks like `let token = mem::take(&mut request_message.fatfinger_token);`

2021-07-02 20:45 UTC, shepmaster commented on token_challenge/src/hmac.rs
> +        }
```suggestion
        ensure!(token_bytes.len() >= 8, TokenTooShort);
```

2021-07-02 20:45 UTC, shepmaster commented on token_challenge/src/hmac.rs
> +    MacError { inner: hmac::crypto_mac::MacError },
```suggestion
    #[snafu(display("Failed to verify MAC: {}", source))]
    #[snafu(context(false))]
    MacError { source: hmac::crypto_mac::MacError },
```

2021-07-02 20:45 UTC, shepmaster commented on token_challenge/src/hmac.rs
> +        }
```suggestion
        ensure!(age_seconds >= 0, FutureTokenError);
```

2021-07-02 20:45 UTC, shepmaster commented on token_challenge/src/hmac.rs
> +        }
```suggestion
        ensure!(age_seconds <= self.token_seconds as i64, ExpiredError);
```

2021-07-02 20:45 UTC, shepmaster commented on token_challenge/src/log.rs
> +        })
```suggestion
        NoTokenProvided {
            description,
            new_token,
        }.fail()
```

2021-09-29 08:36 UTC, tustvold commented
I'm going to close this as it appears to have a large number of merge conflicts now. We can resurrect this if and when this functionality becomes urgent

2021-09-29 08:36 UTC, closed without merging