feat: add parquet cache size setting to database rules
influxdata/influxdb_iox pull request #2058
Opened 2021-07-19 22:04 UTC by pauldix

This is the first part of adding the ability to use the locally attached disk as a cache for Parquet files. Follow on work will include:
* [ ] Add ParquetCache backed by an ObjectStore configured for local filesystem
* [ ] Update ParquetChunk and DbChunk to call `read_filter` with necessary information to either cache the file or download
* [ ] Plumb through some sort of locking above DbChunk that can be passed down so concurrent queries to the same chunk don't trigger simultaneous downloads
* [ ] Load ParquetCache state on startup (lists everything so it knows what is cached and has a size)

2021-07-20 07:22 UTC, crepererum commented on generated_types/protos/influxdata/iox/management/v1/database_rules.proto
> +  ParquetCacheLimit parquet_cache_limit = 17;
why not use `uint64` directly and treat `0` as "No Cache"? It's not that `0` would have any other sane semantic. In contrast, the current mapping with an additional object even has an illegal value (`Some(0)` which will not map to `Some(NonZeroUsize(0))`).

2021-07-20 07:24 UTC, crepererum requested changes

2021-07-20 07:24 UTC, crepererum commented on src/commands/database.rs
> +    pub parquet_cache_limit: Option<NonZeroUsize>,
I would prefer to use the same type (`u64`) here as in the proto configs. Sure on 64bit platforms they are usually identical, but it's totally unnecessary to let engineers wonder about the implications of the `usize <-> u64` conversion if we can just use the same type.

2021-07-20 11:48 UTC, alamb commented
>  Plumb through some sort of locking above DbChunk that can be passed down so concurrent queries to the same chunk don't trigger simultaneous downloads

FWIW I think you can do this within the cache itself (rather than having to add locks at a higher level) -- anything that makes a request for a file that does not exist is going to have to wait anyways, so it can wait on the cache layer.

2021-07-20 12:00 UTC, alamb approved these changes

2021-07-20 13:06 UTC, e-dard commented on data_types/src/database_rules.rs
> +    pub parquet_cache_limit: Option<NonZeroUsize>,
I can see a couple of issues with the suggested `target_free_disk_space` approach:

 1) it's unusual to specify a resource limit based on the total free resource amount. I don't think I've ever used another product that does that to be honest.
 2) it now puts the burden on IOx to know how to assess free space on the associated volume on all supported platforms. Perhaps not an issue in practice, but still something to consider.

The nice thing about specifying it in terms of a cache limit is that IOx can determine whether it's within the limit just by looking at the files it knows how to read and size, i.e., entirely within the "application".

@pauldix I wonder if we can just use a `u64` and have the semantics be `0` disables the cache and everything else sets it. I don't think that there is a sensible default value, so I would probably default `parquet_cache_limit` to `0` (disabled). We can use documentation to express the benefits of enabling it?

2021-07-20 13:07 UTC, e-dard reviewed
Couple of thoughts.

2021-07-20 13:41 UTC, pauldix commented on data_types/src/database_rules.rs
> +    pub parquet_cache_limit: Option<NonZeroUsize>,
`None` implies that there is no caching. The operator will have to specify a local cache directory to make caching an option even at the DB level (plan is to add this option on the first item from the list).

2021-07-20 13:43 UTC, pauldix commented
I'm fine with using a `u64` and having a `0` mean that it's disabled. I went with this route based on the Slack conversation about optional parameters yesterday. This method definitely felt a little convoluted, but it feels like we don't have consensus yet on how to deal with optional database rules settings.

2021-07-20 13:45 UTC, pauldix commented on data_types/src/database_rules.rs
> +    pub parquet_cache_limit: Option<NonZeroUsize>,
I'm inclined to agree with @e-dard. I think it'll be easier to reason about and build a system where it's just a limit. Given I was going to use the ObjectStore API as the abstraction to get to the local filesystem, it doesn't have a "how much space do you have left" call you can make. And object stores don't really have that anyway.

I think it's ok to have the operator specify this during their configuration of the system. For developers just testing it out, they won't need to because they won't need the local filesystem cache just to get started.

2021-07-20 14:53 UTC, NGA-TRAN approved these changes

2021-07-20 14:53 UTC, NGA-TRAN commented on data_types/src/database_rules.rs
> +    pub parquet_cache_limit: Option<NonZeroUsize>,
I like the idea of setting the limit. We need to have a mechanism to set aside that limit for us to use to avoid running into out-of-disk before we hit that limit and crash (or the like)

2021-07-20 15:17 UTC, alamb commented on data_types/src/database_rules.rs
> +    pub parquet_cache_limit: Option<NonZeroUsize>,
I am fine with either approach -- I just wanted to bring up a suggestion

2021-07-21 09:35 UTC, crepererum approved these changes

2021-07-21 09:42 UTC, merged