fix: Make heappy and nonheappy mutually exclusive
influxdata/influxdb_iox pull request #2356
Opened 2021-08-19 16:37 UTC by mkmik

Closes #2288

2021-08-19 16:45 UTC, alamb approved these changes
looks good to me other than potentially adding the `noheappy` as a default option

2021-08-19 16:45 UTC, alamb commented on Cargo.toml
> +noheappy = ["tikv-jemalloc-sys"]
it seems like this should be a "default" feature (aka it would be nice to get this without having to do `--features=noheappy` 🤔

2021-08-19 16:45 UTC, alamb commented on Dockerfile
> +  cargo build --target-dir /influxdb_iox/target --release --features azure,gcp,aws,jaeger,otlp,pprof,heappy && \
FYI @jacobmarble  -- not sure if you have any opinions about heappy being in the dockerfile (possibly slower but also then you can have heap profiling)

2021-08-19 16:45 UTC, alamb commented on src/main.rs
> +compile_error!("you need to pick either heappy or noheappy feature, cargo can't pick a default out of a mutually exclusive set");
❤️

2021-08-19 17:06 UTC, carols10cents commented on Cargo.toml
> +noheappy = ["tikv-jemalloc-sys"]
Yeah I would rather have CI have to have `--no-default-features --features=heappy` than to locally have to do `--features=noheappy`

2021-08-19 17:20 UTC, carols10cents commented
This does look like the best way that's possible to do this right now, aside from making a default choice for ease of development. Also I wonder if we should switch to [the new feature resolver](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver), which as I understand it, won't *directly* help with this problem, exactly, but would help if dev, build, or target-specific dependencies mess with the `unprefixed_malloc_on_supported_platforms` flag? More details: https://rust-lang.github.io/rfcs/2957-cargo-features2.html

2021-08-19 19:50 UTC, mkmik commented on Dockerfile
> +  cargo build --target-dir /influxdb_iox/target --release --features azure,gcp,aws,jaeger,otlp,pprof,heappy && \
Fwiw, we didn't notice any major slowdowns. 

I still need to compare our benchmarks with and without the heappy linked in.

2021-08-20 07:16 UTC, crepererum requested changes

2021-08-20 07:16 UTC, crepererum commented on Cargo.toml
> +noheappy = ["tikv-jemalloc-sys"]
I agree w/ the default feature.

Since `noheappy` just implies "use jemalloc unprefixed", why not call the feature `jemalloc_global` or `jemalloc_unprefixed` instead? Then the compile error in main could also explain why they both clash.

Also, we're now effectively back to what #2350 proposed feature-wise, just w/ different names.

2021-08-20 07:26 UTC, mkmik commented
The main difference is the compile time error vs runtime error

2021-08-20 08:01 UTC, crepererum commented
> The main difference is the compile time error vs runtime error

Oh, I meant to use `compile_error` in my PR :sweat_smile:

2021-08-20 09:47 UTC, mkmik commented
done:

now by default we enable the `jemalloc_replacing_malloc` (long but explicit name) and use `--no-default-features` everywhere we enable heappy. 

@crepererum PTAL

2021-08-20 10:37 UTC, crepererum approved these changes

2021-08-20 10:37 UTC, crepererum commented on src/main.rs
> +compile_error!("you need to pick either heappy or jemalloc_replacing_malloc feature, cargo can't pick a default out of a mutually exclusive set");
I'll probably remove this particular error because for valgrind we need neither of them (aka use the default system allocator).

2021-08-20 12:05 UTC, mkmik commented on src/main.rs
> +compile_error!("you need to pick either heappy or jemalloc_replacing_malloc feature, cargo can't pick a default out of a mutually exclusive set");
ok, feel free to change this in the PR that enables valgrind. I'd like to make sure we're not accidentally losing memory stats

2021-08-20 12:06 UTC, merged