feat: first step to add delete_predicate into chunk catalog
influxdata/influxdb_iox pull request #2448
Opened 2021-08-30 21:17 UTC by NGA-TRAN

Second check box of #2396 

Add delete_predicates into chunk catalog

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-08-30 21:18 UTC, NGA-TRAN commented on server/src/db/catalog/chunk.rs
> +    pub delete_predicates: Arc<Vec<Predicate>>,
@crepererum Even though this is just a draft, can you help see if this is the right place to store the delete_predicates with the chunk catalog?

2021-08-31 07:19 UTC, crepererum commented on server/src/db/catalog/chunk.rs
> +    pub delete_predicates: Arc<Vec<Predicate>>,
I wonder if we need to store them on a chunk-level instead of on a partition- or even table-level. We're likely going to store them (in the preserved catalog) on a more coarse-grained level anyway.

2021-08-31 13:37 UTC, NGA-TRAN commented on server/src/db/catalog/chunk.rs
> +    pub delete_predicates: Arc<Vec<Predicate>>,
We do want to store them on a chunk-level because them only effect on chunks before their delete time. I do not think table-level is what we want because we will unexpectedly apply them on chunks of the table that created after deletes.
Let me dig where the chunk-level info stores

2021-08-31 14:36 UTC, NGA-TRAN commented on server/src/db/catalog/chunk.rs
> +    pub delete_predicates: Arc<Vec<Predicate>>,
@crepererum To follow up our discussion, here is is[ the link](https://github.com/influxdata/influxdb_iox/blob/317a83fc50d0c9e884fe90c88676ec1cb7e2f5c5/data_types/src/partition_metadata.rs#L175t )hat defines the supported predicate and its time range. I need to convert these 3 strings into them into a [Predicate](https://github.com/influxdata/influxdb_iox/blob/7602bde850976f3447d18fa1af558d7bc2c79f79/query/src/predicate.rs#L53) that includes predicate expressions and time ranges

2021-09-03 10:09 UTC, crepererum requested changes
I think the parser needs a tiny bit more work.

TBH I'm not a huge fan of these deeply nested hand-rolled parsers and would prefer having something that forces a more structured approach (like [rowa](https://github.com/rust-analyzer/rowan) or [logos](https://github.com/maciejhirsz/logos)) or even something that works with a freestanding grammar (like [ungrammar](https://github.com/rust-analyzer/ungrammar), [pest](https://github.com/pest-parser/pest), [lalrop](https://github.com/lalrpop/lalrpop)), but I think that's something we can do in some future.

2021-09-03 10:09 UTC, crepererum commented on influxdb_line_protocol/src/lib.rs
> +    if input.contains(" or ")
You probably want something like `input.to_lowercase()` here and some lines down as well (the `AND` check).

2021-09-03 10:58 UTC, e-dard requested changes
I think overall this is looking good @NGA-TRAN! 🎉 

However, I think it's worth getting the parsing correct before we move forwards. I will send you an internal link with some test cases for the current parser.

2021-09-03 10:58 UTC, e-dard commented on influxdb_line_protocol/src/lib.rs
> +    // This is very silly and expensive
I don't think this will work correctly for all valid cases. There are some relevant line-protocol considerations:

 - tag keys can contain whitspace;
 - tag keys can contain `AND`;
 - tag keys are case sensitive.

Therefore it is possible to write the following into Cloud 2:

```
cpu,server\ AND\ abc=foo temp=100
cpu,server\ and\ abc=foo temp=300
```

This will produce two distinct time-series. In IOx we would store them as a table like this:

```
"server AND abc | server and abc | temp   | time
         foo   |          NULL  |   100  |  12345667
         NULL  |          foo   |   100  |  12345667
```

Finally, if we issue a delete with the following predicate:

```
"server AND abc" = foo
```

The **only** one row shoudl be deleted from the table.

However, I think that this logic here would result in a broken expression being built because the input would be split halfway into a tag key.

2021-09-03 10:58 UTC, e-dard commented on influxdb_line_protocol/src/lib.rs
> +///    "col= 100"  -- white space before 100
The above two are both valid expressions in InfluxDB Cloud

2021-09-03 10:58 UTC, e-dard commented on influxdb_line_protocol/src/lib.rs
> +///    "col=abc"   -- abc is not embedded in a double quote
tag values do not need to be surrounded by double quotes. For example the following predicate is valid:

inserting the following
```
cpu,server=a temp 22.3
```

and then deleting with this predicate
```
server=a
```

Should result in the data being deleted.

In actual fact, if you provided the following predicate:

```
server="a"
```

Then nothing should get deleted because the `"` characters get interpreted as literals (that is, you're saying please delete any rows with the literal value `"a"` in the column `server`.

2021-09-03 10:58 UTC, e-dard commented on influxdb_line_protocol/src/lib.rs
> +        let input = "col=123";
It might be good to DRY things up a bit here and make these into table driven tests.

2021-09-03 10:58 UTC, e-dard commented on influxdb_line_protocol/src/lib.rs
> +    pub op: String,      // either "=" or "!="
I agree with @crepererum that it might be good to make this an `enum`.

The other thing to consider here is that we need to decide where to translate the special `_measurement` and `_field` column names into the correct table name and column name respectively.

2021-09-03 13:30 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +    if input.contains(" or ")
I did convert it to lower case and discover it will make the case like this "city=Boston" wrong so I removed it :)

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/management.rs
> +        // done in the server's delete function. Should do it here at the client side instead?
I think so, too. Let me move the parser call here

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +    #[snafu(display(r#"Unable to parse delete expression with white space '{}'"#, value))]
I am not happy with this either. Let me rewrite the delete parser not using line protocol one

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +    // This is very silly and expensive
This is a very good input. Let me play with the tests you pointed me to and rewrite this parser

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +    pub op: String,      // either "=" or "!="
Yeah, the `_measurement` and `_field` need more thinking

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +///    "col= 100"  -- white space before 100
Yeah, I need to rewrite the parser

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +///    "col=abc"   -- abc is not embedded in a double quote
This is a good input, Edd

2021-09-03 14:00 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +        let input = "col=123";
Currently I make different unit tests and this one is for single expression but I think the test might be organized differently after I rewrite a new parser

2021-09-03 14:58 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +///    "col=abc"   -- abc is not embedded in a double quote
@e-dard I have read the [Flux Delete Syntax](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/), for string data type, we have to provide double quote. Here is examples:
 
Valid:
    ```
 city="Boston" -- string embedded in double quotes
 city = "Boston" -- white spaces supported
 temp=45.7  -- number no need quotes
temp = 45.6 -- white spaces supported
```

2021-09-06 05:51 UTC, NGA-TRAN reviewed
@e-dard and @crepererum 
I have refactored the code to create a clear structures to add parser at client side, as well as converting code to management API and vice versa. I have also added framework for ed-to-end tests.
There are a lot to do but I am happy this is clear enough to get reviewed and merged

2021-09-06 05:51 UTC, NGA-TRAN commented on data_types/src/job.rs
> -    Delete { delete_info: DeleteInfo },
We do not need the delete job (yet) so remove it make the code cleaner

2021-09-06 05:51 UTC, NGA-TRAN commented on data_types/src/partition_metadata.rs
> -#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
Since no Delete job is not needed, its DeleteInfo no is not needed either

2021-09-06 05:51 UTC, NGA-TRAN commented on influxdb_iox_client/src/client/management.rs
> +    ServerError(tonic::Status),
Yes, I will add more as I go. I think I will need to move some Error I out other places here, too.

2021-09-06 07:24 UTC, crepererum commented on influxdb_line_protocol/src/lib.rs
> +    if input.contains(" or ")
Wait, but what if the input contains `city=" or "`? Do you bail out?

2021-09-06 10:58 UTC, alamb commented on influxdb_line_protocol/src/delete_parser.rs
> +#![deny(rustdoc::broken_intra_doc_links, rustdoc::bare_urls)]
I wonder if we have considered (re)using any of the code from the `sqlparser` / data fusion expression parser here?



Perhaps we could do something like rewrite the delete predicates to:

```
DELETE FROM <foo> WHERE <predicate>
```

And then run the https://github.com/sqlparser-rs/sqlparser-rs parser.

This would let us be sure the same syntax for timestamps and expressions were used. 

Even if we don't do this as part of the initial PR, I think consolidating the predicate parsing / handling in a future PR would save us both confusing user behavior when delete predicate support was inconsistent with query predicates as well as a second code path to maintain. I would be happy to help work on this

2021-09-06 13:37 UTC, NGA-TRAN commented on influxdb_line_protocol/src/lib.rs
> +    if input.contains(" or ")
The parser will be redone next. I have removed all the code regarding this

2021-09-06 13:42 UTC, NGA-TRAN commented on influxdb_line_protocol/src/delete_parser.rs
> +#![deny(rustdoc::broken_intra_doc_links, rustdoc::bare_urls)]
@alamb The purpose of this refactor is exactly for that (to reuse the available parser). Beside the range timestamps that @e-dard suggested to keep them separated in the management API to avoid user to delete everything by accident, the delete predicate is not yet parsed yet and I have planned to ask you about using some available one in DF. This is just a place to plug the others in.

2021-09-07 10:31 UTC, e-dard reviewed
Looking good.

I agree with figuring out how we might leverage the other SQL parser for handling the non-time based predicates.

This PR mainly covers the management API and some initial parsing work, but it looks like it also touches on some plumbing around query nodes actually processing deletes. I think it's important to remember that when we run IOx in Cloud we will be processing deletes on the same Kafka consumption path, and those deletes will be encapsulated in Flat Buffer messages. I'm assuming that that work be handled in follow on PRs?

2021-09-07 10:31 UTC, e-dard commented on influxdb_line_protocol/src/delete_parser.rs
> +    /// represent "="
The doc string here has `///` but the fields are not public. Did you intend the fields to be public?

2021-09-07 10:31 UTC, e-dard commented on influxdb_line_protocol/src/delete_parser.rs
> +    pub fn as_str(&self) -> &'static str {
You could also implement `Display for ProvidedDeleteOp`.

2021-09-07 10:31 UTC, e-dard commented on influxdb_line_protocol/src/delete_parser.rs
> +    pub fn parse_delete(start: &str, stop: &str, predicate: &str) -> Result<Self> {
I think it would be more idiomatic to call this fallable constructor `try_new` ?

2021-09-07 10:31 UTC, e-dard commented on query/src/test.rs
> +    fn delete_predicates(&self) -> Arc<Vec<Predicate>> {
Does this need a TODO somewhere or is it redundant?

2021-09-07 13:24 UTC, NGA-TRAN commented
> when we run IOx in Cloud we will be processing deletes on the same Kafka consumption path, and those deletes will be encapsulated in Flat Buffer messages. I'm assuming that that work be handled in follow on PRs?

@e-dard : this is a good reminder especially this is my first time to look into creating new management API and Flat Buffer. I will add this in the todo list and might need some input.

2021-09-07 13:24 UTC, NGA-TRAN commented on influxdb_line_protocol/src/delete_parser.rs
> +    pub fn as_str(&self) -> &'static str {
Will do

2021-09-07 13:24 UTC, NGA-TRAN commented on influxdb_line_protocol/src/delete_parser.rs
> +    pub fn parse_delete(start: &str, stop: &str, predicate: &str) -> Result<Self> {
Good idea

2021-09-07 13:24 UTC, NGA-TRAN commented on query/src/test.rs
> +    fn delete_predicates(&self) -> Arc<Vec<Predicate>> {
This is trait function. I will add comment.

2021-09-07 13:26 UTC, NGA-TRAN commented on influxdb_line_protocol/src/delete_parser.rs
> +    /// represent "="
Good catch. Yes, public.

2021-09-07 13:42 UTC, NGA-TRAN commented on influxdb_line_protocol/src/delete_parser.rs
> +    /// represent "="
hah, I wonder why I used it as a public field somewhere already and it compiled. This is an enum and we do not need pub, @e-dard  :)

2021-09-07 14:35 UTC, e-dard approved these changes
👍

2021-09-07 15:34 UTC, crepererum approved these changes

2021-09-07 15:34 UTC, merged