fix: perf broken after Protobuf changes
influxdata/influxdb_iox pull request #2479
Opened 2021-09-07 22:29 UTC by jacobmarble

Broken at #2458

Also adding CI check to prevent regression

2021-09-08 07:11 UTC, crepererum requested changes

2021-09-08 07:11 UTC, crepererum commented on perf/perf.py
> +                'direction': 1,
IIRC you could also use a string here:

```suggestion
                'direction': 'DIRECTION_WRITE',
```

2021-09-08 07:11 UTC, crepererum commented on perf/perf.py
> +            print(response.content.decode('UTF-8'))
```suggestion
            print(response.text)
```

2021-09-08 07:11 UTC, crepererum commented on perf/perf.py
> +        got = response.content.decode('UTF-8').strip()
```suggestion
        got = response.text
```

2021-09-08 07:11 UTC, crepererum commented on .circleci/config.yml
> +    steps:
From looking at the CI results: I think we need a newer python version here. `python3` seems to default to version 3.5 which is too old. Could we at least get a 3.8?

2021-09-08 15:05 UTC, jacobmarble commented on perf/perf.py
> +            print(response.content.decode('UTF-8'))
I reverted this because it was failing with some version of Python 3.

2021-09-08 15:07 UTC, jacobmarble commented on .circleci/config.yml
> +    steps:
The CircleCI image has up to 3.7.0. I'm switching to that in the current iteration. If that doesn't work, then I'll have it install 3.9.x, which will take more time on every execution.

2021-09-09 00:21 UTC, jacobmarble commented on .circleci/config.yml
> +    steps:
So many things. Now using Python 3.8, as packaged with Ubuntu 20.04.

2021-09-09 00:30 UTC, jacobmarble commented on perf/perf.py
> +            print(response.content.decode('UTF-8'))
Python 3.8, as installed on the most recent CircleCI/Ubuntu 20.04 image, yields this error:
```
'bytes' object has no attribute 'text'
```

2021-09-09 07:09 UTC, crepererum approved these changes

2021-09-09 14:24 UTC, merged