feat: Add tag_set and tag_pairs to measurements in Data Generator
influxdata/influxdb_iox pull request #2571
Opened 2021-09-17 20:13 UTC by pauldix

This adds the ability to specify a tag_set and a collection of tag_pairs to measurements in the data generator. Tag pairs are evaluated once when the generator is created. This avoids re-running handlebars evaluations while generating data for tags that don't change value.

This commit also fixes an issue when printing the generation output to stdout while generating from more than one agent. Previously it would be garbled together.

Follow on PRs will update the tag generation code in measurement specs to be more consistent and optimized for performance. I'll be removing the restriction of using different options while using tag_set and tag_pairs. I wanted to get this in first to show the structure of what is output.

Running this from the project root will show the example output for the included schema that uses this new feature:
```
 cargo run -p iox_data_generator -- --spec ./iox_data_generator/schemas/storage_cardinality_example.toml --print
```

And a snippet of that output looks like this:
```
storage_usage_bucket_cardinality,bucket_id=1_2Q2iaNH0Y6qpCHo,env=whatever-environment-1,host=storage-0,hostname=0,node_id=0,org_id=1_00nRAqX0VxfOBEl,partition_id=1,role=storage,url=http://127.0.0.1:6060/metrics/usage gauge=721566i 1631909529018737000
storage_usage_bucket_cardinality,bucket_id=1_2Q2iaNH0Y6qpCHo,env=whatever-environment-1,host=storage-0,hostname=0,node_id=0,org_id=1_00nRAqX0VxfOBEl,partition_id=2,role=storage,url=http://127.0.0.1:6060/metrics/usage gauge=1415953i 1631909529018737000
storage_usage_bucket_cardinality,bucket_id=1_2Q2iaNH0Y6qpCHo,env=whatever-environment-1,host=storage-0,hostname=0,node_id=0,org_id=1_00nRAqX0VxfOBEl,partition_id=3,role=storage,url=http://127.0.0.1:6060/metrics/usage gauge=5762156i 1631909529018737000
```

2021-09-19 11:24 UTC, alamb reviewed
I think @shepmaster  or @carols10cents  are the best to review this change as they are most familiar with the code. 

BTW it is a follow on to https://github.com/influxdata/influxdb_iox/pull/2499 which I reviewed, so I am also happy to review if they don't have time.

2021-09-20 00:55 UTC, carols10cents requested changes
Some fixes, some guesses about what might help with the performance!

2021-09-20 00:55 UTC, carols10cents commented on iox_data_generator/src/specification.rs
> +    /// If set to true, all samples generated will include a `data_spec=[name]`
What if `include_spec_tag` is set to `Some(false)` or `None`? I actually don't see any use of `include_spec_tag` anywhere, is it something that's going to be used in the future or is it something that ended up not being needed?

This caught my eye because `Option<bool>` is fairly rare... it does happen when the semantics of "unset" are different from the semantics of "explicitly set to true" or "explicitly set to false", but it looks like this could be `bool` that defaults to `false` if not specified by using `#[serde(default)]`?

2021-09-20 00:55 UTC, carols10cents commented on iox_data_generator/src/specification.rs
> +    /// If `include_spec_tag` is set to true, eveyr point generated from this
```suggestion
    /// If `include_spec_tag` is set to true, every point generated from this
```

2021-09-20 00:55 UTC, carols10cents commented on iox_data_generator/src/measurement.rs
> +                }
Yeeeaahhh I would bet that all this string allocation is an impact on the performance... and I see `DataPoint` stores owned `String`s. I wonder if that can be changed to be `impl AsRef<str>`, which might also need a `+ 'static`, so that `DataPoint` could hold either `String` or `Arc<str>`?

2021-09-20 00:55 UTC, carols10cents commented on iox_data_generator/src/tag_set.rs
> +    pub value: Arc<String>,
Because `String`s are a pointer to bytes on the heap, and `Arc`s are a pointer to the heap, this is adding an extra layer of indirection. This can be:

```suggestion
    pub key: Arc<str>,
    pub value: Arc<str>,
```

and where you construct `TagPair`s, if you have a `String` you can do `string.as_str().into()` (deref coercion isn't being as helpful as I wish it would be here) and if you have a `&str` you can do `string_slice.into()` to get `Arc<str>`s.

I don't know if or how much this is impacting the performance, but making the change certainly can't *hurt*.

2021-11-04 13:13 UTC, carols10cents commented
I think this is superseded now by #2989, so I'm going to close it!

2021-11-04 13:13 UTC, closed without merging