WIP s3 retry
influxdata/influxdb_iox pull request #2625
Opened 2021-09-23 21:18 UTC by carols10cents

Not ready yet.

Closes #2483

2021-09-25 08:19 UTC, tustvold requested changes
I think we can avoid bringing in a new dependency, which I think would be worthwhile doing.

Perhaps it is a something for a separate PR but I wonder if we might simply improve the utility of the errors returned by the object store API, so that it is easier for the callers to determine the class of error encountered and act on it. 

In many cases the plumbing for retries already exists, e.g. the Server and Database state machines, it just doesn't have a way to introspect the error in a meaningful way and so assumes the failure is fatal.

Currently it isn't even possible from the errors to determine if the error was that the object doesn't exist! Retries aside, I think having actionable errors returned would be good, as currently they're more like stack traces... This in turn would allow callers to retry based on the policy that makes sense for them. In almost all cases I can think of non-permanent errors should just be retried indefinitely, either directly or as part of a pre-existing retry loop.

I dunno, I missed the conversations that led to this PR so feel free to ignore me, but it seems a little strange to me that retries would be implemented at this level, where there is very little context as to the operations being performed

2021-09-27 13:04 UTC, alamb approved these changes
When thinking about this PR it seems to me that combination of retries + streaming makes for the awkward API of a function that returns a stream.

I wonder if all the streaming complexity for PUT is really worth it (especially since we end up writing to tempfiles anyways). Could we make this whole thing simpler / easier to maintain by removing the API that implies we are doing streaming PUTs, make it clear we are buffering, and then just use the tempfile?



> Currently I've hardcoded the number of times a request is retried to 10. Should this be configurable via a command-line option/env var, or is this fine for now?

I think a hard coded constant is fine for now -- we can make it configurable if/when we have a need to change it. I am not sure it will need much tuning: either the request is likely to pass after the first or second retry or else it is going to fail pretty much non stop

> What logging would be useful? 

I would suggest: 
* `debug!` for: Every time a request is retried, including the error that prompted the retry
* `warn!` if the operation failed, including the number of times it was retried and the error that prompted the most recent retry

2021-09-27 13:04 UTC, alamb commented on object_store/src/aws.rs
> +        let resp = s3_request(move || {
As in it will retry the `get` from the beginning, or will simply not retry the `get` at all?

FWIW I also agree that we can postpone retrying the `get` to some future PR if/when we have evidence that it is needed

2021-09-27 13:04 UTC, alamb commented on object_store/src/aws.rs
> +    FutureRetry::new(
I am a big fan of reducing dependencies (we have over 500 already). Trading a little duplication for fewer dependencies seems like an excellent tradeoff to me

2021-09-27 13:04 UTC, alamb commented on object_store/src/aws.rs
> +    // TODO: log number of attempts?
Recommend logging at `debug!` level the number of attempts and at `info!` level on an actual failure

2021-09-27 13:04 UTC, alamb commented on object_store/src/aws.rs
> +    // TODO: make the number of retries configurable
I recommend making it a crate level `pub const` so it is clear retries are occurring and the number can be changed, but no need to make it more configurable than that

2021-09-27 13:07 UTC, alamb commented
> I dunno, I missed the conversations that led to this PR so feel free to ignore me, but it seems a little strange to me that retries would be implemented at this level, where there is very little context as to the operations being performed

@tustvold  what level would you recommend retries to be performed? If we did it at each callsite in IOx we would both duplicate a lot of code, as well as likely end up missing adding retries to some places that should have them.

The usecase for retries is "Amazon gives some sort of 500 internal error and retrying the request will succeed for some opaque and unknowable reason"

2021-09-27 13:09 UTC, alamb commented on object_store/src/lib.rs
> +    async fn put<F, S>(
it would be nice to make this docstring contain a bit more information about what `S` and `F` are, for people who are trying to use this crate and are not (yet) `futures` and rust trait experts yet

I think especially helpful would be the context that `bytes` is a function due to retries -- and that it will be called once for each attempt

2021-09-27 13:56 UTC, tustvold commented
> @tustvold what level would you recommend retries to be performed? If we did it at each callsite in IOx we would both duplicate a lot of code, as well as likely end up missing adding retries to some places that should have them.

I think we come at the same issue from two sides. The current object store API, with its asynchronous streams, request oriented design, etc... seems to me to be more of a low-level abstraction of the object store APIs as they actually are. When I call `put` request I expect it to do that - send a put request. In my mind this is a very good thing as the semantics are easily mappable onto the object store's API.

If I instead want to `WriteFile` or `WriteBytes` to object store, I would expect that to be a separate struct that would use the object store API to achieve this, with any valid retries, etc... This would avoid code duplication, whilst preserving the low level object store API for situations that need/want it. _It would also avoid the contextless retries that can be fertile ground for retry storms and similarly self-inflicted issues._

But perhaps we don't wish to keep this separation, in which case perhaps we should alter the API to make it more amenable to retries as you suggest. I don't feel particularly strongly about it, but I do feel that this PR as currently written feels a bit like there is an impedance mismatch between the API and the desired semantics

_TBC my "request changes" concerned the dependency, not necessarily the retries themselves_

2021-09-27 14:37 UTC, carols10cents commented
Ok I am seeing a number of suggestions that are smaller to do that I'm going to do as part of this PR:

- [ ] Avoid bringing in a new dependency by switching futures_retry for a `while` loop
- [ ] Revert the changes to retry `get` requests
- [ ] Change `put` requests to not do fake streaming since they're not doing real streaming anyway
- [ ] Make the `aws` method `list_objects_v2` `pub`
- [ ] Make the number of retries `pub const`
- [ ] Add logging
- [ ] Add documentation

Bigger changes that sound like they need more discussion:

- [ ] Expose more information about the semantics of the errors returned 
- [ ] Implement retry logic at a higher level

Does that sound right?

2021-09-27 14:46 UTC, carols10cents commented
Actually, I think `put` **is** doing streaming [if the length of the stream is specified](https://github.com/influxdata/influxdb_iox/blob/8e89dde85cab4d862bca0650b32b45e9e8c99ac2/object_store/src/aws.rs#L148), which it is in every non-test code scenario I can find:

- [catalog transaction files](https://github.com/influxdata/influxdb_iox/blob/8e89dde85cab4d862bca0650b32b45e9e8c99ac2/parquet_file/src/catalog/internals/proto_io.rs#L45)
- [parquet files](https://github.com/influxdata/influxdb_iox/blob/8e89dde85cab4d862bca0650b32b45e9e8c99ac2/parquet_file/src/storage.rs#L221)
- [database rules](https://github.com/influxdata/influxdb_iox/blob/8e89dde85cab4d862bca0650b32b45e9e8c99ac2/iox_object_store/src/lib.rs#L591)

2021-09-27 15:15 UTC, alamb commented
> The current object store API, with its asynchronous streams, request oriented design, etc... seems to me to be more of a low-level abstraction of the object store APIs as they actually are. When I call put request I expect it to do that - send a put request. In my mind this is a very good thing as the semantics are easily mappable onto the object store's API.

@tustvold  -- I agree with this assessment.

However, when I use an object store  and say `put` I expect it to do what i ask or else return an error of either
1.  I did something wrong
2. there is something fundamentally wrong with the service 

Transient 500 errors from AWS that will succeed if you rerun them do not fall into this category. I don't think handling such errors should *not* be done in IOx logic itself which is complicated enough without having to account for transient object store failures. It would be ideal if AWS did this itself but as nonsense such as https://github.com/influxdata/influxdb_iox/issues/2483 illustrates, they put it back to their clients to deal with

Are you primarily concerned with the extra `Fn()` stuff that is added to the APIs?

2021-09-27 15:18 UTC, tustvold commented
> Actually, I think put is doing streaming if the length of the stream is specified, which it is in every non-test code scenario I can find:

In all those examples though we have already hydrated the entire payload into a cheaply-cloneable Bytes array? I.e. the streaming is not necessary. TBC I like the streaming APIs, and they will be very useful for avoiding hydrating entire parquet files into memory, etc... and this was why I suggested what I did, but perhaps I've just muddied the water and we can add that later.

> Make the aws method list_objects_v2 pub

I meant more expose the semantics as the public API across all object stores, definitely something for a future PR though

> Bigger changes that sound like they need more discussion that I can make new issues for but won't be addressing for this PR:

I think this is sensible

> Transient 500 errors from AWS that will succeed if you rerun them do not fall into this category. I don't think handling such errors should not be done in IOx logic itself which is complicated enough without having to account for transient object store failures

I agree with this entirely, as written we handle these failures in both the AWS client and then also have to handle them in IOx as we can't adequately express the context of how long to retry for. If the get request corresponds to loading a parquet file for query, we want to try a couple of times and then bail out with an error to the client, if instead we are loading the database rules for a database we don't want to bail out ever, just keep retrying until we succeed

2021-09-27 15:59 UTC, alamb commented
@tustvold and I had a nice face to face  chat. I think the consensus is that the extra complexity required to support an streaming API and retries strikes us both as "not good" but the various ways we can think to improve the situation all require substantial effort that is hard to justify at this time

Given how important the retry feature is to IOx's resilience, our suggestion is to:
1. Go with the approach in this PR
2. Change the number of retries from 10 to 3 (to minimize request amplification)
3. Put a note in the backlog (maybe an issue, maybe not) that some "higher level" APIs ('put file' or 'put from memory') might make the crate easier to work with than the lower level 'put data from a stream that comes from a generator function'.

FWI @carols10cents

2021-09-27 16:01 UTC, carols10cents commented
> the various ways we can think to improve the situation all require substantial effort that is hard to justify at this time

> In all those examples though we have already hydrated the entire payload into a cheaply-cloneable Bytes array?

What if `put` takes a cheaply-cloneable `Bytes` array?

2021-09-27 17:37 UTC, carols10cents commented on object_store/src/aws.rs
> +        let resp = s3_request(move || {
Filed https://github.com/influxdata/influxdb_iox/issues/2642 for GET requests.

2021-09-27 18:30 UTC, carols10cents commented
Ok, I think this is ready for rereview. I also ran the integration tests with AWS, Google, and Azure locally and all passed ✅

2021-09-27 18:37 UTC, carols10cents commented
And I've filed https://github.com/influxdata/influxdb_iox/issues/2643 for tracking enabling retrying at a higher abstraction level.

2021-09-27 20:09 UTC, alamb approved these changes
Looks great to me -- thank you @carols10cents  -- all of my original comments were addressed (very well!). It probably makes sense to give @tustvold  a chance to review tomorrow if he would like to

2021-09-27 20:09 UTC, alamb commented on object_store/src/lib.rs
> +    async fn put(&self, location: &Self::Path, bytes: Bytes) -> Result<(), Self::Error>;
So the idea here is that since we currently have no actual streaming write usecase (aka all writes are either from a file or an in memory buffer we can simplify the API and just take `Bytes`)? If so I like it 👍

2021-09-27 20:09 UTC, alamb commented on server/src/db.rs
> +            .put_parquet_file(path, Bytes::new())
it is so much nicer to read ❤️

2021-09-27 20:09 UTC, alamb commented on object_store/src/gcp.rs
> -        let temporary_non_streaming = bytes
FYI @mkmik  -- the interface is simplified and now we don't need to buffer locally as well

2021-09-27 20:09 UTC, alamb commented on object_store/src/aws.rs
> +pub const MAX_NUM_RETRIES: u32 = 3;
👍

2021-09-27 20:09 UTC, alamb commented on object_store/src/aws.rs
> +/// If the executed `Future` returns a 5xx server error, this function will wait an amount of
👍

2021-09-27 20:09 UTC, alamb commented on object_store/src/aws.rs
> +                    let wait_time = Duration::from_millis(2u64.pow(attempts) * 50);
the retry times appear to be `50ms`, `100ms` and `200ms` which seems reasonable for the first try. Making it 100 (for `100ms`, `200ms` and `400ms`) might be ok too but that is just a hunch. 

I suggest making the `50` a module level constant as well

2021-09-27 20:21 UTC, carols10cents commented on object_store/src/lib.rs
> +    async fn put(&self, location: &Self::Path, bytes: Bytes) -> Result<(), Self::Error>;
You got it dude!

2021-09-27 20:39 UTC, alamb commented on object_store/src/lib.rs
> +    async fn put(&self, location: &Self::Path, bytes: Bytes) -> Result<(), Self::Error>;
![full-house-michelle-tanner](https://user-images.githubusercontent.com/490673/134981752-e6a86a4e-f480-45e5-b7fa-821e4e5d2ff8.gif)

🤣

2021-09-29 12:27 UTC, merged

2021-09-29 12:33 UTC, alamb commented
🎉