feat: compact_object_store_chunks - initial implementation that also list steps to complete it
influxdata/influxdb_iox pull request #3156
Opened 2021-11-18 15:15 UTC by NGA-TRAN

This is the first part of  #3089. The function is available but only step 1 is implemented and tested. Step 2-4 will be in the following PRs

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-11-18 15:24 UTC, NGA-TRAN commented on server/src/db.rs
> +            let chunks = vec![];
This will be done after all todos inside `compact_object_store_chunks(partition, chunks)` completed

2021-11-19 09:41 UTC, crepererum reviewed
Needs style and test changes, but I think overall that's a good start from where we can piece-by-piece add the remaining functionality + tests (like partition/db checkpoints and delete predicates, ...).

2021-11-19 09:41 UTC, crepererum commented on lifecycle/src/policy.rs
> +            // This is just a trait function that this test may not need
if you don't need it, just put `unimplemented!("some reason")` in there.

2021-11-19 09:41 UTC, crepererum commented on server/src/db/catalog/partition.rs
> +    pub fn contiguous_object_store_chunks(&self, chunk_orders: &BTreeSet<ChunkOrder>) -> bool {
This function is complex enough to demand a unit test.

2021-11-19 09:41 UTC, crepererum commented on server/src/db/catalog/partition.rs
> +                if !chunk_orders.contains(&order) && chunk_orders.range(order..).count() > 0 {
`chunk_orders.range(order..).count() > 0` seems like a really costly check just to determine if there's anything at/after `order` within `chunk_order`.

You could probably get the last element once (before iterating over `chunks`):

```rust
let last_element: Option<ChunkOrder> = chunk_orders.iter().rev().next();
```

and then just compare that:

```rust
last_element.map(|o| order <= o).unwrap_or(false)
```

2021-11-19 09:41 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +)> {
Please use a struct here, esp. since the tuple elements are not strongly-typed (e.g. `u64` could be anything). Always prefer a struct over a tuple + docs. Performance-wise they are the same btw.

2021-11-19 09:41 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +            chunk.set_compacting_object_store(registration)?;
I'm pretty sure we have this bug in other places as well, but whenever this state transition fails (e.g. at the third chunk) you might have some chunks already in the new lifecycle (e.g. the first two chunks). This lifecycle action will never be cleaned and the chunks are in this state forever. So ideally we would abort the lifecycle action here as well.

2021-11-19 09:41 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +    let chunk_id = ChunkId::new();
@tustvold Since we've talked about it: it's perfectly fine to create freestanding chunk IDs w/o involving the in-mem catalog.

2021-11-19 09:41 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +        assert!(compact_non_persisted_chunks.is_err());
please check the error variant to string repr.

2021-11-19 09:41 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +        // test 2: persisted non persisted chunks
Could you please split this into multiple test functions? I find "series-style" tests quite hard to reason about.

2021-11-19 19:22 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +            chunk.set_compacting_object_store(registration)?;
This is a good point. I think this action is needed to let other conflicting processes not change these chunks. However, we have not tried to change the action back after we are done. In this case, if it succeeds, all chunks will be dropped and we do not need to do anything. However, if it fails, then we have to set the action to the chunks' original ones.

What do you think if I create a ticket to handle setting the action to its stage before compacting/persisting for not only this case but for all available code that we believe hitting this bug? @crepererum and @tustvold

2021-11-19 19:23 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    let chunk_id = ChunkId::new();
Any action for me here or this message is for @tustvold only?

2021-11-19 19:23 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    // Todo: ask Marco if this cleanup_lock is needed
@crepererum See question above

2021-11-19 19:43 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +            chunk.set_compacting_object_store(registration)?;
There is already code to handle this - https://github.com/influxdata/influxdb_iox/blob/main/lifecycle/src/policy.rs#L412

There has been discussion around removing the need for this loop as a performance optimisation, but it hasn't been a priority.

2021-11-19 20:18 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +            chunk.set_compacting_object_store(registration)?;
> removing the need for this loop as a performance optimisation

@tustvold : Can you be clearer what `this loop` means? Do I need any action here?

2021-11-19 20:32 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +            chunk.set_compacting_object_store(registration)?;
> `this loop`

The code loops through every chunk looking for failed lifecycle actions, it would be nice to detect the failure as a consequence of some handle being dropped and enqueue recovery at "source". This would eliminate the need to go looking for failed jobs. The main reason it was implemented this way is to allow for backoff, but backoff could be achieved in other ways.

>  Do I need any action here

No action needed, if it shows up in a profile we can look into then :smile:

2021-11-19 20:59 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +            chunk.set_compacting_object_store(registration)?;
Sounds good. In this specific case we need this loop to check for OS chunks and get their chunk order anyway.

2021-11-19 21:21 UTC, NGA-TRAN commented
@crepererum I have addressed all you comments.
@tustvold : you have to review this first thing Monday morning or I will bug you 😄 
I need this PR in to have the following pieces go easier

2021-11-22 08:59 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +    let chunk_id = ChunkId::new();
This was only meant to be an FYI, nothing actionable :)

2021-11-22 09:04 UTC, crepererum requested changes
The DB clean-up lock needs to be moved a bit.

2021-11-22 09:04 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +    // Todo: ask Marco if this cleanup_lock is needed
Yes, and I think you're not holding it long enough here. The lock MUST be acquired BEFORE you store a parquet file and MUST be released AFTER you completed the preserved catalog transaction. Otherwise the "cleanup parquet files"-background-worker might just delete the parquet file that you are about to add to the catalog.

2021-11-22 11:07 UTC, tustvold reviewed
Looks good to me, some minor nits.

2021-11-22 11:07 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +    // Todo: this as copied from persist.rs and should be revived to match the needs here
I think you can just use `make_db` here which calls `TestDb::builder().build().await`.

These tests don't need to be overriding the late_arrive_window_seconds as compacting object store is not concerned with such concepts. By extension I think it doesn't need the time provider, as Wall time has no bearing on its behaviour. 

`worker_backoff_millis` is just a hack to stop the lifecycle policy interfering and starting compactions, etc... in parallel - but I think for these tests there is unlikely to be anything to trigger such behaviour and so you might get away without it

2021-11-22 11:07 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +        time.inc(late_arrival);
All this stuff about time providers and late arrival is not needed here, as we aren't concerned with persisting unpersisted data (which must have been in-memory for late_arrival_seconds)

2021-11-22 11:07 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +        // todo: Need to ask Marco why there is no handle created here
Legacy comment?

2021-11-22 11:07 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +            .contains("Cannot compact the provided persisted chunks. They are not contiguous"));
Would be good to print the error string on assertion failure

2021-11-22 11:10 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +    let _partition = partition.into_data().partition;
Could also use `std::mem::drop(partition)` or simply leave it to exiting the scope of the function to drop the lock

2021-11-22 15:17 UTC, crepererum approved these changes

2021-11-22 15:17 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +        {
:+1:

2021-11-22 15:25 UTC, merged

2021-11-22 15:41 UTC, NGA-TRAN commented
@tustvold 
Hah: I forgot to remove "ataumerge" and kodiak has merged it after it got an approval. I am addressing your comments and they will go with my next PR which might include new pieces

2021-11-22 18:45 UTC, NGA-TRAN reviewed
ALl @tustvold 's comments have been addressed in #3183