feat: update os compacted chunk in both in memory and preserved catalog
influxdata/influxdb_iox pull request #3252
Opened 2021-11-29 20:17 UTC by NGA-TRAN

Another piece of #3089 

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-11-29 20:22 UTC, NGA-TRAN reviewed
@tustvold and @crepererum : these are the last 2 pieces of the compact_os_chunks puzzle. My next step is to add the rest of the tests

2021-11-29 20:22 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +            //   . Add the new created os_chunk in the in-memory catalog
@crepererum : Since we need the delete predicates for updating the preserve catalog, I think we need to update the in-memory catalog before the preserved catalog to avoid loosing delete predicates due to lock gaps. Let me know if this is feasible solution

2021-11-30 10:14 UTC, tustvold requested changes
This drops chunks from the in-memory catalog before updating the preserved catalog, as this latter operation is fallible we either need some way to rollback the changes to the in-memory catalog or to perform the operations in the other order.

I've tried to explain how this might work, but it might be easiest to talk through how to do this synchronously

2021-11-30 10:14 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +    transaction.commit().await.context(CommitError)?;
You need to call `handle.flush` if the transaction commits - otherwise nothing actually gets flushed from the mailbox :laughing: 

FWIW I don't think it is necessary to flush pending deletes from the mailbox, as this operation doesn't update any of the checkpointing information, but I guess it can't hurt

2021-11-30 10:54 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +            //   . Add the new created os_chunk in the in-memory catalog
I was about to answer, but it took me a while to write down what I had in mind. @tustvold and I had a conservation about this issue a while back and IIRC we came up w/ this plan: #3255.

In general there's no way you can do the in-mem transaction before the persisted transaction because the latter one can always fail due to IO.

2021-11-30 15:21 UTC, NGA-TRAN reviewed
Thanks @tustvold and @crepererum . I think I got the idea. Will put them in the right order

2021-11-30 15:21 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +            //   . Add the new created os_chunk in the in-memory catalog
Thanks both @tustvold and @crepererum. Very helpful

2021-11-30 15:21 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    let partition = db
Let me keep the pointer to partition instead. I was a bit confused about the way to get partition and acquire its read/write lock but I think I got it now.

2021-11-30 15:21 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    transaction.commit().await.context(CommitError)?;
I will integrate this with #3255

2021-11-30 21:47 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    transaction.commit().await.context(CommitError)?;
@tustvold With the new changes, I am not sure if we need the `handle.flush` anymore. Can you check?

2021-11-30 23:20 UTC, NGA-TRAN reviewed
@tustvold and @crepererum : These PR does 2 things:
1. Handle  delete predicates per your suggestions. I feel quite confident about the changes.
2. Handle empty result.

You may want to review them all

2021-11-30 23:20 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/management/v1/chunk.proto
> +  // todo: how to make this enum(ChunkId)?
@tustvold : can we do this or we need another field for ChunkId?

2021-11-30 23:20 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    #[ignore]
This test does not pass yet. I know where the bug happens but need more time to investigate. It does not affect others though. I will fix it after this PR is merged

2021-12-01 09:44 UTC, crepererum commented on server/src/db.rs
> +                            Some(id) => (id, true),
In this case you need to use BOTH chunk IDs (the ID of the chunk itself AND the ID of the to-be-created chunk). The reason is that the compaction that is currently in progress might fail (either the compaction itself fails or the commit to the preserved catalog fails) and in the failure case we don't wanna loose the delete predicate.

This is somewhat a tee construct, i.e. it sends the delete predicates to multiple chunks (the existing one and the to-be-created one).

2021-12-01 09:44 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +    transaction.commit().await.context(CommitError)?;
I think it's still the same. There's no need to touch the mailbox here, since the background worker (or another persistence lifecycle action) will lazily take care of that.

2021-12-01 09:44 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +    delete_predicates.sort();
(This is my 2nd try writing this because the GitHub UI scoping of "cancel" is buggy :angry: ).

This is a bit tricky because now you have a lock gap between "we determine the delete predicates" and "we modify the partition". During this gap new predicates might be added that are just lost (at least from the in-mem view).

# Solution 1
Move the `let mut partition = partition.write();` to the start of the function. That SHOULD work but I find it a somewhat weak lock interaction.

# Solution 2
This is similar to what we do in other places.

1. In `mark_chunks_to_compact` collect for each chunk that you're about to include the delete predicates (e.g. in a `BTreeMap`). Let's call this variable `delete_predicates_before`. For these predicates we know that they are materialized by the compaction.
2. Remove the marked code block.
3. Some lines down replace the `for id in chunk_ids {` block with:

```rust
let mut delete_predicates = HashSet::new();
for id in chunk_ids {
    let chunk = partition
        .force_drop_chunk(*id)
        .expect("There was a lifecycle action attached to this chunk, who deleted it?!");
    let before = delete_predicates_before.get(id).expect("chunk existed before compaction");
    for pred in chunk.delete_predicates() {
        if !before.contains(&pred) {
            delete_predicates.insert(pred);
        }
    }
}
```

CC @tustvold could you please double-check my lock reasoning here?

2021-12-01 14:26 UTC, NGA-TRAN commented on server/src/db.rs
> +                            Some(id) => (id, true),
Good point

2021-12-01 14:26 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    delete_predicates.sort();
@crepererum I like solution 2 better. In that case, we do not need to read delete predicates from mailbox at all, right?

2021-12-01 14:59 UTC, crepererum commented on server/src/db/lifecycle/compact_object_store.rs
> +    delete_predicates.sort();
> I like solution 2 better. In that case, we do not need to read delete predicates from mailbox at all, right?

Right.

2021-12-01 15:00 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    delete_predicates.sort();
I think we still need both the `delete_predicate_after` from compacted chunks and the ones in the mailbox. Let me add them in

2021-12-01 15:02 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    delete_predicates.sort();
Hah, did not see your response. Let three of us catch up on this after standup so we are on the same page

2021-12-01 15:05 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    delete_predicates.sort();
Actually I agree with @crepererum that we do not need to get the ones in the mailbox because they will be done in the background later

2021-12-01 15:29 UTC, NGA-TRAN commented
@crepererum and @tustvold : I think all the known locking gaps have been solved. Can you have a look to get this merged? I am focusing on more tests now. This needs a lot of tests

2021-12-01 16:54 UTC, crepererum commented on server/src/db.rs
> +                    let (to_be_created_chunk_id, compacting_os) =
I think you can make this an `Option<ChunkId>` because the `to_be_created_chunk_id` is not used if `compacting_os = false`.

2021-12-01 17:45 UTC, crepererum commented on generated_types/protos/influxdata/iox/management/v1/chunk.proto
> +  // todo: how to make this enum(ChunkId)?
I think protobuf enums are solely marker/integer-based and cannot contain any payload. So I think we need a new field on `Chunk` or even better a new struct:

```proto
message ChunkLifecycleAction {
  enum Type {
    // No lifecycle
    CHUNK_LIFECYCLE_ACTION_UNSPECIFIED = 0;

    /// Chunk is in the process of being written to object storage
    CHUNK_LIFECYCLE_ACTION_PERSISTING = 2;

    /// Chunk is in the process of being compacted
    CHUNK_LIFECYCLE_ACTION_COMPACTING = 3;

    ...
    }

    Type type = 1;
    bytes target_chunk_id = 2;
}
```

Since the protobuf is only used between our CLI client and the server and we don't preserve the data anywhere, I think this somewhat bigger change is OK.

2021-12-01 17:47 UTC, tustvold approved these changes
I _think_ this is good, but its a bit late in the day so I might have missed something. Will look through again tomorrow morning

2021-12-01 17:47 UTC, tustvold commented on server/src/db.rs
> +                        if compacting_os {
```suggestion
                        if let Some(to_be_created) = to_be_created_chunk_id {
```

Should remove the need for the boolean and the `unwrap`

2021-12-01 17:47 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +        Ok(dbchunk) // todo: consider to return Ok(None) when appropriate
Is this todo outdated? This is an Option?

2021-12-01 17:47 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +    let delete_predicates = {
Why do we sort the delete predicates?

2021-12-01 17:47 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +) -> Result<Option<Arc<DbChunk>>> {
```suggestion
) -> Option<Arc<DbChunk>> {
```

This should be infallible

2021-12-01 17:47 UTC, tustvold commented on server/src/db/lifecycle/compact_object_store.rs
> +    //  . en-to-end tests to not only verify row num but also data
```suggestion
    //  . end-to-end tests to not only verify row num but also data
```

2021-12-01 18:26 UTC, NGA-TRAN commented on server/src/db/lifecycle/compact_object_store.rs
> +    let delete_predicates = {
I asked myself the same question. It was done in both `compact` and `persist` chunk. @crepererum has some reason for it?

2021-12-01 18:26 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/management/v1/chunk.proto
> +  // todo: how to make this enum(ChunkId)?
I will address this in a different PR

2021-12-01 18:35 UTC, merged

2021-12-02 14:23 UTC, alamb commented on generated_types/protos/influxdata/iox/management/v1/chunk.proto
> +  // todo: how to make this enum(ChunkId)?
Different PR is https://github.com/influxdata/influxdb_iox/pull/3275