Create a build-time-optimized release build profile
influxdata/influxdb_iox pull request #3319
Opened 2021-12-06 18:07 UTC by carols10cents

Closes #3316

A "full build" was me deleting `/target` and then running the command. A "rebuild" was me changing a particular `unreachable!` to a `panic!` in the `read_buffer` crate.

| Command | Full build | Rebuild |
|-----------|-----------|---------|
| `cargo build --release` |  7m 24s | 5m 13s |
| `cargo build --profile quick-release` | 4m 11s | 2m 06s |

Bikeshed time:

- Should the profile optimizing for compile time be `--release` or should the profile optimizing for binary size be `--release`?
- What should the name of the non-`--release` profile be?
- Any other comparison stats you want to see?
- Any other settings that should be changed?

2021-12-06 18:53 UTC, e-dard commented
I like the idea of `release` and `quick-release`! This makes me happy and is just what I was looking for!

2021-12-06 18:54 UTC, e-dard approved these changes
![](https://c.tenor.com/Jf9JQpRb4PsAAAAC/hell-yeah-thats-what-im-talking-about.gif)

2021-12-06 20:27 UTC, alamb approved these changes
Thank you @carols10cents

2021-12-06 20:27 UTC, alamb commented on Cargo.toml
> +[profile.quick-release]
I suggest some description of the difference of `release` and `quick-release`

Perhaps something like that `release` takes significantly longer to compile but may make a faster binary, and that `quick-release` is for dev iterations

2021-12-06 21:08 UTC, carols10cents commented on Cargo.toml
> +[profile.quick-release]
Good call! Just added!

2021-12-06 21:09 UTC, carols10cents commented on Dockerfile
> +ARG PROFILE=release
@crepererum is this what you wanted to happen in the Dockerfile with regards to this change? I'm not sure that I've understood correctly. Thanks!

2021-12-07 08:42 UTC, crepererum approved these changes

2021-12-07 08:42 UTC, crepererum commented on Dockerfile
> +ARG PROFILE=release
This is precisely what I wanted, thanks! :mrs_claus:

2021-12-07 11:20 UTC, crepererum requested changes

2021-12-07 13:54 UTC, crepererum commented on Dockerfile
>      du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target
```suggestion
    objcopy --compress-debug-sections "target/$PROFILE/influxdb_iox" && \
    cp "/influxdb_iox/target/$PROFILE/influxdb_iox" /root/influxdb_iox && \
    du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target
```

2021-12-08 14:49 UTC, carols10cents commented on Dockerfile
>      du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target
Oooooooh yep. That'll be a problem. Great catch!

2021-12-08 15:58 UTC, carols10cents commented
@crepererum I think this is ready for re-review, thank you!

2021-12-08 16:29 UTC, crepererum approved these changes
:tada:

2021-12-08 21:18 UTC, merged