feat: add regex to bucket writers assignment in data generator
influxdata/influxdb_iox pull request #3346
Opened 2021-12-08 21:25 UTC by pauldix

This adds the ability to specify a regex to match against database names when specifying what agents should write to which buckets in the data generator.

A default has also been added for ratio so that it doesn't need to be specified if only a single database writer is defined.

Closes #3344

2021-12-08 22:03 UTC, alamb approved these changes

2021-12-08 22:03 UTC, alamb commented on iox_data_generator/src/specification.rs
> +        let use_ratio =
Would it make sense to do `use_ratio = <if any bucker writer has ratio set>` rather than just checking the first one?

When written this way it seems like if some writer other than the first has a `ratio` specified, it will be silently ignored in favor of `regex`

2021-12-08 22:03 UTC, alamb commented on iox_data_generator/src/specification.rs
> +name = "whatevs"
whatevs whatevs!

2021-12-09 08:57 UTC, crepererum requested changes

2021-12-09 08:57 UTC, crepererum commented on iox_data_generator/src/specification.rs
> +                        "Bucket_writers percentages > 1.0. Writer {:?} and later skipped.",
```suggestion
                        "Bucket_writers ratio > 1.0. Writer {:?} and later skipped.",
```

2021-12-09 08:57 UTC, crepererum commented on iox_data_generator/src/specification.rs
>  pub struct BucketWriterSpec {
As a future user, it took me quite a while to understand the data flow graph here and why "ratio" and "regex" don't work together (or at least why it doesn't make sense). I think what would help:

1. rename `ratio` to `database_ratio`
2. rename `regex` to `database_regex`
3. replace the term "bucket" with "database" everywhere except at the one place where it specifies a bucket within an org (i.e. `database_name = <org>_<bucket>`
4. clearly state that the ratio here is an interval "cum sum prev. ratios" to "cum sum prev. ratios + ratio" of the database name list. The database name list is NOT shuffled or anything.

2021-12-09 15:34 UTC, pauldix commented on iox_data_generator/src/specification.rs
>  pub struct BucketWriterSpec {
Does it make sense why you wouldn't use them together?

My thinking was that if you're using ratios, you're describing how to split up the entire list of provided databases. If you're using regex, then you have some naming scheme in the provided databases so you want to split them up explicitly based on that naming scheme.

2021-12-09 15:43 UTC, pauldix commented on iox_data_generator/src/specification.rs
>  pub struct BucketWriterSpec {
The bucket/database thing is also where I thought this whole thing is a little wonky. The data generator writes to the InfluxDB 2.0 API so it writes to org & bucket. However, the list this takes is a database list because I assumed that would be easiest to generate since that's what would be getting used to configure the IOx servers. I can change it to `database`.

2021-12-09 16:31 UTC, crepererum commented on iox_data_generator/src/specification.rs
>  pub struct BucketWriterSpec {
> Does it make sense why you wouldn't use them together?

I'm wondering how the dataflow graph would look like if they are used together. What is "ratio" going to measure them, pre regex split or post regex split?

2021-12-10 09:52 UTC, crepererum approved these changes

2021-12-10 10:11 UTC, merged