feat: Add db_name/namespace to DmlWrite and DmlDelete
influxdata/influxdb_iox pull request #3531
Opened 2022-01-25 18:56 UTC by pauldix

This is required for the new ingester to be able to work with the write buffer. The protobuf that gets serialized over Kafka already includes the database name, it just wasn't getting carried through to the marshaled Dml operation.

2022-01-26 08:45 UTC, crepererum requested changes
Please adjust

https://github.com/influxdata/influxdb_iox/blob/52866fe6a90ea372957a29ec4c604552824b9ee6/dml/src/lib.rs#L426

To check the names as well. We should probably implement a proper `PartialEq` at some point.

2022-01-26 11:15 UTC, domodwyer approved these changes
Makes sense to me!

2022-01-26 11:15 UTC, domodwyer commented on dml/src/lib.rs
> +    namespace: String,
You'll need a getter to be able to read this back out the struct (same with deletes) 👍

2022-01-26 11:15 UTC, domodwyer commented on influxdb_iox/src/influxdb_ioxd/http/dml.rs
> +        let write = DmlWrite::new(db_name.as_str(), tables, DmlMeta::unsequenced(span_ctx));
We can avoid converting the `DatabaseName` to a `str` and then [to a `String`](https://github.com/influxdata/influxdb_iox/blob/8180b007aec9cee33276a33a67de002f73d30032/dml/src/lib.rs#L224) straight after by using `&db_name`:

```suggestion
        let write = DmlWrite::new(&db_name, tables, DmlMeta::unsequenced(span_ctx));
```

This works because there is a `From<&DatabaseName> for String` [impl allowing the direct conversion](https://github.com/influxdata/influxdb_iox/blob/8180b007aec9cee33276a33a67de002f73d30032/data_types/src/database_name.rs#L88-L92).

Same thing for the delete path too 👍

2022-01-26 11:15 UTC, domodwyer commented on router2/src/sharded_write_buffer.rs
> +                namespace.as_str(),
```suggestion
                &namespace,
```

2022-01-26 11:15 UTC, domodwyer commented on router2/src/sharded_write_buffer.rs
> +            namespace.as_str(),
```suggestion
                &namespace,
```

2022-01-26 22:41 UTC, pauldix commented
Ok, fixed up and pushed

2022-01-27 00:42 UTC, pauldix commented
Ok wow, was a bit more of a pain than I thought to fix all the testing machinery. Hopefully working now

2022-01-27 09:54 UTC, crepererum requested changes

2022-01-27 09:54 UTC, crepererum commented on write_buffer/src/core.rs
> +            context.database_name(),
I think for these tests it would be helpful if the name that is used to create the `DmlWrite` and the one that is used during write buffer creation are different because this is exactly the use case you're aiming for (e.g. create an `iox_shared` Kafka topic into which we serialize a write for the namespace `customer_1`).

I know this might sound a bit pedantic, but it's too easy to confuse these two names somewhere in the code.

With that I think `context.database_name()` is not actually required.

2022-01-27 12:27 UTC, crepererum commented
I'm stealing this PR now.

2022-01-27 14:12 UTC, merged