feat: wire up the write buffer to the ingester process
influxdata/influxdb_iox pull request #3533
Opened 2022-01-25 19:19 UTC by pauldix

This adds the scaffolding for the ingester server to consume data from Kafka. Future work will implement the actual buffering of data and add tests for the ingest handler.

This also includes the commit from #3531. Once that is merged in I'll rebase this branch to clean up the PR diff. In the meantime, viewing commit dda6563d475da90cf3f623c8b3f36e0f424c3142 will show what this PR is meant to add.

2022-01-26 08:58 UTC, crepererum reviewed
Where are the tests? :wink:

2022-01-26 08:58 UTC, crepererum commented on ingester/src/handler.rs
> +    join: Shared<BoxFuture<'static, Result<(), Arc<JoinError>>>>,
Can we not use a normal `JoinHandle` here? Then you could get away w/o the extra `CancellationToken` because `JoinHandle` has an `abort` method.

In either case though (using a join handle or this somewhat complicated construction here), I want you to stop the background thread when `IngestHandlerImpl` is dropped:

```rust
impl Drop for IngesterHandlerImpl {
    fn drop(&mut self) {
        // e.g.
        self.join.abort();
    }
}

2022-01-26 08:58 UTC, crepererum commented on ingester/src/handler.rs
> +                continue;
I have seen similar patterns in my code and I think this is a bit hard to read. You're normally better off extracting the loop body into a function returning `Result<(), Error>` where you can just use `?` and then have a single `match` statement that ignores/logs the error.

BTW: I think we want some error count metric here.

2022-01-26 08:58 UTC, crepererum commented on ingester/src/handler.rs
> +    while let Some(db_write_result) = stream.next().await {
Tracing is missing, but we (or I) can do that later. We are actually able to create tracing spans here that are linked to the traces on the router side, so we can correlate errors / weird behavior here all the way back to the frontend HTTP request that created the to-be-ingested data.

2022-01-26 11:48 UTC, domodwyer approved these changes
It's all coming together!

Might be worth making the `debug!(something semi-important has gone wrong)` into `WARN` level logs, so we see them in prod and act on them. For example, if we were never able to update the sequencer watermark we might not notice if it's logging at `DEBUG`.

2022-01-26 11:48 UTC, domodwyer commented on influxdb_iox/src/commands/run/ingester.rs
> +    }
Bit of a gotcha! The range below is:

```rust
(config.kafka_partition_range_start
        ..config.kafka_partition_range_end)
```

But the range end is not inclusive, so if you give it a "just read from sequencer 1" config:

```
kafka_partition_range_start=1
kafka_partition_range_end=1
```

You wind up with a range of `(1..1)` which [is of length 0](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=59a47f754bbdd3577f005175967cbf69).

It's probably less error prone to check that we have some sequencers once we're done initialising:

```rust
if kafka_partitions.is_empty() {
    return Err(...)
}
```

Might be good to document the range inclusiveness (or lack of!)

2022-01-27 14:40 UTC, pauldix commented on ingester/src/handler.rs
> +    join: Shared<BoxFuture<'static, Result<(), Arc<JoinError>>>>,
Sounds good, I was just copying what was done elsewhere.

2022-02-01 23:13 UTC, pauldix commented on ingester/src/handler.rs
> +            .buffer_operation(sequencer_id, dml_operation.clone())
This clone isn't ideal, but the metrics and span recorder are borrowing the DML operation. The data buffer actually needs to take ownership of the underlying mutable batches, which aren't used in the span and metrics at all, so there's probably metrics/span additions I can make so that they can work using the meta info, which isn't used in the buffer.

2022-02-01 23:24 UTC, pauldix commented
Ok, this is finally ready with the data going into the buffer. I moved a bunch of stuff over to `data.rs`. I need to add a bunch of tests there, but I think this is important to get in. The test in `handler.rs` goes through the entire pathway of getting data in the write buffer, reading it out, putting it into the data buffer and having the catalog get updated along the way.

I removed the `catalog_update.rs` for now because that is changing quite a bit and there wasn't anything really happening there yet. Next I'll be adding some basic lifecycle stuff which will have new hooks in `data.rs` to kick off persistence and then update the catalog after.

2022-02-01 23:32 UTC, pauldix commented on ingester/src/data.rs
> +        let partition_key = format!(
This bit will need to be fixed. To get things moving along, I just had it assume that all data within the mutable batch belongs to the same partition. I know this isn't yet guaranteed on the router side, but ideally it will be. I've logged #3603 to track that.

2022-02-02 11:07 UTC, crepererum requested changes
Found some code quality issues and minor bugs, but overall I think this works.

2022-02-02 11:07 UTC, crepererum commented on ingester/src/handler.rs
> +            tokio::time::sleep(Duration::from_millis(10)).await;
Pro tip for the future (you don't have to change that now): there's a tokio function for that, i.e. 

```rust
let t_0 = Instant::now();
loop {
    // do something

    assert!(t_0.elapsed() < Duration::from_secs(2));
    tokio::time::sleep(Duration::from_millis(10)).await;
}
```

can be written as

```rust
tokio::time::timeout(
    Duration::from_secs(2),
    async {
        loop {
            // do something

            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    },
).await.expect("timeout");
```

Sure it's a bit more nested by the reader can immediately see that you're putting a timeout on a payload.

2022-02-02 11:07 UTC, crepererum commented on dml/src/lib.rs
> +    pub fn tables_into_iter(self) -> impl Iterator<Item = (String, MutableBatch)> {
```suggestion
    pub fn into_tables(self) -> impl Iterator<Item = (String, MutableBatch)> {
```

The "Rusty" naming is `into_x` for transforming a container into an iterator of it's parts. See `{HashMap,BTreeMap}::{into_keys,into_values}` for example.

2022-02-02 12:59 UTC, domodwyer commented on ingester/src/data.rs
> +                        .expect("table name must exist in delete"),
The router does not resolve it in any way - it just passes the delete predicate into the DML op and pushes it down the tube to the ingester.

I'm not sure we could resolve it in the router without it being racy with concurrent table creation in another router - worth a discussion 👍

2022-02-02 14:14 UTC, pauldix commented on ingester/src/data.rs
> +            .context(CatalogSnafu)?;
I don't think we'll need the optimization for some time as we don't have that many deletes hitting any single cluster.

2022-02-02 14:15 UTC, pauldix commented on ingester/src/handler.rs
> +        let write_buffer: &'static mut _ = Box::leak(write_buffer);
Ah yes, I forgot to add a comment on this! Thanks for adding the context 😄

2022-02-02 14:18 UTC, pauldix commented on ingester/src/handler.rs
> +    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
Ah, I added this before because the test was freezing up, but I just took it out and everything completes correctly. Will remove.

2022-02-02 18:46 UTC, pauldix commented on ingester/src/data.rs
> +        t.insert(table.name, Arc::clone(&data));
Good catch!

2022-02-02 18:47 UTC, pauldix commented on ingester/src/data.rs
> +                        .expect("table name must exist in delete"),
I thought that this was going to get enforced at the HTTP API level to require a table. @e-dard, I believe you looked into the behavior on the delete API?

2022-02-02 18:48 UTC, pauldix commented on ingester/src/handler.rs
>  //! Ingest handler
yeah, not really a handler. More like the running ingester server. Should I rename in a followup PR?

2022-02-02 19:25 UTC, pauldix commented on ingester/src/data.rs
>  //! Data for the lifecycle of the Ingester
haha good point. I'll add it in a followup PR 😄

2022-02-02 22:16 UTC, pauldix commented on ingester/src/data.rs
> +        match dml_operation {
The operation actually has to be taken apart in the namespace because a write can apply to many tables.

2022-02-03 08:29 UTC, crepererum commented on ingester/src/data.rs
> +                        .expect("table name must exist in delete"),
I'm pretty sure the HTTP API allows that because we deal w/ that in the current ingester code and @tustvold and I thought about it multiple times when pondering about delete routing.

2022-02-03 08:32 UTC, crepererum approved these changes
OK, let's merge this and let's improve docs / naming in a follow-up PR, so we can unblock the team and get a test bench run.

2022-02-03 09:11 UTC, tustvold commented on ingester/src/data.rs
> +                        .expect("table name must exist in delete"),
Deletes without tables I'm pretty certain are allowed, the thing we decided not to support is deletes with `__field` predicates as they aren't really deletes but upserts.

One thing to perhaps bear in mind, is that it isn't always trivial to infer what tables a delete concerns. This is something that has come up in the pruning logic, you can stick `__measurement` anywhere including in a nested chain of expressions. The current ingest tier is pessimistic in this regard

2022-02-03 11:47 UTC, merged