feat: insert persisted info into the catalog in one transaction
influxdata/influxdb_iox pull request #3636
Opened 2022-02-03 18:58 UTC by NGA-TRAN

a task of #3564 

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-02-03 22:54 UTC, NGA-TRAN commented
I have turn this PR to draft and will modify it a bit. Do not review it yet

2022-02-04 10:14 UTC, crepererum commented on iox_catalog/src/interface.rs
> +        txt: Option<&mut Transaction<'_, Postgres>>,
Yeah cannot stick a postgres-specific transaction to the generic interface. A file-based or in-mem catalog doesn't have postgres. And even if that would be a generic transaction I think the interface here is the wrong way around. The repositories should be bound to a transaction or UoW (Unit of Work) so it's clear which scope all getters and setters have. I can draft a design for this on Monday if you wish me to do that.

2022-02-04 10:55 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +        txt: Option<&mut Transaction<'_, Postgres>>,
I think sinking a little bit of time into getting the API right for txns up front is a great idea 👍

2022-02-04 14:52 UTC, domodwyer requested changes
I think we're missing test coverage for the postgres catalog functions `exist` and `count` and I think they need refactoring to give the correct result we're after - I'm happy to help with this if you want 👍

2022-02-04 14:52 UTC, domodwyer commented on iox_catalog/src/mem.rs
> +    }
I think it would be nice to move this logic _outside_ of the catalog as it only calls public catalog methods and doesn't need any internal postgres state - it uses the catalog, it is not implementing the catalog (aside from txns).

I guess @crepererum already has similar plans with his txn proposal - it would be nice to to have to duplicate this logic for different catalog implementations (the in-mem catalog implementation is almost identical) when they will do the same thing via the public catalog API.

2022-02-04 14:52 UTC, domodwyer commented on iox_catalog/src/postgres.rs
> +    }
I think this logic is wrong - the result will always have 1 row with `count = 0` so it is not empty:

```sql
iox=# SELECT count(*) FROM iox_catalog.parquet_file WHERE id =42;
 count
-------
     0
(1 row)
```

I would imagine we need to access the count value in the result and compare it to 0 instead of checking if there are no rows.

We will have to change the query from a `ParquetFile` we're specifying in the `query_as::<_, ParquetFile>` generics as it is not returning the columns that go into a `ParquetFile` - I can help with this if you want 👍

2022-02-04 14:52 UTC, domodwyer commented on iox_catalog/src/postgres.rs
> +    }
Same as `exist()` I think this logic is probably wrong.

2022-02-04 15:03 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +    }
Good catch about count(*) always return value @domodwyer.
Let me add tests and see if I figure out how to change this. Otherwise, I will ping you for help

2022-02-04 15:05 UTC, NGA-TRAN commented
@domodwyer 
> I think we're missing test coverage for the postgres catalog functions exist and count and I think they need refactoring to give the correct result we're after - I'm happy to help with this if you want 

Yeah, I put this as draft to add tests for Postgres functions. Let me do that and I think I might need your help to get column and read value if I cannot figure out from sql documents

2022-02-04 23:14 UTC, NGA-TRAN commented
@crepererum and @domodwyer : this is ready for review. If there are no major issues, I think we may want to have this merged to have all behaviors available for testing persistence. When Marco has the new abstract available, we will refactor it.

2022-02-07 12:15 UTC, domodwyer approved these changes
Looking good! 👍

2022-02-07 12:15 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +            .unwrap());
❤️

2022-02-07 14:44 UTC, merged