refactor: Clean up some future clippy warnings from nightly
influxdata/influxdb_iox pull request #3892
Opened 2022-03-01 21:01 UTC by alamb

# Rationale

Clippy is not working great on 1.59 for me due to https://github.com/rust-lang/rust-clippy/issues/8470 so I want to use nightly clippy as a workaround. Sadly when I do so I get a bunch of errors (below) due to clippy lints that are not (yet) stable

# Changes
1. Clean up the code so clippy nightly also runs cleanly

I ran

```shell
cargo +nightly clippy --all-targets --all-features --workspace -- -D warnings
```

And cleaned up all the warnings

# Example failures
```
error: question mark operator is useless here
   --> sqlx-hotswap-pool/src/lib.rs:200:9
    |
200 | /         Ok(PgPoolOptions::new()
201 | |             .min_connections(1)
202 | |             .max_connections(5)
203 | |             .connect_timeout(Duration::from_secs(2))
...   |
224 | |             .connect(&dsn)
225 | |             .await?)
    | |____________________^
    |
    = note: `-D clippy::needless-question-mark` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark
help: try removing question mark and `Ok()`
    |
200 ~         PgPoolOptions::new()
201 +             .min_connections(1)
202 +             .max_connections(5)
203 +             .connect_timeout(Duration::from_secs(2))
204 +             .idle_timeout(Duration::from_secs(500))
205 +             .test_before_acquire(true)
  ...

error: could not compile `sqlx-hotswap-pool` due to previous error
warning: build failed, waiting for other jobs to finish...
error: called `cloned().flatten()` on an `Iterator`. It may be more efficient to call `flatten().cloned()` instead
   --> mutable_batch/src/payload/filter.rs:147:32
    |
147 |           let expected: Vec<_> = ranges
    |  ________________________________^
148 | |             .iter()
149 | |             .cloned()
150 | |             .flatten()
    | |______________________^
    |
    = note: `-D clippy::iter-overeager-cloned` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#iter_overeager_cloned
help: try this
    |
147 ~         let expected: Vec<_> = ranges
148 +             .iter().flatten().cloned()
    |

error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
   --> lifecycle/src/policy.rs:618:40
    |
618 | fn sort_free_candidates<P>(candidates: &mut Vec<FreeCandidate<'_, P>>) {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `&mut [FreeCandidate<'_, P>]`
    |
    = note: `-D clippy::ptr-arg` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

error: question mark operator is useless here
  --> influxdb2_client/src/api/label.rs:12:9
   |
12 |         Ok(self.get_labels(None).await?)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try removing question mark and `Ok()`: `self.get_labels(None).await`
   |
   = note: `-D clippy::needless-question-mark` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark

error: question mark operator is useless here
  --> influxdb2_client/src/api/label.rs:17:9
   |
17 |         Ok(self.get_labels(Some(org_id)).await?)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try removing question mark and `Ok()`: `self.get_labels(Some(org_id)).await`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark

error: question mark operator is useless here
  --> influxdb2_client/src/api/write.rs:58:9
   |
58 |         Ok(self.write_line_protocol(org, bucket, body).await?)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try removing question mark and `Ok()`: `self.write_line_protocol(org, bucket, body).await`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark

error: build failed
```

2022-03-01 21:05 UTC, alamb commented on iox_catalog/src/lib.rs
> -    schema: &mut Cow<'_, NamespaceSchema>,
This is the only change I do not feel confident -- perhaps @domodwyer  can check me on it

I made it due to this clippy lint: https://rust-lang.github.io/rust-clippy/master/#ptr_arg

However, I was not able to convince myself that all paths in `validate_mutable_batch` were actually calling `to_mut()` so this may be a behavior change. If it is, I will find some way to silence clippy wihtout the change

2022-03-01 21:05 UTC, alamb commented on mutable_batch/tests/writer_fuzz.rs
> -        .cloned()
clippy told me this should be `flatten().cloned()` and then that failed to compile 🤦  so I did this workaround which I think is equivalent

2022-03-01 21:05 UTC, alamb commented on influxdb2_client/src/api/label.rs
> -        Ok(self.get_labels(None).await?)
this seems like a legitimate cleansing of the code so 👍  for clippy

2022-03-02 15:43 UTC, carols10cents commented on mutable_batch/tests/writer_fuzz.rs
> -        .cloned()
I filed a bug for this: https://github.com/rust-lang/rust-clippy/issues/8494

2022-03-02 16:10 UTC, alamb commented on mutable_batch/tests/writer_fuzz.rs
> -        .cloned()
Thank you -- very nice reproducer

2022-03-02 16:39 UTC, carols10cents commented on iox_catalog/src/lib.rs
> -    schema: &mut Cow<'_, NamespaceSchema>,
Yeah, I think in the `Some` branch of the `match schema.tables.get(table_name) {`, the schema won't be cloned, but with this change, the schema will always be cloned which it looks like Dom was trying to avoid here. I think we should `allow(clippy::ptr_arg)` on this function. I think this is a clippy bug similar to some of the other bugs for this lint where it suggested changing a Vec to a slice when Vec methods were used... I've filed a bug here: https://github.com/rust-lang/rust-clippy/issues/8495

2022-03-02 16:40 UTC, carols10cents requested changes
We should allow the ptr_arg one; the rest looks fine.

2022-03-03 11:39 UTC, domodwyer requested changes

2022-03-03 11:39 UTC, domodwyer commented on iox_catalog/src/lib.rs
> -    schema: &mut Cow<'_, NamespaceSchema>,
Yes @carols10cents is spot on thanks for calling it out @alamb  - this breaks the copy-on-write behaviour by always copying it - what an unfortunate lint bug!

2022-03-03 17:31 UTC, alamb commented on iox_catalog/src/lib.rs
> +// &mut Cow is used to avoid a copy, so allow it
Here is the change to get clippy to skip the silliness

2022-03-03 17:33 UTC, alamb commented
Sorry I had to force-push this as my `merge` commit got flagged as not a Semanitic PR

2022-03-03 17:34 UTC, alamb commented on iox_catalog/src/lib.rs
> -    schema: &mut Cow<'_, NamespaceSchema>,
Changed this to `#[allow(...)]`

2022-03-03 17:38 UTC, domodwyer requested changes

2022-03-03 17:38 UTC, domodwyer commented on iox_catalog/src/lib.rs
> -    schema: &mut Cow<'_, NamespaceSchema>,
It looks like you've might have missed reverting the `Cow` change?

2022-03-03 17:51 UTC, alamb commented
> It looks like you've might have missed reverting the Cow change?

Seems to have been lost in the rebase to get semantic PR happy 😭

2022-03-03 17:52 UTC, domodwyer approved these changes
👍

2022-03-03 18:33 UTC, alamb commented
Semantic PR is killing me!

2022-03-03 19:14 UTC, merged