WIP: delete fully processed tombstones
influxdata/influxdb_iox pull request #4116
Opened 2022-03-23 16:44 UTC by NGA-TRAN

Closes #3953 

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-03-24 20:58 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        self.remove_fully_processed_tombstones(tombstones).await?;
This is the last piece of `find_and_compact` which triggers the (integration) tests for find_and_compact

2022-03-24 20:58 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +                // they are overlap before adding process tombstones
This is the bug and its fix @carols10cents . In the original design, we did not see this at all 😄

2022-03-24 20:58 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    async fn remove_fully_processed_tombstones(
This is the main purpose of this PR

2022-03-24 20:58 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    async fn test_find_and_compact() {
Since the last piece is connected, this integration test helps verify the last piece in a full context of compaction

2022-03-24 20:58 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +      OR (parquet_file.min_time > $4 AND parquet_file.min_time <= $5));
Fix another bug here. The tests for this are in  `test_find_and_compact`

2022-03-24 20:58 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +        );
@carols10cents : I tried `WHERE id IN ($1)` and then `.bind(&ids[..])`  like you did with `= ANY($1)` but it did not work. They said array should work for Postgres and not sure what I missed. I use this as a workaround

2022-03-24 21:02 UTC, NGA-TRAN commented on querier/src/chunk/mod.rs
> +pub async fn collect_read_filter(chunk: &QuerierChunk) -> Vec<RecordBatch> {
@crepererum : I moved this out of the tests module to be able to use it in tests of the compactor crate

2022-03-24 21:21 UTC, pauldix requested changes
Found one logic bug in counting how many files a tombstone applies to. Also a question about removing tombstones and processed tombstones in a single transaction. Other than that it looks good!

2022-03-24 21:21 UTC, pauldix commented on compactor/src/compact.rs
> +            .count_by_overlaps(
in order for the parquet file to overlap with the tombstone, it must have a `min_sequence_number` < the tombstone's sequence number. Otherwise, this tombstone was created before the parquet file in question so it shouldn't be applied.

2022-03-24 21:21 UTC, pauldix commented on iox_catalog/src/mem.rs
> +    async fn remove(&mut self, tombstone_ids: &[TombstoneId]) -> Result<usize> {
shouldn't this also remove the processed tombstone records associated with these tombstones?

2022-03-24 21:21 UTC, pauldix commented on iox_catalog/src/mem.rs
> +    async fn remove(&mut self, tombstone_ids: &[TombstoneId]) -> Result<usize> {
Oh, I see you have this as two separate operations, one against tombstones and one against processed tombstones. Seems like it would be better to have a single catalog function to call that does both in a single transaction.

2022-03-25 15:55 UTC, carols10cents requested changes
Suggestions!

2022-03-25 15:55 UTC, carols10cents commented on compactor/src/compact.rs
> +        let tombstone = repos.tombstones().get_by_id(tombstone_id).await;
This is doing one query per tombstone, and this query in particular is getting the rest of the tombstone columns for a tombstone ID, but we had all the tombstone data in the GroupWithTombstones in `groups_with_tombstones`. Could we keep the whole `Tombstone` around, dedupe the collection by `TombstoneId` instead, and then avoid all these queries to get the data again?

2022-03-25 15:55 UTC, carols10cents commented on compactor/src/utils.rs
> +    }
We could store the tombstones as a `BTreeMap` to begin with, if that's more useful! I just picked the simplest data structure based on what I knew at the time :)

If this stays, the code could be simplified as:

```suggestion
    pub fn tombstones(&self) -> BTreeMap<TombstoneId, Tombstone> {
        self.tombstones
            .iter()
            .map(|ts| (ts.id, ts.clone()))
            .collect()
    }
```

2022-03-25 18:17 UTC, NGA-TRAN commented on iox_catalog/src/mem.rs
> +    async fn remove(&mut self, tombstone_ids: &[TombstoneId]) -> Result<usize> {
The their code are in different places but they are in one transaction but let me put them on one place to make it easier to read and maintenance

2022-03-25 20:32 UTC, NGA-TRAN reviewed
@carols10cents and @pauldix The pR is ready for second review

2022-03-25 20:32 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .count_by_overlaps(
Done: I have added sequence number and compare that while reading the catalog

2022-03-25 20:32 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .context(RemoveTombstonesSnafu)?;
@carols10cents äter a lot of thoughts, I decided we do not need to have any warning about which rows not deleted. The catalog will throw error if something wrong happens and we already capture it

2022-03-25 20:40 UTC, pauldix approved these changes

2022-03-28 13:44 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +WHERE id = ANY($1);
Should these two DELETEs be done in a transaction?

2022-03-28 13:54 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +WHERE id = ANY($1);
Good catch. I removed the transaction on purpose assuming sqlx/postgres will auto commit but I forgot there are 2 delete statements in here. Working not to add transaction back

2022-03-28 14:11 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .context(RemoveTombstonesSnafu)?;
This comment is no longer valid here because new code has just been added

2022-03-28 14:11 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        let mut txn = self
@carols10cents I have made the caller to start the transaction

2022-03-28 14:12 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +WHERE id = ANY($1);
Have made the caller to start the transaction

2022-03-28 14:42 UTC, carols10cents approved these changes
Ok, I think this is good to go now. I have a tiny optimization that I'll submit in a new PR 👍🏻

2022-03-28 18:35 UTC, merged