feat: applying tomsbtones to cold partitions and compact them
influxdata/influxdb_iox pull request #4226
Opened 2022-04-04 15:40 UTC by NGA-TRAN

Closes #

Describe your proposed changes here.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-04-07 18:56 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    pub async fn partitions_with_files_to_compact(&self) -> Result<Vec<PartitionWithParquetFiles>> {
This functions find candidate `cold` partitions which are partitions that files with overlapped tombstones

2022-04-07 18:56 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +                            && file.min_time() <= group_file.max_time())
The reason to to invoke function `min_time()` rather than its member `min_time` because `file` and `group_file` are now traits

2022-04-07 18:56 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +        assert_eq!(t1.max_time, Timestamp::new(10));
Replace with values  right here to make it easier to see it overlaps with which files.

2022-04-07 21:44 UTC, carols10cents requested changes
A few suggestions and questions!

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +                        .list_by_tombstone(ts.clone())
Looking at the implementations of `list_by_tombstone`, they don't look like they need to own the `Tombstone` (which doesn't implement `Copy` like a lot of the other interface types do, because it holds a serialized predicate `String`)

I think if `list_by_tombstone` takes `&Tombstone` instead, then this `clone` can be removed--

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +                        file.add_tombstones(vec![ts.clone()]);
-- and then this clone can be removed too, because `ts` can be moved into `add_tombstones` here, right?

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +                partitions.extend(ps);
`Vec` implements [the `Extend` trait](https://doc.rust-lang.org/core/iter/trait.Extend.html), so it can be extended with an iterator, and we can save some time by not collecting into an intermediate vector here:

```suggestion
                    );

                partitions.extend(ps);
```

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +        files: Option<Vec<Arc<dyn FileMeta>>>,
`Option<Vec<_>>` is kind of a rare type to see-- this might be what you want though, I'm not sure. It depends on what you want to happen if this function gets `Some(vec![])` - should it fetch files from the catalog? Right now it won't, it'll hit the `Some` case and then the early `is_empty` return. 🤷🏻‍♀️  

If providing an empty list of files *should* cause a fetch from the catalog, then the `Option` can be removed here and the `match` can be changed to instead check if the vector is empty or not (the existing `is_empty` check will still need to be there to make sure we don't do anything if no files were provided *and* the catalog doesn't return any files).

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +                    .map(|f| Arc::clone(&(*f)) as Arc<dyn FileMeta>)
This can be a little simpler, `f` is already `&Arc`:

```suggestion
                    .map(|f| Arc::clone(f) as Arc<dyn FileMeta>)
```

I wish there was a way to coerce this whole `Vec` at once, but I don't know of a way :(

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +                        .map(|f| f.parquet_files_with_timbstone())
Nit, typo in method name here:

```suggestion
                        .map(|f| f.parquet_files_with_tombstone())
```

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/compact.rs
> +            .map(|f| Arc::clone(&(*f)) as Arc<dyn FileMeta>)
This can be a bit simpler:

```suggestion
            .map(|f| Arc::clone(f) as Arc<dyn FileMeta>)
```

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/query.rs
> +        parquet_file_with_tobstones: &ParquetFileWithTombstone,
Nit: typo in parameter name through here:

```suggestion
        parquet_file_with_tombstones: &ParquetFileWithTombstone,
```

2022-04-07 21:44 UTC, carols10cents commented on compactor/src/utils.rs
> +            if !self.contains(f) {
So [`PartialEq`](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html) has particular guarantees implementations are expected to uphold, namely that "equal" and "not equal" are consistent with each other... I'm sure this would be rare, but I don't see anything in the type itself preventing one `GroupWithMinTimeAndSize` from having duplicate items in its `parquet_files`, which could lead to `self` and `other`'s lengths being equal but not having the same items.

Because this is only used for tests, I think it would be better to make a little helper function in the tests that use this that would check the min time and sizes, then extract out a vec of parquet file IDs from both self and other, then sort and compare those vecs directly.

2022-04-07 22:52 UTC, pauldix reviewed
Had a look through, I think it's worth having a quick discussion tomorrow morning.

2022-04-07 22:52 UTC, pauldix commented on compactor/src/compact.rs
> +                    //    2. Need to handle the case that one or many of these files are also included in other background cycle
I think the same scheduler that runs the other compactions should do this. So it's something like:
1. Look for level 0 compactions, perform them
2. Look for level 1 tombstone compactions

We could have it perform one level 0, then a level 1, then level 0, etc.

2022-04-07 22:52 UTC, pauldix commented on compactor/src/compact.rs
> +                    //    1. Should we only read level-1 files only (right now, we read all files that overlap with the tombstone)?
I think if we have the level 0 being handled elsewhere, we should limit it to partitions with only level 1 files. See my next comment on the L0 vs. L1.

2022-04-07 22:52 UTC, pauldix commented on compactor/src/compact.rs
> +        files: Option<Vec<Arc<dyn FileMeta>>>,
This construction feels odd to me. I think it would make more sense to split into two functions. Right now `compact_partition` looks up the files and then goes through the compaction process. You could change it so that there is a function `compact_files` which takes the files and move all the compaction code into there. Then keep the function signature for `compact_partition` the same, but have it do the file lookup and call the new `compact_files` function.

2022-04-07 22:52 UTC, pauldix commented on compactor/src/compact.rs
> +                            && file.min_time() <= group_file.max_time())
Why use traits for a data object? I think it makes more sense to have simple data objects, which can be made in testing scenarios and use traits only for things that have some sort of behavior or remote connection you want to mock out.

2022-04-07 22:52 UTC, pauldix commented on data_types2/src/lib.rs
> +pub trait FileMeta: Debug + Sync + Send + 'static {
Not sure why this is a trait as it seems like it should just be a plain data object.

2022-04-07 22:52 UTC, pauldix commented on iox_catalog/src/postgres.rs
> +  );
I wonder how expensive this query is going to be 😬

2022-06-27 21:36 UTC, alamb commented
marking as a draft so it is clear it isn't actively waiting for a review

2022-08-26 19:32 UTC, closed without merging