feat: Add `SequencerProgress` reporting to ingester
influxdata/influxdb_iox pull request #4238
Opened 2022-04-05 17:42 UTC by alamb

Part of https://github.com/influxdata/influxdb_iox/pull/4227
re https://github.com/influxdata/influxdb_iox/issues/4145

# Rationale

For ingester to respond usefully to a "do you know about the write in this write token" it needs to be able to get the current progress of its ingesters

# Changes
1. Add `SequencerProgress` structure that tracks how far each sequencer is
2. Add `get_progresses` so the  `ingester` can report on its progress
3. Tests

2022-04-05 17:43 UTC, alamb commented on ingester/src/data.rs
> +            // This is super confusing: "sequencer_id" in the router2
Filed https://github.com/influxdata/influxdb_iox/issues/4237 😢  -- I lost quite a while on this issue

2022-04-05 22:29 UTC, pauldix requested changes

2022-04-05 22:29 UTC, pauldix commented on ingester/src/data.rs
> +            let desired_partition = KafkaPartition::new(sequencer_id.get().into());
Wait, is the data type being passed in to this function a catalog SequencerId type? Because if so, it's wrong to convert it to a KafkaPartition. The SequencerId used in the map is the actual catalog id. This function should be taking a vec of KafkaPartition. Either that or it should be taking in the sequencer ids and looking up in the map based on that. The confusion I was talking about is in the metric label naming, not in the types used in either the router or the ingester. Both places should be using the correct types everywhere. It's only in the metric labels for observability that the name `sequencer_id` may refer to either the catalog id or the kafka partition.

2022-04-05 22:29 UTC, pauldix commented on ingester/src/data.rs
> +    async fn update_progress(&self, mut progress: SequencerProgress) -> SequencerProgress {
This seems like a very strange pattern to me. Why pass progress down and return it? Is this some sort of optimization to avoid just having everything return their progress and they combine the result? The `update` is strange to me because you're not updating the state of the buffer, you're actually asking for the state of the buffer and returning it back aggregated up.

2022-04-05 22:29 UTC, pauldix commented on ingester/src/data.rs
> +    fn to_sequencer_id(kafka_partition: KafkaPartition) -> SequencerId {
This shouldn't be necessary, we shouldn't be swapping these types anywhere like this.

2022-04-05 22:29 UTC, pauldix commented on write_summary/src/progress.rs
> +    pub fn readable(&self, sequence_number: SequenceNumber) -> bool {
Looks right

2022-04-05 22:29 UTC, pauldix commented on write_summary/src/progress.rs
> +    pub fn persisted(&self, sequence_number: SequenceNumber) -> bool {
Strictly speaking this should work and is true. However, because partitions can be persisted out of order, it would be better to check if a given partition id is persisted up to that sequence number. That can actually be answered via the catalog alone. Although if this is just going to be used for e2e test driving then I think it's ok.

2022-04-05 23:37 UTC, alamb commented on ingester/src/data.rs
> +    async fn update_progress(&self, mut progress: SequencerProgress) -> SequencerProgress {
I don't have any particular reason for doing it this way rather than say returning a `SequencerProgress` and aggregating it explicitly. Thus just seemed more functional to me. My mind may have been poisoned by rust 🤔

2022-04-05 23:38 UTC, alamb commented on ingester/src/data.rs
> +    fn to_sequencer_id(kafka_partition: KafkaPartition) -> SequencerId {
I agree -- the reason it is needed is spelled out in https://github.com/influxdata/influxdb_iox/issues/4237 (namely that when the write buffer says "sequencer_id = 5" it means (from the ingester's perspective) that kafka_partiton = 5 (not sequencer_id = 5)

2022-04-05 23:40 UTC, alamb commented on write_summary/src/progress.rs
> +    pub fn persisted(&self, sequence_number: SequenceNumber) -> bool {
The feeback I got on https://docs.google.com/document/d/1VFB7xmVn_ezet0gzFxE9x5pNS-1IhXi26OQOWsjn5OU/edit?disco=AAAAWWmxENQ was that tracking write info on a per-partition basis was too fine grained and thus I only track per-sequencer information.

Thus, since I don't have partition ids I can't do the check per partition and so the test is conservative.

2022-04-05 23:40 UTC, alamb commented on ingester/src/data.rs
> +    async fn update_progress(&self, mut progress: SequencerProgress) -> SequencerProgress {
I can change it so structs are passed back up and aggregated if you prefer

2022-04-05 23:44 UTC, alamb commented on ingester/src/data.rs
> +            let desired_partition = KafkaPartition::new(sequencer_id.get().into());
> The SequencerId used in the map is the actual catalog id. This function should be taking a vec of KafkaPartition.

I will change the signature of this function to use `KafkaPartition`. That is a good idea to minimize the confusion

>  Either that or it should be taking in the sequencer ids and looking up in the map based on that. The confusion I was talking about is in the metric label naming, not in the types used in either the router or the ingester.  Both places should be using the correct types everywhere. 

I don't think this is accurate. `sequencer_id` refers to kafka partition in the `dat_types::Sequence` type (stored in the `DmlMeta` structure, for example 

https://github.com/influxdata/influxdb_iox/blob/main/data_types/src/sequence.rs#L1-L4

2022-04-06 10:50 UTC, alamb commented on ingester/src/data.rs
> +            let desired_partition = KafkaPartition::new(sequencer_id.get().into());
Fixed in 64db5f0b264b793e8a0fe07df84ee2aa6487eb8b

2022-04-06 10:50 UTC, alamb commented on ingester/src/data.rs
> +    async fn update_progress(&self, mut progress: SequencerProgress) -> SequencerProgress {
Changed to `update()` everywhere in 41906985f30a7990cc4a3820d39ff6d0d1c53d79

2022-04-06 10:50 UTC, alamb commented on ingester/src/data.rs
> +    fn to_sequencer_id(kafka_partition: KafkaPartition) -> SequencerId {
removed

2022-04-06 10:57 UTC, alamb commented on ingester/src/data.rs
> +    pub(crate) async fn progresses(
Note the API has been changed to take `KafkaPartition` rather than `SequencerId`

2022-04-06 11:08 UTC, domodwyer approved these changes
I was reviewing this as you changed it all! What time do you start working?! 😂 

Looks good now we're taking a `progress(KafkaPartition)` 👍

2022-04-06 11:08 UTC, domodwyer commented on write_summary/src/lib.rs
> +                    .unwrap_or(true)
When querying a single ingester with a set of sequence numbers, I think this line changes the semantics of the API from "Can I read this data?" to "Can I not read this data?" which is subtly different. 

As an example, imagine if there was an off-by-one misconfiguration and no ingester was responsible for sequencer number 100 - if you ask all the ingesters you would get back "YES you can read it" but it hasn't been ingested and cannot be read.

I understand not wanting to burden the client with having to know which ingesters are responsible for what sequence numbers however - I'm not proposing we change this behaviour but it's worth calling out.

2022-04-06 11:32 UTC, domodwyer commented on write_summary/src/lib.rs
> +                    .unwrap_or(true)
Perhaps we can return a "I am not responsible for this sequencer" value to the client (as opposed to failing the request). This means the client still doesn't need to know which ingester is responsible for what sequencer but does allow the client to discover this information if needed, and avoid a false "you can read it" positive response. I can't think of any downsides to this approach.

2022-04-06 11:51 UTC, alamb commented on write_summary/src/lib.rs
> +                    .unwrap_or(true)
I like the idea of distinguishing between "yes for sure", "no for sure" and "I don't know" -- I will make this change

2022-04-06 11:51 UTC, alamb commented
> I was reviewing this as you changed it all! What time do you start working?! 😂


Sorry about that!

2022-04-06 13:18 UTC, alamb commented on write_summary/src/lib.rs
> +                    .unwrap_or(true)
in c4cb0bce1

2022-04-06 13:44 UTC, domodwyer approved these changes
Looking good!

2022-04-06 13:54 UTC, pauldix commented on ingester/src/data.rs
> +    pub(crate) async fn progresses(
Ah, I didn't notice that was `SequencerId` before. So it was the OG data type, not the Catalog type.

2022-04-06 15:13 UTC, merged