WIP: Use the sort key stored in the catalog during compaction
influxdata/influxdb_iox pull request #4254
Opened 2022-04-07 20:28 UTC by carols10cents

Fixes #4249.

2022-04-08 15:12 UTC, alamb approved these changes
Looks good to me, but I think @NGA-TRAN  should also review prior to merging

2022-04-08 15:12 UTC, alamb commented on schema/src/sort.rs
> +                    Arc::new(StringArray::from(vec!["a", "b"])) as ArrayRef,
these tests might be easier to read with a helper like:

```rust
fn to_string_array(i: impl IntoIterator<Item=Option<&str>)) -> ArrayRef {
  let array = StringArray = i.into_iter().collect();
  Arc::new(array)
}
```

2022-04-08 16:06 UTC, NGA-TRAN requested changes
It looks good. Just need a bit of removing missing data columns from the `sort_key`

2022-04-08 16:06 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .expect("Partition sort key should have been available in the catalog");
I suggest after this line, you remove columns from the `sort_key` that are missing from PK of the `merged_schema`. By doing this, I think we will optimize DF plan building and execution, and also reduce the chance of bug introducing in DF because the sort key contains unknown columns of the input data.

Adding tests for this case would be helpful, too

2022-04-08 17:26 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .expect("Partition sort key should have been available in the catalog");
And you may want to panic if the `sort_key` does not include all PK columns of the `merged_schema` too

2022-04-10 10:37 UTC, alamb commented on iox_tests/src/util.rs
> +        Some(catalog_sort_key) => {
Makes sense -- sorry I didn't realize it was in test-only code. My bad

2022-04-11 18:24 UTC, carols10cents commented on compactor/src/compact.rs
> +            .expect("Partition sort key should have been available in the catalog");
I believe the `panic_logging` crate in iox makes sure panics are logged as a tracing span.

I've implemented the filtering in the last commit, I think this PR is ready for re-review now!

2022-04-12 15:47 UTC, NGA-TRAN commented on schema/src/sort.rs
> +        assert_eq!(expected, filtered);
👍

2022-04-13 12:51 UTC, merged