feat: Store parquet_metadata in catalog, but don't fetch it by default
influxdata/influxdb_iox pull request #4262
Opened 2022-04-08 17:59 UTC by carols10cents

Connects to #4124.

This is an incremental step to stop fetching the parquet_metadata column from the parquet_files table for most parquet_files queries, which should help with performance.

The places that do use the metadata are still fetching it and decoding it for now. For one place, I made a special `_with_metadata` catalog method. For the other place, I'm doing more queries to get each parquet file's metadata column. It was slightly easier to do each place this way, but not impossible to change either place to use the other technique, so let me know if you'd like me to make these consistent.

However, the next steps should be trying to move to using other catalog data instead of the parquet_metadata, so that change may be moot. These next steps are not trivial 😅 

If we end up removing all uses of the `parquet_metadata` column, then we can stop saving it in the catalog altogether, but this PR isn't there yet. If we decide to keep using `parquet_metadata`, I might recommend storing it in a different catalog table than `parquet_files` so that we don't have to remember not to do `SELECT *` on `parquet_files`.

2022-04-08 19:01 UTC, alamb commented
I plan to review this later this afternoon

2022-04-08 21:06 UTC, alamb approved these changes
I really like the idea of this incremental evolution 👍 nice work @carols10cents 

Someone with more experience with the catalog  and compactor code should probably review this, but it looks great to me

2022-04-08 21:06 UTC, alamb commented on data_types2/src/lib.rs
> +#[derive(Debug, Clone, Copy, PartialEq, sqlx::FromRow)]
👍  for making it copy once the metadata is no lonegr inlined

2022-04-08 21:06 UTC, alamb commented on iox_catalog/src/postgres.rs
> +        // Deliberately doesn't use `SELECT *` to avoid the performance hit of fetching the large
👍

2022-04-08 21:06 UTC, alamb commented on iox_catalog/src/metrics.rs
> +        "parquet_parquet_metadata" = parquet_metadata(&mut self, id: ParquetFileId) -> Result<Vec<u8>>;
such `parquet`!

I wonder if this should be `parquet_metadata` rather than the double `parquet_parquet_metadata`?

2022-04-11 08:49 UTC, crepererum approved these changes
Good first step! :)

2022-04-11 14:25 UTC, carols10cents commented on compactor/src/compact.rs
> +        let mut query_chunks = Vec::with_capacity(overlapped_files.len());
Yeah, that would be annoying to `zip` back together again though. I think I'm going to do the same thing here for `list_by_partition_not_to_delete` that I did for  `list_by_table_not_to_delete`; adding a `_with_metadata` version.

2022-04-11 14:27 UTC, carols10cents commented on iox_catalog/src/metrics.rs
> +        "parquet_parquet_metadata" = parquet_metadata(&mut self, id: ParquetFileId) -> Result<Vec<u8>>;
Sure! I think this is just the metric name so it can be whatever.

2022-04-12 16:21 UTC, NGA-TRAN requested changes
The PR looks good. We only need to not use `withMetadata` in the Compactor

2022-04-12 16:21 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .list_by_partition_not_to_delete_with_metadata(partition_id)
We do not need `column metadata` during compaction. I think most places do not need them. Do you think you can modify the catalog (Postgres and memory) to replace `select *` with select specific columns? Otherwise, the compactor performance will suffer here.

2022-04-12 16:21 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        mut parquet_files: Vec<ParquetFileWithMetadata>,
Same here and all other places in the compactor, we do not want `ParquetFileWithMetadata`. `ParquetFile` is good enough help with better performance and less memory usage

2022-04-12 16:21 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        groups: Vec<Vec<ParquetFileWithMetadata>>,
Same

2022-04-12 16:21 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            .list_by_table_not_to_delete_with_metadata(table.table.id)
I know this is only  a test but if you have `list_by_table_not_to_delete`, use it instead

2022-04-12 16:21 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        ParquetFileWithMetadata {
same here. No metadata needed

2022-04-13 14:55 UTC, NGA-TRAN approved these changes
Ah, It makes sense. Looks good then

2022-04-13 15:38 UTC, merged