Simplify object_store path handling
influxdata/influxdb_iox pull request #4534
Opened 2022-05-07 20:26 UTC by tustvold

*Draft as I'll take another pass if we like where this is headed*

Whilst reviewing the object store abstraction from the perspective of using it in Datafusion (https://github.com/apache/arrow-datafusion/issues/2445) a couple of pain points cropped up that would make it quite painful to use for this purpose:

* The use of enumerations would make out-of-crate extension impossible, e.g. to add HDFS support
* Paths can't be created without knowledge of the object store they are for

Fortunately with the change made by @crepererum in https://github.com/influxdata/influxdb_iox/pull/3393 we treat all paths the same, and no longer need any notion of directory vs file. Not only does this solve the above problem, but is also eliminates a whole host of complexity. Unfortunately we use paths in a LOT of places... I think this is definitely an "oh lawd he comin"...

2022-05-08 12:17 UTC, alamb reviewed
I skimmed a bunch of the changes in usage of the ObjectStore and I think it looks great

I did not scrutinize the implementation but overall I like where this is headed 👍

2022-05-08 12:17 UTC, alamb commented on iox_object_store/src/lib.rs
> +        Path::from_iter([
`from_iter` certainly looks good to me 👍

2022-05-08 14:38 UTC, tustvold commented on clap_blocks/src/object_store.rs
> +#[cfg(feature = "gcp")]
This logic is moved into here to simplify the object_store crate, and make it easier for external consumption. If a feature isn't enabled, you will get a compile error

2022-05-08 14:38 UTC, tustvold commented on iox_object_store/src/paths/parquet_file.rs
> +            .child("00000000-0000-0000-0000-00000000000a.parquet")
Because we no longer distinguish between directories and filenames, we need an additional level to get the UnexpectedDirectory error, otherwise we would just get InvalidChunkId.

2022-05-08 14:38 UTC, tustvold commented on object_store/src/aws.rs
> +        let raw_prefix = prefix.map(|p| format!("{}{}", p.to_raw(), DELIMITER));
We add the trailing delimiter to the path name, so that we don't need to perform additional filtering afterwards

2022-05-08 14:38 UTC, tustvold commented on object_store/src/aws.rs
> -                        .filter(move |meta_res| match meta_res {
The trailing delimiter is included in the request, so we don't need to do this anymore

2022-05-08 14:38 UTC, tustvold commented on object_store/src/cache.rs
> -//! This module contains a trait and implementation for caching object storage objects
The cache functionality is not implemented and so I just took the opportunity to remove it

2022-05-08 14:38 UTC, tustvold commented on object_store/src/buffer.rs
> -//! This module contains a `Stream` wrapper that fully consumes (slurps) a
This doesn't seem to be used, so just removed it

2022-05-08 14:38 UTC, tustvold commented on object_store/src/disk.rs
> +        let walkdir = WalkDir::new(&resolved_prefix).min_depth(1).max_depth(1);
This technically could just list a directory, but I kept it using WalkDir for consistency

2022-05-08 14:38 UTC, tustvold commented on object_store/src/dummy.rs
> -/// Stub when s3 is not configured
This code is moved into clap_blocks as it is really a quirk of the IOx binary build, and would be confusing in an externally published object_store crate

2022-05-08 14:38 UTC, tustvold commented on object_store/src/gcp.rs
> +        assert!(err.contains("Unable to DELETE data"), "{}", err)
Interestingly this is a different behaviour from S3

2022-05-08 14:38 UTC, tustvold commented on object_store/src/lib.rs
> -pub struct ObjectStoreImpl {
ObjectStoreApi is now object-safe, and so this isn't needed

2022-05-08 14:38 UTC, tustvold commented on object_store/src/lib.rs
> +    #[snafu(display("Generic {} error: {}", store, source))]
This enumeration is made generic, so that ObjectStoreApi can be implemented outside of this crate

2022-05-08 14:38 UTC, tustvold commented on object_store/src/lib.rs
> +pub mod aws;
This structure is made public to make it easier to extend with object store specific structures, e.g. config

2022-05-08 14:38 UTC, tustvold commented on object_store/src/lib.rs
> +#[cfg(test)]
This is only needed in tests now

2022-05-08 14:38 UTC, tustvold commented on object_store/src/instrumentation.rs
> +        inner: Arc<dyn ObjectStoreApi>,
This needed to be changed to `Arc<dyn ObjectStoreApi>` as previously it worked because `ObjectStoreImpl` was a concrete type. This is no longer the case with, the clap_blocks::object_store returning `Arc<dyn ObjectStoreApi>`

This would mean either implementing `ObjectStoreApi` for `Arc<dyn ObjectStoreApi>` or just passing this `Arc<dyn ObjectStoreApi>` directly. The latter was less code and seemed simpler.

As we made this change, it made sense to just do the same for `TimeProvider`.

2022-05-08 14:38 UTC, tustvold commented on object_store/src/path/parts.rs
> -            "" => Self(String::from(EMPTY)),
We no longer allow empty path segments within `Path`

2022-05-08 14:38 UTC, tustvold commented on object_store/src/path/parts.rs
> +pub struct PathPart<'a> {
This is made `Cow` to allow `Path` to split up its owned `String` into an iterator of `PathPart` without copying

2022-05-08 14:38 UTC, tustvold commented on object_store/src/path/mod.rs
> +    pub fn parts(&self) -> impl Iterator<Item = PathPart<'_>> {
There is a subtlety to this design worth highlighting.

Constructing a `PathPart` from a string escapes the provided string, `Path::from_iter` takes an iterator of things convertible to `PathPart`. By returning an iterator of `PathPart` instead of an iterator of `&str` we allow constructions like

`Path::from_iter(other_path.parts().take(1))`

Without this resulting in double-escaping

2022-05-08 14:38 UTC, tustvold commented on object_store/src/path/parsed.rs
> -mod tests {
These tests are adapted and moved into mod.rs

2022-05-08 14:38 UTC, tustvold commented on object_store/src/path/cloud.rs
> -#[cfg(test)]
These tests are moved into mod.rs

2022-05-08 14:38 UTC, tustvold commented on object_store/src/path/file.rs
> -mod tests {
These tests are no longer relevant as we don't distinguish between directories and files

2022-05-09 15:53 UTC, carols10cents requested changes
This generally looks ok to me, there's one failing test for me and a few things that look out of date or redundant now.

Changing from the enum to be trait-based to be extensible makes sense!

Some things to think about in regards to open-sourcing this and using it outside of IOx, for future PRs:

- There's still use of the environment variable `INFLUXDB_IOX_BUCKET` in the integration tests
- It'd be really good to actually do integration testing with the services in CI, but that gets... interesting...
- It'd be good to test the local file system object store with Windows in CI too
- To be friendly to people who want to extend this, it'd be nice to write up a guide with instructions and explanation of the semantics of implementors of the trait
- Should the object_store crate continue to live in this repo or should it get its own? Either way, it should probably have its own README

2022-05-09 15:53 UTC, carols10cents commented on object_store/src/path/mod.rs
> +    }
These two tests are the same now, since adding a trailing delimiter is now part of each object store's implementation. So I think one can be deleted?

2022-05-09 15:53 UTC, carols10cents commented on object_store/src/path/parts.rs
> -            "" => Self(String::from(EMPTY)),
What do you mean by "no longer allow"? I can do `let part: PathPart<'_> = "".into();` and I don't get any errors or panics, and the test case for that was removed.

2022-05-09 17:29 UTC, tustvold commented on object_store/src/gcp.rs
> +        assert!(err.contains("Unable to list data"), "{}", err)
Aah... I did not realise we don't test that in CI...

2022-05-09 17:47 UTC, tustvold commented on object_store/src/path/mod.rs
> +        // All directories match but file name is not a prefix
:eagle: :eye:

2022-05-09 18:06 UTC, tustvold commented
> Some things to think about

Yup, there definitely will be further changes to get this ready for publication. Thanks for enumerating some of them for me :grin:

2022-05-09 18:43 UTC, merged