feat: Add ingester CLI and env option to skip to oldest available WB seq num
influxdata/influxdb_iox pull request #4638
Opened 2022-05-19 00:59 UTC by carols10cents

Fixes #4624.

The default behavior of the ingester is to panic if the min unpersisted sequence number in the catalog is unknown to the write buffer due to the retention policies having evicted that sequence number.

Specifying `--skip-to-oldest-available` changes this behavior to skip to the oldest sequence number the write buffer does have available and go from there.

Before this PR, the `IngestHandlerImpl` would have the `WriteBufferStreamHandler`  create a stream of writes from the write buffer and pass that stream to the `SequencedStreamHandler`.

This PR instead has the `IngestHandlerImpl` give the `WriteBufferStreamHandler` to the `SequencedStreamHandler` to hold. That way, when the `SequencedStreamHandler` gets the "unknown sequence number" error from the stream (and if the CLI option is set), the `SequencedStreamHandler` can call a new `reset_to_earliest` method on `WriteBufferStreamHandler` and then ask `WriteBufferStreamHandler` to create a new stream.

There's a `reset_to_earliest_once` boolean that should prevent an infinite loop of resetting to earliest and still getting the "unknown sequence number" error; I'm not sure if/how that would be possible but it seemed like a good thing to try and prevent just in case.

2022-05-19 15:02 UTC, crepererum commented on write_buffer/src/core.rs
>  }
I know this is WIP, just wanted to say that the interface changes look good :+1:

2022-05-19 18:41 UTC, alamb reviewed
I think @domodwyer  is the most familiar with the ingester code and is the best reviewer for this PR

2022-05-19 18:41 UTC, alamb commented on influxdb_iox/src/commands/run/all_in_one.rs
> +        let skip_to_oldest_available = true;
💯

2022-05-20 07:15 UTC, crepererum commented on clap_blocks/src/ingester.rs
> +        env = "INFLUXDB_IOX_SKIP_TO_OLDEST_AVAILABLE"
IMHO that's a dangerous trap. We can do that for our current prod deploy if we want, but on the long run prod shouldn't do that. If we "forget"/loose data because the ingester was down for that long, I would like to get paged because that means that we might need to open a customer-visible incident.

2022-05-20 07:21 UTC, crepererum requested changes
write buffer needs a test

2022-05-20 07:21 UTC, crepererum commented on write_buffer/src/core.rs
> +    fn reset_to_earliest(&mut self);
This needs a generic test here in `core.rs`. The most basic version would just test that a call to this jumps back to the earliest sequence number (which is likely 0).

However I would like if we could actually have a test that involves deleting/forgetting data. For that we would need to extend `TestContext` with some "delete entries prior to X" method. We have all the functionality in place (for all WB implementations) to achieve that, it's just not wired up. If you want I can implement that. If you wanna have this PR merged fast, just implement the easy test (= reset to 0), open a follow-up ticket for the advanced test (= interaction w/ deletes) and assign that that to me.

2022-05-20 10:48 UTC, alamb commented on clap_blocks/src/ingester.rs
> +        env = "INFLUXDB_IOX_SKIP_TO_OLDEST_AVAILABLE"
> If we "forget"/loose data because the ingester was down for that long, I would like to get paged because that means that we might need to open a customer-visible incident.

I agree this is a serious issu

It is probably worth thinking about  if it is better to get the service back up (possibly with some data loss) than or cause an outage. That is probably not a strictly technical decision

2022-05-20 11:43 UTC, domodwyer commented
I intend to review this shortly - thanks @carols10cents 👍

2022-05-20 13:44 UTC, domodwyer approved these changes
```
       ┌─┐ 
       ║"│ - looks great!!
       └┬┘ 
       ┌┼┐ 
        │  
       ┌┴┐ 
```

2022-05-20 13:44 UTC, domodwyer commented on ingester/src/stream_handler/handler.rs
> +
Perhaps this could live in the match for `WriteBufferErrorKind::UnknownSequenceNumber` in the block below to keep all the "if this error happens" logic together :+1:

2022-05-20 13:44 UTC, domodwyer commented on ingester/src/stream_handler/handler.rs
> +            let maybe_op = match dbg!(maybe_op) {
Sneaky sneaky!

2022-05-20 13:44 UTC, domodwyer commented on write_buffer/src/core.rs
> +impl WriteBufferStreamHandler for Box<dyn WriteBufferStreamHandler> {
❤️ thank you for preserving the `Steam` handler impl (rather than ripping it out and replacing it with the box)

2022-05-20 13:44 UTC, domodwyer commented on ingester/src/stream_handler/handler.rs
> +            stream_ops = $stream_ops:expr,  // Ordered set of stream items to feed to the handler
I feel scrutinised 🔍  :joy:

2022-05-20 13:44 UTC, domodwyer commented on write_buffer/src/core.rs
> +    fn reset_to_earliest(&mut self);
Do you think this could return the (approximate?) number of ops skipped - that'd help us derive a finger-in-the-air kind of estimate as to how much we jumped.

I'm aware the offset can jump forwards due to internal messages and therefore `offset delta != write loss count`, but it would still provide an approximation of the magnitude of data loss. 

This could be exposed as a metric in the ingest stream handler, which when >0 means we have a problem and we can alert off of it.

2022-05-20 14:50 UTC, carols10cents commented on write_buffer/src/core.rs
> +    fn reset_to_earliest(&mut self);
🤦🏻‍♀️ I felt like I was forgetting something! I should have re-read the issue before posting. You very clearly said there should be a metric :)

2022-05-20 17:03 UTC, carols10cents commented on ingester/src/stream_handler/handler.rs
> +            let maybe_op = match dbg!(maybe_op) {
whoopsie!

2022-05-20 17:04 UTC, carols10cents commented on ingester/src/stream_handler/handler.rs
> +            stream_ops = $stream_ops:expr,  // Ordered set of stream items to feed to the handler
lol I can't handle lines being longer than 100 chars 😅

2022-05-20 17:21 UTC, carols10cents commented on write_buffer/src/core.rs
> +    fn reset_to_earliest(&mut self);
Hmmm so I don't think I can implement this in `reset_to_earliest` for the kafka implementation, because we don't actually know what the earliest is until we next try to fetch a record....... thinking.....

2022-05-20 17:40 UTC, carols10cents commented on write_buffer/src/core.rs
> +    fn reset_to_earliest(&mut self);
Taking the easy way out; filed this issue ;) https://github.com/influxdata/influxdb_iox/issues/4651

2022-05-21 00:35 UTC, carols10cents commented
Ok, I think this is ready for rereview now. The test for the metric was...... interesting.... channels and streams everywhere.

2022-05-23 08:23 UTC, crepererum approved these changes

2022-05-23 09:57 UTC, domodwyer approved these changes
I took a quick look at the metrics (and test channel extravaganza!) and looks fantastic to me - thanks @carols10cents 👍

2022-05-23 09:57 UTC, domodwyer commented on ingester/src/stream_handler/handler.rs
> +        ));
Nice - this metric will automatically turn up on the dashboards 🎉

2022-05-23 13:14 UTC, merged