feat: Implement gRPC and storage interface for read_group_aggregate
influxdata/influxdb_iox pull request #474
Opened 2020-11-23 16:25 UTC by alamb

Rationale: We need to implement the `read_window_aggregate` gRPC service (#449) to provide Flux (and maybe InfluxQL)  compatible group push down with the other storage engines (OSS and Cloud).

See the the design [spec](https://docs.google.com/document/d/1yY2CcicBK32rUkS8VQtHztGCJJhnU-pO_NAwThKa6Jc/edit#) for supporting `read_window_aggregate`

This PR implements:
* Storage interface: `storage/src/groupby.rs`
* gRPC --> storage interface translation (including input validation)
* storage --> gRPC data translation
* Capability and capability response claiming support for window aggregates (which isn't quite true yet, but will be)

After this PR, the only thing left to do is actually hooking this up into the write buffer for plan execution.

Here is how this PR fits into past and planned PRs:

- [x] Update the protobuf definitions: (https://github.com/influxdata/influxdb_iox/pull/444)
- [x] Implement window_bounds from the Go code. (https://github.com/influxdata/influxdb_iox/pull/460)
- [x] Implement gRPC trappings and translation (this PR)
- [ ] Implement read_window_aggregate plan in write_buffer_database, and add end-to-end test

2020-11-23 16:32 UTC, alamb commented on src/server/rpc/expr.rs
> +pub fn make_read_group_aggregate(
This module has most of the actual input validation checking -- it is thrilling stuff

2020-11-23 16:32 UTC, alamb commented on src/server/rpc/storage.rs
> +            group,
Given my understanding of how `read_group` and `read_window_aggregate` work, they can share most of the query execution path (aka they are both aggregations, the major differences is grouping and aggregate) -- so that is how this code is structured -- to share a common implementation

2020-11-23 16:32 UTC, alamb commented on src/server/rpc/storage.rs
>      async fn read_window_aggregate(
here is the newly implemented gRPC implementation (though the write buffer database doesn't implement this kind of query yet)

2020-11-23 16:32 UTC, alamb commented on storage/src/groupby.rs
> +//! This module contains definitionsf or Timeseries specific Grouping
```suggestion
//! This module contains definitions for Timeseries specific Grouping
```

2020-11-23 16:32 UTC, alamb commented on storage/src/groupby.rs
> +//! InfluxDB
```suggestion
//! InfluxDB classic
```

2020-11-23 16:32 UTC, alamb commented on storage/src/groupby.rs
> +    /// The bounds are then calculated at a high leve by
```suggestion
    /// The bounds are then calculated at a high level by
```

2020-11-23 16:32 UTC, alamb commented on storage/src/groupby.rs
> +    /// specifics of the Duration
```suggestion
    /// specific Duration
```

2020-11-23 16:32 UTC, alamb commented on storage/src/lib.rs
> +        gby_agg: GroupByAndAggregate,
this is the major interface change to the query layer -- it now take a structure that has group by and aggregate information

2020-11-23 16:32 UTC, alamb commented on write_buffer/src/database.rs
> +                unimplemented!("query groups with window aggregates are not yet implemented");
Removing this will be the subject of the next PR
![giphy](https://user-images.githubusercontent.com/490673/99988378-8e835400-2d7f-11eb-95d1-7a01efd60ccb.gif)

2020-11-23 19:11 UTC, carols10cents requested changes

2020-11-23 19:11 UTC, carols10cents commented on src/server/rpc/storage.rs
> +        let mut expected_capabilities: HashMap<String, Vec<String>> = HashMap::new();
Ah yeah this is pretty much what I was suggesting above ;) Which then leads me to wonder if this test is worthwhile because it's now testing that the same values are hardcoded in two places, hmm....

2020-11-23 19:11 UTC, carols10cents commented on src/server/rpc/storage.rs
> +            gby_agg : GroupByAndAggregate::Columns {
```suggestion
            gby_agg: GroupByAndAggregate::Columns {
```

I would have expected rustfmt to catch this, hmm

2020-11-23 19:11 UTC, carols10cents commented on src/server/rpc/storage.rs
> +            gby_agg : GroupByAndAggregate::Window {
```suggestion
            gby_agg: GroupByAndAggregate::Window {
```

2020-11-23 19:11 UTC, carols10cents commented on src/server/rpc/storage.rs
> +        // Test with window.every and window.offset durations specified
Another case where the comments seem like they'd be better as new test functions? Is there setup being shared?

2020-11-23 19:11 UTC, carols10cents commented on src/server/rpc/storage.rs
> +            gby_agg : GroupByAndAggregate::Window {
```suggestion
            gby_agg: GroupByAndAggregate::Window {
```

2020-11-23 19:11 UTC, carols10cents commented on src/server/rpc/storage.rs
> +            Ok(vec![s])
This is a test helper function that you could choose to write however you wanted, right? And this is testing the number of aggregate_frames that are returned? Why return the value you want to test as a string in a one-element vector rather than returning `Ok(data_frames.len())`? Or is this a placeholder for future expansion...?

2020-11-23 19:11 UTC, carols10cents commented on tests/end-to-end.rs
> +    // Note: it is almost certain that the read group response is incorrect
😂

2020-11-23 20:54 UTC, alamb commented on src/server/rpc/expr.rs
> +                location: "window.every".into(),
I think the strings are only getting allocated when an actual error occurs (they are in a closure on `map_err` rather than a snafu `context` call. 

I think your suggestion of two separate error types is the way to go -- thank you - I will make it happen.

I just need to figure out how to do proper snafu error handling without messing up the flow when I am coding -- having to switch to the top of the file, add some new type, name fields and format strings whenever I make a function call 😓

2020-11-23 20:54 UTC, alamb commented on src/server/rpc/expr.rs
> +    };
Seems reasonable and it works. Adding in ab36576c9156592d6ad128742e49cb8620c58766

2020-11-23 20:54 UTC, alamb commented on src/server/rpc/expr.rs
> +fn convert_duration(duration: Option<RPCDuration>) -> Result<WindowDuration, &'static str> {
@carols10cents  - I did it this way because I wanted context here (namely what field was being converted using `convert_duration`) but context of the call *within* the same module; I couldn't figure out an elegant way of using Snafu to do so. 

The options I considered were
1. Make a new snafu error type just for thus function (that I could use as the `source` field in the module error type)
2. Use `source: Box::<Error>` in the module error type, which still didn't seem to allow me to use `ResultExt::except`

I am probably missing something. Also as an aside, is there any way to easily find all the methods available on a `#snafu`'d type? rust_analyzer seems to have problems with the macros, and the docs https://docs.rs/snafu/0.6.9/snafu/index.html have reference about how Snafu is implemented, and examples of how to use it, but not reference of the generated types

2020-11-23 20:54 UTC, alamb commented on src/server/rpc/expr.rs
> +    match (duration.nsecs != 0, duration.months != 0) {
I like this suggestion -- i will refactor. Thank you @carols10cents

2020-11-23 20:54 UTC, alamb commented on src/server/rpc/expr.rs
> +    let storage_aggregate = match convert_aggregate_type(aggregate.r#type)? {
It was to avoid having to repeat `r#type` many times. However, I think I can make this look better. I'll give it a shot

2020-11-23 20:54 UTC, alamb commented on src/server/rpc/expr.rs
> +        // now window specified
the reason to keep it in a single test was that it was testing a single function - `make_read_window_aggregate`

It was much shorter (in terms of lines) before `rustfmt` ...

2020-11-23 21:05 UTC, alamb commented on src/server/rpc/expr.rs
> +use storage::groupby::{Aggregate as StorageAggregate, GroupByAndAggregate};
https://github.com/influxdata/influxdb_iox/pull/477

2020-11-23 21:14 UTC, alamb commented on src/server/rpc/storage.rs
> +            Ok(vec![s])
yes this is a test helper

good eyes -- it is indeed a test for future expansion -- namely if I wanted to test the integration of the code to translate the query results back into gRPC structures (SeriesFrame, etc).

This code is is shamefully copy/pasted from `read_filter` I believe

2020-11-24 18:01 UTC, e-dard approved these changes
Looks great!

2020-11-24 18:37 UTC, alamb commented on src/server/rpc/expr.rs
> +    if aggregate_type == RPCAggregateType::None as i32 {
The annoying part is that I don't think I can make a `From<RPCAggregate>` implementation unless I put it in `groupby.rs` (b/c the `RPCAggregate` type is defined in some module by generated code. I would prefer not to have a dependency from storage --> rpc gunk. There is already a dependency in the other direction

2020-11-24 18:40 UTC, alamb commented on storage/src/exec/seriesset.rs
> +//! NOTE: The InfluxDB classic storage engine not only returns
Hopefully it has somewhat more staying power...

2020-11-24 18:41 UTC, merged

2020-11-24 18:49 UTC, domodwyer approved these changes
Looks good - I have a couple questions to figure out how we write stuff more than actual code comments!

2020-11-24 18:49 UTC, domodwyer commented on src/server/rpc/expr.rs
> +    let agg = convert_aggregate(Some(aggregates.into_iter().next().unwrap()))?;
Do we want to explicitly panic if the vec is empty? If not, how about:

```suggestion
    let agg = convert_aggregate(aggregates.into_iter().next())?;
```

2020-11-24 18:49 UTC, domodwyer commented on src/server/rpc/expr.rs
> +fn convert_aggregate(aggregate: Option<RPCAggregate>) -> Result<StorageAggregate> {
With the preface of "I'm not totally sure what I'm looking at yet", what's the reasoning for not leveraging [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) for these types of conversions? My go to "I need X in the form of Y" would have me looking at the docs for a `From`/`TryFrom` implementation rather than an explicit conversion func. 

I had a quick play and tried adding the following to `storage/src/groupby.rs`, mostly to satisfy my own curiosity:

```rust
#[derive(Debug, Snafu)]
pub enum Error {
    #[snafu(display("Error creating aggregate: Unsupported none aggregate"))]
    NoneAggregate {},

    #[snafu(display("Error creating aggregate: Unknown aggregate type {}", aggregate_type))]
    UnknownAggregate { aggregate_type: i32 },
}

use generated_types::{aggregate::AggregateType as RPCAggregateType, Aggregate as RPCAggregate};
use snafu::Snafu;
use std::convert::TryFrom;

impl TryFrom<RPCAggregate> for Aggregate {
    type Error = Error;

    fn try_from(aggregate: RPCAggregate) -> Result<Self, Self::Error> {
        let aggregate_type = aggregate.r#type;

        if aggregate_type == RPCAggregateType::None as i32 {
            NoneAggregate {}.fail()
        } else if aggregate_type == RPCAggregateType::Sum as i32 {
            Ok(Aggregate::Sum)
        } else if aggregate_type == RPCAggregateType::Count as i32 {
            Ok(Aggregate::Count)
        } else if aggregate_type == RPCAggregateType::Min as i32 {
            Ok(Aggregate::Min)
        } else if aggregate_type == RPCAggregateType::Max as i32 {
            Ok(Aggregate::Max)
        } else if aggregate_type == RPCAggregateType::First as i32 {
            Ok(Aggregate::First)
        } else if aggregate_type == RPCAggregateType::Last as i32 {
            Ok(Aggregate::Last)
        } else if aggregate_type == RPCAggregateType::Mean as i32 {
            Ok(Aggregate::Mean)
        } else {
            UnknownAggregate { aggregate_type }.fail()
        }
    }
}
```

Then the calls to `convert_aggregate()` instead become:

```rust
pub fn make_read_group_aggregate(
    aggregate: Option<RPCAggregate>,
    _group: RPCGroup,
    group_keys: Vec<String>,
) -> Result<GroupByAndAggregate> {
    let gby_agg = GroupByAndAggregate::Columns {
        agg: aggregate
            .ok_or(EmptyAggregate {})
            .map(StorageAggregate::try_from)??,
        group_columns: group_keys,
    };
    Ok(gby_agg)
}
```

This makes no material difference I believe, beyond moving the errors around a bit which you might not want. The only upside is the reflexive `TryInto` implementation which I don't think is needed, so this is more of a question of code style and learning how we write stuff I guess :)

2020-11-24 18:57 UTC, alamb commented on src/server/rpc/expr.rs
> +    let agg = convert_aggregate(Some(aggregates.into_iter().next().unwrap()))?;
I think check above for `aggregates.len() == 1` covers the empty case, but in general I don't like this pattern to de-"destruture" a Vec, but sadly I don't know any better way

However the change to avoid unwrap is nice -- I'll do that in a follow on PR

2020-11-24 18:59 UTC, alamb commented on src/server/rpc/expr.rs
> +fn convert_aggregate(aggregate: Option<RPCAggregate>) -> Result<StorageAggregate> {
I think I learned something new today -- `TryFrom` sounds like a better plan. I'll take a shot at that in a follow on PR

2020-11-24 19:04 UTC, alamb commented on src/server/rpc/expr.rs
> +fn convert_aggregate(aggregate: Option<RPCAggregate>) -> Result<StorageAggregate> {
Oh, so what I would like to do is avoid a dependency from the query layer back to the RPC implementations -- I would like to avoid a dependency in `storage/src/groupby.rs` back to generated types. Not that there is anything wrong with that other than a general preference to minimize dependencies. 

I still think we can make it look nicer. PR coming...

2020-11-24 19:18 UTC, alamb commented on src/server/rpc/expr.rs
> +fn convert_aggregate(aggregate: Option<RPCAggregate>) -> Result<StorageAggregate> {
hmm, my attempts did not produce any better code.

@domodwyer  I would be happy tp merge in any improvements you have in this area -- I have probably an unecessary desire to keep the compilation units smaller (aka not have one single crate) to keep re-compile / test cycles down... But I know that is likely an old fashioned desire.