fix: optimize field columns for all-time predicates
influxdata/influxdb_iox pull request #5046
Opened 2022-07-05 23:20 UTC by lesam

Also fix timestamp range to allow selecting points at MAX_NANO_TIME

Closes #4827 

Describe your proposed changes here.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).

2022-07-05 23:25 UTC, lesam commented on iox_query/src/frontend/influxrpc.rs
> +                    last_timestamp: 0,
I could make this the system `now` time, but I think a constant signalling value would be better since it is much more clear to our users that it does not represent the time of any particular field value. `MIN_NANO_TIME` or `MAX_NANO_TIME` might also be good but zero was nicely 'default-y'.

2022-07-05 23:33 UTC, lesam commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
Note this change!

2022-07-05 23:34 UTC, lesam commented on predicate/src/lib.rs
> +            if range.start() <= MIN_NANO_TIME && range.end() == i64::MAX {
Note this change!

2022-07-06 00:05 UTC, lesam commented on predicate/src/lib.rs
> +            if range.start() <= MIN_NANO_TIME && range.end() > MAX_NANO_TIME {
Note also this change!

2022-07-06 07:21 UTC, crepererum requested changes

2022-07-06 07:21 UTC, crepererum commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
This sounds really hackish to me. If you wanna allow no time restriction at all, then use `Option<TimestampRange>`.

We clamp it because `i64` is NOT a valid nanosecond range (now that I write that I think the clamping is actually incomplete, `start` must also be clamped by `MAX_NANO_TIME` and `end` must also be clamped by `MIN_NANO_TIME`). Otherwise other parts of the stack will likely explode when constructing filter predicates based on this data. Since this type is used for other requests as well, I suspect a user can now send out-of-bounds values and either get an error or (even worse) get the querier to panic.

2022-07-06 07:21 UTC, crepererum commented on service_grpc_influxrpc/src/service.rs
> +            range: Some(make_timestamp_range(i64::MIN, i64::MAX - 1)),
This is what I meant with typing: Use `None` if you actually mean "no restriction", not some magic out-of-bounds values.

2022-07-06 09:45 UTC, lesam commented on service_grpc_influxrpc/src/service.rs
> +            range: Some(make_timestamp_range(i64::MIN, i64::MAX - 1)),
This is actually just to avoid the 'optimized' case so the test doesn't change. This filter says 'range is all time except `i64::MAX-1`. Passing `None` still works fine and would actually mean 'all time'.

2022-07-06 10:08 UTC, lesam commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
I disagree about clamping by MAX_NANO_TIME (though I agree we probably should clamp end by MIN_NANO_TIME for safety).

The definition for MAX_NANO_TIME:

```
/// maximum time that can be represented.
///
/// 2262-04-11 23:47:16.854775806 +0000 UTC
///
/// The highest time represented by a nanosecond needs to be used for an
/// exclusive range in the shard group, so the maximum time needs to be one
/// less than the possible maximum number of nanoseconds representable by an
/// int64 so that we don't lose a point at that one time.
/// Source: [influxdb](https://github.com/influxdata/influxdb/blob/540bb66e1381a48a6d1ede4fc3e49c75a7d9f4af/models/time.go#L12-L34)
pub const MAX_NANO_TIME: i64 = i64::MAX - 1;
```

Filter expressions need to be able to express the time range 'all representable timestamps above 1000', since the end of the range is exclusive this is the range `{1000, MAX_NANO_TIME+1}` == `{1000, i64::MAX}`.

IDPE unfortunately gets this right for tag keys:

https://github.com/influxdata/idpe/blob/master/storage/store/store.go#L1395-L1397

But wrong for ReadFilter:

https://github.com/influxdata/idpe/blob/master/storage/store/store.go#L1086-L1088

2022-07-06 10:17 UTC, lesam commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
Flux does have the bounds correct:

https://github.com/influxdata/flux/blob/master/execute/bounds.go#L15-L28

2022-07-06 10:31 UTC, lesam commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
Filed https://github.com/influxdata/influxdb/issues/23519 for OSS2

2022-07-06 10:49 UTC, lesam commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
> now that I write that I think the clamping is actually incomplete, start must also be clamped by MAX_NANO_TIME and end must also be clamped by MIN_NANO_TIME

I agree end should also be clamped by MIN_NANO_TIME, fixed now.

2022-07-06 11:28 UTC, crepererum commented on data_types/src/lib.rs
> +    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
We had a quick 1:1 chat, I agree w/ @lesam 's statements here.

2022-07-06 11:29 UTC, lesam commented
Created https://github.com/influxdata/influxdb_iox/issues/5051

2022-07-06 12:01 UTC, merged