WIP: Select compaction candidates
influxdata/influxdb_iox pull request #5131
Opened 2022-07-14 17:32 UTC by NGA-TRAN

Closes #5105

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> -
Per new design, we do not have this value anymore  because we do not care how large all L-0 files are. We only pick to a few L0 to compact. As part of #5106, @carols10cents has planed to add more appropriate metrics.

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    compaction_query_most_l0_duration: Metric<DurationHistogram>,
These 2 queries are only 55ms for now but since we have  a concern they will grow, add metrics for them

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +                "Duration of catalog query that gets recent highest ingested throughput partitions",
```suggestion
                "Duration of a catalog query that gets the most recent highest ingested throughput partitions",
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +                "Duration of catalog query that gets partitions with the most l0 files",
```suggestion
                "Duration of a catalog query that gets partitions with the most level-0 files",
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    ///     The one with the most files will be first in the list.
```suggestion
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        // Number of most recent highest ingested throughput partitions
```suggestion
        //  Max number of the most recent highest ingested throughput partitions
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        num_partitions_per_sequencer: i32,
```suggestion
        max_num_partitions_per_sequencer: i32,
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        // Minimum number of most recent writes per partition we want to count
```suggestion
        // Minimum number of the most recent writes per partition we want to count
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            // get partition with the most level-0 file
```suggestion
            // get partition with the most level-0 files
```

2022-07-15 16:17 UTC, NGA-TRAN commented on compactor/src/compact.rs
> -
This struct includes fields we no longer need. The PartitionParam is used instead

2022-07-15 18:04 UTC, pauldix approved these changes
Does what we talked about for partition selection. I'll let others comment on Rust style & code specifics.

2022-07-15 18:50 UTC, carols10cents requested changes

2022-07-15 18:50 UTC, carols10cents commented on compactor/src/compact.rs
> +                "compaction_query_most_l0__duration",
It looks like there's an extra underscore in this metric name? 

```suggestion
                "compaction_query_most_l0_duration",
```

2022-07-15 18:50 UTC, carols10cents commented on compactor/src/compact.rs
> +    ///  1. If there are partitions with new writes within the last 4 hours, pick them.
Also through here, I think this "write" means "write of a parquet file to object storage" rather than `DmlWrite`:

```suggestion
    ///  1. If there are partitions with new persisted files within the last 4 hours, pick them.
```

2022-07-15 18:50 UTC, carols10cents commented on compactor/src/compact.rs
> +    #[ignore]
Why is this test ignored?

2022-07-15 18:50 UTC, carols10cents commented on iox_catalog/src/mem.rs
> +        partitions.truncate(num_partitions as usize);
This can be:

```suggestion
        let partitions = partitions.into_iter().map(|(k, _)| k).take(num_partitions as usize).collect::<Vec<_>>();
```

2022-07-15 18:50 UTC, carols10cents commented on iox_catalog/src/mem.rs
> +        // Partitions with select file count > min_num_files
I don't think this comment applies here because there isn't a `min_num_files` in the `most_level_0_files_partitions` query?

2022-07-15 18:50 UTC, carols10cents commented on iox_catalog/src/mem.rs
> +        partitions.truncate(num_partitions as usize);
Same here with `take` rather than `truncate`

2022-07-15 18:50 UTC, carols10cents commented on iox_catalog/src/metrics.rs
> +        "most_level_0_files_partitions" =  most_level_0_files_partitions(&mut self, sequencer_id: SequencerId, num_partitions: i32) -> Result<Vec<PartitionParam>>;
Wait a second, these metrics wrappers are automatically making duration metrics for these catalog operations, right? So the metrics in compactor are recording the same data and aren't really needed?

2022-07-15 18:50 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +    and to_timestamp(created_at/1000000000) > now() -  ($2 || 'hour')::interval
If this query ends up being slow, the first thing I would look at is if it's possible for us to compute the value that `created_at` should be compared to in Rust and pass it once rather than having Postgres do the math *and* the comparison

2022-07-15 19:22 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    ///  1. If there are partitions with new writes within the last 4 hours, pick them.
Will replace `writes` with `ingested files`

2022-07-15 19:22 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        minimun_recent_ingested_files: i32,
The Postgres function `recent_highest_throughput_partitions` require  integer. We can either cast i32 to usize or usize to i32

2022-07-15 19:22 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    #[ignore]
Good catch. Should not 😄

2022-07-15 19:22 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +            vec![sequencer.id],
will do

2022-07-15 19:22 UTC, NGA-TRAN commented on compactor/src/handler.rs
>                      if compact_and_upgrade.compactable() {
No, we do not need them. When the new `compaction_partition` available, we should not use these anymore

2022-07-15 19:22 UTC, NGA-TRAN commented on iox_catalog/src/mem.rs
> +        // Partitions with select file count > min_num_files
Good catch

2022-07-15 19:22 UTC, NGA-TRAN commented on iox_catalog/src/metrics.rs
> +        "most_level_0_files_partitions" =  most_level_0_files_partitions(&mut self, sequencer_id: SequencerId, num_partitions: i32) -> Result<Vec<PartitionParam>>;
This is interesting. I will need to read the code a bit more and see if it does what we want to remove other code

2022-07-15 19:22 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +    and to_timestamp(created_at/1000000000) > now() -  ($2 || 'hour')::interval
I do not think the concern is the work of Postgres doing the math. The concern is there are a lot of data that lead to a lot of comparison. 
If we compute something here, we can only compute the value for `now() -  ($2 || 'hour')::interval`. We do not know `created_at` and there are a lot of rows of data with different values of `created_at`.
Postgres will rewrite this query to compute `now() -  ($2 || 'hour')::interval` once and reuse for all rows. It is actually very cheap compared with the comparison work

2022-07-15 19:27 UTC, NGA-TRAN commented on clap_blocks/src/compactor.rs
> +    pub compaction_max_number_partitions_per_sequencer: i32,
The `COMPACTION` is helpful when I search `INFLUXDB_IOX_COMPACTION`. There are many `INFLUXDB_IOX_` environment flags

2022-07-15 19:30 UTC, carols10cents commented on clap_blocks/src/compactor.rs
> +    pub compaction_max_number_partitions_per_sequencer: i32,
Yes, the environment variable should have compaction in it, but the field name doesn't need it

2022-07-15 22:04 UTC, NGA-TRAN commented on iox_catalog/src/metrics.rs
> +        "most_level_0_files_partitions" =  most_level_0_files_partitions(&mut self, sequencer_id: SequencerId, num_partitions: i32) -> Result<Vec<PartitionParam>>;
You are right. I am going remove the other metrics

2022-07-15 22:11 UTC, NGA-TRAN reviewed
I have addressed all but one. Will do that next before asking for re-reviewing

2022-07-15 22:11 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +    #[ignore]
I will address this next. Somehow the time_provide does not match yet

2022-07-16 11:56 UTC, NGA-TRAN commented
@carols10cents It is ready for second round

2022-07-18 14:52 UTC, carols10cents commented on clap_blocks/src/compactor.rs
> +        env = "INFLUXDB_IOX_COMPACTION_MAX_NUMBER_PARTITION_PER_SEQUENCER",
The flag is named "compaction min number recent writes per partition", the environment variable is named "compaction *max* number partition per *sequencer*, and the struct field is named "min number recent ingested files per partition", I think these should all be consistent?

2022-07-18 14:57 UTC, carols10cents commented on compactor/src/compact.rs
> +        minimun_recent_ingested_files: i32,
It seems to me that casting in one place (in the postgres implementation of that function) is better than casting to usize in multiple places?

2022-07-18 15:07 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +    and to_timestamp(created_at/1000000000) > now() -  ($2 || 'hour')::interval
> We do not know created_at and there are a lot of rows of data with different values of created_at.

Right, I was saying compute the value that `created_at` *should be compared to*. That is, don't convert created_at `to_timestamp`, instead compute `now_nanos() - 2_hours_in_nanoseconds` in Rust, once, and make the condition here `created_at > $2` where ` $2 is the Rust-computed value of 2 hours ago in nanoseconds, then Postgres can do an integer comparison rather than a timestamp comparison (which my gut says should be faster). Again, though, I don't see a reason to do this unless we observe this query to be slow.

2022-07-18 15:22 UTC, carols10cents commented on clap_blocks/src/compactor.rs
> +    pub min_number_recent_ingested_files_per_partition: i32,
The flag and field name are still different from the environment variable? Flag and field name are "min number recent", the environment variable is "min recent number".

2022-07-18 16:05 UTC, NGA-TRAN commented on compactor/src/compact.rs
> +        minimun_recent_ingested_files: i32,
In addtition to these 2 values, I have made all relevant iSomethign in this struct  to uSomething

2022-07-18 16:25 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +    and to_timestamp(created_at/1000000000) > now() -  ($2 || 'hour')::interval
It is actually no that simple. Let us keep this for now. Only do this if  we hit the issue

2022-07-18 18:05 UTC, merged