feat: grouped aggregates for low-cardinality columns
influxdata/influxdb_iox pull request #527
Opened 2020-12-04 21:53 UTC by e-dard

## Background

This PR adds some initial support for `read_group` aggregates in Segment Store.
Currently it only supports one particular type of grouped aggregates; I will continue to add support for other cases until all general cases are covered.

Expressed in SQL, the kinds of read_group aggregate support (pinching a bit of InfluxDB terminology here...) added in this PR could be expressed in SQL like:

```sql
SELECT SUM(duration), COUNT(foo), MIN(bar) ...
FROM "cpu"
GROUP BY "region", "host", .... 
```

Concretely, for the code-paths in this PR to be hit the following conditions need to be true:

* No predicates on the query that apply to the segment (including time);
* All grouping columns are `RLEDictionary` encoded;

There can be predicates on the query, but they must not filter any data in the segment, so a time-range that overlaps the entire segment is fine, as is a filter that matches all values in a column.
The reason for these restrictions is that the algorithm that does the grouping leverages some pre-computed set data that all rle-encoded columns hold.

Typically grouped aggregates are done in a few steps:

1) Apply all filters and determine what set of rows you're working with on each column;
2) With this intermediate row set calculate each group key across all grouping columns for each `row_id` in the row set.
3) Store these group keys as keys to a hashmap and store the aggregates as the values, which can be built as you go.

An alternative approach is to not build a hashmap but instead to create another table view with the filtered rows that is then sorted on the grouping columns.
You can then stream through the columns you're aggregating in row-order and build the aggregates that way; the hashtable approach is often faster but YMMV.

However, for these scenarios I wanted to see if I could leverage the fact that we already had all the groups pre-computed on each column in compressed bitsets. 

## Implementation

Each rle-encoded columns stores a mapping between each `encoded_id` (the integer that encodes the logical string value in a row) and all of the `row_ids` that contain that value.
These are stored in compressed roaring bitmaps.

For example, suppose you have the following column data:

```
["east", "east", "west", "east", "south", "south"]
```

we may encode that as:

```
"east" -> 1
"south" -> 2
"west" -> 3
```

and then we will store the pre-computed rows in compressed bitsets for each _encoded_ valus. 
Like this:

```
1: {0, 1, 3}
2: {4, 5}
3: {2}
```

where the sets are compressed.

Now, given another column with a pre-computed grouping like:

```
1: {1, 3, 4}
2: {0, 5}
3: {6}
```

we could simply intersect the bitsets for each group combination resulting in the final group keys and row_ids to apply the aggregates to:

```
(1, 1) -> {1, 3}
(1, 2) -> {0}
(2, 2) -> {5}
```

you can group by as many columns as needed this way as a chain of set intersections.

Cool. All good then?
Well not really because you can't tell what the group keys are unless you check all the candidate's sets against each other, so if you do it naively (which is what I have done here for a starter implementation), you very likely have a non-linear algorithm :-1:.

I think the approach is interesting through and I'm pretty sure you could implement a linear version by "draining" the bitsets as you calculate group keys, but I didn't continue down that road as there is other `read_group` surface area to cover first.

## Commits

Some of the less boring commits in the PR:

* 7bc9738 - This adds the basic algorithm for applying read_group aggregates to columns that support returning pre-computed bit-sets for each distinct value in the column. I think the algorithm is linearithmic (maybe quadratic) because it lazily generates all possible group keys via an cartesian product iterator and then does set operations to determine if each candidate group key is a valid group key. It does short-circuit aggressively though.
* 42f56f4 - Benchmarks used to assess performance. I'll describe these below.
* 7ae27f5 - With benchmarks comes profiling, and with profiling usually comes easy wins. This one checks whether any rows could exist for a group key before allocating a new bitset.
* 3f8208d - This one avoids copying all `encoded_ids` out of the column initially and defers the copy until we know we need to use it to materialise a logical column value.
* 1043495 - This one was fun. Profiling showed that a lot of time was being spent fetching the bitsets for each distinct column value out of their respective `BTreeMaps`. The maps are indexed by integers (the `encoded_id`s for the logical column values). Not only are the maps indexed by integers but they're also guaranteed to be `[0, N)` where `N` is the number of distinct values in the column. So let's use a vector here and simply index into it with the `encoded_id` integer. This was a big performance win.
* f524240 - Solidify the vector idea in the general encoding APIs.

## Results

There are three different benchmarks in the PR, which use a basic data-set that generates column data similar to that found in a tracing use-case.
There are low cardinality columns in the segment, e.g., things like `env`, `data_centre` or `cluster`. 
And there are high cardinality columns like `request_id`, `trace_id` and `span_id`. 
The code described in this PR only applies to grouping on low-cardinality columns that are RLE encoded.

The three benchmarks are as follows:

* One of them varies the cardinality of the results whilst fixing the number of rows in the segment to 500,000. The cardinality of the results just means the number of grouped aggregates produced (the number of group keys). It varies between 2, 20, 200 and 2,000.
* One of them fixes the cardinality (to 200), but varies the number of columns grouped to produce that result set. It varies grouping on 1, 2 or 3 columns.
* One of them fixes cardinality and columns and varies the number of rows in the segment.

The initial results seem interesting (to me anyway). 
Firstly, let's address the current problem which is above-linear behaviour of the current implementation.
Here is a graph showing this behaviour, taken from the first benchmark that varies cardinality for a 500,000 rows segment.

<img width="933" alt="Screenshot 2020-12-04 at 21 18 29" src="https://user-images.githubusercontent.com/501993/101218337-cb522380-367a-11eb-8e10-411b371be2f4.png">

Grouping throughput goes from `~250us` to calculate 200 grouped aggregates (`~800K` groups/second) to `~15ms` to calculate 2,000 grouped aggregates (`~130K).
Ideally we would expect the throughput to be the same as we increased the number of groups.

It's not all bad though.
One interesting aspect to this approach is that it's relatively immune to the actual size of the segments. 
That is, larger segments (number of rows) don't really change the performance of the grouping much.
Here are some benchmarks showing this:

<img width="973" alt="Screenshot 2020-12-04 at 20 14 28" src="https://user-images.githubusercontent.com/501993/101218370-de64f380-367a-11eb-99c5-e852cff795c6.png">

The benchmarks do the equivalent of `SELECT COUNT(duration) FROM cpu GROUP BY "data_centre", "cluster"` but varying the number of rows to process from 250,000 to 1 million.
You can see there is barely any performance change of the query between processing 250K rows (`~245 us`) and processing 1M rows (`~302 us`), which is pretty cool.

Finally, here is a cool [criterion](https://github.com/bheisler/criterion.rs) feature that shows the efforts of some performance tuning I did in the latter commits after doing some profiling:

<img width="966" alt="Screenshot 2020-12-04 at 20 29 03" src="https://user-images.githubusercontent.com/501993/101218504-15d3a000-367b-11eb-8b6d-7647608e8bc8.png">

## Summary

I think for the right kind of queries where you want to get aggregates across low cardinality columns, this implementation could work really well.
One example w [...]

2020-12-05 14:01 UTC, alamb reviewed
I can't say I fully groked this entire PR , but I did read it pretty carefully and I think it is good to merge to me.

I was  somewhat confused about the explanation in the PR's description -- 
In your example, I can't tell if we are grouping by "region", or "region1", "region2" (aka are the two encoded columns the *same* column that needs to be aggregated, or are they two columns that form a compound group key-- I think it is the latter , and I found https://github.com/influxdata/influxdb_iox/pull/527/files#diff-05b254f51e0af46c018ef89da62237a52959aed4c59c6651b4f83835295fe51dR383-R413 to help understanding what is going on with this code better

2020-12-05 14:01 UTC, alamb approved these changes

2020-12-07 12:19 UTC, e-dard commented on segment_store/src/segment.rs
> +        ReadGroupResult::default()
The general case is coming next. It won't be `default()` for long.

2020-12-07 12:20 UTC, e-dard commented on segment_store/src/column/dictionary.rs
> +                    enc.group_row_ids().unwrap_left(),
They don't return the same value. One returns a `Vec<&T>` and one returns a `Vec<T>`. Since the types are both owned, but one has a borrowed  inner type `Cow` doesn't work, so `Either` is just a general purpose enum that's useful for internal APIs.

2020-12-07 12:21 UTC, e-dard commented on segment_store/src/table.rs
> +            return ReadGroupResults::default(); //TODO(edd): return an error here "group key column x not found"
By the time any of this is hooked up it will all be implemented. I'll change all these to `todo!()` on the next PR though. Good idea 👍

2020-12-07 12:27 UTC, e-dard commented on segment_store/src/segment.rs
> +        while row < expected_rows {
Boy. I don't know what I was thinking here. Fixed in 44c05db. Good spot.

2020-12-07 12:31 UTC, e-dard commented on segment_store/src/segment.rs
> +                vec![("counter", AggregateType::Sum)],
👍  See 0e77656

2020-12-07 12:36 UTC, e-dard commented on segment_store/src/column.rs
> +    pub fn update(&mut self, other: Value<'a>) {
The code in this PR is already doing vectorised aggregation because it's calling the aggregate functions directly on the columns. See here: https://github.com/influxdata/influxdb_iox/blob/0e77656527d45cfcee77eb210c6bad7e46a45bb6/segment_store/src/segment.rs#L451-L469

This code actually snuck in to this PR really because I don't need it until the general case, which is coming in this week. The reason it's dispatch per row is because typically the general group by case involves handling each row one at a time to build the group keys. In that case, performing non-vectorised aggregates probably won't have much if any perf downside. Of course I will be benchmarking to answer this question :-)

2020-12-07 12:38 UTC, e-dard commented on segment_store/src/column.rs
> +impl<'a> std::ops::AddAssign<&Scalar> for Scalar {
I agree. These implementations are not the best way to go if you can do vectorised aggregates. There are specialised methods on the column encodings for that.

2020-12-07 12:45 UTC, e-dard commented
> I was somewhat confused about the explanation in the PR's description --
In your example, I can't tell if we are grouping by "region", or "region1", "region2" (aka are the two encoded columns the same column that needs to be aggregated, or are they two columns that form a compound group key-- I think it is the latter , and I found https://github.com/influxdata/influxdb_iox/pull/527/files#diff-05b254f51e0af46c018ef89da62237a52959aed4c59c6651b4f83835295fe51dR383-R413 to help understanding what is going on with this code better

It was the latter - it's about grouping on multiple columns. I have added more context/example to the PR description; hope it helps. The link doesn't seem to take me anywhere - I think linking to the code diff on the PR sometimes breaks. I have found if you click on "View File" on the PR diff it takes you somewhere you can link to.

2020-12-07 13:58 UTC, domodwyer commented on segment_store/src/column.rs
> +            Column::String(_, data) => data.all_values(),
I'm curious, is the explicit chunking in [all_values()](https://github.com/influxdata/influxdb_iox/blob/main/segment_store/src/column/fixed.rs#L147-L152) in order to coerce the rustc into vectorising it?

2020-12-07 15:00 UTC, e-dard commented on segment_store/src/column.rs
> +            Column::String(_, data) => data.all_values(),
Thanks for spotting this. Actually the chunking in the encoding implementations of `all_values` was done like that because I used it another spot to do some aggregation. The point was to avoid some extra bounds checks by doing `chunks[3]` then `[2]` `[1]` `[0]` etc. But for this I moved the order around (because the order matters). But I should have just reverted back to a simple loop because it's just as performant (I just benchmarked it). I'll tidy this up in another PR 👍

2020-12-07 15:34 UTC, domodwyer approved these changes
Looks neat - I'm not totally sure I fully the layout of grouped keys, etc yet though!

2020-12-07 15:34 UTC, domodwyer commented on segment_store/src/lib.rs
> +pub fn time_range_predicate<'a>(from: i64, to: i64) -> Vec<segment::Predicate<'a>> {
I couldn't see this being called - might be dead code?

We could also make use of [`Range`](https://doc.rust-lang.org/stable/std/ops/struct.Range.html) to encode these bounds - it has a well-defined half-open range, or even be generic over an impl of [`RangeBounds`](https://doc.rust-lang.org/stable/std/ops/trait.RangeBounds.html) that allows the caller to be specific with bounds handling (inc. unlimited)

You'd then be able to implement `From<Range<u64>> for Predicate` which would be [rather concise](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0d21dc9c06adbc8b15b6953daa46fa90):

```rust
    let time_range: Predicate = (start..end).into();
```

2020-12-07 18:32 UTC, e-dard commented on segment_store/src/lib.rs
> +pub fn time_range_predicate<'a>(from: i64, to: i64) -> Vec<segment::Predicate<'a>> {
will address this cruft this week.

2020-12-07 19:20 UTC, alamb commented on segment_store/src/column/dictionary.rs
> +                    enc.group_row_ids().unwrap_left(),
i see

2020-12-09 15:52 UTC, carols10cents commented
Trying to make sure I understand the PR description first... I'm not sure I do, because I think there's a value missing in the intersection?

> we could simply intersect the bitsets for each group combination resulting in the final group keys and row_ids to apply the aggregates to:
> 
> (1, 1) -> {1, 3}
> (1, 2) -> {0}
> (2, 2) -> {5}
> ```

Shouldn't this also contain `(3, 3) -> {2}`?

2020-12-09 15:58 UTC, e-dard commented
@carols10cents 🤦 fixing now. Let me know if you can review this as I was going to merge it today otherwise 😄

2020-12-09 16:33 UTC, carols10cents requested changes
Going to eat lunch but submitting what I have so far

2020-12-09 16:33 UTC, carols10cents commented on segment_store/src/column.rs
> +            },
The code in here looks kind of like a partial `PartialOrd` implementation, and I see that you have `PartialOrd` derived on `Value`... do you know of a reason this logic can't be put in `PartialOrd` and then you can call `max` and `min` sorts of functions?

2020-12-09 16:33 UTC, carols10cents commented on segment_store/src/column.rs
> +    }
Can this use `matches!` like `Scalar::is_null` does?

2020-12-09 16:33 UTC, carols10cents commented on segment_store/src/column.rs
> +        if _rhs.is_null() {
Usually starting a parameter name with an underscore indicates it's unused in the body, but I see `_rhs` is immediately being used... Is there a reason you wanted this to be `_rhs` rather than `rhs`?

2020-12-09 16:33 UTC, carols10cents commented on segment_store/src/column.rs
> +    fn add_assign(&mut self, _rhs: &Scalar) {
same `_rhs` here

2020-12-09 16:33 UTC, carols10cents commented on segment_store/src/column.rs
> +impl<'a> std::ops::AddAssign<&Scalar> for &mut Scalar {
I see `'a` being declared here but I don't see it being used anywhere?

2020-12-09 16:36 UTC, e-dard commented on segment_store/src/column.rs
> +            },
I feel like I tried to go down this path but it didn't work out. I'll see if I can get it working.

2020-12-09 17:09 UTC, e-dard commented on segment_store/src/column.rs
> +impl<'a> std::ops::AddAssign<&Scalar> for &mut Scalar {
surprised `clippy` didn't spot that.

2020-12-09 17:58 UTC, carols10cents commented on segment_store/src/column.rs
> +impl<'a> std::ops::AddAssign<&Scalar> for &mut Scalar {
Submitted an issue: https://github.com/rust-lang/rust-clippy/issues/6437

2020-12-09 18:41 UTC, carols10cents requested changes
Pausing to try some things

2020-12-09 18:41 UTC, carols10cents commented on segment_store/src/column.rs
> +            }
Another place with a variable starting with an underscore that is being used... I'd call this `inner` or similar? 

Also have, you benchmarked this Vector+Bitmap case to see if it's actually inefficient? I agree the code seems like it's doing a lot of work, but it's hard to be sure sometimes... if it's actually only relevant for testing anyway, it's fine.

2020-12-09 18:41 UTC, carols10cents commented on segment_store/src/segment.rs
> +        &self.columns[*self.all_columns_by_name.get(name).unwrap()]
Is this `unwrap` really ok to do? How can we be sure?

2020-12-09 18:41 UTC, carols10cents commented on segment_store/src/segment.rs
> +    ) -> ReadFilterResult<'_> {
I have yet to see a use of `&'a self` that's actually what you want. When I take all the lifetimes out of here:

```
    pub fn read_filter(
        &self,
        columns: &[ColumnName<'_>],
        predicates: &[Predicate<'_>],
    ) -> ReadFilterResult<'_> {
```

I get this error message:

```
error[E0623]: lifetime mismatch
   --> segment_store/src/segment.rs:174:9
    |
170 |         columns: &[ColumnName<'_>],
    |                    -------------- this parameter and the return type are declared with different lifetimes...
171 |         predicates: &[Predicate<'_>],
172 |     ) -> ReadFilterResult<'_> {
    |          --------------------
173 |         let row_ids = self.row_ids_from_predicates(predicates);
174 |         ReadFilterResult(self.materialise_rows(columns, row_ids))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...but data from `columns` is returned here

```

Which is using lifetime info from `materialize_rows`, which is also using `&'a self`, and if I take the lifetimes out of there:

```
    fn materialise_rows(
        &self,
        columns: &[ColumnName<'_>],
        row_ids: RowIDsOption,
    ) -> Vec<(ColumnName<'_>, Values<'_>)> {
```

now I see:

```
error[E0623]: lifetime mismatch
   --> segment_store/src/segment.rs:184:38
    |
179 |         columns: &[ColumnName<'_>],
    |                    -------------- this parameter and the return type are declared with different lifetimes...
180 |         row_ids: RowIDsOption,
181 |     ) -> Vec<(ColumnName<'_>, Values<'_>)> {
    |          ---------------------------------
...
184 |             RowIDsOption::None(_) => results, // nothing to materialise
    |                                      ^^^^^^^ ...but data from `columns` is returned here
```

I'm starting to think the problem here is with `ReadFilterResult`, its definition ties the lifetimes of the column names and the values together but I don't think that's the case. I'm going to try some things out locally and maybe send a branch.

2020-12-09 19:32 UTC, e-dard commented on segment_store/src/segment.rs
> +    ) -> ReadFilterResult<'_> {
I was going to ping you this week about the lifetimes on self. I remember you telling me they're often not what we want but I couldn't get rid of them this time. Let me know if you figure it out!

2020-12-09 21:43 UTC, e-dard commented on segment_store/src/column.rs
> +            }
yeah I did preface with *seems* given i didn't take the trouble to benchmark it. And the note will let me pause for thought if I do need to use it in a non-test path. Fixing the variable.

2020-12-09 21:47 UTC, e-dard commented on segment_store/src/segment.rs
> +        &self.columns[*self.all_columns_by_name.get(name).unwrap()]
`unwrap` is OK because the segment is immutable and it's up to the segment owner (`table.rs`) to validate that the segment _may_ have data for the column first. If the segment couldn't have data for the column (because the column didn't exist, say) then the query wouldn't make it this far. I'll add a comment.

2020-12-10 15:14 UTC, carols10cents approved these changes
I'm good with this, we're going to keep improving on it in future PRs :)

2020-12-10 15:56 UTC, merged

2020-12-10 16:00 UTC, alamb commented
🎉

2020-12-10 16:02 UTC, e-dard commented
@carols10cents has some sweet refactoring to clarify lifetimes in the segment store. We will be getting that merged in a separate PR next.