feat: Add metrics on the size of files created by compaction
influxdata/influxdb_iox pull request #5348
Opened 2022-08-08 19:43 UTC by carols10cents

Closes #5327

I'm not sure if this is the most useful way to do this or not-- this records the total size of newly created files as a result of a compaction operation, with an attribute that differentiates whether those newly created files were a result of running compaction or just upgrading a single non-overlapping level 0 file to level 1.

The other option I considered was recording the diff of the size of the input files and the output files for one operation (so only logging a value if there was a difference; when a single non-overlapping level 0 file gets upgraded to level 1, the diff would be 0). This would better show how each operation is contributing to "how well the compactor works", whereas I think the way I have it here is only really useful in the aggregate? I'm not sure, so I thought I'd check.

2022-08-08 19:51 UTC, pauldix commented
I'm not sure what exactly we want to determine based on the issue #5327. What's the question we're hoping to answer here? Some guesses:
1. Are L0 files getting compacted? (we'd only need two counts: L0 files created, and L0 files compacted (regardless of upgrade or rewrite))
1. How many L0 files are getting rewritten vs. how many upgraded (this would just be a single counter)
1. What size are files getting compacted to? (this would be way harder to effectively measure while compactions are actively running, and I'm not sure how useful it is)

I'm not sure that a gauge is useful for answering any of these questions.

2022-08-08 20:31 UTC, carols10cents commented
Yeah I'm not sure either :-/ "to evaluate how well the compactors work" is what Nga said.

2022-08-08 20:32 UTC, carols10cents commented
What *would* you find useful, @pauldix ?

2022-08-08 21:15 UTC, pauldix commented
I think maybe the following:
1. Counter for L0 files getting created (would be in the ingester)
2. Counter for L0 files getting compacted (in the compactor)
3. Counter for L1 files getting compacted (in the compactor)

Then we'd be able to visualize these as rates, which would be pretty easy to compare. I'm not sure the sizes are very helpful, unless they're histograms, which might be interesting. If doing that then we'd also get the counter from the histogram as part of it. 

So maybe:
1. Histogram of L0 file sizes created
2. Histogram of L0 file sizes compacted
3. Histogram of L1 file sizes compacted

You could start with some buckets of like 500KB, 1MB, 3MB, 10MB, 30MB, Inf.

What do you think?

2022-08-10 18:11 UTC, carols10cents commented
> 1. Histogram of L0 file sizes created
> 2. Histogram of L0 file sizes compacted
> 3. Histogram of L1 file sizes compacted

I can do this! I want to be sure I understand what you mean, though-- when you say "L0 file sizes compacted" and "L1 file sizes compacted", do you mean "sizes of the files selected for compacted"/"input files to compaction" or "sizes of the files created by the compaction operation"/"output files from compaction" or both?

2022-08-11 17:45 UTC, carols10cents commented
I *think* this is ready for re-review now, @pauldix !

2022-08-12 21:10 UTC, pauldix requested changes
Made some recommendations for changing up the metrics a little bit. Let me know if that makes sense.

2022-08-12 21:10 UTC, pauldix commented on compactor/src/parquet_file_combining.rs
> +        let compaction_counter = compaction_counter.recorder(attributes.clone());
The `compaction_counter` should be removed as it's redundant. Having the histogram for sizes will automatically insert a metric to track the count and the sum of the sizes. More info here: https://www.robustperception.io/how-does-a-prometheus-histogram-work/

2022-08-12 21:10 UTC, pauldix commented on compactor/src/parquet_file_combining.rs
> +        if let Some(sizes) = file_sizes_by_level.get(&compaction_level) {
Rather than increment the histogram by the total, it's better to increment it per file. So as you're looping through the files higher up you should be adding each one to the histogram. This will give us the correct view of the count of the individual files and the sizes of those files in the histogram.

Separately, if we want a histogram that tracks the total sizes of a compaction, then we can build that up, which might also be worth doing. So one histogram to track the sizes of the individual files (along with an attribute that tracks the level) and then another that tracks the total compaction size (this one shouldn't have level on it).

2022-08-15 14:12 UTC, carols10cents commented on compactor/src/parquet_file_combining.rs
> +        if let Some(sizes) = file_sizes_by_level.get(&compaction_level) {
This is incrementing it per file, I think-- this hashmap is holding a Vec of sizes, and on the next line I'm iterating through each size and recording each:

```
            for &size in sizes {
                compaction_input_file_bytes.record(size);
            }
```

Am I misunderstanding how the metrics work?

> (this one shouldn't have level on it).

I can take that off :) My thinking of recording these metrics here rather than higher up is that here we're sure the compaction and catalog update has succeeded...?

2022-08-15 14:51 UTC, carols10cents commented
Two new commits for you to review @pauldix -- especially in ef716a5b9032b673f037490ad537a0bf150667fd where the tests are updated, it should be easier to see that the individual file sizes are being logged separately, if I'm understanding metrics correctly (there's always a chance I'm not!)

2022-08-17 15:35 UTC, pauldix approved these changes
Looks good. We'll also want to track L2 once those get in.

2022-08-17 16:08 UTC, merged

2022-08-22 17:24 UTC, NGA-TRAN reviewed
I went over the conversation between Carol and Paul and skimmed the code. It makes sense. I will use them when I work on dashboard