Brandonsov/add bucket location to object store errors
influxdata/influxdb_iox pull request #536
Opened 2020-12-09 07:24 UTC by brandonsov

Closes #140 

This PR adds the members `bucket` and `location` both of `String` type to various `object_store` applicable S3 and GCS error enum variants. Also, adds some unit tests for S3 and GCS to attempt to receive errors that we assert saved the `bucket` and `location` members saved. The unit tests only cover a subset of the error enum variants added.

Questions and Remarks:
1. Should `bucket` and `location` represent `String` objects or `&str`? 
1. I plan to add the snafu display to the modified enum variants, but would like guidance on what the format should be to indicate the `source`, `bucket`, and `location` values.
1. Any guidance on more full code coverage to trigger a `tokio::task::JoinError`.
1. I believe the `put_get_delete_list` test helper function is susceptible to race conditions. Given the rust unit tests are run asynchronously by default, I believe this will frequently throw false negatives if there are other tests that modify the same bucket. I can write up a new issue or modify within this PR if desired. 
1. For local testing of S3, I used [localstack](https://github.com/localstack/localstack) and a [custom rusoto region](https://www.rusoto.org/regions.html). An option to ease this would be the addition of a new environment variable to represent local development and the local AWS mock server endpoint or the local AWS mock server endpoint environment variable and a conditional compilation flag for that endpoint environment variable . I can create the issue if this makes sense.
1. Is there a Google Cloud Storage mock server? I searched online and was not very successful so I tested using real Google Cloud Storage credentials.
1. See inline comment about modification to the `docs/env.example` `AWS_S3_BUCKET_NAME` default environment variable name.
1. Let me know if there's better ways to factor out or reduce some of the error checking in the test cases.
1. I do not fully understand the implications of removing `#[snafu(context(false))]`. I've read https://docs.rs/snafu/0.6.6/snafu/guide/attributes/index.html#controlling-context, but don't believe I understand this well enough. I needed to remove it to allow new `String` members to be added to the enum variant. I received this error if the `[snafu(context(false))]` remained: `Context selectors without context must not have context fields`

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2020-12-09 07:33 UTC, brandonsov commented on docs/env.example
> +# AWS_S3_BUCKET_NAME=bucket-name
Underscore's are invalid in AWS S3 bucket names. Modified to hyphen. Please inform if you would like me to remove this change from this PR

2020-12-09 07:37 UTC, brandonsov commented on object_store/src/lib.rs
> +        }
This function is copied below. It was in 1 location outside of the conditional compilation flags, but because of this, it was failing the linter due to no default code using it. I can remove this function and just copy the querying of the object store in the sections that call this.

2020-12-09 10:40 UTC, e-dard commented
@brandonsov thanks so much for the contribution. The team are going to be reviewing it soon. Recently we updated the `README` to add a [contributing section](https://github.com/influxdata/influxdb_iox#contributing). My question to you is: was that helpful and do you have any feedback on anything that wasn't clear enough or could be improved? Thanks again!

2020-12-09 11:27 UTC, domodwyer requested changes

2020-12-09 11:27 UTC, domodwyer commented on object_store/src/lib.rs
> +            }
We could unwrap the error to remove one level of `if let` unwrapping :)

```suggestion
            // Unwrap the error - this will panic if it is an Ok(_)
            let err = get_nonexistant_object(&integration, Some(location_name))
                .await
                .unwrap_err();

            // Unwrap & Destructure the error
            if let Error(InternalError::UnableToListDataFromS3 { source, bucket }) =
                err.downcast_ref::<crate::Error>().unwrap()
            {
                // Assert!
                assert!(matches!(source, rusoto_core::RusotoError::Unknown(_)));
                assert_eq!(bucket, &bucket_name);
            } else {
                panic!("unexpected error type")
            }
```

2020-12-09 11:27 UTC, domodwyer commented on object_store/src/lib.rs
> +                location: String(_),
I think these should be:

```suggestion
                bucket: _,
                location: _,
```

As the `String` is not a tuple:

```
error[E0532]: expected tuple struct or tuple variant, found struct `String`
   --> object_store/src/lib.rs:643:25
    |
643 |                 bucket: String(_),
    |                         ^^^^^^^^^ help: use struct pattern syntax instead: `String { vec }`
    |
   ::: /Users/dom/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/string.rs:278:1
    |
278 | pub struct String {
    | ----------------- `String` defined here
```

I had to change it to this so it would compile for me. We should be checking that the code compiles with these `cfg`'s even if we're not currently running the tests, so I've made #537 to track this.

2020-12-09 11:27 UTC, domodwyer commented on object_store/src/lib.rs
> +            bucket: self.bucket_name.clone(),
I did this too recently! @carols10cents helpfully explained that the `context()` calls `into()` on the argument inside a closure when the error is triggered - this lets us avoid cloning the string in the happy path so we only pay the price for it if the error occurs which is great!

Rust just needs a little help figuring out that it can do this with a `str`:

```suggestion
            bucket: &*self.bucket_name,
```

This [derefs](https://doc.rust-lang.org/std/string/struct.String.html#deref-methods) the `String` to a `str` and then takes a reference to the resulting `str` so we wind up passing in a `&str` (I believe anyway). Since there is a `From<&str> for String` impl, this has an `into()` string for the closure to call :)

This lets us answer have our cake and eat it:

> Should bucket and location represent String objects or &str?

The error can take a String so it owns the values (no lifetimes for errors is nicer) but we don't have to clone everywhere!

We can probably apply this to all the error paths here :)

2020-12-09 11:27 UTC, domodwyer commented on docs/env.example
> +# AWS_S3_BUCKET_NAME=bucket-name
Good catch, thanks!

2020-12-09 11:27 UTC, domodwyer commented on object_store/src/lib.rs
> +        }
I'm not against a little copying (especially for tests!) but I thought I'd mention we can have a cfg apply with `OR` semantics too with:

```
#[cfg(any(test_aws, test_gcs))]
```

Which looks helpful for this case 👍

2020-12-09 14:26 UTC, alamb commented on object_store/src/lib.rs
> +            bucket: self.bucket_name.clone(),
Yes, this is something that I find confusing about the use of Snafu's `context` calls as well -- they are always constructed on the happy, but they don't have the same type as the erorr variant (so in this case the `bucket` field in `Context(UnableToPutDataToGcs { ...})`  is not a `String` but rather `impl Into<String>`

2020-12-09 14:26 UTC, alamb commented on object_store/src/lib.rs
> +                bucket: self.bucket_name.to_owned(),
Does this work? (and similar changes in the rest of the error paths)

```suggestion
                bucket: self.bucket_name,
```

2020-12-09 14:43 UTC, shepmaster commented on object_store/src/lib.rs
> +            bucket: self.bucket_name.clone(),
> Rust just needs a little help figuring out that it can do this with a `str`:

Kind of. The problem with `bucket: self.bucket_name` is that it would try to move ownership of `bucket_name` but that's disallowed because you don't own `self` (it's `&self`).

You don't have to deref-and-re-reference `String` either, as `&String` also implements `Into<String>`:

```rust
fn x(_: impl Into<String>) {}

fn main() {
    let s = String::new();
    x(&s);
}
```

So should be able to be:

```rust
bucket: &self.bucket_name,
```

2020-12-09 17:51 UTC, brandonsov commented
> @brandonsov thanks so much for the contribution. The team are going to be reviewing it soon. Recently we updated the `README` to add a [contributing section](https://github.com/influxdata/influxdb_iox#contributing). My question to you is: was that helpful and do you have any feedback on anything that wasn't clear enough or could be improved? Thanks again!

@e-dard The docs were helpful, but I think something to call out would be the semantic title and comments.

2020-12-09 18:16 UTC, brandonsov commented on object_store/src/lib.rs
> +                location: String(_),
Updated `String(_)` to `_` in the pattern match

2020-12-09 19:28 UTC, brandonsov commented on object_store/src/lib.rs
> +                bucket: self.bucket_name.to_owned(),
Applied this change here:
https://github.com/influxdata/influxdb_iox/pull/536#discussion_r539363479
Given the explanation in the linked comment explained this not to be possible

2020-12-09 19:29 UTC, brandonsov commented on object_store/src/lib.rs
> +            bucket: self.bucket_name.clone(),
Applied the `bucket: &self.bucket_name` change. Appreciate the explanation.

2020-12-09 19:30 UTC, brandonsov commented on object_store/src/lib.rs
> +            }
:man_facepalming: Thanks! Simplified the error checking in the tests to this pattern.

2020-12-09 19:31 UTC, brandonsov commented on object_store/src/lib.rs
> +        }
Refactored the helper function and const variable out again with the conditional compilation flag.

2020-12-09 19:36 UTC, brandonsov commented
All comments above have been addressed. In this project, does the author resolve the conversation when they deem it to be addressed or the person who left the initial comment?

2020-12-09 19:42 UTC, alamb commented
> All comments above have been addressed. In this project, does the author resolve the conversation when they deem it to be addressed or the person who left the initial comment?

 I recommend the author does so, but I don't think we have it written down explicitly anywhere

2020-12-09 19:46 UTC, alamb reviewed
I think this is looking good enough to merge in my mind. Thank you @brandonsov !

I didn't run the tests against remote object stores, but I think this code makes the code better and the focus on testing is impressive. 

> Any guidance on more full code coverage to trigger a tokio::task::JoinError.
I don't think this path needs to be tested -- it happens on lower level errors I believe

> I believe the put_get_delete_list test helper function is susceptible to race conditions. Given the rust unit tests are run asynchronously by default, I believe this will frequently throw false negatives if there are other tests that modify the same bucket. I can write up a new issue or modify within this PR if desired.

Another ticket would be personal suggestion

> For local testing of S3, I used localstack and a custom rusoto region. An option to ease this would be the addition of a new environment variable to represent local development and the local AWS mock server endpoint or the local AWS mock server endpoint environment variable and a conditional compilation flag for that endpoint environment variable . I can create the issue if this makes sense.

yes, thank you

2020-12-09 19:47 UTC, alamb approved these changes

2020-12-10 13:22 UTC, pauldix reviewed
Additional tests look great. Just one comment/question on style.

2020-12-10 13:22 UTC, pauldix commented on object_store/src/lib.rs
> +        let location_string = location.to_string();
From a style point of view, I don't think we'd normally have a type as part of the variable name. Thoughts @e-dard or @alamb?

2020-12-10 13:29 UTC, e-dard commented on object_store/src/lib.rs
> +        let location_string = location.to_string();
Agree. Should be `location`.

2020-12-10 13:50 UTC, e-dard requested changes
Looking great. Thank you! Just some spelling issues around `existent`, and I wonder (but I'm not sure as I don't have these tests setup to run locally right now) if some of the `.unwrap` calls in the tests can be replaced with `?`.

2020-12-10 13:50 UTC, e-dard commented on object_store/src/lib.rs
> +    const NON_EXISTANT_NAME: &str = "nonexistantname";
Please can you change the spelling of:

```rust
const NON_EXISTANT_NAME: &str = "nonexistantname";
```

to:

```rust
const NON_EXISTENT_NAME: &str = "nonexistentname";
```

and update the references.

2020-12-10 13:50 UTC, e-dard commented on object_store/src/lib.rs
> +    async fn get_nonexistant_object(
All these functions should use the adjective `nonexistent`, rather than `nonexistant`

2020-12-10 13:50 UTC, e-dard commented on object_store/src/lib.rs
> +                .unwrap();
Just wondering if the `unwrap` calls in these tests can mostly be replaced with `?`?

2020-12-10 14:45 UTC, alamb commented on object_store/src/lib.rs
> +                .unwrap();
I think in general our codebase is somewhat inconsistent about using `unwrap()` or `?` in tests -- I filed https://github.com/influxdata/influxdb_iox/issues/544 to track picking a consistent pattern and documenting it

2020-12-10 17:15 UTC, brandonsov commented on object_store/src/lib.rs
> +        let location_string = location.to_string();
Ah right I forgot to call this out. I made it a new variable because `location` was previously being used in tokio spawn blocking closure and the errors required the `location` variable as well. Would like guidance on how to best solve this issue.

2020-12-10 17:18 UTC, brandonsov commented on object_store/src/lib.rs
> +    const NON_EXISTANT_NAME: &str = "nonexistantname";
Updated all typos, thanks!

2020-12-10 17:18 UTC, brandonsov commented on object_store/src/lib.rs
> +    async fn get_nonexistant_object(
Updated all typos, thanks!

2020-12-10 17:20 UTC, e-dard approved these changes

2020-12-10 17:25 UTC, brandonsov commented on object_store/src/lib.rs
> +                .unwrap();
Updated to `?`

2020-12-10 17:30 UTC, alamb commented on object_store/src/lib.rs
> +        let location_string = location.to_string();
Right -- in this case it seems like we need to make two owned things (one for use after `await` and another for the closure). 

My simplest suggestion is to simply rename it to something that makes it clear a copy is needed to pass to the closure:

```suggestion
        let location_copy = location.to_string();
```

An alternate would be to make the copy in an inner closure:
```rust
let location = location.string();
{ 
  let location = location.clone();
  let _ = tokio::task::spawn(...)
  ...
}
```

2020-12-10 17:43 UTC, brandonsov commented on object_store/src/lib.rs
> +        let location_string = location.to_string();
Updated to `location_copy`

2020-12-10 17:50 UTC, alamb commented
I think this is looking ready to merge -- what do you think @domodwyer ?

2020-12-10 18:14 UTC, domodwyer commented
Looks great! 🎉 

Thanks very much for contributing @brandonsov - it's much appreciated!

2020-12-10 18:14 UTC, domodwyer approved these changes

2020-12-10 18:23 UTC, merged