[WIP] Support Azure blob storage
influxdata/influxdb_iox pull request #547
Opened 2020-12-10 16:53 UTC by jeschkies

Closes #528

This patch adds support for Microsoft Azure Blob storage.

Outstanding:
- [ ] Test code.
- [ ] Configure credentials.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2020-12-10 16:56 UTC, jeschkies commented on object_store/src/lib.rs
> +        );
This duplicates the logic for Google Cloud Storage. Should it be consolidated?

2020-12-10 16:56 UTC, jeschkies commented on object_store/src/lib.rs
> +            .put_block_blob()
I need to read up on https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs

2020-12-10 16:56 UTC, jeschkies commented on object_store/src/lib.rs
> +    },
This error is used in all cases not just for `list`.

2020-12-10 16:56 UTC, jeschkies commented on object_store/Cargo.toml
> +azure_sdk_storage_core = "0.44.4"
We might want to switch to https://github.com/Azure/azure-sdk-for-rust once it is released.

2020-12-11 11:41 UTC, domodwyer requested changes
**Thank you** @jeschkies this is looking really good! 🎉 

There's a few minor bits, but overall looks very nice - we definitely need to cover this in tests to ensure correctness / lock in behaviour. We're looking into running integration tests as part of CI soon, but for now it would have to be checked locally.

Again, **thank you for contributing** - it's really appreciated! Let us know if we can help with anything!

2020-12-11 11:41 UTC, domodwyer commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
I'm not hugely familiar with Azure, but I wonder if we should be deleting any associated snapshots? I had a quick look at [the API docs] and they say that:

> Note that in order to delete a blob, you must delete all of its snapshots.

I suspect this is due to some sort of CoW mechanism at the storage layer. However if IOx never creates snapshots, for a blob to have a snapshot it must have been created by the operator, which means maybe they wanted a point-in-time backup of IOx state? Are there any other mechanisms that would wind up with snapshots of IOx blobs being created? I'm not sure if deleting the snapshot would be a good idea - it might surprise whoever created it!

What do you think? I'm definitely not an Azure expert, so it's a bit of an open question! 

[the API docs]: https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob

2020-12-11 11:41 UTC, domodwyer commented on object_store/src/lib.rs
> +                .with_prefix(prefix.unwrap());
I don't think we want to unwrap here - if the caller specifies `prefix = None` in the call, then we would panic!

2020-12-11 11:41 UTC, domodwyer commented on object_store/src/lib.rs
> +        Ok(stream::unfold(ListState::Start, move |state| async move {
This is cool! I really like this pattern - I've learnt something new, thanks! :)

2020-12-11 11:41 UTC, domodwyer commented on object_store/src/lib.rs
> +    },
So if we remove the `#[snafu(context(false))]` line, snafu won't create an `Into<InternalError>` for the `AzureError` and instead you have to use `context()` to convert the error types at the appropriate places in the code - it's nice and easy though!

From this:
```rust
        self.client
            .put_block_blob()
            .with_container_name(&self.container_name)
            .with_blob_name(location)
            .with_body(&temporary_non_streaming)
            .finalize()
	    .await?;
```

to this:

```rust
        self.client
            .put_block_blob()
            .with_container_name(&self.container_name)
            .with_blob_name(location)
            .with_body(&temporary_non_streaming)
            .finalize()
            .await
            .context(UnableToPutDataInAzure)?;
```

This allows us to have typed errors for each potential error path. This lets callers further up the chain determine what has gone wrong even if they do not know what object store operations were dispatched at a lower level in the code, (say a caller does `get_latest()` which internally would do a list & get operation) - they should have enough information to tell the user which failed.

We should maintain parity with the others and have an error type for each call path - add any additional error information that is helpful - we should definitely include the path to the data being operated in (@brandonsov just added a load of bucket//location info to the existing paths in #536 - thanks! 🎉 )

2020-12-11 13:05 UTC, jeschkies commented on object_store/src/lib.rs
> +            std::env::var("STORAGE_ACCOUNT").expect("Set env variable STORAGE_ACCOUNT first!");
Good point. I parametrized the `new` method. Callers must load the credentials themselves then. I also added a `new_from_env`.

2020-12-11 13:06 UTC, jeschkies commented on object_store/src/lib.rs
> +                .with_prefix(prefix.unwrap());
Good catch. That was from prototyping.

2020-12-11 13:28 UTC, jeschkies commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
Thanks for the input. I don't know Azure well enough myself. If IOx always creates new blobs I think we should not delete snapshots.

2020-12-16 13:15 UTC, jeschkies commented
@domodwyer, could you take another look. Is there a time line for an Azure test account?

I have some difficulties with the semantic commit message. What should it look like? I will squash my change before merging.

2020-12-17 11:32 UTC, domodwyer commented on object_store/src/lib.rs
> +        );
This is fine to leave I think - I'm not against a bit of copying where it makes sense!

2020-12-17 11:43 UTC, domodwyer commented on object_store/src/lib.rs
> +    },
Looks great now! Thanks 👍

2020-12-17 11:51 UTC, domodwyer commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Only)
I think we need to not call `with_delete_snapshots_method()` in order to not request deletion of the snapshots at all?

The [docs are a bit light on details](https://docs.rs/azure_sdk_core/0.43.7/azure_sdk_core/enum.DeleteSnapshotsMethod.html) but I'm (literally) guessing:

* `Include` means "delete the blobs and any associated snapshots"
* `Only` means "leave the blobs but delete the snapshots"?

If that is the case the `put_get_delete_list` integration test should be failing - have you had chance to run it? I will speak with the team about getting an Azure test account in standup this afternoon and will run the tests myself once we're set up 👍

2020-12-17 11:51 UTC, domodwyer commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
I think we need to not call `with_delete_snapshots_method()` in order to not request deletion of the snapshots at all?

The [docs are a bit light on details](https://docs.rs/azure_sdk_core/0.43.7/azure_sdk_core/enum.DeleteSnapshotsMethod.html) but I'm (literally) guessing:

* `Include` means "delete the blobs and any associated snapshots"
* `Only` means "leave the blobs but delete the snapshots"?

If that is the case the `put_get_delete_list` integration test should be failing - have you had chance to run it? I will speak with the team about getting an Azure test account in standup this afternoon and will run the tests myself once we're set up 👍

2020-12-17 11:57 UTC, domodwyer commented on object_store/src/lib.rs
> +            .put_block_blob()
I've had a quick look myself and it seems like the right type to go with - I'm definitely not an Azure expert (or even user currently!) though.

2020-12-17 12:01 UTC, domodwyer requested changes
Just one outstanding question on the snapshot bits - I'm going to try and run this myself as soon as I can.

With respect to the commits, all our subject lints are linted to conform to the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) spec - I find [this](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) to be a handy reference! Squashing this down to something like `feat: Azure support for object store` would be great 👍 

It looks like [the lints](https://github.com/influxdata/influxdb_iox/pull/547/checks?check_run_id=1563875115) want you to run `cargo fmt` too - I think we're nearly good to merge! 🎉

2020-12-17 13:01 UTC, jeschkies commented on object_store/src/lib.rs
> +            .put_block_blob()
I need to run the tests. I don't have an account though so I'd have to make one :slightly_smiling_face:

2020-12-17 16:11 UTC, jeschkies commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
I need to setup an account. I hope I get around to it in the next days.

2020-12-17 16:22 UTC, domodwyer commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
Awesome - I'm working on doing the same my side so I'll let you know if I get there first!

2021-01-06 16:59 UTC, jeschkies reviewed
@domodwyer, I've finally got around to testing my change. There were a few bugs that I've fixed. I hope this unblocks this PR :slightly_smiling_face:

2021-01-06 16:59 UTC, jeschkies commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
It would fail when I used `Only`.

2021-01-08 12:16 UTC, domodwyer commented on object_store/src/lib.rs
> +            .with_delete_snapshots_method(DeleteSnapshotsMethod::Include)
I see now `with_delete_snapshots_method()` must be called (the Azure crate docs are pretty indecipherable...) - thanks for testing and sorry for misleading you 😄

2021-01-08 12:16 UTC, domodwyer commented
Hey @jeschkies 

Sorry for the delay! I took some festive holiday - I hope you've had a good break too!

I've just ran the e2e tests, looks good! Awesome stuff, thanks for contributing :)

Dom

2021-01-08 12:17 UTC, domodwyer approved these changes

2021-01-08 12:19 UTC, domodwyer commented
Ah I just saw the lint failures & conflicts!

If it's difficult to resolve give me a shout and I'll take care of it - I'll merge it as soon as it's passing :)

2021-01-08 12:22 UTC, jeschkies commented
> Sorry for the delay! I took some festive holiday - I hope you've had a good break too!

No worries. I assumed so : )

> Ah I just saw the lint failures & conflicts!

I'm giving it a try. Let's see.

2021-01-08 15:41 UTC, jeschkies commented
@domodwyer, it's finally mergable! At least I hope it's good to go.

2021-01-08 16:08 UTC, domodwyer approved these changes
Looks great! 🎉 

Thanks for the contribution @jeschkies - it's really appreciated!

2021-01-08 16:09 UTC, merged