chore: changed `iox_shared` to `iox-shared`
influxdata/influxdb_iox pull request #5549
Opened 2022-09-04 11:43 UTC by alamb

Based on https://github.com/influxdata/influxdb_iox/pull/5421 from @gulio-python 

Closes https://github.com/influxdata/influxdb_iox/issues/5403
Closes https://github.com/influxdata/influxdb_iox/issues/5421

2022-09-05 08:45 UTC, crepererum commented on import/src/aggregate_tsm_schema/update_catalog.rs
> +            .create_or_get("iox-shared")
IIRC this is an invalid Kafka topic name and was actually "fixed" a while back to contain an underscore instead of a `-`. Note that our CI may not detect this because we use Redpanda.

2022-09-05 09:01 UTC, lukebond commented on import/src/aggregate_tsm_schema/update_catalog.rs
> +            .create_or_get("iox-shared")
i have no experience with this, just some drive-by googling here:

https://github.com/apache/kafka/blob/a126e3a622f2b7142f3543b9dbee54b6412ba9d8/clients/src/main/java/org/apache/kafka/common/internals/Topic.java#L33

and

https://github.com/apache/kafka/blob/a126e3a622f2b7142f3543b9dbee54b6412ba9d8/clients/src/main/java/org/apache/kafka/common/internals/Topic.java#L55-L56

seems to me that both `-` and `_` are valid characters in a topic name. although maybe that's not the whole story. do you have anything more concrete you can share?

2022-09-05 09:06 UTC, crepererum commented on import/src/aggregate_tsm_schema/update_catalog.rs
> +            .create_or_get("iox-shared")
> do you have anything more concrete you can share?

Sadly not, maybe just works :shrug:

2022-09-05 09:39 UTC, crepererum commented on import/src/aggregate_tsm_schema/update_catalog.rs
> +            .create_or_get("iox-shared")
Found it: #3747

2022-09-05 09:44 UTC, lukebond requested changes
you know this code better than me @alamb so LMK if i'm mistaken on these comments.

regarding the comment thread with @crepererum, i think it should be fine to merge and find out. as per the issue this PR closes (https://github.com/influxdata/influxdb_iox/issues/5403), we use this topic name in prod so i think it's fine. besides, this PR mostly aligns the tests to match that to avoid confusion.

2022-09-05 09:44 UTC, lukebond commented on querier/src/cache/read_buffer.rs
> +    let metrics = ChunkMetrics::new(metric_registry, "iox-shared");
@alamb i think this one shouldn't be changed- it's a DB name rather than a Kafka topic and it's not in a test so would probably break in prod by pointing to something different to what it did before?

2022-09-05 09:44 UTC, lukebond commented on querier/src/cache/read_buffer.rs
> +            .get_observer(&Attributes::from(&[("db_name", "iox-shared")]))
likewise this one i believe, see previous comment

2022-09-05 09:47 UTC, lukebond commented on import/src/aggregate_tsm_schema/update_catalog.rs
> +            .create_or_get("iox-shared")
looks like this PR is updating the tests to match what you did in that PR!

2022-09-05 13:48 UTC, crepererum requested changes

2022-09-05 13:48 UTC, crepererum commented on service_grpc_catalog/src/lib.rs
> +            let topic = repos.topics().create_or_get("iox_-shared").await.unwrap();
```suggestion
            let topic = repos.topics().create_or_get("iox-shared").await.unwrap();
```

2022-09-06 13:28 UTC, crepererum commented on querier/src/cache/read_buffer.rs
> +    let metrics = ChunkMetrics::new(metric_registry, "iox-shared");
This one is fine. It's a placeholder name since we don't have per-DB/per-namespace metrics anymore.

2022-09-06 13:28 UTC, crepererum approved these changes

2022-09-06 13:56 UTC, lukebond commented on querier/src/cache/read_buffer.rs
> +            .get_observer(&Attributes::from(&[("db_name", "iox-shared")]))
same for this one @crepererum ?

2022-09-06 14:14 UTC, crepererum commented on querier/src/cache/read_buffer.rs
> +            .get_observer(&Attributes::from(&[("db_name", "iox-shared")]))
yes

2022-09-06 16:16 UTC, merged

2022-09-06 16:17 UTC, lukebond commented
thanks @gulio-python for doing this work, sorry it took so long to get merged

2022-09-07 10:42 UTC, alamb commented
🎉  thanks all!