feat: Add `SELECT` statement parsing
influxdata/influxdb_iox pull request #5692
Opened 2022-09-20 07:32 UTC by stuartcarnie

Helps #5633

This PR teaches the InfluxQL parser how to recognise a `SELECT` statement. It is accompanied by a number of unit tests, however, #5738 is intended to broaden the testing to a larger corpus of statements.

### Other notable changes

Refactors expression parsing into two modules to distinguish arithmetic expressions from conditional expressions. InfluxQL universally allows conditional expressions in a `WHERE` clause of any statement, but only arithmetic expressions in other places, such as the projection list of a `SELECT` statement.

Adds a new generic type, `OneOrMore` and accompanying trait, `Parser` to the `common` module to allow generic parsing of a list of parsers. This is used in both the `expression::arithmetic` and `expression::conditional` modules to permit customisation of the valid set of operands which may be parsed. This was necessary, as there are different set of operands for a field in a `SELECT` projection vs in a `WHERE` clause.

2022-09-28 04:25 UTC, stuartcarnie commented on influxdb_influxql_parser/src/common.rs
> +            unsigned_integer,
Reuse some existing code

2022-09-28 04:26 UTC, stuartcarnie commented on influxdb_influxql_parser/src/delete.rs
> +            "invalid DELETE statement, expected FROM or WHERE",
Followed this pattern everywhere of 

> invalid _something_, expected _list of symbols / tokens_

2022-09-28 04:29 UTC, stuartcarnie commented on influxdb_influxql_parser/src/identifier.rs
> -
All of these have been removed, as we no longer have any dead code 🥳

2022-09-28 04:30 UTC, stuartcarnie commented on influxdb_influxql_parser/src/literal.rs
> +pub fn unsigned_integer(i: &str) -> ParseResult<&str, u64> {
Reuse this in several places

2022-09-28 04:31 UTC, stuartcarnie commented on influxdb_influxql_parser/src/show_measurements.rs
> +        assert_matches!(got, OnExpression::AllDatabases);
Per your recommendation, @crepererum – thanks!

2022-09-28 04:32 UTC, stuartcarnie commented on influxdb_influxql_parser/src/show_tag_values.rs
> +fn identifier_list(i: &str) -> ParseResult<&str, InList> {
`InList` leverages the new `OneOrMany` type

2022-09-28 14:21 UTC, NGA-TRAN approved these changes
Very nice

2022-09-28 14:21 UTC, NGA-TRAN commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        let (_, got) = arithmetic_expression("5- -(3|2)").unwrap();
I wonder what happens with the expressions "5--(3|2)", "2|5%3"

2022-09-28 14:21 UTC, NGA-TRAN commented on influxdb_influxql_parser/src/expression/conditional.rs
> +pub enum ConditionalOperator {
It will be consistent and informative if you add a comment to link to the document of these operators as you did for data type

2022-09-28 14:21 UTC, NGA-TRAN commented on influxdb_influxql_parser/src/expression/conditional.rs
> +                cond_op!(cond_op!(6, Eq, 7), And, cond_op!(7, NotEq, 1))
Nice

2022-09-28 14:21 UTC, NGA-TRAN commented on influxdb_influxql_parser/src/select.rs
> +impl Display for SelectStatement {
This statement looks good and no need to change anything. I am just wondering whether we can extend sqlx parser somehow or we must go with this new SelectStatement 🤔 
@alamb may knows this better

2022-09-28 15:05 UTC, carols10cents commented on influxdb_influxql_parser/src/common.rs
> +    pub rest: Option<Vec<T>>,
Ahhh I meant to click "start a review". I'm still reviewing this PR.

2022-09-28 17:24 UTC, carols10cents requested changes
Overall, looks great, just a few cleanups/improvements!

2022-09-28 17:24 UTC, carols10cents commented on influxdb_influxql_parser/src/literal.rs
> +pub fn literal_no_regex(i: &str) -> ParseResult<&str, Literal> {
I'm confused, this comment says "including regular expressions" but the function is named `literal_no_regex`?

2022-09-28 17:24 UTC, carols10cents commented on influxdb_influxql_parser/src/select.rs
> +/// The offset argument accepts either a duration
This comment seems unfinished... either a duration or...?

2022-09-28 17:24 UTC, carols10cents commented on influxdb_influxql_parser/src/select.rs
> +            } => write!(f, "TIME({}, {})", interval, offset)?,
Same comment as other Display impls

2022-09-28 17:24 UTC, carols10cents commented on influxdb_influxql_parser/src/select.rs
> +            Self::Null => f.write_str("NULL")?,
Same comment as other Display impls

2022-09-28 17:24 UTC, carols10cents commented on influxdb_influxql_parser/src/select.rs
> +        );
These two cases look the same, should one be removed or changed?

2022-09-29 00:03 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        ///   and casting it to an `integer`
As you presumed, `float` and `integer` conversions are supported in both directions, per [our docs](https://docs.influxdata.com/influxdb/v1.8/query_language/explore-data/#cast-operations):

> The :: syntax allows users to perform basic cast operations in queries. Currently, InfluxDB supports casting [field values](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#field-value) from integers to floats or from floats to integers.

2022-09-29 00:06 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        let (_, got) = arithmetic_expression("5- -(3|2)").unwrap();
For the expression `5--(3|2)`, `--` will be treated as a comment, once I resolve #5663, which is the same as Go implementation.

For `2|5%3`, `|` and `%` have the same precedence and are left associative, so the result will be the same as `(2|5)%3`

2022-09-29 02:04 UTC, stuartcarnie commented on influxdb_influxql_parser/src/common.rs
> +    pub rest: Option<Vec<T>>,
I was originally thinking that would avoid an allocation of `Vec<T>` for the many cases where it will have a single element. However, now looking at the internals, it appears an empty Vec does not allocate on the heap, so I'll switch this out:

https://github.com/rust-lang/rust/blob/b30c88623cf1f8f3e67b189fb2c5df5a0d89aaed/library/alloc/src/raw_vec.rs#L122-L123

You are correct that I was conveying that this type must be one or more elements. I'll refactor it to use your suggested approach and hide the `contents` behind appropriate APIs

2022-09-29 02:05 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +                    Some(args) if !args.is_empty() => {
This too was me thinking I was avoiding the allocation of an empty `Vec<T>`, figuring it started with some default capacity on the heap, but it turns out it does not, so I'll also remove `Option<Vec<Expr>>` here too.

Thanks!

2022-09-29 02:54 UTC, stuartcarnie commented on influxdb_influxql_parser/src/common.rs
> +    pub rest: Option<Vec<T>>,
Addressed and greatly simplified in de62d18fac99f4e1ef77f52cee6af5fb7c0527d5.

Thanks for the feedback, @carols10cents 🙇🏻

2022-09-29 02:56 UTC, stuartcarnie commented on influxdb_influxql_parser/src/common.rs
> +    pub fn separated_list1<'a>(
Once I addressed your [earlier comment](https://github.com/influxdata/influxdb_iox/pull/5692#discussion_r982527476)[^1], this was pretty simple:

https://github.com/influxdata/influxdb_iox/blob/de62d18fac99f4e1ef77f52cee6af5fb7c0527d5/influxdb_influxql_parser/src/common.rs#L273-L282

[^1]: Addressed in de62d18fac99f4e1ef77f52cee6af5fb7c0527d5

2022-09-29 03:03 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +                    Some(args) if !args.is_empty() => {
Addressed in 4fbf03683c9dae65f245671a39886b338f18a10a

2022-09-29 03:03 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/conditional.rs
> +}
Addressed in 4fbf03683c9dae65f245671a39886b338f18a10a

2022-09-29 03:06 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        Ok(())
Ooh, nice catch, thank you!

2022-09-29 03:08 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        // Fallible cases
Great catch - test case added for invalid data type.

2022-09-29 03:11 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +    }
Done!

2022-09-29 03:14 UTC, stuartcarnie commented on influxdb_influxql_parser/src/literal.rs
> +pub fn literal_no_regex(i: &str) -> ParseResult<&str, Literal> {
Oops, missed the comment when I removed regular expression parsing from this combinator. Great catch, thanks!

2022-09-29 03:16 UTC, stuartcarnie commented on influxdb_influxql_parser/src/select.rs
> +/// The offset argument accepts either a duration
```
/// The offset argument accepts either a duration, datetime-like string or `now`.
```

2022-09-29 03:23 UTC, stuartcarnie commented on influxdb_influxql_parser/src/select.rs
> +        );
"are you really sure you can parse a call with a wildcard" 😆 

I've removed the duplicate – good catch!

2022-09-29 03:24 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        Ok(())
I've reviewed all `Display` implementations in the crate and simplified where possible.

2022-09-29 03:29 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/conditional.rs
> +pub enum ConditionalOperator {
Unfortunately the documentation doesn't really have a separate link for conditional operators. It has a binary_op description here:

https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#expressions

But that may be confusing, as it includes arithmetic operators also.

2022-09-29 03:40 UTC, stuartcarnie commented on influxdb_influxql_parser/src/select.rs
> +impl Display for SelectStatement {
We did consider amending the sqlparser-rs crate, but determined InfluxQL would have been too invasive for an existing SQL parser and we also wanted to produce an AST that more closely modelled the existing Go implementation.

We only intend to use the `SelectStatement` for InfluxQL support.

2022-09-29 03:43 UTC, stuartcarnie commented on influxdb_influxql_parser/src/expression/arithmetic.rs
> +        let (_, got) = arithmetic_expression("5- -(3|2)").unwrap();
I had also added a test case that will be uncommented when #5663 is resolved:

https://github.com/influxdata/influxdb_iox/blob/0753df8ae1cd543a1b08439e5c35c37db96d421a/influxdb_influxql_parser/src/expression/arithmetic.rs#L475-L476

2022-09-29 03:44 UTC, stuartcarnie commented
@carols10cents thank you for the thorough review, it is very much appreciated. I have implemented all your feedback in this PR.

@NGA-TRAN thank you too for your review – I've replied to your questions and linked any issues

2022-09-29 14:17 UTC, carols10cents approved these changes
The updates look great, thank you!!! 🎉

2022-09-29 23:10 UTC, merged