Implement `debug parquet_to_lp` command to convert parquet to line protocol
influxdata/influxdb_iox pull request #5734
Opened 2022-09-23 15:58 UTC by alamb

Draft until:
- [ ] Complete port
- [ ] Add unit tests
- [x] Add end to end tests

Closes https://github.com/influxdata/conductor/issues/1175

# Rationale
I want to locally reproduce some pathological cases we are seeing on our production system by ingesting the same data from production. 

However, today IOx only supports *ingesting* line protocol but there is no way to get the data back out as line protocol.

In the long term, it is likely we would want to offer users a way to get data out of IOx in the same form it went in (aka line protocol). While this is not my near term goal I will write the code so it could support this usecase without major rework. 

# Changes
1. Add a `parquet_to_line_protocol` crate with the core logic for reading parquet data and converting it to 
1. Add a `influxdb_iox debug parquet_to_lp` command that cover
2.  (MAYBE FOLLOW ON) Nice to have -- implement a "LineProtocol" output format option for printing the results of queries as line protocol

# Example runs
(TODO)

2022-09-23 19:34 UTC, alamb commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +#[tokio::test]
here is a new end to end test showing this command

2022-09-23 19:34 UTC, alamb commented on influxdb_line_protocol/src/builder.rs
> +    fn test_float_formatting() {
This was a new test I wrote when I thought I had a bug in my converter

2022-09-23 19:34 UTC, alamb commented on parquet_file/src/metadata.rs
> +    pub fn to_base64(&self) -> std::result::Result<String, prost::EncodeError> {
Refactored slightly so I can call these functions directly from the converter code

2022-09-23 19:34 UTC, alamb commented on parquet_to_line_protocol/src/batch.rs
> +pub(crate) fn convert_to_lines(
This is the core IOx code that translates from RecordBatches back into the LineProtocol format (using the fancy builder created by @mkmik  in https://github.com/influxdata/influxdb_iox/pull/5183 👨‍🍳 👌

2022-09-23 19:34 UTC, alamb commented on parquet_to_line_protocol/src/batch.rs
> +    fn no_fields() {
The tests simply ensure that parsing / converting  line protocol results in the same thign

2022-09-23 19:34 UTC, alamb commented on parquet_to_line_protocol/src/lib.rs
> +        // Use datafusion parquet reader to read the metadata from the
🤔 it would probably be possible to use just the Arrow one

Though doing it this way will allow eventually to read multiple files quite easily

2022-09-23 21:53 UTC, carols10cents requested changes
Overall, this is great!

This works great! How I tested:

- Found a parquet file I had laying around (it wasn't very big)
- Ran `cargo run -- debug parquet-to-lp 07574213-8c6d-4c8e-a594-fd0a8e353e97.parquet` and got the expected line protocol printed to stdout
- Ran `cargo run -- debug parquet-to-lp -o output.txt 07574213-8c6d-4c8e-a594-fd0a8e353e97.parquet` and got the expected line protocol in the file output.txt
- Ran `cargo run -- -v debug parquet-to-lp 07574213-8c6d-4c8e-a594-fd0a8e353e97.parquet` and saw some logs along with the output
- Ran `cargo run -- debug --help` and saw appropriate docs for the `parquet-to-lp` subcommand
- Ran `cargo run -- debug parquet-to-lp --help` and saw appropriate docs for the options and argumnets to the `parquet-to-lp` subcommand
- Ran `cargo run -- debug parquet-to-lp` and saw an appropriate error message
- Ran `cargo run -- debug parquet-to-lp influxdb_iox/src/main.rs` and got the error message:

```
Error in parquet_to_lp subcommand: Error converting: Error infering IOx schema: Parquet error: Parquet error: Invalid Parquet file. Corrupt footer
```

which is fine, a bit repetitive and verbose, but I don't think that behavior is introduced in this PR.

I do have a bunch of little picky things I commented on :)

2022-09-23 21:53 UTC, carols10cents commented on influxdb_iox/src/commands/debug/mod.rs
> +    /// Convert IOx parquet files back into line protocol format
I *think* the official documentation usually capitalizes Parquet in this sort of context? You're on the team though, so you probably have a better idea of how important this is to the project :)

```suggestion
    /// Convert IOx Parquet files back into line protocol format
```

2022-09-23 21:53 UTC, carols10cents commented on influxdb_iox/src/commands/debug/parquet_to_lp.rs
> +/// Convert IOx parquet files into InfluxDB Line Protocol format
Parquet should probably be capitalized here too, and in this spot you've capitalized Line Protocol but I don't see that capitalized in official docs? https://docs.influxdata.com/influxdb/v2.4/reference/syntax/line-protocol/

```suggestion
/// Convert IOx Parquet files into InfluxDB Line Protocol format
```

2022-09-23 21:53 UTC, carols10cents commented on parquet_to_line_protocol/src/lib.rs
> +    // columns are tags and field sfields is stored
Extra fields snuck in here:

```suggestion
    // columns are tags and fields is stored
```

2022-09-23 21:53 UTC, carols10cents commented on parquet_to_line_protocol/src/batch.rs
> +use std::result::Result;
I don't think this line is needed? `Result` is in the prelude and is in scope by default?

2022-09-23 21:53 UTC, carols10cents commented on parquet_to_line_protocol/src/lib.rs
> +    #[snafu(display("Error infering IOx schema: {}", source))]
Typo:

```suggestion
    #[snafu(display("Error inferring IOx schema: {}", source))]
```

2022-09-23 21:53 UTC, carols10cents commented on parquet_to_line_protocol/src/batch.rs
> +/// Return an iterator over all non null tags in a batch
Copypasta?

```suggestion
/// Return an iterator over all non null fields in a batch
```

2022-09-23 21:53 UTC, carols10cents commented on parquet_to_line_protocol/src/batch.rs
> +/// Find the timestamp value for the specifid row
Typo

```suggestion
/// Find the timestamp value for the specified row
```

2022-09-23 21:53 UTC, carols10cents commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +                        "Could not file {} in {}",
I think this is supposed to say:

```suggestion
                        "Could not find {} in {}",
```

2022-09-26 10:32 UTC, alamb reviewed
> `Error in parquet_to_lp subcommand: Error converting: Error infering IOx schema: Parquet error: Parquet error: Invalid Parquet file. Corrupt footer`
> which is fine, a bit repetitive and verbose, but I don't think that behavior is introduced in this PR.

I agree this behavior is non ideal -- I'll try and make it better using the source ext from snafu

2022-09-26 10:32 UTC, alamb commented on influxdb_iox/src/commands/debug/mod.rs
> +    /// Convert IOx parquet files back into line protocol format
Capitalization is good! I don't know of any particularly stringent style guides, but capitalizing proper names sounds like a good plan to me. Thank you

2022-09-26 10:32 UTC, alamb commented on influxdb_iox/src/commands/debug/parquet_to_lp.rs
> +/// Convert IOx parquet files into InfluxDB Line Protocol format
good call -- will change to `Parquet` and `line protocol`

2022-09-26 10:32 UTC, alamb commented on parquet_to_line_protocol/src/batch.rs
> +/// Return an iterator over all non null tags in a batch
🤦

2022-09-26 10:32 UTC, alamb commented on parquet_to_line_protocol/src/batch.rs
> +use std::result::Result;
You are correct. Removed in c2706f948

2022-09-26 11:02 UTC, alamb commented
> I agree this behavior is non ideal -- I'll try and make it better using the source ext from snafu

@carols10cents  I started to work on this in https://github.com/influxdata/influxdb_iox/pull/5739 and would love your feedback there

2022-09-26 14:17 UTC, carols10cents approved these changes
Thank you!!!

2022-09-26 14:17 UTC, merged