fix: always pick cold partitions in next cycle even if it has been pa…
influxdata/influxdb_iox pull request #5772
Opened 2022-09-29 18:33 UTC by NGA-TRAN

…rtially compacted recently

Closes #5755 

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-09-29 18:36 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +            created_at: time_five_hour_ago,
The is the change of the test: instead of a L-0 created long a go, make it a L1 created recently. This partition is still a cold partition

2022-09-29 18:50 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +                                .and(predicate::str::contains(r#""compactionLevel": 2"#)),
Since now we have cold compaction that will compact everything to level-2, this is the expected output now. I am not sure why it still passed with 1 recently

2022-09-29 19:53 UTC, carols10cents requested changes
Close, I think!

2022-09-29 19:53 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +       max(case when compaction_level=0 then parquet_file.created_at end) is null
Could you change all the instances of `compaction_level=0` in the query to `compaction_level = $4`? I've been parameterizing compaction levels so that the Rust enum is the source of truth about what enum values equal what integers and there's only one place to update if we decide to change them in the future.

2022-09-29 19:53 UTC, carols10cents commented on iox_catalog/src/interface.rs
> +            created_at: time_five_hour_ago,
Isn't the case of a L-0 file created long ago still a valid test case though? That is, if hot compaction isn't keeping up and a level 0 file gets old, then we want to choose it for cold compaction?

In other words, why is this changing the parquet file in the test setup rather than creating a new test setup scenario?

2022-09-29 19:53 UTC, carols10cents commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +                                .and(predicate::str::contains(r#""compactionLevel": 2"#)),
This is suspicious... this makes me think that before this PR, the partition in this test was being treated by the compactor as a hot partition and going from 0 -> 1, and now with these changes it's being treated as a cold partition and going from 0 -> 1 -> 2? We should figure out why that is.

2022-09-29 20:01 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +            created_at: time_five_hour_ago,
I have gone over the tests and we have 3 partitions, all with L-0 files which means they are duplicates. Actual they are `one` and `three` partitions are similar. The reason we created 3 partitions because we want to test num_partitions =2. Thus, instead of adding a new test, we change the partition `three` to make it include no-L0 but still a cold partition.

I also add num_partitions = 5 test to make sure we return all 3 of them

2022-09-29 20:02 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +       max(case when compaction_level=0 then parquet_file.created_at end) is null
Good idea. Working on it

2022-09-29 20:16 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +                                .and(predicate::str::contains(r#""compactionLevel": 2"#)),
Found the reason. The `Step::Compact` invokes `run_compaction` that will call `run_compactor_once`.

The `run_compactor_once` invokes hot that will compact all L0s into L1 and then cold. Before the change if there are only L1 files, the cold will check for their `created_at` and if recently, do nothing. With this change, if there are only L1s which is the case, the cold will work.

So actually, this is a test for the change, too 🎉

2022-09-29 20:16 UTC, NGA-TRAN commented
@carols10cents I have addressed your comment. One code change and 2 other explanations.

2022-09-29 20:19 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +       max(case when compaction_level=0 then parquet_file.created_at end) is null
Done

2022-09-29 20:57 UTC, NGA-TRAN commented
I actually want to change a bit more. No new write the last N hours means we need to consider create_time of deleted files, too

2022-09-29 22:09 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +HAVING count(case when to_delete is null then 1 end) > 0
Make sure we only return data of non-deleted files

2022-09-29 22:09 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +       max(case when compaction_level= $4 then parquet_file.created_at end)
make sure we consider created-time of deleted L0, too

2022-09-29 22:10 UTC, NGA-TRAN commented
@carols10cents : I have committed the code to also consider `create_at` of deleted L0. This is now ready for re-review. I have added more tests to cover all cases I think but this is a bit tricky and hope you give it a stare to see if I miss anything

2022-09-30 14:48 UTC, carols10cents commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +                                .and(predicate::str::contains(r#""compactionLevel": 2"#)),
Good!!!!!

2022-09-30 15:54 UTC, merged