feat: Enforce namespace column limits from the cache
influxdata/influxdb_iox pull request #5819
Opened 2022-10-07 18:37 UTC by carols10cents

Connects to https://github.com/influxdata/influxdb_iox/issues/4349.

Adding many columns at once, which `write` does through `validate_or_insert_schema`, was not checking the namespace `max_columns_per_table` limit because [the query was complicated and expensive](https://github.com/influxdata/influxdb_iox/pull/4351).

This PR adds a function `validate_column_limits` that takes the mutable batches in a write and the in-memory NamespaceSchema cache and checks that, as far as the cache knows, the columns in all the batches won't cause the table to go over the namespace's limit.

In addition to [the race condition I mentioned](https://github.com/influxdata/influxdb_iox/issues/4349#issuecomment-1270622632), this solution has another limitation that updating the `max_columns_per_table` limit on the namespace in the catalog doesn't update the namespace cache value, so if we change the limits at runtime, they won't take effect until that namespace schema is entirely reloaded into the cache, likely at router startup. If that's not ok, let me know and I can work on a solution!

2022-10-11 10:29 UTC, domodwyer requested changes
Looking good! 

Might be worth documenting the column limit enforcement behaviour in the `SchemaValidator` [docs](https://github.com/influxdata/influxdb_iox/blob/755453385c5ebc749b7d17b7c93e648c89cdf23f/router/src/dml_handlers/schema_validation.rs#L41-L85), especially the expected raciness of this impl (which is a fine trade-off 👌) so we can point people at it when they ask "wat do".

Worth noting it's more racy than it first appears, because when requests are spread over 6 routers, it is calculated across 6 caches which are eventually consistent - the "overshoot" of this impl increases with the number of routers. https://github.com/influxdata/influxdb_iox/issues/5005 will help reduce this overshoot.

2022-10-11 10:29 UTC, domodwyer commented on router/src/dml_handlers/schema_validation.rs
> +        }
I think the variable `table_column_names` actually being the full set of columns after line 283 caused the error message inconsistency above! If we were to use the proposed error, then `OverColumnLimit` would be something like:

```rust
struct OverColumnLimit {
    table_name: String,

    // Number of resultant columns after merging the write with existing
    // columns.
    merged_column_count: usize,

    // Number of columns already in the table.
    existing_column_count: usize,

    // The configured limit.
    max_columns_per_table: usize,
}
```

And this block could be:

```suggestion
        let mut existing_columns = schema
            .tables
            .get(table_name)
            .map(|t| t.column_names())
            .unwrap_or_default();

        let existing_column_count = existing_columns.len();
        let merged_column_count = {
            existing_columns.append(&mut batch.column_names());
            existing_columns.len()
        };

        if merged_column_count > schema.max_columns_per_table {
            return Err(OverColumnLimit {
                table_name: table_name.into(),
                merged_column_count,
                existing_column_count,
                max_columns_per_table: schema.max_columns_per_table,
            });
        }
```

This test case will highlight the bad var usage, where `num_batch_columns` is currently asserting as being 5, despite the write containing only one new column:

```rust
        // Create a table that is at the column limit.
        {
            let table = namespace.create_table("bananas").await;
            table.create_column("greatness", ColumnType::I64).await;
            table.create_column("tastiness", ColumnType::I64).await;
            table.create_column("timestamp", ColumnType::Time).await;
            let schema = namespace.schema().await;
            // Adding columns over the limit is an error
            let batches = lp_to_writes("bananas i_got_music=42i 123456");
            assert_matches!(
                validate_column_limits(&batches, &schema),
                Err(OverColumnLimit {
                    table_name: _,
                    num_batch_columns: 1, // i_got_music
                    max_columns_per_table: 3
                })
            );
        }
```

2022-10-11 10:29 UTC, domodwyer commented on router/src/dml_handlers/schema_validation.rs
> +        let batches = lp_to_writes("nonexistent val=42i 123456");
Nice 42 👋

2022-10-11 10:29 UTC, domodwyer commented on router/src/dml_handlers/schema_validation.rs
> +        table.create_column("i_got_music", ColumnType::I64).await;
Looks like a missing shadowing of `schema` to use the new table/columns:

```suggestion
        table.create_column("i_got_music", ColumnType::I64).await;
        let schema = namespace.schema().await;
```

Perhaps worth scoping the tests to avoid re-use:

```rust
        // Table exists with a column in the schema,
        {
            let table = namespace.create_table("i_got_columns").await;
            table.create_column("i_got_music", ColumnType::I64).await;
            let schema = namespace.schema().await;
            // Columns already existing is ok
            let batches = lp_to_writes("i_got_columns i_got_music=42i 123456");
            assert!(validate_column_limits(&batches, &schema).is_ok());
            // Adding columns under the limit is ok
            let batches = lp_to_writes("i_got_columns,tag1=A i_got_music=42i 123456");
            assert!(validate_column_limits(&batches, &schema).is_ok());
            // Adding columns over the limit is an error
            let batches = lp_to_writes("i_got_columns,tag1=A,tag2=B i_got_music=42i 123456");
            assert_matches!(
                validate_column_limits(&batches, &schema),
                Err(OverColumnLimit {
                    table_name: _,
                    num_batch_columns: 4, // tag1, tag2, i_got_music & timestamp
                    max_columns_per_table: 3
                })
            );
        }
```

2022-10-12 17:08 UTC, carols10cents commented on router/src/dml_handlers/schema_validation.rs
> +        table.create_column("i_got_music", ColumnType::I64).await;
Yuuuuup, and laziness on my part just asserting `is_err` 😪

2022-10-12 17:17 UTC, carols10cents commented on iox_catalog/src/lib.rs
> +        .collect();
Oh good call! My brain gets lost in type soup sometimes...

2022-10-12 17:34 UTC, carols10cents commented
@domodwyer Great comments, thank you!! I think this is ready for rereview :)

2022-10-13 14:11 UTC, carols10cents commented
Putting this back to draft-- Dom and I chatted and I'm going to change the "broken table" behavior in this PR :)

2022-10-13 15:53 UTC, carols10cents commented
@domodwyer two new commits for you to get rid of the broken table behavior!

2022-10-13 16:20 UTC, domodwyer commented
Awesome! Thank you - I'll review this tomorrow morning my time :+1:

2022-10-14 11:26 UTC, domodwyer approved these changes
Fantastic stuff 🎉 

Thanks for the PR etiquette, pushing a couple of commits instead of rewriting the old ones - makes reviewing additive changes much easier :+1:

2022-10-14 11:26 UTC, domodwyer commented on router/src/dml_handlers/schema_validation.rs
> +            // Columns already existing is an error, this table is in a broken state
Nice TDD 👍

2022-10-14 11:34 UTC, merged