chore: update rskafka
influxdata/influxdb_iox pull request #5998
Opened 2022-10-28 11:20 UTC by crepererum

Includes additional logging to debug https://github.com/influxdata/idpe/issues/16278

2022-10-28 11:41 UTC, domodwyer requested changes

2022-10-28 11:41 UTC, domodwyer commented on .cargo/config
> +    "-C", "link-arg=-Wl,--icf=all",
This looks unintentional?

2022-11-01 06:32 UTC, crepererum commented on .cargo/config
> +    "-C", "link-arg=-Wl,--icf=all",
yes, code-gen experiments :sweat_smile:

2022-11-01 06:34 UTC, mkmik approved these changes

2022-11-01 06:39 UTC, merged