feat: flag partitions for delete
influxdata/influxdb_iox pull request #6075
Opened 2022-11-07 22:52 UTC by NGA-TRAN

First part of #6025 to flag partitions to delete
Next PR I will invoke this in GC

Describe your proposed changes here.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-11-08 10:48 UTC, lukebond requested changes

2022-11-08 10:48 UTC, lukebond commented on iox_catalog/src/interface.rs
> +        // No retention period set, nothing should be flagged for deletion
suggest prefixing comment with `1. ` so that the `2. ` and `3. ` further down makes sense

2022-11-08 10:48 UTC, lukebond commented on iox_catalog/src/interface.rs
> +                                                     // 3. flag for select again and shold not get anything return becasue the partitions are already flagged for deletion
fix alignment here. think you need a newline in between to get around the auto formatter

2022-11-08 10:48 UTC, lukebond commented on iox_catalog/src/interface.rs
> +        assert!(ids.len() > 1); // fail PG
this `// fail PG` is a note for you perhaps? if it's to remain in the PR when not a draft then i don't know what it means. same with `'// fail mem` below

2022-11-08 10:48 UTC, lukebond commented on iox_catalog/src/mem.rs
> +                if p.to_delete.is_some() {
wouldn't this return `None` from the `flag_for_delete_by_retention` function? i don't see the compiler complaining about this but it surprised me. wonder if it would be nicer to do something like:

```rust
        Ok(stage
            .partitions
            .iter_mut()
            // don't flag if already flagged for deletion
            .filter(|f| f.to_delete.is_none())
            .filter_map(|p| {
                stage
                    .tables
                    .iter()
                    .find(|t| t.id == p.table_id)
                    .and_then(|t| {
                      ...
```

2022-11-08 10:48 UTC, lukebond commented on iox_catalog/src/mem.rs
> +                                if naive_date.is_ok() {
i think the error handling of `parse_from_str` would be nicer with something like this:

```rust
NaiveDate::parse_from_str(
  &p.partition_key.to_string(),
  "%Y-%m-%d",
)
.ok() // convert result to option
.and_then(|naive_date| { // return None if None, else call closure with existing logic & no need to unwrap
  ...
})
```

2022-11-08 21:01 UTC, NGA-TRAN commented
@lukebond The pR is ready for review

2022-11-09 11:07 UTC, lukebond approved these changes
a couple of cosmetic and style things but otherwise LGTM!

2022-11-09 11:07 UTC, lukebond commented on iox_catalog/src/mem.rs
> +                                if let Some(retention_ns) = ns.retention_period_ns {
these `if let Some(...) { } else { None }` blocks could be cleaner like so:

```rust
ns.retention_period_ns.and_then(|retention_ms| {
})
```

which will return `None` if it's `None` and call the close if `Some`. there are three places in this block where you could do that.

not enough to make me decline the review of course!

2022-11-09 11:07 UTC, lukebond commented on iox_catalog/src/postgres.rs
> +            update partition p
just cosmetic of course but it'd be nice if the SQL keywords were uppercased like all the others in the file

2022-11-09 11:56 UTC, lukebond commented
@NGA-TRAN i'm going to make the changes i suggested above and merge, then rebase #6090 because it's difficult to review when it includes these changes as well

2022-11-09 12:06 UTC, merged

2022-11-09 14:47 UTC, NGA-TRAN reviewed
Thanks for the suggestions and commit @lukebond