refactor: generic deferred loader helper
influxdata/influxdb_iox pull request #6095
Opened 2022-11-09 15:19 UTC by domodwyer

**This PR makes no functional change the system.**

Instead, it splits apart the `DeferredSortKey` so the "deferred load" bit of it can be reused.

---

* refactor: generic deferred loader helper (3e1103a8e)

      Splits the DeferredSortKey loader introduced in #5807 into two parts - a
      generic helper type that implements deferred/background loading of
      values, and SortKey specific logic for use with it.
      
      As this will be more widley used, this implementation features improved
      behaviour of the deferred loader under concurrent demand requests
      (multiple calls to get() do not attempt to concurrently resolve the
      value), as well as complete cancellation safety (cancelling the get()
      doesn't affect the liveness of the background task).

2022-11-09 15:25 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +}
It's a state machine!

2022-11-09 15:25 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +                }
When initialising a `DeferredLoad` a background task is spawned and it waits until the random timer fires, or it is asked to resolve the value.

2022-11-09 15:25 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +                    let _ = task_waker.send(());
A user can wake up the background task and get it to resolve the value (by executing the future) by calling `get()`. 

If it is the first call to `get()` and the value hasn't yet been loaded in the background, the caller triggers the background task to execute the future immediately, and then waits for the result.

2022-11-09 15:25 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +        waker.notified().await;
All other concurrent callers to `get()` also wait for the result in the same way as the triggering caller.

2022-11-09 15:25 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +                        }
Once the future execution is complete, the background task stores the result.

2022-11-09 15:25 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +                }
And wakes up any `get()` callers that are still waiting for the value.

2022-11-09 19:49 UTC, carols10cents requested changes
I have some questions and thoughts of various importance :)

2022-11-09 19:49 UTC, carols10cents commented on ingester/src/deferred_load.rs
> +    /// indoors during lightening storms.
1. 🤣 
2. Typo, "lightening" should be "lightning"
3. This is a bit dark, isn't it? How about:

```suggestion
    /// multiple times, I'd suggest entering a lottery and/or checking changes for bugs.
```

2022-11-09 19:49 UTC, carols10cents commented on ingester/src/deferred_load.rs
> +        assert_eq!(d.get().await, 42);
If something about `get` is wrong and doesn't resolve the future immediately, instead waiting for the background task, isn't it likely that this test will hang rather than fail? That is, shouldn't this test be using `with_timeout_panic` like some of the other tests are with a value like 5s?

2022-11-10 13:34 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +    /// The option facilitates taking ownership of the state to transition, and
I am totally fine with comments like this! I try to doclink to types as much as possible because a) it's nice, b) good docs are nice, and c) it helps keep our docs in-sync when we change the names of types/remove things. Admittedly (c) is unlikely to happen for `Option`, but ya never know 😆

2022-11-10 13:36 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +    pub(crate) fn new<F>(deadline: Duration, loader: F) -> Self
Yeah and it's not actually really a deadline if we're putting a pedantic hat on - saying "it must complete in 5 seconds" is not something we can uphold; if the task is scheduled and starts the sleep 10 seconds later, then 💩

2022-11-10 13:37 UTC, domodwyer commented on ingester/src/deferred_load.rs
> +        assert_eq!(d.get().await, 42);
Yes, truthfully I remembered I should be adding timeouts about half way through the tests and didn't bother going back over what I had already wrote 🦡

2022-11-10 18:37 UTC, carols10cents approved these changes
Thanks, this LGTM now!

2022-11-10 19:16 UTC, merged

2022-11-11 00:26 UTC, alamb commented on ingester/src/data/partition/resolver/sort_key.rs
> +impl SortKeyResolver {
FWIW this looks nontrivially similar to the `cache_system` crate from @crepererum  -- https://github.com/influxdata/influxdb_iox/tree/main/cache_system that is used in the querier

As the ingester grows more sophisticated caching it might be worth investing time to see if we can unify the caching mechanisms in the two (and get access to the common metrics, etssting, etc)

2022-11-11 09:59 UTC, crepererum commented on ingester/src/data/partition/resolver/sort_key.rs
> +impl SortKeyResolver {
I agree.