feat: gRPC that creates namespace
influxdata/influxdb_iox pull request #6103
Opened 2022-11-09 22:14 UTC by NGA-TRAN

Closes #6096 

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-11-09 22:16 UTC, NGA-TRAN commented on clap_blocks/src/write_buffer.rs
> +
@domodwyer I have refactored this to reuse in both router and create namespace as you suggested. Their CLI commands are different and I do not want to use router's config for namespace

2022-11-10 10:13 UTC, domodwyer requested changes
I think I understand some of the confusion I've had in slack! I left some comments but we can chat on zoom later today if you want :+1:

Thanks for building this out 🙏

2022-11-10 10:13 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +        const NEW_RETENTION_PERIOD_NS: i64 = 5 * 60 * 60 * 1000 * 1000 * 1000;
Perhaps we ensure this stays in sync:

```suggestion
        const NEW_RETENTION_PERIOD_NS: i64 = NEW_RETENTION_PERIOD * 60 * 60 * 1000 * 1000 * 1000;
```

2022-11-10 10:13 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +
What is the difference between `retention_duration` and `retention_period_hours`? Can we not reuse the existing `create()` method to keep the catalog interface small & concise?

2022-11-10 11:05 UTC, lukebond commented on iox_catalog/src/interface.rs
> +
`retention_duration` is old and unused and will be removed in https://github.com/influxdata/influxdb_iox/issues/6029 - i think Nga is holding off removing it until the replacement field is working, which is a small epic here: https://github.com/influxdata/influxdb_iox/issues/3053

removing it as part of this PR will touch a lot of places (i tried in an earlier PR and recoiled!).

2022-11-10 13:28 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +
I see - perhaps we can keep using the existing method / fields in this API in this PR, and change everything in one go? It seems like it will be confusing if the user says "retention: 4 days", and the API creates a database entry with "infinite" and "4 hours", and all the existing code ignores the "4 hours" bit - ideally we'd do an atomic change over to add the new field and use it, but looks like it's already in the database schema.

A clean changeover might be better where add the namespace API in one (this) PR, and then open another PR for #6029 after that changes all the code to use the new retention in one go rather than leaving it inconsistent.

2022-11-10 18:10 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
> +  string query_pool = 4;
Silly me to interpret it that if we use the same parameter in the client request as done above https://github.com/influxdata/influxdb_iox/pull/6103/files#r1018465409, when we remove the parameter, we will remove them everywhere.

Using the one populated on the server side makes more sense. Let me do it then.

2022-11-10 18:10 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
>    rpc UpdateNamespaceRetention(UpdateNamespaceRetentionRequest) returns (UpdateNamespaceRetentionResponse);
@alamb suggested me to use Schema API for namespace (update and create). Moving them somewhere else is not that tricky. Where  do you suggest them @alamb and @domodwyer ?

2022-11-10 18:10 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +
@domodwyer : let me try to see if I can remove `retention_duration` first and then come back to this PR. I agree it will be cleaner. I hoped to understand  `retention_duration` better as we proceed with `retention_period_hour` and then remove `retention_duration` but I think by doing the opposite way (removing `retention_duration` first), I might get a lot better insight to implement `retention_period_hour`

2022-11-10 18:21 UTC, NGA-TRAN commented
I have converted to draft. I will come back after #6029

2022-11-10 18:22 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +
That makes sense too! I think today everything everywhere uses the hard-coded const (or hard-codes "inf" themselves):

https://github.com/influxdata/influxdb_iox/blob/93e11d4c9172fb3ae87d66d9f8a84f2a496df587/iox_catalog/src/lib.rs#L38-L39

So removing it should be fairly painless - nothing cares about it / makes use of the value today as far as I know.

2022-11-14 20:47 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
>    rpc UpdateNamespaceRetention(UpdateNamespaceRetentionRequest) returns (UpdateNamespaceRetentionResponse);
@domodwyer: Let us do this in a separate PR after we have a decision of this discussion https://influxdata.slack.com/archives/CRK9M8L5Q/p1668193721306879

2022-11-14 20:47 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
> +  reserved 3, 4;
Let me know if you think I should remove these reserved? I remove them in this PR but this PR is not yet merged

2022-11-14 20:47 UTC, NGA-TRAN commented on querier/src/handler.rs
> +        SchemaServiceServer::new(SchemaService::new(Arc::clone(&self.catalog), None, None))
We will return `unimplemented` if the create namespace is invoked from Querier. Provide no topic and query pool here will do the job

2022-11-14 20:47 UTC, NGA-TRAN commented on router/src/server/grpc.rs
> +    query_pool_id: QueryPoolId,
Store topic id and query pool id in this struct when the router is created

2022-11-14 20:47 UTC, NGA-TRAN commented on router/src/server/grpc.rs
> +        ))
And then they are provided to the Schema service

2022-11-14 20:47 UTC, NGA-TRAN commented
@domodwyer and @lukebond : The PR is ready for rereviewing

2022-11-14 21:42 UTC, mkmik commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
> +  reserved 3, 4;
Did you add these fields in a previous commit of this PR and later removed them?

If yes, then we don't have to declare them as reserved here

2022-11-14 22:06 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
> +  reserved 3, 4;
Yeah, the field #3 and #4 were added in a previous commit but not merged yet. I will remove this line

2022-11-15 20:38 UTC, alamb commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
>    rpc UpdateNamespaceRetention(UpdateNamespaceRetentionRequest) returns (UpdateNamespaceRetentionResponse);
I believe the consensus at the meeting was to put this API into the existing namespace service https://github.com/influxdata/influxdb_iox/blob/main/generated_types/protos/influxdata/iox/namespace/v1/service.proto and also run that gRPC service in the router server/process

2022-11-15 20:40 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/schema/v1/service.proto
>    rpc UpdateNamespaceRetention(UpdateNamespaceRetentionRequest) returns (UpdateNamespaceRetentionResponse);
Yeah @lukebond is working on this

2022-11-17 14:47 UTC, lukebond commented
i have rebased this PR on main after merging #6151, which moved the namespace API to the router and put the update retention call in there. this PR now adds the create API call to the namespace API after said refactor. i also kept retention in nanoseconds except where it interfaces the user: the CLI.

2022-11-17 15:25 UTC, NGA-TRAN reviewed
Thanks so much @lukebond for splitting namespace service and merge it here

2022-11-17 15:27 UTC, domodwyer commented on iox_catalog/src/postgres.rs
> +        .bind(retention_period_ns) // $1
that's right - sqlx maps `Option` to a nullable field 🎉

2022-11-18 09:28 UTC, domodwyer approved these changes
Approving because code looks great - thank you for going the extra mile on this 🙏

Minor comments, but good to merge after :+1:

2022-11-18 09:28 UTC, domodwyer commented on influxdb_iox/src/commands/namespace/create.rs
> +    /// If not specified, the default retention period will be used.
```suggestion
    /// If not specified, an infinite retention period will be used.
```

2022-11-18 09:28 UTC, domodwyer commented on iox_catalog/src/interface.rs
> +    ) -> Result<Namespace>;
We should merge this with `create()` as they're functionally identical if you pass `None` as the retention period.

2022-11-18 09:28 UTC, domodwyer commented on iox_catalog/src/interface.rs
> -pub async fn update_namespace_retention<R>(
Thank you for removing this :+1: I am keen on keeping the API surface area as small as possible in the catalog because otherwise it becomes (more of!) a monster!

2022-11-18 09:28 UTC, domodwyer commented on service_grpc_namespace/src/lib.rs
> +            return Err(Status::unimplemented("topic_id or query_id not set"));
This perhaps should be a "you gave us an invalid argument" response:

```suggestion
            return Err(Status::invalid_argument("topic_id or query_id not set"));
```

That signifies that the user-provided input is bad/insufficient/broken, whereas the `unimplemented` would mean "this action is not available", suggesting a code/server issue.

2022-11-18 11:15 UTC, lukebond commented on iox_catalog/src/interface.rs
> +    ) -> Result<Namespace>;
have done this now

2022-11-18 11:17 UTC, lukebond commented
merging namespace `create` and `create_with_retention` touched a lot of files (mostly adding `, None` to test code). also found a constant only used in tests but not limited to `#[cfg(test)]` which proved too difficult to limit to `#[cfg(test])` because of how the atalog interface/mem/postgres setup works w.r.t. tests. i did tidy up its usage a little and rename the `create_namespace` helper that was silently setting retention to 1hr in all tests that used it.

2022-11-18 12:51 UTC, lukebond commented
i modified the behaviour introduced in #6148 that gave the mem catalog impl a default retention period of 1hr. touched a lot of places but avoids a trap that i walked right into and resulted in all the extra commits above until i realised what was going on

2022-11-18 13:02 UTC, merged