chore: Update datafusion again
influxdata/influxdb_iox pull request #6108
Opened 2022-11-10 15:23 UTC by alamb

# Rationale
* Keep up with changes in DataFusion.
* Test if https://github.com/apache/arrow-datafusion/pull/4122 causes us any problems

# Changes:
1. Update DataFusion pin to https://github.com/apache/arrow-datafusion/commit/4d621c5c0da387f50c9ab6f3a9ee568062ee9976
2. Update APIs for differences

2022-11-10 16:51 UTC, alamb commented on query_tests/cases/in/duplicates_ingester.expected
> +|               |               SortExec: [state@4 ASC,city@1 ASC,time@5 ASC]                                                                                                            |
This diff doesn't make it easy to see, but the difference is that a new SortExec is added here

The reason this happens is that the new `BasicEnforcement` rule added in https://github.com/apache/arrow-datafusion/pull/4122 by @mingmwang is (correctly) deciding that since the `ParquetExec` declares its output is not sorted, then the output of the `UnionExec` is also therefore not sorted, and thus needs to be resorted prior to the sort preserving merge.

 I think the way to avoid this is to teach DataFusion that the ParquetExec is actually sorted (which is is) and then everything will work out.


As a bonus, I think at least some part of the logic in the plan construction of IOx (that adds SortExec's in to sort the data) could potentially be removed as it is now covered by the DataFusion optimizer. I think this is very much in line with  @crepererum 's ideas from https://github.com/influxdata/influxdb_iox/issues/6098

2022-11-10 17:10 UTC, crepererum approved these changes

2022-11-10 18:26 UTC, alamb commented on query_tests/cases/in/duplicates_ingester.expected
> +|               |               SortExec: [state@4 ASC,city@1 ASC,time@5 ASC]                                                                                                            |
Filed upstream issue: https://github.com/apache/arrow-datafusion/issues/4169

2022-11-14 19:29 UTC, alamb commented on iox_query/src/provider/physical.rs
> +        let output_ordering =
Creating this output ordering is important to tell  DataFusion the data is already sorted so that it doesn't put another sort in our plan

2022-11-14 19:30 UTC, alamb commented on querier/src/namespace/query_access.rs
> +                "|               |             ParquetExec: limit=None, partitions=[1/2/1/4/<uuid>.parquet], output_ordering=[host@0 ASC, time@2 ASC], projection=[host, perc, time] |",
the difference in these plans is that the output ordering is now specified

2022-11-14 19:31 UTC, alamb commented
@crepererum  FYI this PR has changed substantially since you last reviewed it

2022-11-14 21:58 UTC, NGA-TRAN approved these changes
So nice that we can see the output ordering in the plan now and that we upgrade DF but keep our query plan optimal. Thanks @alamb
Those query plans are worth keeping

2022-11-14 21:58 UTC, NGA-TRAN commented on iox_query/src/provider/physical.rs
> +        }
So the whole purpose of this match is to not clone the key when possible?

2022-11-14 21:58 UTC, NGA-TRAN commented on iox_query/src/provider/physical.rs
> +                            .add_parquet_file(chunk.as_ref(), parquet_input.object_meta);
I asked myself why the `combine_sort_key` returns `None` when one of the input is none. But when I come to this line I see it makes sense 👍

2022-11-14 21:58 UTC, NGA-TRAN commented on iox_query/src/provider/physical.rs
> +        );
You may want to add a test to combine `skey_t1_t2` with `skey_t2_t1` and I think it will return None, right?

2022-11-14 21:58 UTC, NGA-TRAN commented on parquet_file/src/storage.rs
> +            output_ordering: None,
I am not sure I understand the comment

2022-11-14 21:58 UTC, NGA-TRAN commented on query_tests/cases/in/duplicates_parquet.expected
> +|    |             ParquetExec: limit=None, partitions=[1/1/1/1/00000000-0000-0000-0000-000000000002.parquet, 1/1/1/1/00000000-0000-0000-0000-000000000003.parquet], predicate=state_min@0 <= MA AND MA
Even though there are no highlight here, the differences are the output-ordering 👍

2022-11-15 09:31 UTC, crepererum requested changes
Needs some more work regarding the overflow test (see comment) and the parquet chunk grouping due to inter-partition sort key inconsistencies.

2022-11-15 09:31 UTC, crepererum commented on iox_query/src/exec/non_null_checker.rs
> +    fn required_input_distribution(&self) -> Vec<Distribution> {
Is the distribution "per input node" now instead of "for all inputs"?

2022-11-15 09:31 UTC, crepererum commented on parquet_file/src/storage.rs
> +            // This is not correct for production: they are ordered
```suggestion
            // Parquet files ARE actually sorted but we don't care here since we just construct a `collect` plan.
```

2022-11-15 09:31 UTC, crepererum commented on querier/src/ingester/flight_client.rs
>          // see https://github.com/influxdata/influxdb_iox/issues/5974
No, we still need this test because there might be a different expression construct hitting this limit. I can construct one for you (using some ugly nested case statements for example).

2022-11-15 09:31 UTC, crepererum commented on iox_query/src/provider/physical.rs
> +        match combined_sort_key {
`combined_sort_key.map(|k| if ... {...} else {...})` is the more Rusty way, but that's optional

2022-11-15 09:31 UTC, crepererum commented on iox_query/src/provider/physical.rs
> +        // no existing sort key means the data wasn't consistently sorted so leave it alone
This will happen in prod. The issue is that we have chunks for different partitions here (I think) and partitions have different sort orders. You may chose to NOT address this now, since this requires changes to the chunk grouping, but then we at least need to track this in a somewhat-urgent (= next week) follow-up ticket.

2022-11-15 20:57 UTC, alamb commented on iox_query/src/exec/non_null_checker.rs
> +    fn required_input_distribution(&self) -> Vec<Distribution> {
Yes, exactly, it is per-child, to handle cases like joins where the children may / may not be partitioned correctly to perform a parallel equijoin without redistributing the inputs

2022-11-15 20:57 UTC, alamb commented on iox_query/src/provider/physical.rs
> +        }
yes, that is correct -- I expect the sort key will commonly be the same so avoiding the cloning will be substantial. I will make this clear in comments.

2022-11-15 20:57 UTC, alamb commented on iox_query/src/provider/physical.rs
> +        // no existing sort key means the data wasn't consistently sorted so leave it alone
It does sound somewhat concerning, though I don't fully follow what the concern is -- if we are merging chunks from different partitions with different sort orders together that will result in wrong results.

2022-11-15 20:57 UTC, alamb commented on iox_query/src/provider/physical.rs
> +        match combined_sort_key {
I tried doing this and the borrow checker was not happy:

```
error[E0505]: cannot move out of `existing_sort_key` because it is borrowed
  --> iox_query/src/provider/physical.rs:65:31
   |
63 |         let combined_sort_key = SortKey::try_merge_key(&existing_sort_key, chunk_sort_key);
   |                                                        ------------------ borrow of `existing_sort_key` occurs here
64 |
65 |         combined_sort_key.map(|combined_sort_key| {
   |                           --- ^^^^^^^^^^^^^^^^^^^ move out of `existing_sort_key` occurs here
   |                           |
   |                           borrow later used by call
...
69 |                 existing_sort_key
   |                 ----------------- move occurs due to use in closure
```

2022-11-15 20:57 UTC, alamb commented on iox_query/src/provider/physical.rs
> +                            .add_parquet_file(chunk.as_ref(), parquet_input.object_meta);
I added some comments to `combine_sort_key` to try and make this clearer

2022-11-15 20:57 UTC, alamb commented on iox_query/src/provider/physical.rs
> +        );
Agreed. Added in e5c1365cd

2022-11-15 20:57 UTC, alamb commented on parquet_file/src/storage.rs
> +            output_ordering: None,
I think @crepererum 's rewording is much better -- does that make more sense?

```rust
 // Parquet files ARE actually sorted but we don't care here since we just construct a `collect` plan.
```

?

2022-11-15 20:57 UTC, alamb commented on querier/src/ingester/flight_client.rs
>          // see https://github.com/influxdata/influxdb_iox/issues/5974
Ah, I see -- I will see if I can construct such a thing

2022-11-15 21:56 UTC, alamb commented on querier/src/ingester/flight_client.rs
> +                let expr = (0..n).fold(lit(false), |expr, _|{
I have made another deeply nested expression as suggested by @crepererum  in addition to a second test that verifies deeply nested `AND`s now work

2022-11-15 21:57 UTC, alamb commented on querier/src/ingester/flight_client.rs
>          // see https://github.com/influxdata/influxdb_iox/issues/5974
done

2022-11-16 10:48 UTC, crepererum commented on iox_query/src/provider/physical.rs
> +        // no existing sort key means the data wasn't consistently sorted so leave it alone
Ah, because this is only relevant for de-dup, right? Well, then let's leave it. If it is a performance issue in some way (because we insert merges that shouldn't be there), we can address this later.

2022-11-16 10:49 UTC, crepererum approved these changes

2022-11-16 14:34 UTC, alamb commented on iox_query/src/provider/physical.rs
> +        // no existing sort key means the data wasn't consistently sorted so leave it alone
yeah -- I hope once we have completed the predicate pushdown work (we are very close) and "run on any data size" then we can move on to profiling and improving performance for large numbers of parquet files

2022-11-16 14:41 UTC, merged