feat: Prune chunks fully outside retention period in querier
influxdata/influxdb_iox pull request #6180
Opened 2022-11-18 22:51 UTC by NGA-TRAN

This is the PR implement the first half of #6028  that prunes chunks fully outside of the retention period.
My next PR will apply predicate to remaining chunks to filter specific rows that are outside the retention period

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-11-21 10:39 UTC, alamb approved these changes
I think this looks great -- thank you @NGA-TRAN 

It would be great if @crepererum looked at this as well prior to merge as he is the querier expert.

2022-11-21 11:52 UTC, crepererum requested changes

2022-11-21 11:52 UTC, crepererum commented on querier/src/cache/namespace.rs
> +    pub retention_period_ns: Option<i64>,
Can we type this?

```suggestion
    pub retention_period: Option<Duration>,
```

2022-11-21 11:52 UTC, crepererum commented on querier/src/table/mod.rs
> +        };
This should go to `chunks_inner`. The only reason `chunks` is split into `chunks` and `chunks_inner` is the span scope and error propagation. All actual logic lives in `chunks_inner`.

2022-11-21 11:52 UTC, crepererum commented on querier/src/namespace/query_access.rs
> +        let outside_retention = inside_retention - 2 * 60 * 60 * 1_000_000_000; // 2 hours ago
If the retention would be properly typed (also see my comment in the cache section), we wouldn't need this arcane math here.

2022-11-21 11:52 UTC, crepererum commented on querier/src/namespace/query_access.rs
> +    #[tokio::test]
I would have expected a `query_test` (including `EXPLAIN`) for this. I'm also bringing this up because now you're adding filter predicates to EVERY chunk (in contrast to what your PR description says it does), even the ones that are fully within the retention window. This will come with some major overhead.

The fact that this also filters our entire chunks early is a mere side effect (this will work with every time-based predicate).

2022-11-21 17:18 UTC, alamb commented on querier/src/table/mod.rs
> +        };
```suggestion
        let predicate = match self.namespace_retention_period {
            // Add expression to only keep chunks inside the retention period: time >= now - retention_period
            Some(retention_period) => {
                let retention_time_ns = self
                    .chunk_adapter
                    .catalog_cache()
                    .time_provider()
                    .now()
                    .timestamp_nanos()
                    - retention_period.as_nanos() as i64;
                predicate.clone().with_retention(retention_time_ns)
            }
            None => predicate,
        };
```

2022-11-21 17:22 UTC, NGA-TRAN commented on querier/src/namespace/query_access.rs
> +    #[tokio::test]
@crepererum  I have added the 2 explains for this test. Are they what you expected here or somewhere else?

Questions: 
1. Does the `chunks_inner`do early chunk pruning and decide which chunks to read? I think that is what I meant for this PR. Sorry for the confusion. 
2. I also see the `chunks_inner` asks Ingester for data which will also now filter data outside of the retention period because we add the retention predicate, right?
3. Do you think this is the right approach?

2022-11-21 17:22 UTC, NGA-TRAN commented on predicate/src/lib.rs
> +        let time = ScalarValue::TimestampNanosecond(Some(retention_time), None);
Thanks.

2022-11-21 17:22 UTC, NGA-TRAN commented on querier/src/namespace/query_access.rs
> +            cpu,host=zz load=01 {}\n
Done

2022-11-21 17:22 UTC, NGA-TRAN commented on querier/src/cache/namespace.rs
> +    pub retention_period_ns: Option<i64>,
Done

2022-11-21 17:23 UTC, NGA-TRAN commented on querier/src/table/mod.rs
> +        };
Done

2022-11-22 09:41 UTC, crepererum commented on querier/src/namespace/query_access.rs
> +    #[tokio::test]
> I have added the 2 explains for this test. Are they what you expected here or somewhere else?

I was more aiming for tests in the `query_test` crate since there we already have loads of infrastructure instead of spraying the tests over the whole repo.


> 1. Does the `chunks_inner`do early chunk pruning and decide which chunks to read? I think that is what I meant for this PR. Sorry for the confusion.

It does. :+1: 


> 2. I also see the `chunks_inner` asks Ingester for data which will also now filter data outside of the retention period because we add the retention predicate, right?

Yes. I think this is correct for consistency reasons. I would be more worried if we would use different mechanisms for parquet and ingester data.


> 3. Do you think this is the right approach?

TBH I'm slightly worried about the execution-time overhead, but I think it's in the same as `select ... from ... where time > X`, so this is OK. Let's walk this route for now and let's rather invest into some predicate-pruning later where we can remove time-based predicates from chunks where the outcome is clear (e.g. chunks which are completely within the requested period and hence don't need any row-based filtering).

2022-11-22 09:43 UTC, crepererum commented
I really would like to see the query tests within the `query_test` crate instead of in `querier`. I leave it up to @NGA-TRAN if she wants to do this in this PR here or in a follow-up PR.

2022-11-22 09:43 UTC, crepererum approved these changes

2022-11-22 14:54 UTC, NGA-TRAN commented on querier/src/namespace/query_access.rs
> +    #[tokio::test]
Thanks @crepererum. I will move the tests in the follow-up PR

2022-11-28 17:10 UTC, alamb commented
I believe the code in this PR has been merged under the aegis of other PRs

2022-11-28 17:34 UTC, NGA-TRAN commented
Close this as it was merged in #6198

2022-11-28 17:34 UTC, closed without merging