feat: push retention predicate down to ParquetExec
influxdata/influxdb_iox pull request #6213
Opened 2022-11-22 22:12 UTC by NGA-TRAN

Closes #

Describe your proposed changes here.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2022-11-23 17:34 UTC, NGA-TRAN commented
@alamb and @crepererum 
This PR has a different approach for filtering data outside retention period. In #6209, we did 2 steps: (i) early pruning chunks by adding `time >= retention_time` to early pruning predicate and then (ii) add `time < retention_time` into delete predicate to filter data after scanning the remaining chunks

We have found after the above PR that we can do better than just simply adding `time >= retention_time` into where predicate and then everything will be taken care for us. So this PR does:
1. Remove code did in previous PR #6209
2. Adding `time >= retention_time` to normal predicate. I found this must be done in 2 places, one for normal SQL and one for grpc.

I found this is more efficient but I will wait for both you you to review before making any move

2022-11-23 17:36 UTC, NGA-TRAN commented on querier/src/table/mod.rs
> -    }
This test is no longer needed because we do not add retention predicate into delete predicate anymore

2022-11-23 17:36 UTC, NGA-TRAN commented on querier/src/namespace/query_access.rs
> +                "+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Since we now have tests in query_tests, I am happy to remove this test here if you think it is better that way

2022-11-23 21:35 UTC, alamb requested changes
Actually, something doesn't look right upon more careful examination of the plans

2022-11-23 21:35 UTC, alamb commented on querier/src/namespace/query_access.rs
> +                "+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------
yes I think removing the explain plans here would make maintaining the code easier

2022-11-24 09:08 UTC, crepererum reviewed
So the overall change is to encode the predicate as part of the predicate instead of the delete predicate, right?

The reason that this leads to a different query plan is clearly a weakness in our plan construction. They are semantically identical. I think we should fix the phys. plan construction, also see https://github.com/influxdata/influxdb_iox/issues/6098#issuecomment-1326153144 .

2022-11-24 09:08 UTC, crepererum commented on querier/src/namespace/query_access.rs
> +        let predicate = if let Some(retention_period) = table.namespace_retention_period() {
Why duplicate this logic here and in the other `query_access` part (there are two because one is used for InfluxRPC, one for SQL) instead of making this part of `QuerierTable::chunks`?

2022-11-24 09:09 UTC, crepererum commented on query_tests/cases/in/retention.expected
> +|               |               ParquetExec: limit=None, partitions=[1/1/1/1/00000000-0000-0000-0000-000000000001.parquet], predicate=time_max@0 >= -3600000000000, output_ordering=[host@0 ASC, time@2
That's a bug in the phys. plan construction than. When building it, I was under the impression that the `ParquetExec` filter is exact.

2022-11-24 09:23 UTC, crepererum commented on query_tests/cases/in/retention.expected
> +|               |               ParquetExec: limit=None, partitions=[1/1/1/1/00000000-0000-0000-0000-000000000001.parquet], predicate=time_max@0 >= -3600000000000, output_ordering=[host@0 ASC, time@2
Oh, I think I know what's going on:

The outer `FilterExec` is created by DF itself because that's the predicate we actually want to apply (from an SQL user PoV). Now we mess with the predicate during phys. plan expansion and hence it's somewhat out-of-sync.

2022-11-24 09:24 UTC, crepererum commented
OK, so thinking about this and the bug it introduces, I would say let's rather improve the phys. plan construction and group chunks by delete predicate to avoid the excessive subtrees.

2022-11-24 09:30 UTC, crepererum commented
Also: why does `iox_query` not push down delete predicates to the chunks? I think we really should fix `iox_query` instead of adding more hacks to `querier`.

2022-11-28 16:06 UTC, NGA-TRAN commented
I have opened https://github.com/influxdata/influxdb_iox/issues/6241 to implement delete predicate pushdown and close this

2022-11-28 16:06 UTC, closed without merging