feat: Make a mode for the querier to use ingester2 instead, behind the rpc_write feature flag
influxdata/influxdb_iox pull request #6337
Opened 2022-12-05 22:34 UTC by carols10cents

Closes #6336

This enables a querier to connect to an ingester2 **but does not do any of the catalog cache reloading yet!!!!**

I am, however, able to run a router in RPC write mode with:

```
cargo run --features=rpc_write -- run router-rpc-write --api-bind=127.0.0.1:8081 --ingester-addresses=127.0.0.1:8042
```

And an ingester2 instance with:

```
cargo run --features=rpc_write -- run ingester2 --grpc-bind=127.0.0.1:8042
```

And a querier with: (**NOTE THAT THE INGESTER ADDRESS NEEDS THE `http://` OR IT WON'T WORK RIGHT NOW** does this need to be changed in this PR?)

```
cargo run --features rpc_write -- run querier-rpc-write --ingester-addresses=http://127.0.0.1:8042 --grpc-bind 127.0.0.1:8043  --api-bind 127.0.0.1:8044
```

And I'm pretty sure the querier contacts the ingester2 and gets results, I'm not sure that I have the right persistence settings to ensure I'm not actually seeing data the querier is getting from the object store, but I do see the ingester get a request!

Also note that the `querier-rpc-write` mode and `--ingester-addresses` are not accessible or visible without the `--features rpc_write` flag enabled.

2022-12-06 16:56 UTC, crepererum commented
> but does not do any of the catalog cache reloading yet!!!!

Is this work tracked somewhere?

2022-12-06 17:06 UTC, crepererum requested changes
This is too much copy-paste. In vein of the long duration of this switch-over, this ain't gonna fly (code de-sync, half-fixed bugs, maintenance burden, code complexity). Please abstract the relevant bit. I offer you to help with this if you just point me out to the low-level RPC interface that I shall call (is this still flight-based?).

2022-12-06 17:06 UTC, crepererum commented on querier/src/ingester/mod.rs
> +    // This backoff config is used to retry requests for a specific table-scoped query.
Copied configs. Every change to the existing code (or to this one) will automatically de-sync this. Please move these configs into a const/lazy/method/whatever.

2022-12-06 17:06 UTC, crepererum commented on querier/src/ingester/mod.rs
> +        // Shard indexes aren't relevant for the RPC write path. This should always be `None`, but
> This should always be `None`

Then please `assert!` this.

2022-12-06 17:06 UTC, crepererum commented on querier/src/ingester/mod.rs
> +            let request = GetPartitionForIngester {
So what's different in this copy-pasta? The construction of the `request`?

2022-12-07 14:34 UTC, carols10cents commented
> Is this work tracked somewhere?

Indeed it is!! See the linked issues in this tracking issue: https://github.com/influxdata/influxdb_iox/issues/6317

2022-12-07 15:00 UTC, pauldix commented
@crepererum one thing to keep in mind is that we're trying to get to the basic working prototype as quickly as possible. Hopefully the duration of the switchover is going to be 4 weeks or less. So that's the scope of how long a little mess is going to exist where we clean things up after.

2022-12-07 18:47 UTC, carols10cents commented on clap_blocks/src/querier.rs
> +    }
I was going to have the switch be only based on which variant of the `IngesterAddresses` enum that `ioxd_querier` gets, but the querier also needs to know whether to create a sharder using the shards in the catalog or not, so this boolean is for that purpose.

2022-12-07 18:56 UTC, carols10cents commented on querier/src/database.rs
> +        };
This is where the sharder either needs to be created or not, but the ingester connections have already been configured, so this needed the boolean.

2022-12-07 18:59 UTC, carols10cents commented on querier/src/ingester/mod.rs
> +        )),
This is a consequence of sharing the most code and having some irrelevant parts carried along in the types-- to me, this is "messier", because it'll be more involved to remove the old code, but the overall amount of copy-pasted code to stand up a querier is indeed less. Tradeoffs everywhere! 🤷🏻‍♀️

2022-12-07 19:00 UTC, carols10cents commented on querier/src/ingester/mod.rs
> +            }
The inside of this arm is moved without changes from below.

2022-12-07 19:03 UTC, carols10cents commented
@crepererum @pauldix This is ready for re-review! Please note in the description that the command for the querier has changed-- there is no `querier-rpc-write` command anymore, just `querier`.

2022-12-08 11:25 UTC, crepererum approved these changes
Looks good, thanks a lot for the clean up :+1:

2022-12-08 14:07 UTC, merged