feat: Extract `encode_stream_for_flight` from flight implementation
influxdata/influxdb_iox pull request #6460
Opened 2022-12-22 12:58 UTC by alamb

refactor: Extract conversion of RecordBatches to FlightData into iox_arrow-flight

re #6390 

# Rationale:
The details of converting `RecordBatch`es into streams of `FlightData` is common across all flight implementations (including flight SQL) and thus belongs upstream in arrow-rs.

In addition,  I also need something like this upstream in arrow-rs to write reasonable tests for do_get

Also, I think getting it into arrow-rs will allow more expert analysis of this code / improvement over time by the community (such as currently having to hydrate dictionaries, etc)

This PR extracts the general purpose translation into a `encode_stream_for_flight`

2022-12-23 12:19 UTC, alamb commented on arrow_util/src/optimize.rs
> -/// Hydrates a dictionary to its underlying type
moved into `iox_arrow_flight` in preparation for upstreaming

2022-12-23 12:19 UTC, alamb commented on ingester/src/querier_handler.rs
> +                                        let batch =
this change is to map the error types.

The whole structure of the `ingester` / `ingester2` handlers could be improved significantly. I plan to do so after I get the basic flight code upstreamed into arrow

2022-12-23 12:19 UTC, alamb commented on ingester2/src/server/grpc/query.rs
> +                                let batch =
As in `ingester` these changes are to massage the error types (as `ingester2` has a mostly copy/paste version of the handler from `ingester`).  I plan to clean the this whole implementation up after `ingester` is gone and  I have upstreamed this code to arrow-rs.

cc @domodwyer  and @carols10cents

2022-12-23 12:19 UTC, alamb commented on iox_arrow_flight/src/encode.rs
> +        let data_stream = input
I will admit getting to this async stream code took a lot of finagling, but i am quite pleased with how it worked out

2022-12-23 12:19 UTC, alamb commented on iox_arrow_flight/src/encode.rs
> +/// * <https://github.com/influxdata/influxdb_iox/issues/4275>
```suggestion
```

2022-12-23 12:19 UTC, alamb commented on service_grpc_flight/src/lib.rs
> +        let query_results = ctx
Here is an example use of the new decoder in the flight API implementation. cc @crepererum 

I am quite pleased with how this looks now - and it is a preview of what I hope this code will look like eventually in the ingester.

2022-12-23 12:19 UTC, alamb commented
I don't plan to merge this until the holiday break is over, but I wanted to get it up in case anyone has time to review

2023-01-02 16:20 UTC, carols10cents requested changes
I'm confused about whether `max_batch_size` et al are in bytes or number of rows, and I'd like to see that resolved before merging (I suspect you'd like that too :))

Some doc nits and possible small performance suggestions that you can feel free to take or leave!

2023-01-02 16:20 UTC, carols10cents commented on iox_arrow_flight/src/encode.rs
> +    let output = output.into_iter().map(Ok);
Feel free to punt this until profiling to know if this makes a difference, but I think some allocations can be saved with:

```suggestion
    let output: Vec<_> = split_batch_for_grpc_response(batch, max_batch_size)
        .into_iter()
        .map(|batch| {
            let (flight_dictionaries, flight_batch) = flight_data_from_arrow_batch(&batch, options);
            flight_dictionaries
                .into_iter()
                .chain(std::iter::once(flight_batch))
        })
        .flatten()
        .map(Ok)
        .collect();
```

2023-01-02 16:20 UTC, carols10cents commented on service_grpc_flight/src/lib.rs
> +        let query_results = ctx
The new code is definitely much nicer than the code that was here 🎉

2023-01-03 11:10 UTC, crepererum reviewed
Just had a quick look since @carols10cents already did an awesome job her. I really like the upstream movement and the clean up of the API. It kinda grew over the last months a bit too much and really needed some grooming.

2023-01-03 16:50 UTC, alamb commented on iox_arrow_flight/src/encode.rs
> +pub struct StreamEncoderBuilder {
FWIW I thought a bit more about this and I think with some judicious use of `flatten` this could actually be used for ingester / ingester2. But we'll get there eventually

2023-01-03 18:06 UTC, alamb commented on iox_arrow_flight/src/encode.rs
> +pub const GRPC_TARGET_MAX_BATCH_SIZE: usize = 2097152;
Indeed -- actually I just moved the code around (it used to be in arrow_util/src/optimize.rs) but I should have caught it during initial review as well 😆  Will fix here

2023-01-04 12:29 UTC, crepererum approved these changes

2023-01-04 13:36 UTC, merged

2023-01-18 21:35 UTC, alamb commented on ingester2/src/server/grpc/query.rs
> +                                let batch =
https://github.com/influxdata/influxdb_iox/pull/6623 is the promised cleanup