feat: preliminary thought on how to filter files for hot and cold
influxdata/influxdb_iox pull request #6717
Opened 2023-01-26 15:14 UTC by NGA-TRAN

Implements https://github.com/influxdata/idpe/issues/16983#issuecomment-1403779671

2023-01-26 15:15 UTC, NGA-TRAN commented
@crepererum : what do you think about this approach?

2023-01-26 15:19 UTC, NGA-TRAN commented on compactor2/src/driver.rs
> +            //   . Filter out all L1 files that do overlap with any L0 files
I mean `do not overlap`

2023-01-26 15:36 UTC, crepererum commented on compactor2/src/driver.rs
> +            // TODO: build a level file filter for this
you shouldn't touch the driver[^1], this should all happen in components. I think this can all be done in `DataFusionPlanner`.

[^1]: except for really rare, fundamental algorithm changes.

2023-01-26 15:36 UTC, crepererum commented on compactor2/src/driver.rs
> +            // Question for Marco: I do not see where we canncel compaction without L0 files. We need to remove that filter, too
https://github.com/influxdata/influxdb_iox/blob/68380a32e5fb25f00cf8956ef533b73799a4cf2c/compactor2/src/components/hardcoded.rs#L74-L76

2023-01-26 15:38 UTC, NGA-TRAN commented on compactor2/src/driver.rs
> +            // TODO: build a level file filter for this
Yes, that is way I mean `build a new filter` in the components

2023-01-26 23:03 UTC, NGA-TRAN commented
This is now ready for review. Quite a conflict with Marco's recent merge because we both added (and I also remove)  filters and removing available ones. It took me a while to get to the filter that caused my new tests fail. Hopefully, less tricky or no conflict before this get merged 😄

2023-01-27 09:58 UTC, crepererum requested changes
I think the mode detection needs a better design.

2023-01-27 09:58 UTC, crepererum commented on compactor2/src/component_tests.rs
> +#[cfg(test)]
What's that test set? Is it testing the interaction of multiple components? If so, it should probably go in `compactor2::components::tests`.

2023-01-27 09:58 UTC, crepererum commented on data_types/src/lib.rs
> +        }
```suggestion
        write!(f, "{}", self as i16)
```

This works because of:

```rust
#[repr(i16)]
pub enum CompactionLevel {
...
```

2023-01-27 09:58 UTC, crepererum commented on compactor2/src/driver.rs
> +    }
The logging is already covered by `compactor2::components::df_planner::logging`. No need to add yet another loggging here. For `Initial`: This should be another `DataFusionPlanner` wrapper and it should probably panic because this would not be an error we eventually wanna deal with but a massive code bug.

2023-01-27 09:58 UTC, crepererum commented on compactor2/src/driver.rs
> +                if components
This shouldn't branch. Every IF-statement is bad code smell (even though sometimes it cannot be avoided). Say now if we wanna add yet another compaction level or a different hot-cold-warm logic, we again need to fiddle with the core driver. Instead this should be:

```rust
enum Mode {
    Warm,
    Cold,
}

let mode = components.mode_detection(&branch);
type_compaction(
    files,
    partition_info,
    &components,
    mode,
    Arc::clone(&job_semaphore),
    scratchpad_ctx,
)
```

However I'm wondering if the hot-cold detection is per-branch or actually for the whole partition? Because you have yet-another filter stage for every mode and I'm wondering what happens to the filtered-out files in the next fixed-point-loop iteration? I think what you wanna do is to detect the mode in every FP-loop iteration (but before calling `split` and `divide`), then pass the mode to the `split`, `divide`, `plan`, etc.

2023-01-27 15:17 UTC, NGA-TRAN commented on compactor2/src/driver.rs
> +                if components
Thanks for the Mode suggestion, I will  work on it.

Regarding hot-cold detection, I want to stick with `branch` (at least for now but I think we will stay like that for the long run). This way, we will be able to compact the first/older half partition with cold while we will do hot for the second half (the half can become 1/n of the partition). With a lot of files per partition ingetser2 introduces, we want to approach this way. I will add comment to explain this there.
I will also add comments for the invariance that (1) file sets in different branch use not overlap, and (2) L1s files must be contiguous in each and all branches in the case of cold compaction.

Regarding filter, I have delima thought:
- Pros: Very powerful IMO.
     - When we understand the abstract well, it will be very easy to implement and just invoke `apply` and everything is done for us. 
     - Adding more filters is also super easy
- Cons: 
   - There are many levels of filters and make it a bit hard to understand at first
   - When there are bugs, it will be hard to debug and figure out when the filters are applied.
So the pros seems outweigh the cons. We just need to add comments which we have no time for it now

2023-01-27 15:47 UTC, NGA-TRAN commented on data_types/src/lib.rs
> +        }
Interestingly, I got the error:
```
error[E0606]: casting `&CompactionLevel` as `i16` is invalid
  --> data_types/src/lib.rs:68:25
   |
68 |         write!(f, "{}", self as i16)
   |                         ^^^^^^^^^^^
   |
   = help: cast through a raw pointer first
```

2023-01-27 15:53 UTC, NGA-TRAN commented on compactor2/src/driver.rs
> +    }
Actually, I have added the panic in the DF planner

2023-01-27 18:35 UTC, NGA-TRAN commented on compactor2/src/driver.rs
> -            );
Since all branches do not overlapped, let us not (yet) to recursively compact result of a comapction

2023-01-27 18:37 UTC, NGA-TRAN commented
OK, I have addressed all comments.
If the upgrade is simple, I include them in here

2023-01-27 22:34 UTC, NGA-TRAN commented
I have also added the upgrade files into this PR

2023-01-30 11:33 UTC, crepererum commented on data_types/src/lib.rs
> +        }
Sorry, I've missed a de-ref `*`:

`write!(f, "{}", *self as i16)`

2023-01-30 11:46 UTC, crepererum commented on compactor2/src/driver.rs
> -            );
Wouldn't the next loop just do nothing then? If that's not the case, then this is probably buggy to begin with. Also see https://influxdata.slack.com/archives/CRK9M8L5Q/p1675078126027019?thread_ts=1675076577.714539&cid=CRK9M8L5Q

2023-01-30 11:46 UTC, crepererum commented on compactor2/src/components/mod.rs
> +    pub cold_files_filter: Arc<dyn FilesFilter>,
These two are unused I think?

2023-01-30 13:43 UTC, NGA-TRAN commented on compactor2/src/components/mod.rs
> +    pub cold_files_filter: Arc<dyn FilesFilter>,
They are used. They are one of the 2 keys of this PR

2023-01-30 13:46 UTC, NGA-TRAN commented on compactor2/src/components/mod.rs
> +    pub cold_files_filter: Arc<dyn FilesFilter>,
Wait, let me check.

2023-01-30 14:10 UTC, NGA-TRAN commented on compactor2/src/components/mod.rs
> +    pub cold_files_filter: Arc<dyn FilesFilter>,
Good catch. I missed invoking them inside the hot/cold compaction

2023-01-30 14:10 UTC, NGA-TRAN commented on compactor2/src/driver.rs
> -            );
Let us have a chat. I do not think this is related to the one in the slack and I want it work this way, too

2023-01-30 14:56 UTC, NGA-TRAN commented
A quick update about this PR.

@crepererum and I have chatted. There are 3 main things to add in this:
1. Since I am at the right place, I will fix the indefinitely inner-loop we found [here ](https://influxdata.slack.com/archives/CRK9M8L5Q/p1675076577714539) by having  3 compaction types: hot, cold, nothing. The nothing will produce 0 created file and will lead to end of the loop.
2. I need to address the missing calls of `hot_files_filter` and `cold_files_filter`
3. I also found a bug in overlap/non-overlapped elimination  this PR introduce and need to address before merging

2023-01-30 22:12 UTC, NGA-TRAN commented
Due to incident today, I had to commit this in the middle of the code. All the failures are expected. Will continue tomorrow

2023-01-31 22:55 UTC, NGA-TRAN commented
I have made quite good progress for this but need 3 more bigs steps before it is ready for review
- [ ] Get the right non-overlaps and upgrades
- [ ] integration Tests
- [ ] Draw examples

2023-02-01 21:09 UTC, NGA-TRAN commented
I have started moving piece by piece from this PR to main. This stay open until I got all of them

2023-02-06 13:43 UTC, NGA-TRAN commented
Close this as all of its work has been merge din many PRs

2023-02-06 13:43 UTC, closed without merging