docs: high-level documentation for `comapctor2`
influxdata/influxdb_iox pull request #6818
Opened 2023-02-02 14:19 UTC by crepererum

I recommend to render the docs locally with `cargo doc --no-deps --workspace --document-private-items` and read that output. It's way easier to parse than the markdown version.

2023-02-02 14:25 UTC, domodwyer approved these changes
Fantastic stuff - really shows the thought that has gone into it.

2023-02-02 14:25 UTC, domodwyer commented on compactor2/src/lib.rs
> +#![doc = include_str!("../img/driver.svg")]
I had no idea you could just wang in some SVG :+1:

2023-02-02 14:25 UTC, domodwyer commented on compactor2/src/lib.rs
> +//! - **single method:** Most interfaces will only have a single method. This is because they have one dedicated job.
Often undervalued property :+1:

2023-02-02 16:11 UTC, alamb approved these changes
Thank you for this -- I agree with Dom that it is really helpful

2023-02-02 16:11 UTC, alamb commented on compactor2/src/lib.rs
> +//! The driver is the heart of the compoactor and describes and executes the framework.
```suggestion
//! The driver is the heart of the compactor and describes and executes the framework.
```

2023-02-02 16:11 UTC, alamb commented on compactor2/src/lib.rs
> +//! The [config] allows the compoactor to set up a wide range of component setups. The config options fall roughly into
```suggestion
//! The [config] allows the compactor to set up a wide range of component setups. The config options fall roughly into
```

2023-02-02 19:01 UTC, NGA-TRAN approved these changes
I like you document `objectives` and the must-documented interface of the `components` as well as how to implement them to keep the system consistent. The `Config` options are also nice.  

I have one strong option and a few comments for next documents:

**. Opinion:** I think you want to remove the `duplicate_within_file`. This will lead to not only things I put in the detailed comment but also how we deduplicate them without further information for something similar to chunk order.  Let us remove it to avoid confusing or providing hopes to readers.

**Follow-on PRs:** description of boxes/components in the `driver.svg` (or add comments like this where they are implemented). Each of them is very powerful and either provides great performance  or handles error/concurrency. It was hard to review each of them without clear comments which we do not have, we want to add them now.

**Note for myself: ** Even though I have added a lot of comments in building split files and how to compact them to achieve the 7 goals you mentioned here, I should draw picture as you did with `driver.svg` to describe and document them, too.

2023-02-02 21:11 UTC, NGA-TRAN requested changes
Let  have `duplicates_within_files` remove

2023-02-03 09:50 UTC, crepererum commented on compactor2/src/lib.rs
> +//! [^duplicates_within_files]: Technically the ingester already does that but the compactor could easily take over that job.
I'll adjust the comment to say that there are currently no plans, but the high-level design of the compactor is totally unaffected by this and the components could easily be adjusted to cope with it.

2023-02-03 10:03 UTC, crepererum commented on compactor2/src/lib.rs
> +//! - **O4 -- max file size:** Parquet files should have a maximum size. Too large files will likely OOM the querier.
I'll take the "OOM" wording.

As said in slack, this is technically NOT possible, since due to zstd compression, RLE and pages in the parquet files, the size sometimes might be exceeded. I'll try to find a better wording.

I don't think I support the "and likely be less efficient to fetch" bit. What does "efficient" even mean here? Because "per row IO ops" likely go down the larger the file is.

2023-02-03 10:05 UTC, crepererum commented on compactor2/src/lib.rs
> +//! - **O7 -- costs:** The comapctor shall be cost-efficient.
This is a not what this point is about. Cost is a reason for itself. You draw a follow-up conclusion (which may not even be true for all algorithms). There are many other cost-related factors. So just avoiding file rewrites but in turn perform massive IO or require super large K8s pods may not be a good way to achieve this. Hence, I deliberately do NOT include this here.

2023-02-03 10:17 UTC, crepererum commented on compactor2/src/lib.rs
> +//! - **O4 -- max file size:** Parquet files should have a maximum size. Too large files will likely OOM the querier.
done

2023-02-03 14:19 UTC, NGA-TRAN approved these changes
Nice. I think there is one paragraph you just added and you meant `>` but you used `<`. See detailed comment

2023-02-03 14:19 UTC, NGA-TRAN commented on compactor2/src/lib.rs
> +//! - **O1 -- duplicates:** Duplicate across files should be removed[^duplicates_within_files]. Removing duplicates
👍

2023-02-03 14:19 UTC, NGA-TRAN commented on compactor2/src/lib.rs
> +//!     estimated by assuming that "sum size of input files <= sum size of output files". However there are certain
Do you mean "sum size of input files >= sum size of output files"

Input size usually greater than compacted output, right?

2023-02-06 08:29 UTC, crepererum commented on compactor2/src/lib.rs
> +//!     estimated by assuming that "sum size of input files <= sum size of output files". However there are certain
fixed

2023-02-06 08:37 UTC, merged