feat: gRPC measurement_names support for read buffer 7cf906b
influxdata/influxdb_iox pull request #697
Opened 2021-01-25 17:05 UTC by alamb

This PR adds proper support for `meausrement_names` for gRPC queries to data in the read buffer.  It is the first time gRPC requests will include data in the read buffer 🎉 

It is built on https://github.com/influxdata/influxdb_iox/pull/696 for testing. 

The only slightly sketchy bit is skipping the predicate scenarios with the read buffer (as predicate's are not yet supported there). I'll add some notes inline

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-01-25 20:46 UTC, carols10cents requested changes
The tests are definitely better than before! Just a few small suggestions :)

2021-01-25 20:46 UTC, carols10cents commented on server/src/db.rs
> +        // Create several scenarios, scenaro has the same data, but
```suggestion
        // Create several scenarios, scenario has the same data, but
```

2021-01-25 20:46 UTC, carols10cents commented on server/src/db.rs
> +        PredicateBuilder::default().timestamp_range(0, 201).build()
I feel like this could be just as (or more) concise but more easily extensible if you replace all the `ts_pred_0_201`, etc functions with one function like:

```
    fn tsp(r1: i64, r2: i64) -> Predicate {
        PredicateBuilder::default().timestamp_range(r1, r2).build()
    }
```

and then the call sites would be `tsp(0, 201)` rather than `ts_pred_0_201()`. Not sure if I'm missing something though.

2021-01-25 20:46 UTC, carols10cents reviewed
Ugh I meant to hit comment not request changes.

2021-01-25 20:48 UTC, carols10cents commented
Oh bleh and I didn't see that this builds on #696 that wasn't in yet...

2021-01-25 20:51 UTC, carols10cents approved these changes
Sorry for all the noise. I moved my comments over to the other PR where they belong; this one is fine!

2021-01-25 21:36 UTC, alamb commented
Thanks @carols10cents

2021-01-25 21:51 UTC, alamb commented on server/src/db.rs
> +    /// HACK: until predicate support is implemented for read buffer,
And actually, @e-dard  added just that support in https://github.com/influxdata/influxdb_iox/pull/698#pullrequestreview-575836058 -- so once that is merged I can remove this sketchiness.

2021-01-26 17:42 UTC, e-dard approved these changes
Wonderful!

2021-01-26 18:15 UTC, merged