chore(iox/compactor): add test cases tracking max_l0_created_at
influxdata/influxdb_iox pull request #7181
Opened 2023-03-10 19:53 UTC by Joe-Blount

This PR adds test cases that I believe show a mishandling of max_l0_created_at when overlaps exist between all 3 levels of files.

The new test file takes the approach of describing a base case with a potential vulnerability for mishandling, then adding complicating permutations to that base case trying to trick the compactor into mishandling the potential vulnerability.

More base cases and permutations can likely be added, but I think this is enough to get started.  I'd like to determine if there is agreement on the issue see before spending more time expanding the test.

The naming convention is intended to keep things organized if we have several more base cases with permutations on each.

Helps: https://github.com/influxdata/idpe/issues/17258

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-03-10 20:25 UTC, NGA-TRAN reviewed
Since the assumption in all of the tests in this PR `that the L2's max_l0_created_at time is between that of the two L1s` cannot happen in our design (see the detail), I wonder  whether you want to modify the assumption first?

Similarly, I have added comments in the ticket https://github.com/influxdata/idpe/issues/17258 that two out of three assumptions  cannot go with each other.  To handle that, we must always compact L0s with all overlapped L1s before compacting L1s  with overlapped L2s.

2023-03-10 20:25 UTC, NGA-TRAN commented on compactor2/tests/layouts/created_at.rs
> +    // Note that the L2's max_l0_created_at time is between that of the two L1s.
The assumption `that the L2's max_l0_created_at time is between that of the two L1s.` is not correct and never happens in our design. If an L2 file overlap in time range with an L1 file, the L2's max_l0_created_at is always older than the one of L1. 

In your case, file L2.1 overlaps with both L1.2 and L1.3. The max_l0_created_at of L2.1 but be older/before the ones of both L1.2 and L1.3

2023-03-10 20:27 UTC, NGA-TRAN requested changes
Have the assumptions to modify first

2023-03-11 11:37 UTC, alamb commented on compactor2/tests/layouts/created_at.rs
> +    // Note that the L2's max_l0_created_at time is between that of the two L1s.
The idea to add another invariant check to ensure this knowledge is 💯  https://github.com/influxdata/idpe/issues/17258#issuecomment-1464380736

2023-03-22 18:05 UTC, NGA-TRAN commented on compactor2_test_utils/src/lib.rs
> +}
The 2 panic functions look good

2023-03-22 18:08 UTC, NGA-TRAN commented on compactor2/tests/layouts/created_at.rs
> +    // and L1.3 must have a newer max_l0_created_at than L2.1.
WIth the way to split and then compact a subset of files, `newer` means `>=` which you do correctly with the panic. I think you want to define newer in this comment, too

2023-03-22 18:09 UTC, NGA-TRAN commented on compactor2/tests/layouts/created_at.rs
> +    // Mishandling the max_lo_created_at in L1.2 is the key vulnerability targeted by this case case.
```suggestion
    // Mishandling the max_l0_created_at in L1.2 is the key vulnerability targeted by this case case.
```

2023-03-22 18:12 UTC, NGA-TRAN commented on compactor2/tests/layouts/created_at.rs
> +                .with_max_l0_created_at(Time::from_timestamp_nanos(5)), // Older than L2 - That violates an invariant
👍

2023-03-22 22:14 UTC, merged