feat: `SHOW FIELD KEYS` InfluxQL plan+exec
influxdata/influxdb_iox pull request #7405
Opened 2023-03-31 10:36 UTC by crepererum

Closes https://github.com/influxdata/idpe/issues/17362

I have some questions (see code comments) and there are some TODOs.

2023-03-31 10:36 UTC, crepererum commented on iox_query_influxql/src/plan/planner.rs
> +            return Err(DataFusionError::External(
flipped from internal to external because "internal" usually means "DF-internal" and the display text suggests to open a DF bug. Also extended the error message a bit.

2023-04-03 20:44 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +            return Err(DataFusionError::External(
Ok, that makes sense – we can do a pass over all of the ones in the planner to switch `Internal` → `External`

2023-04-03 20:58 UTC, stuartcarnie reviewed
Looks great so far, Marco!

Please let me know if you have more questions.

2023-04-03 20:58 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        }
@pauldix asserted that we do not handle cross-namespace queries in IOx. Not sure if that will change in the future. 

I don't think the current DataFusion is architecture is amenable to querying across namespaces?

2023-04-03 20:58 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        //              NULLs. However there are now NULLs in the actual output.
Not sure I follow this – from what I can tell, you are referring to the columns being NON-NULL, but DF doesn't allow you to create them that way?

2023-04-03 20:58 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        //              `FROM /does_not_exist/` or something for that test, so we don't need to mock an empty database.
That is correct – choosing a non-existent measurement would be easiest

2023-04-03 20:58 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        )?;
👍🏻

2023-04-03 20:58 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        });
`Values` is a handy tool for these types of plans / queries 💯

2023-04-03 20:58 UTC, stuartcarnie commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
Awesome!

2023-04-03 23:49 UTC, pauldix commented on iox_query_influxql/src/plan/planner.rs
> +        }
That's right, we don't handle cross namespace queries. I believe the `ON` part of show field keys is to specify the measurement (i.e. table), not the database.

2023-04-04 08:27 UTC, crepererum commented on iox_query_influxql/src/plan/planner.rs
> +                todo!()
@stuartcarnie I'm esp. interested in these questions

2023-04-04 20:50 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +                todo!()
```
// - are measurement names de-duplicated? e.g. what's the result of `FROM foo,bar,foo`?
```

Yes, they are deduplicated

```
// - are measurement sorted? e.g. what's the result of `FROM a,c,d` and `FROM /^x/`?
```

Yes, the results are sorted by measurement name

```
// - what happens if a table is not found? Is it just ignored? e.g. `FROM does_not_exist,does_exist` or
```

Correct, the unknown measurements are ignored

```
//   `FROM does_not_exist`
```

Returns an empty result

2023-04-05 23:29 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +            return Err(DataFusionError::External(
@crepererum see for some thoughts

- https://github.com/influxdata/influxdb_iox/issues/7462

2023-04-05 23:55 UTC, stuartcarnie requested changes
Overall looks good, @crepererum. As you suspected `LIMIT` and `OFFSET` apply _per measurement_, so there will need to be some changes to accommodate that.

I believe I can refactor my implementation, so you can use it here. I will propose a change in a separate PR and ask for your feedback, as I want to understand if the change in logical plan is still efficient.

2023-04-05 23:55 UTC, stuartcarnie commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql
💯 Nice coverage of various incarnations of `SHOW FIELD KEYS`

2023-04-05 23:55 UTC, stuartcarnie commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
> +| m1               | str          | string    |
👌🏻 This is good, as the rows should be lexicographically sorted in ascending order by the `iox::measurement` and `fieldKey` columns.

2023-04-05 23:55 UTC, stuartcarnie commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
> +| cpu              | usage_system | float     |
As discussed, this should limit the number of rows, _per measurement_

2023-04-05 23:55 UTC, stuartcarnie commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
> ++------------------+------------+-----------+
As discussed, this should skip 3 rows, _per measurement_.

2023-04-05 23:55 UTC, stuartcarnie commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
> ++------------------+------------+-----------+
As discussed, this should skip 3 rows and limit to 2 rows, per measurement.

2023-04-05 23:55 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +                self.show_field_keys_to_plan(*show_field_keys)
🥳

2023-04-05 23:55 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +                                let regex = parse_regex(regex)?;
```suggestion
                            let regex = parse_regex(regex)?;
                            for name in &all_tables {
```

This can be moved this outside the loop, so it isn't parsed each iteration.

2023-04-05 23:55 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +                    InfluxFieldType::UInteger => "uinteger",
```suggestion
                    InfluxFieldType::UInteger => "unsigned",
```

Sourced from the list of InfluxQL data type names:

https://github.com/influxdata/influxql/blob/1ba470371ec093d57a726b143fe6ccbacf1b452b/ast.go#L177-L186

2023-04-05 23:55 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        let plan = self.limit(plan, show_field_keys.offset, show_field_keys.limit)?;
As noted elsewhere, this won't work for multiple measurements. 

I could refactor the current implementation, so you could reuse it.

I will propose a change and have you look to see if it is any less efficient.

2023-04-05 23:55 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        }
I have refactored this function so you won't have to make this change, as it handles all the operators we might expect from planning InfluxQL

2023-04-06 01:02 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        let plan = self.limit(plan, show_field_keys.offset, show_field_keys.limit)?;
@crepererum see 

https://github.com/influxdata/influxdb_iox/pull/7464 

which refactors the `limit` function, so you can reuse it here.

2023-04-11 08:34 UTC, crepererum commented on iox_query_influxql/src/plan/planner.rs
> +                                let regex = parse_regex(regex)?;
fixed

2023-04-11 08:35 UTC, crepererum commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
> +| cpu              | usage_system | float     |
done

2023-04-11 08:35 UTC, crepererum commented on influxdb_iox/tests/query_tests2/cases/in/influxql_metadata.influxql.expected
> ++------------------+------------+-----------+
done

2023-04-11 08:36 UTC, crepererum commented on iox_query_influxql/src/plan/planner.rs
> +        let plan = self.limit(plan, show_field_keys.offset, show_field_keys.limit)?;
done (however I've changed the code to work w/o a mocked time expression because we don't have any in this case).

2023-04-12 07:41 UTC, stuartcarnie approved these changes
Very nice, @crepererum 💯 

I also like the use of `Scan` over `Values`.

2023-04-12 07:41 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner/select.rs
> +    time_sort_expr: Option<Expr>,
👍🏻

2023-04-12 07:41 UTC, stuartcarnie commented on iox_query_influxql/src/plan/planner.rs
> +        .build()?;
I like this better too 👍🏻

2023-04-12 09:09 UTC, merged