refactor(router/v1): remove unused fields
influxdata/influxdb_iox pull request #7414
Opened 2023-03-31 15:27 UTC by domodwyer

I noticed these are never going to be used (I think?)

---

* refactor(v1): remove unused fields (3ba01f5b0)
      
      We do not intend to do anything with these values, so we can skip
      deserialising them, and therefore remove their types too!
      
      Serde does not perform "strict" deserialisation by default (it does not
      error when it sees a field it does not know about). You can enable
      "strict" mode by adding an #[serde(deny_unknown_fields)] annotation:
      
          https://serde.rs/container-attrs.html#deny_unknown_fields

2023-03-31 18:36 UTC, wiedld requested changes
Please add the `p` field back in. Then this is gtg.

2023-03-31 18:36 UTC, wiedld commented on router/src/server/http/write_v1.rs
> -    p: Option<String>,
I have auth code locally, which consumes this `p` field. As per the authz/authn spec laid out in [this ticket](https://github.com/influxdata/idpe/issues/17265).

2023-03-31 18:36 UTC, wiedld commented on ioxd_router/src/lib.rs
> +pub async fn create_router_server_type(
So clippy doesn't catch an unused lifetime?  😭

2023-03-31 18:37 UTC, wiedld commented on router/src/server/http/write_v1.rs
> -    consistency: Consistency,
Also, you will need to remove the `invalid_consistency` test.

2023-04-04 12:30 UTC, domodwyer commented
Superseded by https://github.com/influxdata/influxdb_iox/pull/7429

2023-04-04 12:30 UTC, closed without merging