feat: add WAL metadata endpoint (#724)
influxdata/influxdb_iox pull request #758
Opened 2021-02-05 18:36 UTC by tustvold

Partially closes #724

Will update `influxdb_iox_client` as separate PR as this one was getting fairly large. I've moved a couple of data structures from within the WAL module to data_types in order to facilitate this.

2021-02-05 20:54 UTC, carols10cents requested changes
Overall, looks great! Just a few tiny comments :)

2021-02-05 20:54 UTC, carols10cents commented on server/src/buffer.rs
> +    // Returns an iterator of segment summaries for stored segments
Should this be a doc comment?

2021-02-05 20:54 UTC, carols10cents commented on server/src/buffer.rs
> +    persisted: Mutex<Option<SegmentPersistence>>,
It looks like this field is now time and location, not just time as the comment says?

2021-02-05 20:54 UTC, carols10cents commented on src/influxdb_ioxd/http.rs
> +            Self::WALNotFound { .. } => self.bad_request(),
Is this a bad request (400) or a not found (404) if someone asks for the WAL metadata from a database that doesn't have a WAL? I can't decide, it's kind of philosophical... if a client says "make me a database that doesn't hvae a WAL", then makes a separate request for the WAL metadata, whose fault is that? 

I don't think this is a huge deal, but probably something to be sure about before committing to API stability :)

2021-02-05 20:54 UTC, carols10cents commented on src/influxdb_ioxd/http.rs
> +        .take(limit.limit.unwrap_or(10))
Tiny nit... `limit.limit` looked unusual to me... given it contains the `WalMetadataQuery` that has both the `limit` and `newer_than`, maybe a better name for the variable would be `query`?

2021-02-05 22:55 UTC, alamb approved these changes
Nice work @tustvold  -- I think this implements https://github.com/influxdata/influxdb_iox/issues/724 as specified

It took me a little while to figure out how to test this locally, but I eventually figured it out

```
curl -v -X "PUT" "http://localhost:8080/iox/api/v1/id" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "id": 42
}'

# setup a db with a WAL
curl -v -X "PUT" "http://localhost:8080/iox/api/v1/databases/26f7e5a4b7be365b_917b97a92e883afc" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "store_locally": true,
  "wal_buffer_config":{"buffer_size":50000,"segment_size":100000,"buffer_rollover":"ReturnError","store_segments":true,"close_segment_after":null}
}'
```

```
curl -v "http://localhost:8080/iox/api/v1/databases/26f7e5a4b7be365b_917b97a92e883afc/wal/meta"
```

And it came back:
```
{
    "segments": [
        {
            "size": 0,
            "created_at": "2021-02-05T22:34:25.724451Z",
            "persisted": null,
            "writers": {}
        }
    ]
}
```

Of course, there seems to be something wrong with my understanding of the actual settings as writes don't seem to work. My local telegraph setup is generating an error now once I setup the database above. However, I don't think that has anything to do with this PR

```
Feb 05 17:37:07.042 ERROR influxdb_iox::influxdb_ioxd::http: Error while handling request error=WritingPoints { org: "26f7e5a4b7be365b", bucket_name: "917b97a92e883afc", source: WalError { source: UnableToDropSegment { size: 0, segment_count: 0 } } } error_message="Internal error writing points into org 26f7e5a4b7be365b, bucket 917b97a92e883afc:  error appending to wal buffer: Unable to drop segment to reduce size below max. Current size 0, segment count 0"
```

So I vote we merge this in and take it one step at a time (API to see the WAL metadata, and then subsequently we can figure out what is wrong with my setup

2021-02-05 22:55 UTC, alamb commented on data_types/src/http.rs
> +    #[serde(skip_serializing_if = "Option::is_none")]
I realize https://github.com/influxdata/influxdb_iox/issues/724 doesn't call for it, but typically such an API has both a `limit` and an `offset` parameter

So you you could page through the data,   10 at a time via:
`limit=10&offset=0`
`limit=10&offset=10`
`limit=10&offset=20`
...

2021-02-05 22:55 UTC, alamb commented on server/src/buffer.rs
> +            // TODO: Mark segment as persisted
any reason not to mark the persistence as part of this PR?

2021-02-08 11:48 UTC, tustvold commented on data_types/src/http.rs
> +    #[serde(skip_serializing_if = "Option::is_none")]
Added :+1:

This won't give "stable" pagination, it could skip elements if the collection is mutated, but it is not impossible for clients to detect this by requesting overlapping ranges, and triggering additional logic in the event of an error.

2021-02-08 11:50 UTC, tustvold commented on src/influxdb_ioxd/http.rs
> +            Self::WALNotFound { .. } => self.bad_request(),
I agree that a 404 would be a more appropriate error, updated :+1:

2021-02-08 11:50 UTC, tustvold commented on src/influxdb_ioxd/http.rs
> +        .take(limit.limit.unwrap_or(10))
Fixed

2021-02-08 11:53 UTC, tustvold commented on server/src/buffer.rs
> +            // TODO: Mark segment as persisted
Currently the spawned task doesn't retain a reference to the segment itself. The implementation as it stands likely needs some review, and I felt it beyond the scope of this particular PR to adapt it, but worth taking the opportunity to document this as not implemented.

2021-02-08 13:31 UTC, alamb approved these changes
I think it looks great!

2021-02-08 13:31 UTC, alamb commented on server/src/buffer.rs
> +            .skip(offset.unwrap_or(0))
beautiful

2021-02-08 16:55 UTC, merged