fix: Don't declare modules within macros; rustfmt can't see them
influxdata/influxdb_iox pull request #7673
Opened 2023-04-26 17:32 UTC by carols10cents

Because of https://github.com/rust-lang/rustfmt/issues/3253, declaring modules within macros results in rustfmt not seeing those modules.

2023-05-05 20:33 UTC, alamb reviewed
Looks neat to me -- I'll run it on my torture test loop and see how it goes

2023-05-05 20:33 UTC, alamb commented on ingester2/src/test_util.rs
> +pub(crate) fn defer_namespace_name_1_sec() -> Arc<DeferredLoad<NamespaceName>> {
👍

2023-05-05 20:33 UTC, alamb reviewed
Looks neat to me -- I'll run it on my torture test loop and see how it goes

2023-05-05 20:48 UTC, alamb commented
I have run my reproducer for https://github.com/influxdata/influxdb_iox/issues/7758 on this branch and it has passed over 500 times (it used to reliably crash after less than 20) 🎉

2023-05-05 21:10 UTC, alamb reviewed
Thank you @carols10cents  -- I don't feel qualified to approve this PR as I don't feel I know enough about the ingester code -- I think @domodwyer  should do so 

However, I confirm it fixes https://github.com/influxdata/influxdb_iox/issues/7758 for me so 🎉 

Thank you so much

2023-05-08 10:20 UTC, domodwyer requested changes
I think we might be able to reduce some of the churn here 🙏 

One thing I'm slightly concerned about is people accidentally via autoimports (or not accidentally!) importing something that's an implementation detail because their thing "should use the real thing" like what happened in ingester1 - I'm genuinely scarred from that experience!

I'd very much prefer to hide everything by default to prevent this, but I agree usability for working with the code is way more important than saving ourselves from ourselves.

That said, I can't reproduce your formatting problem! Or what I think the problem is at least.

2023-05-08 10:20 UTC, domodwyer commented on ingester2/src/init/wal_replay.rs
> +use crate::internal_implementation_details::{
What if we put this in `lib.rs` instead:

```rust
/// This module needs to be pub for the benchmarks but should not be used outside the crate.
pub mod internal_implementation_details {
    pub use super::buffer_tree::*;
    pub use super::dml_sink::*;
    pub use super::partition_iter::*;
    pub use super::persist::*;
    pub use super::wal::*;
}

mod buffer_tree;
mod dml_sink;
mod partition_iter;
mod persist;
mod wal;
```

(note the modules themselves are not `pub`!)

Then I think we wouldn't need to use `internal_implementation_details` in every import within the ingester and it'd become almost transparent (only external callers would have to use it). We could also avoid changing the file layout to shoehorn in the warning.

Arguably we could then go one further, and do:


```rust
#[cfg(feature = "benches")]
pub mod internal_implementation_details {
    //...
}
```

And be back to the hidden-by-default setup (because only the `pub` re-export would be conditional, and not the whole module within the ingester).

2023-05-08 10:33 UTC, domodwyer commented
I picked the test fixes into https://github.com/influxdata/influxdb_iox/pull/7762 so they're in ASAP / independent of these changes :+1:

2023-05-08 14:22 UTC, domodwyer commented
Err yeah - I open the file, save the file, and everything springs into the right place! Should `cargo fmt` not be doing the same thing as rustfmt?!

```shellsession
% cargo fmt --all --check
# Returns 0

% rustfmt --check ingester2/src/buffer_tree/namespace.rs
    <big diff of badness snip>
# Returns 1
```

But asking cargo fmt to explicitly format that file does the right thing:

```shellsession
% cargo fmt --all --check -- ingester2/src/buffer_tree/namespace.rs
    <big diff of badness snip>
# Returns 1
```

This split in behaviour seems wrong to me :shrug: Happy to work around it though!

2023-05-08 14:28 UTC, carols10cents commented
> Err yeah - I open the file, save the file, and everything springs into the right place! Should `cargo fmt` not be doing the same thing as rustfmt?!

It should be, but there's a bug :) https://github.com/rust-lang/rustfmt/issues/3253

2023-05-22 20:34 UTC, carols10cents commented
Yeah I need to redo this, closing! Thank you for the nudge :)

2023-05-22 20:34 UTC, closed without merging