WIP: If namespace or table partition templates are specified, use those
influxdata/influxdb_iox pull request #7692
Opened 2023-04-28 02:00 UTC by carols10cents

Connects to https://github.com/influxdata/idpe/issues/17266.

This PR modifies the `Partitioner` in the router to take into account optionally-specified table and namespace partition templates.

This does NOT store or get the templates from the database yet, nor does it implement the gRPC services to allow changing those non-existent database values

2023-04-28 18:49 UTC, alamb commented on compactor2/tests/layouts/backfill.rs
> +    - "L0, all files 3.33mb                                                                                               "
I don't understand why the input file sizes have changed here as these tests aren't actually making any files 🤔  -- they should be using the simulator to simulate creating files

2023-04-28 20:29 UTC, carols10cents commented on compactor2/tests/layouts/backfill.rs
> +    - "L0, all files 3.33mb                                                                                               "
Hmmmmmm you're right, that's weird. Investigating.

2023-04-28 21:32 UTC, carols10cents commented on compactor2/tests/layouts/backfill.rs
> +    - "L0, all files 3.33mb                                                                                               "
Ok, I'm still not sure exactly what happened, but I think it wasn't changing the *sizes*, it was changing the *ordering*. And I'm not sure exactly why, but I think I was being too clever with the delegation, so I removed it and just made the schema inside the table info public so the compactor gets the same info it always has. 

I've added a new commit (not squashed) that makes this change and undoes the changes to the snapshots, and if you view the whole PR's changes it now shows no changes to the compactor snapshot.

2023-05-02 12:52 UTC, domodwyer commented on data_types/src/lib.rs
> +impl From<&Namespace> for NamespaceSchema {
This is a little misleading! It implies we can derive the `NamespaceSchema` from the `Namespace` type, but in fact it creates an empty shell `NamespaceSchema` with no schema contents (only namespace metadata!)

I'd have a hard time explaining this one if someone used it in a PR expecting it to return a populated `NamespaceSchema`.

What about a `NamespaceSchema::new_empty_from(namepsace)` constructor or similar instead? Or the old `NamespaceSchema::new(fields)` avoided this too I guess by being clear what was going _into_ the new instance.

2023-05-02 12:52 UTC, domodwyer commented on data_types/src/lib.rs
> +pub struct TableInfo {
Perhaps this is a little inconsistent? The partition scheme for the namespace goes in the `NamespaceSchema`, but the table partition scheme does not go in the `TableSchema`!

I'm guessing this is in anticipation of caching it in the router? I'd avoid defining application/usage-specific types in the `data_types` and instead have the "cache type" where the cache is. 

On a potentially related / forward-thinking note, I think it might be time to decouple the `NamespaceCache` from the `NamespaceSchema` type and store a cache-specific value type that contains all the bits we need (namespace metadata + partitioning scheme, and the table schemas, and the table-specific partitioning schemes). I can help with this in-between other work if you want?

2023-05-03 15:00 UTC, carols10cents commented on data_types/src/lib.rs
> +impl From<&Namespace> for NamespaceSchema {
Yeah I did feel like I was kind of shoehorning things in here that didn't quite fit. I like `NamespaceSchema::new_empty_from`, I'll make that change!

2023-05-03 15:01 UTC, carols10cents commented on data_types/src/lib.rs
> +pub struct TableInfo {
Yeah, this is definitely inconsistent and I don't like it either. I did consider making a cache type but wasn't sure if that was the right thing-- glad you like that idea too, I'll do it!

2023-05-03 15:34 UTC, carols10cents commented on data_types/src/lib.rs
> +pub struct TableInfo {
Ah yes here's the wrinkle I ran into that led to me creating `TableInfo` rather than adding the partition template onto `TableSchema`: the `get_table_schema_by_id` function currently creates a `TableSchema` by doing one catalog query *to the columns table* and filtering that on `table_id`:

https://github.com/influxdata/influxdb_iox/blob/05688799c42bc386fcadb695eb630b7299bd8333/iox_catalog/src/interface.rs#L652-L671

This is only used in the ingester, which only uses the `columns` field of the `TableSchema`: https://github.com/influxdata/influxdb_iox/blob/05688799c42bc386fcadb695eb630b7299bd8333/ingester2/src/persist/worker.rs#L292-L307

So I made the new type so that `get_table_schema_by_id` could continue using `TableSchema` without needing to fetch the `partition_type` that it didn't actually need-- however, I think instead I can change `get_table_schema_by_id` to only return `BTreeMap<String, ColumnSchema>` since that's all it needs anyway!

2023-05-03 19:03 UTC, carols10cents commented
Ok, I think this is ready for re-review, there are 3 new commits since the last time you viewed (the other commits were only rebased on `main` to resolve conflicts)

> On a potentially related / forward-thinking note, I think it might be time to decouple the NamespaceCache from the NamespaceSchema type and store a cache-specific value type that contains all the bits we need (namespace metadata + partitioning scheme, and the table schemas, and the table-specific partitioning schemes). I can help with this in-between other work if you want?

I started trying to create a new type in the router just for the router's namespace cache that could be a different type than `NamespaceSchema`, but I quickly ran into that type being passed to `validate_or_insert_schema`, [which is also used by the ingester tests](https://github.com/influxdata/influxdb_iox/search?q=validate_or_insert_schema), and detangling that was starting to seem a bit much for this PR.

2023-05-08 13:27 UTC, domodwyer requested changes
I'd really like to get the newtype wrappers in, and the invariant assert. As much of the other stuff as possible, perhaps the DML trait change as it's part of this PR already, but I realsie you're trying to get something done, so we can ticket it if it's too much.

I'm hoping to clear my PR backlog and do a code this week - I can perhaps help on some of this towards the end of the week.

2023-05-08 13:27 UTC, domodwyer commented on router/src/dml_handlers/partitioner.rs
> +    type WriteInput = HashMap<TableId, (String, Option<Arc<PartitionTemplate>>, MutableBatch)>;
What do you think about adding some newtypes for:

* `TablePartionTemplateOverride`
* `NamespacePartionTemplateOverride`
* `DefaultPartionTemplate`

To help understand what the various types/values are, and ensure we don't confuse them when passing them around?

2023-05-08 13:27 UTC, domodwyer commented on router/src/dml_handlers/trait.rs
> +        namespace_partition_template: Option<Arc<PartitionTemplate>>,
It's a bit of a red flag that we're pushing this through a common trait interface when only one implementer uses it. Two alternatives:

1. Have the partitioner retain a reference to the `NamespaceCache`, and pull the partition template out using the ID/name - this is how other handlers pull handler-specific content out currently. Multiple lookups is a bit wasteful!
2. Change these args to remove `namespace_id` and this new partition template field, and replace it with `&NamespaceSchema` - have the dml stack caller pull the schema out the cache first, before calling `.write()` on the dml handler stack.

I think 2 is definitely cleaner and stops us from pulling the same thing from the cache multiple times (retention validator already does this, schema validator, namespace resolver) and gives us a consistent cache snapshot for all handlers. We should do it! (I convinced myself while typing)

2023-05-08 13:27 UTC, domodwyer commented on router/src/namespace_cache/memory.rs
>      // to 0 as the schemas become fully populated, leaving the common path free
I can't comment high enough, but there's an existing assert a little above this line:

```rust
assert_eq!(old_ns.id, new_ns.id);
```

Given we are defining a [new invariant](https://github.com/influxdata/idpe/issues/17266#issuecomment-1533728989):

> Once created, the partition template is immutable for each namespace / table

We should add an assert to ensure the two namespaces being merged do not have different overrides, which would be Bad(tm):

```rust
assert_eq!(new_ns.partitioning_override(), old_ns.partitioning_override());
```

Or whatever the actual words are :+1:

We should also document this on the `Memory` type (lol I don't need to tell you that!)  but perhaps also we add a section to the router docs:

https://github.com/influxdata/influxdb_iox/blob/d31fcd140078fa708cb5904244c500aaae6dd818/router/src/lib.rs#L1

2023-05-08 13:28 UTC, domodwyer commented
Oh and for clarity - the router is obviously working with _a lot_ of columns, so minimising the allocation/clone overhead is genuinely very beneficial (mostly on the CPU/latency front)

2023-05-08 14:46 UTC, carols10cents commented on data_types/src/lib.rs
> +    }
I'll write up a good-first-issue for making those optimizations after this is merged so I can link to the code 👍🏻

2023-05-09 12:52 UTC, domodwyer approved these changes
This is a fantastic PR - it's clean, it's optimised for the workload, it's readable & concise - it's great! 

It's clear a lot of effort went into this; thank you! 🙏

2023-05-09 12:52 UTC, domodwyer commented on router/src/server/http.rs
> -            }
Nice elimination of failure modes as a result of this change 👌

2023-05-09 12:53 UTC, domodwyer commented
I will push a few commits that are very minor instead of leaving comments about them - I hope you don't mind! I'll then rebase and get this merged.

2023-05-09 13:03 UTC, merged