refactor: Change catalog configuration so it is entirely dsn based / support end to end testing without postgres
influxdata/influxdb_iox pull request #7708
Opened 2023-05-01 11:36 UTC by alamb

# Rationale
Closes https://github.com/influxdata/influxdb_iox/issues/7285

I would like to make it easier to run run end to end  tests (see https://github.com/influxdata/influxdb_iox/issues/7285) and thus permitting the end to end tests to run with sqlite is good

# Changes:
1. Update the catalog configuration to be entirely based on the `INFLUXDB_IOX_CATALOG_DSN` rather than DSN and `INFLUXDB_IOX_CATALOG_TYPE`.

So the DSN can now be one of:
1. postgres (unchanged)
2. `memory` (memory)
3. `sqlite://<filename>`

For end to end testing, it can also be `sqlite` which will result in using a temporary file

Note this does not yet enable the sqlite based catalogs by default in end to end testing (or CI). That is tracked by XXXX

# Example uses
Now you can run end to end tests like this (without postgres) and it works great most of the time:

```sql
TEST_INTEGRATION=1 TEST_INFLUXDB_IOX_CATALOG_DSN=sqlite cargo test --test end_to_end 
```

2023-05-01 14:26 UTC, carols10cents requested changes
I think some comments and error messages that need to be updated to be consistent with the code and each other? 

This looks like an awesome simplification!

2023-05-01 14:26 UTC, carols10cents commented on clap_blocks/src/catalog_dsn.rs
> +    /// Sqlite (a local filename /tmp/foo.sqlite): `sqlite:///tmp/foo.sqlite`
Hm, this says specifying `sqlite` looks like `sqlite:///tmp/foo.sqlite` but the error messages above say it looks like `file:///tmp/catalog.sqlite`? Does the `sqlite` vs `file` protocol matter?

2023-05-01 14:26 UTC, carols10cents commented on clap_blocks/src/catalog_dsn.rs
> +        } else if let Some(file_path) = dsn.strip_prefix("sqlite://") {
Aha, looks like `sqlite://` is required, so the error message text needs to be changed.

2023-05-01 14:26 UTC, carols10cents commented on test_helpers_end_to_end/src/config.rs
> +/// Rewrites the special "iox_test_sqlite" catalog DSN to a new
What is the special "iox_test_sqlite" catalog DSN? I don't see that anywhere else in this PR or in main. 

On line 337 below, it's checking for the exact string `"sqlite"`, is that what this comment should say? 

Are there any tests that currently specify `"sqlite"` as the dsn in the `TestConfig`?

2023-05-01 15:22 UTC, alamb commented on test_helpers_end_to_end/src/config.rs
> +/// Rewrites the special "iox_test_sqlite" catalog DSN to a new
this is a good catch -- it is a left over from a prior implementation -- I will update the docs / comments / error messges

2023-05-01 16:51 UTC, alamb commented on clap_blocks/src/catalog_dsn.rs
> +        } else if let Some(file_path) = dsn.strip_prefix("sqlite://") {
Fixed in 70385eeb0

2023-05-01 16:51 UTC, alamb commented on test_helpers_end_to_end/src/config.rs
> +/// Rewrites the special "iox_test_sqlite" catalog DSN to a new
70385eeb0

2023-05-01 17:35 UTC, carols10cents approved these changes
Looks great now, thank you!

2023-05-02 10:38 UTC, domodwyer approved these changes

2023-05-02 10:39 UTC, alamb commented on clap_blocks/src/catalog_dsn.rs
> -    /// The type of catalog to use. "memory" is only useful for testing purposes.
I also checked a local checkout of `k8-idpe`:

```
-*- mode: grep; default-directory: "~/Software/k8s-idpe/" -*-
Grep started at Tue May  2 06:38:36

rg -n -H --no-heading -e 'INFLUXDB_IOX_CATALOG_TYPE' $(git rev-parse --show-toplevel || pwd)
```

So I am going to claim this is good to go

2023-05-02 10:48 UTC, merged

2023-05-02 11:58 UTC, domodwyer commented
I have reverted this change ⚠️