chore: add tracing to ingester2 response encoding for FlightData grpc do_get
influxdata/influxdb_iox pull request #7724
Opened 2023-05-02 22:28 UTC by wiedld

Want to be able to trace the specific amount of time, during an ingester2 query, which is attributable to the response encoding.

Closes #7618 

---

* chore: add tracing to ingester2 response encoding for FlightData grpc do_get (ff19d17ca748e314367c7dfb6d41f2137cde46e2)

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-05-03 00:05 UTC, wiedld commented on ingester2/src/server/grpc/query.rs
> +                    "per partition",
Was not sure how to test this scenario locally.

2023-05-03 10:34 UTC, alamb commented on ingester2/src/server/grpc/query.rs
> +                    "per partition",
Perhaps you could add something to the tracing end to end tests here: https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox/tests/end_to_end_cases/tracing.rs

2023-05-03 12:50 UTC, domodwyer requested changes
I'm happy to chat about this alter if you want :+1:

2023-05-03 12:50 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +struct StreamRecorder {
There's SO MANY STREAMS in the ingester query execution alone! How about a name that says what it records:

```suggestion
struct FlightEncodingLatencyRecorder {
```

(and associated types)

2023-05-03 12:50 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +        let encoding_span = span_ctx.child_span("ingester encode response");
I think we can remove this `encoding_span` - it's going to have almost exactly the same range as the `query_span` above it, including a load of time spent not encoding (query execution, request parsing, etc).

If we pass in the cloned `query_span`, instead of creating this `encoding_span` we don't lose any encoding-related information! The encoding spans will be children of the query span, which sounds sensible :+1:

2023-05-03 12:50 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +            state: StreamRecorderState::Polling(recorder.child_span(title).map(Box::new)),
Perhaps we drop the `title` param (we won't ever change it at call time) and make the thing it's recording a little more explicit:

```suggestion
            state: StreamRecorderState::Polling(recorder.child_span("frame encoding").map(Box::new)),
```

That way the spans will be labelled with what they're doing - otherwise it'd just say "per partition" for every frame (which is per partition! confusing :fire:)

2023-05-03 12:50 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +    Polling(Option<Box<Span>>),
So you've changed the states of the state machine a little from what I described in the original ticket, and I think it's sent you down a wrong path.

Below the span recorder on #364 starts a span when the decorator is constructed, at the start of the partition response. At the end of the partition response (when it yields `None`) the span ends, and it's emitted - that's going to look like this:

![image](https://user-images.githubusercontent.com/9275968/235916576-d1d1918c-8d45-4086-843f-a697a4dedee0.png)

(I only did the first few - it's actually exceedingly tedious to draw 😂)

The spans will start when the partition is being generated, and stop once the partition response has yielded all the frames.

What we want, is to record the **time the client spent waiting for a frame** which looks like this:

![image](https://user-images.githubusercontent.com/9275968/235916854-2b66b29a-bb84-42b4-ad98-c1bb70984cf6.png)

Where each span is a subset of the entire partition response frame.

If you implement a state enum that is roughly:

```rust
enum FrameEncodeRecorderState {
    Unpolled,
    Polled(child_span),
}
```

and your decorator retains the `query_span` parent:

```rust
struct FlightFrameEncodeRecorder<T> {
    inner: T,
    parent_span: Span,
}
```

Then at construction time, the state is `Unpolled`, then transition to `Polled(span_recorder)` where the span is a child of the parent `query_span` after the first poll call is made, but crucially **before you call `inner.poll()`** (which you are doing via the `ready!()` macro)

Then once the inner stream yields `Ok(Some(_))` you go back to the `Unpolled` state and close the child span - the lifetime of that child span now covers the entire time the caller spent waiting **for that frame** to be yielded.

---

(if you're fully caffeinated, you might say "hey, that `FrameEncodeRecorderState` looks a lot like an `Option`, why don't I use that?" and I'd say "it sure does look a lot like an `Option`, it'll get compiled down to the same thing, but your state enum will be way more descriptive for your usage in code" and we'll all be happy and enjoy our respective time zone appropriate beverage)

2023-05-03 12:50 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +    }
So this is obviously going to change when you change the state machine (see above) but I would like you to consider simplifying this match down to what is actually expected during execution, and remove the invalid branches that are either impossible, or only possible if this code is broken.

For example, is it possible in this code for the state to be `Polled(None)`? A third of the state matching logic is dedicated to something that can never happen. What about `Done` but with the stream not yet complete? That should be impossible because the job of this decorator is to track that!

Instead of writing `INTERNAL_STATES * INNER_STATES` number of branches (a number which quickly gets out of control), frame it as matching the state of the `inner` and assert/unwrap the expected state of your internal FSM state. 

After all, the whole point of this decorator is to track and accurately model the state of the `inner` stream, so the code should reflect that. It'll be way simpler to read, I promise!

2023-05-05 22:30 UTC, wiedld commented on ingester2/src/server/grpc/query.rs
> +                    "per partition",
TY!

2023-05-08 03:03 UTC, wiedld commented on ingester2/src/server/grpc/query.rs
> +    Polling(Option<Box<Span>>),
fixed. Also updating PR description.

2023-05-12 14:57 UTC, domodwyer requested changes
I want you to have a go at https://github.com/influxdata/influxdb_iox/pull/7724#discussion_r1183641542 ! I think it'll make for more readable code, but I also think it'll be a good exercise to expand your toolset.

2023-05-12 14:57 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +            encode_response(response, self.ingester_id, encoding_span).map_err(tonic::Status::from);
Tiny simplification:

```suggestion
        let output =
            encode_response(response, self.ingester_id, span).map_err(tonic::Status::from);
```

And add `.clone()` on the span where it's used above (line 189) instead of at the intro to this func - it's clearer that it's all the same span that way! Less vars == less thinking.

2023-05-12 14:57 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +    Polled(Box<Span>),
I'm guessing you've boxed this for a lint? Perhaps remove the `Box` and silence the lint to avoid the extra allocation per frame :+1:

2023-05-12 14:57 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +        };
If you're changing the `Some` to a different thing, you're probably looking for `map()`! 

Likewise to change `None` to something else, you're probably looking for `unwrap_or()`

Have a go! It'll be tidier :+1:

2023-05-12 14:57 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +        match (&mut stream_recorder.state, message) {
So I've noticed you do matches on tuples a lot to check two variables - it makes for N*M arms to be understood, and isn't the easiest thing to reason about.

It's not a rule that you shouldn't do this, but I think it's a tool you reach for quickly - have a go at this: 

> Instead of writing INTERNAL_STATES * INNER_STATES number of branches (a number which quickly gets out of control), frame it as matching the state of the inner and assert/unwrap the expected state of your internal FSM state.

https://github.com/influxdata/influxdb_iox/pull/7724#discussion_r1183641542

Don't match on two variables here - it's definitely unnecessary. I think perhaps being conscious of writing these N-var tuple matches and looking for alternatives will push you to explore what other tools are available a little more.

2023-05-12 14:57 UTC, domodwyer commented on ingester2/src/server/grpc/query.rs
> +        };
Though now that I look at it more, is this a way of you expressing you want to do nothing when there's no `Span` in the `Option`?

2023-05-15 20:16 UTC, wiedld commented on ingester2/src/server/grpc/query.rs
> +        };
yes, exactly.
But it's clear that this code is readable enough. Will update.

2023-05-15 20:19 UTC, wiedld commented on ingester2/src/server/grpc/query.rs
> +    Polled(Box<Span>),
Yes. `clippy::large-enum-variant`. Will remove the box and suppress the warning.

2023-05-15 22:34 UTC, wiedld commented on ingester2/src/server/grpc/query.rs
> +                    "per partition",
added another test case. TY.

2023-05-16 12:26 UTC, domodwyer requested changes
Where did the state machine go?! This captures the duration of the last poll, not the N polls necessary to yield a frame.

Lets have a chat later about how to move this PR forwards - I feel like it might be becoming a bit frustrating and a bit of a time sink for both of us and I don't want it to be either!

2023-05-16 19:43 UTC, wiedld commented
> Where did the state machine go?! This captures the duration of the last poll, not the N polls necessary to yield a frame.

A state machine requires the use of a previous state, to deferentially decide which transition/action to take for the next state. If you look at [the removed code](https://github.com/influxdata/influxdb_iox/pull/7724/commits/1407d740aeadb41f062897d132ec2a4f34bd3d1b) (which was removed based on your request to remove the tuple matching), you will notice that any time we have a parent_span present (a.k.a. we are tracing) --> the state changes to Polled. This means that the same state is also used for the following match, and whether or not to record ok|err. 

What this meant is that if we are tracing, we only ever have 1 possible current state for the tuple match. So I could remove that second state match (a.k.a. remove the tuple match) and have the exact same behavior. When tested, the new code also has the exact same trace profile as the previous code.

Agreed, we should have a chat about this.

2023-05-18 04:42 UTC, wiedld commented
Closing and redoing (with a clean git history) [here](https://github.com/influxdata/influxdb_iox/pull/7820).

2023-05-18 04:42 UTC, closed without merging