feat: download catalog objects as part of `remote store get-table`
influxdata/influxdb_iox pull request #7779
Opened 2023-05-11 22:32 UTC by alamb

# Rationale
Part of https://github.com/influxdata/influxdb_iox/issues/7744

I want to reproduce issues from production locally ([compactor OOMs specifically](https://github.com/influxdata/idpe/issues/17515)) so we can debug and verify fixes. To do so accurately I want to recreate the catalog state from production by importing parquet files exported via `remote store get-table` so I can reproduce compactor memory usage.

As @crepererum  and @NGA-TRAN  point out on https://github.com/influxdata/influxdb_iox/issues/7744#issuecomment-1534497646 , I can recreate most of the catalog information from the embedded parquet metadata but there are a few field of `ParquetFile` that can not be recovered accurately:
1. `compaction_level`
2. `max_l0_created_at`

Even if we added this to the embedded IOxParquetMetadata that is stored inside the parquet files, it may not always match (as the compactor will sometimes upgrade the compaction_level in the catalog without rewriting the files with updated metadata)

Additionally, there are some fields on the `Partition` I can kind of fake (like `sort_key`) but they may not be the same (e.g. if the parquet files have different subsets of columns). However, to accurately reproduce the catalog I need to use the actual values. Thus I need some way to retrieve the actual catalog objects.

# Changes:
1. updates `remote store get-table` to export the Partition information (as json)
2. Update  `remote store get-table` to export ParquetFile information (as json)
2. Tests for same (TODO)

I plan for the import tool to read all the files (based on extension) and rebuild the catalog from them as a subsequent PR. I think this functionality could also form the basis of a "export / import" feature from one iox instance to another.

# Example usage

In one terminal
```shell
influxdb_iox -v
```

In another terminal, download contents of `cpu` in namespace
`26f7e5a4b7be365b_917b97a92e883afc` to /tmp/cpu.

```
influxdb_iox remote store get-table 26f7e5a4b7be365b_917b97a92e883afc cpu -o /tmp/cpu
found 84 Parquet files, exporting...
downloading file 1 of 84 (3bd88817-d4fe-4f12-8682-809bc6f7b141.2.parquet)...
downloading file 2 of 84 (38ec1a60-62e7-43f6-a832-3368a072962c.2.parquet)...
downloading file 3 of 84 (7405766f-4f33-4994-bd66-3b215c7deadf.2.parquet)...
...
downloading file 82 of 84 (e60a7ec2-dd01-4b95-8e96-a321aad33494.42.parquet)...
downloading file 83 of 84 (5b62bfd6-a1f7-42ae-9c46-100c1703407a.42.parquet)...
downloading file 84 of 84 (8609a558-be18-4cfb-9220-dbb18b281548.42.parquet)...
Done.
```

In addition to the contents of the parquet files, there are now also json files with the relevant catalog information from table, partition, and parquet

```shell
(arrow_dev) alamb@MacBook-Pro-8 influxdb_iox % ls -ltr /tmp/cpu/*.json
ls -ltr /tmp/cpu/*.json
-rw-r--r--@ 1 alamb  wheel    2 May 11 17:20 /tmp/cpu/table.5.json
-rw-r--r--@ 1 alamb  wheel  115 May 11 17:20 /tmp/cpu/partition.2.json
-rw-r--r--@ 1 alamb  wheel  115 May 11 17:20 /tmp/cpu/partition.8.json
-rw-r--r--@ 1 alamb  wheel  116 May 11 17:20 /tmp/cpu/partition.27.json
-rw-r--r--@ 1 alamb  wheel  116 May 11 17:20 /tmp/cpu/partition.31.json
-rw-r--r--@ 1 alamb  wheel  116 May 11 17:20 /tmp/cpu/partition.42.json
-rw-r--r--@ 1 alamb  wheel  490 May 11 17:20 /tmp/cpu/3bd88817-d4fe-4f12-8682-809bc6f7b141.2.parquet.json
-rw-r--r--@ 1 alamb  wheel  491 May 11 17:20 /tmp/cpu/38ec1a60-62e7-43f6-a832-3368a072962c.2.parquet.json
-rw-r--r--@ 1 alamb  wheel  490 May 11 17:20 /tmp/cpu/7405766f-4f33-4994-bd66-3b215c7deadf.2.parquet.json
```

And it contains the JSON encoded client messages:

```shell
cat /tmp/cpu/partition.31.json
{
  "id": "31",
  "tableId": "5",
  "key": "2023-05-08",
  "arraySortKey": [
    "host",
    "cpu",
    "time"
  ]
```

```

2023-05-12 03:52 UTC, crepererum commented
I think we could emebed `max_l0_created_at` within our parquet files. It's basically the maximum creation timestamp of the underlying data prior to any compaction, which acts as some kind of ordering / sequencing info. This never changes for a file and should be known when the file is created – in contrast to the level which changes – so we could just embed it. I can file a PR next week to fix that.

For the level though it is true that we cannot embed it within the file since it may change during the life cycle of a single file (called "upgrading").

2023-05-12 16:11 UTC, NGA-TRAN commented
I agree with @crepererum that we do not need to change `max_l0_created_at`.

Regarding `compaction_level`, we need to also set their `to_delete`. I think there are 3 prominent cases:
1. **Querier use case1 - Reproduce one specific plan with exact input files:**  If we only download specific files (subset of files in a partition) that we know the querier uses as input to a query plan, we just simply make their `compaction_level` L0 and `to_delete` NULL. 
2.**Querier use case 2 - Get the state of the table to run many queries:** We may want to keep `compaction_level` and `to_delete` as is.
3. **Compactor use case**: Need to down load full table to get a lot of files to reproduce a compact plan and do not care if L1s and their soft-deleted L0s coexist, we simply make all files `compaction_level` L0 and `to_delete` NULL. The compaction plan won't be exactly the same which is ok because all we want is a lot of files

2023-05-16 16:55 UTC, alamb commented on import_export/src/file/export.rs
> +/// Exports data from a remote IOx instance to local files.
This is mostly the same code as was in `remote get-table` but I moved it to its own module / crate as it was getting bigger and I want to be able to write more sophisticated tests for it as part of the catalog rebuild tool I am working on in https://github.com/influxdata/influxdb_iox/issues/7744

2023-05-16 16:55 UTC, alamb commented on import_export/src/file/export.rs
> +        println!("found {num_parquet_files} Parquet files, exporting...");
I plan to remove this `println`s in a follow on PR

2023-05-16 16:55 UTC, alamb commented on import_export/src/file/import.rs
> +pub struct ExportedContents {
This is a hint about the structure of the import -- it will take a structure like this that has a bunch of files, and create a new catalog from it.

2023-05-16 17:15 UTC, alamb commented on influxdb_iox_client/src/client/catalog.rs
> +    #[allow(clippy::future_not_send)]
Clippy gets all bent out of shape about `impl Into<String>` so I needed to allow this

For some reason we have this lint explicitly enabled https://github.com/influxdata/influxdb_iox/blob/c9cd1fdc44ea03920ed986959c9894a2b6d57ca9/influxdb_iox/src/main.rs#L9

2023-05-16 17:39 UTC, alamb commented on import_export/src/file/export.rs
> +        println!("found {num_parquet_files} Parquet files, exporting...");
https://github.com/influxdata/influxdb_iox/pull/7805

2023-05-16 17:40 UTC, alamb commented
FYI @carols10cents  as I think you worked on this code before

2023-05-17 14:45 UTC, NGA-TRAN approved these changes
So nice. Thanks @alamb for making this happen

2023-05-17 14:45 UTC, NGA-TRAN commented on import_export/src/file/export.rs
> +    async fn export_table_metadata(
🎉

2023-05-17 15:21 UTC, domodwyer commented on influxdb_iox_client/src/client/catalog.rs
> +    #[allow(clippy::future_not_send)]
These bounds should be `impl Into<String> + Send` - a non-send future winds up cascading up the call chain / types and throws random errors about future bounds without pointing to the problem. @crepererum added the lint to prevent this :+1:

2023-05-17 15:53 UTC, carols10cents requested changes
A few cleanups I'd like to see!

2023-05-17 15:53 UTC, carols10cents commented on import_export/src/file/export.rs
> +        // name) but there is no catalog gRPC call to get a table_id by name
Nit: unclosed delimiter, brain compiling failed. Also I'm not sure what "try and export all relevant tables" means as there should only be one table? Should this say "try and export the relevant table"? Or "try and export all relevant parquet files?" I don't know :)

 ```suggestion
        // try and export all relevant tables (all parquet files
        // should share the same table_id as they are all the same
        // name) but there is no catalog gRPC call to get a table_id by name
```

Also also, "there is no catalog gRPC call to get a table_id by name"... if only we knew who implemented the catalog gRPC calls and could ask them to add a new one....? 🤔 😉

2023-05-17 15:53 UTC, carols10cents commented on influxdb_iox_client/src/client/catalog.rs
> +    #[allow(clippy::future_not_send)]
This is the reason: https://github.com/influxdata/influxdb_iox/pull/1671 :) I think it'd be good to follow that lint since these are public library functions? Changing these to `impl Into<String> + Send` seems to be pleasing to clippy?

2023-05-17 15:53 UTC, carols10cents commented on import_export/src/file/export.rs
> +                    "skipping file {index} of {num_parquet_files} ({} does not match request)",
Here, the zero-based index is printed out, but in `export_parquet_file` there's `let index = index + 1;` before printing out... maybe move the `+1` here by adding a `map` to the `indexed_parquet_file_metadata` creation?

2023-05-17 15:53 UTC, carols10cents commented on import_export/src/file/export.rs
> +            println!("skipping file {index} of {num_parquet_files} ({filename} already exists)");
The file already exists _with the same file size_ (so presumably the same content)... is there a chance someone would see this message and rely on its assurance that it won't overwrite merely existing files, even if they _aren't_ the same content? Probably unlikely given the UUID in the filename, buuuut...

That is, I think this would be better as something like:

```suggestion
            println!("skipping file {index} of {num_parquet_files} ({filename} already exists with the expected file size)");
```

2023-05-17 15:53 UTC, carols10cents commented on influxdb_iox/src/commands/remote/store.rs
>  }
Similarly to the other spot, while you're in here, can we fix this? Remove the `allow` and the `Error`s on the variants?

2023-05-17 15:53 UTC, carols10cents commented on influxdb_iox/tests/end_to_end_cases/remote.rs
> +/// 1 parquet files: 1 partition that has 1 table with 1 parquet files
I feel like this comment has too many "parquet file" repetitions? And tables have partitions, not the other way around, right?

```suggestion
/// Asserts that the directory contains metadata and files for
/// 1 table that has 1 partition with 1 parquet file
```

2023-05-17 15:53 UTC, carols10cents commented on influxdb_iox/tests/end_to_end_cases/remote.rs
> +/// 2 parquet files: 1 partition that has 1 table with 2 parquet files
Similarly,

```suggestion
/// Asserts that the directory contains metadata and files for
/// 1 table that has 1 partition with 2 parquet files
```

2023-05-17 15:54 UTC, carols10cents commented on influxdb_iox_client/src/client/catalog.rs
> +    #[allow(clippy::future_not_send)]
🤣 Andrew, did you see the memo about the cover sheets on the TPS reports??

2023-05-18 11:16 UTC, alamb commented on influxdb_iox_client/src/client/catalog.rs
> +    #[allow(clippy::future_not_send)]
Thank you for the backstory -- will fix and add explination

2023-05-18 12:52 UTC, alamb commented on import_export/src/file/export.rs
> +            println!("skipping file {index} of {num_parquet_files} ({filename} already exists)");
in 6519a6377 👍

2023-05-18 12:52 UTC, alamb commented on import_export/src/file/export.rs
> +                    "skipping file {index} of {num_parquet_files} ({} does not match request)",
Excellent catch. I changed the code in a2e5516e5 so that index is not modified and instead the all the `printlns` are explicitly index + 1

2023-05-18 12:52 UTC, alamb commented on import_export/src/file/export.rs
> +        // name) but there is no catalog gRPC call to get a table_id by name
I agree this comment is confusing. I reworded it to

```
        // Export the metadata for the table. Since all
        // parquet_files are part of the same table, use the table_id
        // from the first parquet_file
```

in a616835d3

2023-05-18 12:52 UTC, alamb commented on import_export/src/file/export.rs
> +    }
I have plans longer term to improve the API / add more filtering APIs to the `RemoteExporter` -- so while you are right that at the moment it is always constructed with a partition filter, that may not always be true. 

I tried to improve the API in 8ed77f3f5

2023-05-18 12:52 UTC, alamb commented on import_export/src/file/export.rs
> +}
In b55e1feee

2023-05-18 12:52 UTC, alamb commented on import_export/Cargo.toml
> +influxdb_iox_client = { path = "../influxdb_iox_client", features = ["flight", "format"] }
in 039922e81

2023-05-18 12:54 UTC, alamb commented on influxdb_iox/tests/end_to_end_cases/remote.rs
> +/// 1 parquet files: 1 partition that has 1 table with 1 parquet files
in c3553e348 👍

2023-05-18 12:54 UTC, alamb commented on influxdb_iox/tests/end_to_end_cases/remote.rs
> +/// 2 parquet files: 1 partition that has 1 table with 2 parquet files
in c3553e348

2023-05-18 14:33 UTC, carols10cents approved these changes
Looks great, thank you!

2023-05-18 16:27 UTC, epage commented on import_export/src/lib.rs
> +//! Import/export utilities for IOx
We do have an impl though (#12148).  It was done in a way to not require MSRV bumps.  Still looking for ways to make it easier to test the feature without exclusively switching to nightly (see https://github.com/rust-lang/cargo/issues/12115#issuecomment-1553307722).

2023-05-18 16:46 UTC, alamb commented
Thanks for the review @carols10cents

2023-05-18 16:52 UTC, merged