feat: Add database rules configuration for mutable buffer
influxdata/influxdb_iox pull request #779
Opened 2021-02-09 21:24 UTC by pauldix

Here's what I'm thinking for the configuration options for the mutable buffer management. If this looks good, I'll follow up with a commit to remove the `store_locally` flag in `DatabaseRules`. After that I can move to actually implement these rules in the server.

2021-02-09 21:54 UTC, alamb approved these changes
Looks good to me. I had some stylistic comments, but I think this is workable as is too

2021-02-09 21:54 UTC, alamb commented on data_types/src/database_rules.rs
> +    pub buffer_size: u64,
I wonder if a name like `target_buffer_size` might be more descriptive (and give us wiggle room so that we don't end having to have exact measurements or have people get confused if IOx doesn't have a tight guarantee or language lawyering us about how much space the mutable buffer is consuming.

2021-02-09 21:54 UTC, alamb commented on data_types/src/database_rules.rs
> +    /// drop partitions in the sort order, regardless of whether they have
I am not sure about what the 'sort order' means here. It is a little confusing as the `partition_drop_order` field seems to be the thing that defines what to drop. 

Also, if we only have one partition which has chunks, which chunk is dropped?

2021-02-09 21:54 UTC, alamb commented on data_types/src/database_rules.rs
> +    /// drop partitions in the sort order, regardless of whether they have
It might also be helpful to explain in what cases we might not be able to drop a partition (e.g. trouble with object store, or not being able to encode / write chunks fast enough to keep up with incoming inserts)

2021-02-09 21:54 UTC, alamb commented on data_types/src/database_rules.rs
> +    pub persist_after_cold_seconds: Option<u32>,
If the mutable buffer internally can make several chunks for a partition , I wonder if the persist rules should be in terms of Chunks too -- as in "persist_after_cold_secods" would also apply to chunks within a partition after they hadn't seen a write for 15 seconds (which would basically be ~15 seconds after they were closed)

2021-02-09 21:54 UTC, alamb commented on data_types/src/database_rules.rs
> +    /// A column name, its expected type, and whether to use the min or max
The obvious usecase here is the value of the `time` column  -- is there any other usecase you can think of?

2021-02-09 21:57 UTC, pauldix commented on data_types/src/database_rules.rs
> +    /// drop partitions in the sort order, regardless of whether they have
The logic I'm going with is to drop entire partitions for now. This is assuming that partitions are by time and become cold for writes. However, I would expect the management API to enable more complex behaviors and dropping individual chunks.

2021-02-09 22:02 UTC, pauldix commented on data_types/src/database_rules.rs
> +    pub persist_after_cold_seconds: Option<u32>,
I'm just building up the most basic logic here. The underlying assumption is that you're partitioning data by time and that you stop writing to that time period after it has passed. Thus you'd have a single chunk and you'd rollover that chunk and persist it. A new chunk wouldn't end up being created because that partition is cold for writes. Once the partition is dropped, if data is later written into that time period, it would create that partition anew in the mutable buffer with a single chunk (should be next ID in line based on the catalog), and this all kind of works.

Where it falls down is if the user explicitly rolls over to another chunk, but if they're doing that they can use the management API to handle whatever that more complex scenario is.

2021-02-09 22:03 UTC, pauldix commented on data_types/src/database_rules.rs
> +    /// A column name, its expected type, and whether to use the min or max
Not particularly, but I wanted it to be flexible enough to specify any column. I chose `CreatedAtTime` as the default because I expect to not even need to use the underlying data in the most common operational case.

2021-02-09 22:27 UTC, alamb commented on data_types/src/database_rules.rs
> +    pub persist_after_cold_seconds: Option<u32>,
that makes sense 👍

2021-02-10 11:01 UTC, domodwyer approved these changes
Looks good, love the detailed docs!

2021-02-10 12:55 UTC, pauldix commented on data_types/src/database_rules.rs
> +    pub persist_after_cold_seconds: Option<u32>,
I guess the issue is that if the user has a partitioning scheme where the partitions never become cold, it won't rollover the chunk so that it can persist it. So maybe this should be expanded a bit? Could have:

```
/// Attempt to close the open chunk of a partition and persist it after it has 
/// passed the estimated size in bytes.
pub persist_after_bytes: Option<u64>
```

Then just update the drop logic to favor dropping persisted chunks (or the entire partition if there is only one chunk).

2021-02-10 16:14 UTC, carols10cents requested changes
I added a failing test to this branch to illustrate what I'm confused about with the docs for the mutable_buffer_config rule; either the docs need to be updated or the code does, I think.

2021-02-10 18:38 UTC, pauldix commented on data_types/src/database_rules.rs
> +    /// When set this will collect writes into a queryable in-memory database
Ah, right how to handle this pattern? Basically, I want the default to be that if they don't pass a mutable buffer config, one will be provided and used. Otherwise, if they don't want to use the mutable buffer, they'd have to explicitly set this option to `None`.

2021-02-10 19:29 UTC, carols10cents commented on data_types/src/database_rules.rs
> +    /// When set this will collect writes into a queryable in-memory database
Hm, maybe change the docs to something like:

"Unless explicitly disabled by setting this to `None`, this will collect writes into a queryable in-memory database called the Mutable Buffer."

and maybe something like "If no value is specified, the mutable buffer will use the default configuration settings of [whatever], which can be customized by explicitly setting this field to [whatever]"?

2021-02-10 19:55 UTC, pauldix commented on data_types/src/database_rules.rs
> +    /// When set this will collect writes into a queryable in-memory database
Ok, updated comment in 51bdd2151b23c06e940312d775e23420c2754c27

2021-02-10 21:40 UTC, carols10cents approved these changes
Works for me!

2021-02-10 23:21 UTC, alamb approved these changes
I think we should get some of these rules, as written, wired up and revise the rules / logic when we have actual operational experience to know what the most important behaviors are. I feel like I am just guessing what policy might be best, but I don't have any experience to draw from

:shipit:

2021-02-10 23:21 UTC, alamb commented on data_types/src/database_rules.rs
> +    /// Unless explicitly disabled by setting this to None (or null in JSON),
👍

2021-02-10 23:36 UTC, merged