feat: add background task tracking
influxdata/influxdb_iox pull request #780
Opened 2021-02-10 12:26 UTC by tustvold

Closes #655

This adds the ability to associate a Future and accompanying metadata, with a TrackerContext. When this future is dropped, i.e. terminated or aborted, it will unregister with the TrackerContext. From the `TrackerContext` it is then possible to get a list of running futures, and trigger termination of them.

This solution is purposefully agnostic to how the future is actually scheduled, as we may wish to do something more sophisticated than `tokio::spawn` in future, or use this to track futures that are not spawned to an executor at all.

2021-02-10 15:41 UTC, domodwyer requested changes
Looks interesting!

2021-02-10 15:41 UTC, domodwyer commented on server/src/tracker.rs
> +    id: AtomicUsize,
Leftover from a refactor? Doesn't appear to be used.

2021-02-10 15:41 UTC, domodwyer commented on server/src/tracker.rs
> +    pub fn terminate(&self, id: TrackerId) -> bool {
This seems to be very similar to the [`AbortHandle`](https://docs.rs/futures/0.3.12/futures/future/struct.AbortHandle.html) from the futures crate - might be worth switching to that rather than rolling our own?

2021-02-10 15:45 UTC, alamb approved these changes
I think this is really cool -- thanks @tustvold !

I think there are some additional tests that might be useful that I commented on. 

Also I think it might be helpful to think through the API in the context of how will use this system. For example, I imagine that we might want a "system wide" registry of tasks which would mean multiple different types of tasks and metadata.

I think it would be helpful to sketch out how that might work. But really I see no reason why can't merge this PR and iterate in subsequent PRs

2021-02-10 15:45 UTC, alamb commented on object_store/Cargo.toml
> +tokio = { version = "1.0", features = ["macros", "fs"] }
what is `fs` needed for?

2021-02-10 15:45 UTC, alamb commented on server/src/lib.rs
> +    segment_persistence_ctx: TrackerContext<SegmentPersistenceTask>,
Can you explain how the following would work:

1. Multiple `SegmentPersistenceTask` -- are they all tracked by the same `segment_persistence_ctx` field?

2.Different types of tasks (e.g. a `LoadReadBufferTask`). Would that require a `TrackerContext` field like `Server::load_read_buffer_ctx`?

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +// Manual Clone to workaround https://github.com/rust-lang/rust/issues/26925
lol we were just talking about this issue

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +    #[allow(dead_code)]
I suggest documenting the return value here (namely that the future was successfully signaled) - or maybe just return `()` if the return value isn't useful

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +    /// Trigger graceful termination of a registered future
Is this more accurate:
```suggestion
    /// Trigger graceful termination of a registered future if it has not yet started executing
```

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +/// and provides the early termination functionality used by
this is cool

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +        if self.as_mut().project().terminate.poll(cx).is_ready() {
I don't know enough about futures to know if after returning `Ready(None)` the future could be polled again. If so we might have to remember that we saw a value in `terminate` previously

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +        match self.project().inner.poll(cx) {
I think you could ue https://doc.rust-lang.org/beta/std/task/enum.Poll.html#method.map here

something like `self.project().inner.poll(cx).map(Some)`

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +    #[tokio::test]
Given you have checks for `std::thread::panicking() ` I wonder if a test that `panic`d with a `TrackerContext` to an outstanding future would be valuable

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +        let task2 = tokio::spawn(receive2.track(&ctx, 2));
I recommend adding a check that metadata can be referenced via task (aka the external interface for "clients" of the `Tracker`)

Something maybe like (untested):
```
assert_eq!(task1.data, 1);
assert_eq!(task2.data, 2);
```

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +        }
```suggestion
          assert_eq!(ctx.tracked().len(), 1);
        }
```

2021-02-10 15:45 UTC, alamb commented on server/src/tracker.rs
> +pub struct TrackerContext<T> {
Rather than `TrackerContext ` what do you think about `TrackerRegistry` or `TrackedList` as names? Context is a fairly generic name and it seems like what this really is a collection of tracked `Future`s

2021-02-10 15:48 UTC, tustvold commented on server/src/tracker.rs
> +    id: AtomicUsize,
It's used within `TrackerContext::track` to assign the next ID, perhaps it could be named better....

2021-02-10 15:49 UTC, tustvold commented on server/src/tracker.rs
> +    pub fn terminate(&self, id: TrackerId) -> bool {
Good shout, was not aware it existed :grinning:

2021-02-10 15:55 UTC, tustvold commented on object_store/Cargo.toml
> +tokio = { version = "1.0", features = ["macros", "fs"] }
The crate depends on the feature, and when running a specific test I ran into issues with it building with the wrong set of tokio features. Happy to remove, cargo feature flags still confuse me...

2021-02-10 15:56 UTC, tustvold commented on server/src/tracker.rs
> +// Manual Clone to workaround https://github.com/rust-lang/rust/issues/26925
Yup

2021-02-10 15:59 UTC, tustvold commented on server/src/tracker.rs
> +        if self.as_mut().project().terminate.poll(cx).is_ready() {
It is illegal to do so - https://doc.rust-lang.org/nightly/core/future/trait.Future.html#panics. There is a fused future if you do need these semantics, but @domodwyer 's suggestion allows removing all this code which is even better :grin:

2021-02-10 16:02 UTC, tustvold commented on server/src/tracker.rs
> +        let task2 = tokio::spawn(receive2.track(&ctx, 2));
Are you suggesting adding a member function to `TrackedFuture` to fetch its stored data?

2021-02-10 16:24 UTC, tustvold commented on server/src/tracker.rs
> +    /// Trigger graceful termination of a registered future
It's more subtle than that, the abort kicks in within poll and so if poll is never called or the process never yields (i.e. returns Poll::Pending) it will have no impact. I've updated to what I think might be clearer?

2021-02-10 16:30 UTC, tustvold commented on server/src/lib.rs
> +    segment_persistence_ctx: TrackerContext<SegmentPersistenceTask>,
Ultimately the TrackerRegistry doesn't care, if you want a single global registry nothing prevents using an enumeration type for the metadata type. Whether we would do this will depend on the APIs we want to express, I didn't want the futures tracking to force our hand either way in this respect.

2021-02-10 17:15 UTC, tustvold commented on server/src/tracker.rs
> +pub struct TrackerContext<T> {
Renamed to TrackerRegistry

2021-02-10 17:34 UTC, carols10cents commented on object_store/Cargo.toml
> +tokio = { version = "1.0", features = ["macros", "fs"] }
I think this is a good change, but should be a separate PR. Cargo feature flags are additive, so I think the object_store crate works the way it is because elsewhere in the workspace we're turning on the tokio fs flag and we should be declaring it explicitly here. 

I'm curious how you got the error though, I've tried building the object_store crate a few different ways and couldn't figure out how to get it to think it isn't in the workspace!

2021-02-10 17:45 UTC, domodwyer reviewed
Looking good! Just a stylistic comment I'm not too bothered by, but I am very interested in the potential for a memory leak - we should be careful choosing to not drop memory and certain of the behaviour.

2021-02-10 17:45 UTC, domodwyer commented on server/src/tracker.rs
> +    id: AtomicUsize,
Ah fair enough - serves me right for PRing at standup 👍

2021-02-10 17:45 UTC, domodwyer commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
Perhaps we can call it `task_tracker` or something? I bet we'll have loads of `ctx` in the code.

Also (and this is totally personal taste) this future extension trait to decorate the future feels easily lost when reading / missed / doesn't feel right - I would have expected the `ctx` to have a `spawn(F: Future)` that handled the decoration internally, rather than spawning it into tokio and making it the responsibility of the caller to add the tracker. 

It feels like we pass down the `ctx` which is responsible for tracking tasks, but don't let it manage the tracking or the task.

2021-02-10 17:45 UTC, domodwyer commented on server/src/tracker.rs
> +        // Avoid double panic by "leaking" Tracker
What happens to the memory if the panic doesn't bring down the process?

In tokio a task that panics causes the worker thread to panic, which then gets respawned and everything carries on. Will this result in a memory leak or does the memory die with the original thread? The memory held by a future may be non trivial to leak.

2021-02-10 17:47 UTC, carols10cents commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
This is fine for this PR, but just a thought I had... do we want tracking of tasks to be opt-in as it is here or do we want it to be opt-out-ish by making the easy/default way of spawning a task anywhere in IOx do tracking and have it enforced by the type system somehow? Again, just something to think about and consider if we find forgetting about tracking of tasks to be a problem.

2021-02-10 17:47 UTC, carols10cents commented on server/src/lib.rs
> +    segment_persistence_ctx: TrackerRegistry<SegmentPersistenceTask>,
Because you've renamed `TrackerContext` to `TrackerRegistry`, should this field also be renamed from `segment_persistence_ctx` to `segment_persistence_registry`?

2021-02-10 17:47 UTC, carols10cents commented on server/src/tracker.rs
> +            let f = futures::future::pending::<()>().track(&reg, ());
Can this be:

```suggestion
            let _f = futures::future::pending::<()>().track(&reg, ());
```

instead?

2021-02-10 17:49 UTC, tustvold commented on object_store/Cargo.toml
> +tokio = { version = "1.0", features = ["macros", "fs"] }
> I'm curious how you got the error though, I've tried building the object_store crate a few different ways and couldn't figure out how to get it to think it isn't in the workspace!

It was probably my IDE doing something funky, I'm afraid I honestly don't remember... It's probably something to do with [this](https://github.com/rust-lang/cargo/issues/4463#issuecomment-737391509), but I'm not really sure.

I've backed out the change, and will submit a separate PR changing the setting on the object_store crate

2021-02-10 17:54 UTC, tustvold commented on server/src/tracker.rs
> +        // Avoid double panic by "leaking" Tracker
Each future has a block of data stored within the metadata structure attached to the TrackerRegistry, the size of this is the size of T plus the size of the AbortHandle (an Arc), and is therefore likely minimal. The potentially more problematic outcome would be that the task would never be seen to terminate. 

I will make a change to reduce the likelihood of hitting this case, to only if the lock is actually poisoned, i.e. would panic, which is the case I'm trying to protect against.

2021-02-10 17:55 UTC, alamb commented on server/src/lib.rs
> +    segment_persistence_ctx: TrackerContext<SegmentPersistenceTask>,
I think that makes sense (aka if we want a global registry we can make a single type of metadata). 👍

2021-02-10 18:02 UTC, alamb approved these changes
Looking even better now!

2021-02-10 18:02 UTC, alamb commented on server/src/tracker.rs
> +    pub fn terminate(&self, id: TrackerId) -> bool {
TIL: AbortHandle

2021-02-10 18:02 UTC, alamb commented on server/src/tracker.rs
> +        // Avoid double panic by "leaking" Tracker
I think we shouldn't worry about memory being leaked in the panic for now as (ideally) we shouldn't be panic'ing in normal operation -- and hopefully we'll be monitoring such events and reacting appropriately (rolling the pods, etc).

2021-02-10 18:03 UTC, alamb commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
This is a good idea (and not for this PR): If we have a global task registry then I think the suggestion to spawn tasks via that registry is the way to go.

2021-02-10 18:14 UTC, domodwyer commented on server/src/tracker.rs
> +        // Avoid double panic by "leaking" Tracker
I agree panicking isn't normal but we should certainly document the behaviour, even if we're not worried by it currently.

2021-02-10 18:15 UTC, alamb commented on server/src/tracker.rs
> +        // Avoid double panic by "leaking" Tracker
documenting sounds good

2021-02-10 18:18 UTC, tustvold commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
> Also (and this is totally personal taste) this future extension trait to decorate the future feels easily lost when reading / missed / doesn't feel right

So the approach I'm taking is largely modeled off the one taken by tokio-tracing to provide instrumentation, but it would definitely be possible to have a member function provide the decoration instead - I thought this made it clearer that the result is just another future you need to do something with

> I would have expected the ctx to have a spawn(F: Future) that handled the decoration internally, rather than spawning it into tokio and making it the responsibility of the caller to add the tracker.

I specifically did not want to do this, as it imposes constraints on how the jobs then get run. Currently we are just dumping all tasks on the default tokio threadpool, which is great for getting something working, but I imagine we will want to change this at some point. Ultimately this component can never be responsible for managing tasks, that's the responsibility of whatever future executor you choose to use, this design has it just handle tracking and early termination - the two things it can actually be responsible for...

2021-02-10 18:29 UTC, tustvold commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
At least in the short-term there are only 3 tasks that we're likely to be interested in tracking and so I don't envisage this being a major problem, but I agree that if we start using this component in more places it could be worth revisiting this?

2021-02-10 18:31 UTC, domodwyer commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
Great reasoning - my comment comes from the belief that we wanted to explicitly spawn these into a background pool though? 

We had a design doc at some point that covered splitting workloads into different pools - I just assumed this was the implementation of it.

2021-02-10 18:34 UTC, tustvold commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
> We had a design doc at some point that covered splitting workloads into different pools - I just assumed this was the implementation of it. If so, I would expect the task system to manage the things in the pool as well as tracking them for cancellation.

Yeah I found that design doc and wasn't sure what to make of it, this was my way of sidestepping that :grinning:

2021-02-10 18:37 UTC, alamb commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
Perhaps https://github.com/influxdata/influxdb_iox/blob/main/docs/multi_core_tasks.md

I am not sure what to make of it either -- I think we had a bunch of theoretical discussions, and possibly were using the terms "cpu bound" differently, and we didn't have any sort of multi job system at that point

I expect that as we start actually running some actions in parallel we will soon discover how far the (single) tokio threadpool will get us

2021-02-10 18:48 UTC, tustvold commented on server/src/tracker.rs
> +        // Avoid double panic by "leaking" Tracker
I've backed this change out and left a comment describing, ultimately it can only manifest when the tracker's mutex has been poisoned which we don't have a way to handle anyway and so this added complexity is largely pointless.

2021-02-11 10:04 UTC, domodwyer commented on server/src/buffer.rs
> +            .track(ctx, task_meta),
Yeah I think "cpu bound" as used in that doc is probably misleading - I assume we'd want some sort of priority system, where latency insensitive background tasks can't dominate the CPU runtime, but if it's not well defined it's definitely not for this PR!

2021-02-11 10:05 UTC, domodwyer approved these changes

2021-02-11 10:31 UTC, tustvold commented
^ squashed and rebased onto main

2021-02-11 11:24 UTC, merged