chore(7618): trace ingester response encoding v2
influxdata/influxdb_iox pull request #7820
Opened 2023-05-18 04:42 UTC by wiedld

Closes #7618 

---

* test: integration test for tracing of queries to the ingester (ef0bb0e60)

* chore: add FlightFrameEncodeRecorder to record spans per each polling result (e3ac0a09d)

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-05-18 13:17 UTC, domodwyer requested changes
This is a great step! It's looking like what I would expect this decorator to look like - great progress!

So in the interest of trying to avoid a back-and-forth, I'm going to suggest the following all at once:

1. **Document it** - at the very least, add some comments to the decorator type describing _what it does_. What it is measuring is subtle, and important - explain why you're doing it! Save someone else the job of having to comprehensively understand the code and the semantics of the underlying encoder to understand what this does.

2. Move it to another file - lets keep the business logic of handling a query RPC request away from the metrics, and in turn, limit the scope visibility across types. It's good practice to avoid having giant files with mixes of responsibilities, as it also mixes interior visibility across those types. Separate modules for separate concerns!

3. [Record metrics](https://github.com/influxdata/influxdb_iox/issues/7618#issuecomment-1517871908) as per the ticket - the same durations as the spans, so we can graph the distribution in aggregate instead of inspecting individual spans. 

While this is definitely a great step forwards, it doesn't quite capture the time frames we're looking for - we want to capture the _time the caller spends waiting for each frame_ which includes sourcing a batch, and encoding it. This measures the _time between frames_ which is not the same thing! It also starts recording in the constructor, which means it measures the time between construction and being used too - imagine this:

```rust
let encoder = FlightDataEncoder::new();
let call_stack = FlightFrameEncodeRecorder::new(encoder);

// Wait 10 seconds after initialising the decorator, before asking
// the encoder for a frame.
std::thread::sleep(10 seconds);

// Now ask for a frame
call_stack.poll()
```

This 10 seconds shouldn't appear in the "how long it took to encode a frame" traces - it's not time spent waiting on the encoder, but because it is in the constructor, the trace span will cover the entire 10s.

In order to help make what we're measuring a more concrete concept, rather than a description of a behaviour, I've wrote up a test that asserts **a subset** of the correct behaviours. It's hard to comprehensively test everything because it's all time based, so I've used bounds checking to ensure the span durations overlap with expected ranges, the correct number of spans are emitted, and a few other properties. If you get stuck with the test failing **reach out** in case the test is subtly wrong in some way - I'm writing it blind as I can't test my test is correct! 🔥 

I don't think this is the case because of the bounds checking, but because it's all time based, it may suffer from false-positives (i.e. it passes when it shouldn't sometimes). You might find it is more accurate if you increase the `POLL_BLOCK_TIME` value, but please put it back down before pushing so the test is still relatively fast. I don't think there's any case where the test will flake and falsely fail when the code under test is correct, but again, if unsure, reach out!

2023-05-19 10:50 UTC, savage-engineer commented on ingester/src/server/grpc/query/instrumentation.rs
> +                SpanRecorder::new(this.parent_span.as_mut().map(|s| s.child("frame encoding")));
I think this only needs an immutable borrow here. This would then allow the `FlightFrameEncodeRecorder` to store `parent_span` as an `Option<Arc<Span>>`. 

I had a play about and managed to get `encode_response` to take the span as `Option<Arc<Span>>`, which I _think_ would make the `span.clone()` call a bit cheaper. I tried to get something working with `Option<&Span>` but bumped into some complex lifetime/move semantics that didn't seem worth resolving.

I'm not familiar with this code path or whether it'd actually provide a benefit though, so may want to defer to @domodwyer

2023-05-19 12:31 UTC, domodwyer commented on ingester/src/server/grpc/query/instrumentation.rs
> +            // assert_eq!(span3.ctx, span_ctx);
So I'm not exactly sure if this is the right way to assert the property we want - that the spans are all child spans of the span passed into the decorator at init. I couldn't test it at the time!

You might need to change this bit :+1:

2023-05-19 13:29 UTC, domodwyer reviewed
Your impl is now correct! It records the poll durations nicely 🎉 

When I saw your code and that the tests were still failing, I went and had a look - the frame encoder actually emits two frames for the first data payload. You mislead yourself by changing the tests to only look at three spans instead of the full set! By changing it back, and adding `dbg!()` over the `poll` return value, it became clear that 4 frames were being emitted and I remembered there's a schema frame preamble, so we should expect 4 spans before the end 👍

I updated the test to account for this, and it now passes :tada: I also captured the ending span, that covers the poll that returns `None`, and I've updated the "parent of" assert I mentioned above.

---

Before continuing, it'd be good to clean up the `if let <state>` blocks in the match arms - it implies that the state may be this value or may not, and we only want to take an action if it is. That's definitely not the case - it should be a known state, or the code is broken! I refactored it a little locally, and I'll put it in a diff here, but have a go yourself first:

<details><summary>Refactor</summary>
<p>

```diff
diff --git a/ingester/src/server/grpc/query/instrumentation.rs b/ingester/src/server/grpc/query/instrumentation.rs
index 4223beaba..2125c1380 100644
--- a/ingester/src/server/grpc/query/instrumentation.rs
+++ b/ingester/src/server/grpc/query/instrumentation.rs
@@ -14,6 +14,21 @@ enum FrameEncodeRecorderState {
     Polled(SpanRecorder),
 }
 
+impl FrameEncodeRecorderState {
+    /// Unwrap `self`, returning the [`SpanRecorder`] and setting `self` to
+    /// [`FrameEncodeRecorderState::Unpolled`].
+    ///
+    /// # Panics
+    ///
+    /// Panics if `self` is not [`FrameEncodeRecorderState::Polled`].
+    fn take_recorder(&mut self) -> SpanRecorder {
+        match std::mem::replace(self, FrameEncodeRecorderState::Unpolled) {
+            Self::Unpolled => panic!("unwrapping incorrect state"),
+            Self::Polled(recorder) => recorder,
+        }
+    }
+}
+
 #[pin_project]
 pub(crate) struct FlightFrameEncodeRecorder {
     #[pin]
@@ -43,27 +58,22 @@ impl Stream for FlightFrameEncodeRecorder {
                 SpanRecorder::new(this.parent_span.as_mut().map(|s| s.child("frame encoding")));
             *this.state = FrameEncodeRecorderState::Polled(recorder);
         };
+
         let poll = this.inner.poll_next(cx);
 
-        match &poll {
+        match poll {
             Poll::Pending => {}
             Poll::Ready(None) => {
-                // end
-                *this.state = FrameEncodeRecorderState::Unpolled;
+                this.state.take_recorder().ok("complete");
             }
             Poll::Ready(Some(Ok(_))) => {
-                if let FrameEncodeRecorderState::Polled(recorder) = this.state {
-                    recorder.ok("data emitted");
-                    *this.state = FrameEncodeRecorderState::Unpolled;
-                };
+                this.state.take_recorder().ok("data emitted");
             }
             Poll::Ready(Some(Err(_))) => {
-                if let FrameEncodeRecorderState::Polled(recorder) = this.state {
-                    recorder.error("error");
-                    *this.state = FrameEncodeRecorderState::Unpolled;
-                };
+                this.state.take_recorder().error("error");
             }
         }
+
         poll
     }
 }
```

</p>
</details> 

**This isn't a stylistic thing** - it's an accurate representation of the expected behaviour, and shows how this decorator works. It's a combination of writing defensive code, and communicating to others what the actual states are at any time.

Now just some docs & metrics and we're good to go! 👍

2023-05-19 19:37 UTC, wiedld commented on ingester/src/server/grpc/query/instrumentation.rs
> +                SpanRecorder::new(this.parent_span.as_mut().map(|s| s.child("frame encoding")));
nice catch.

2023-05-25 18:03 UTC, wiedld commented
Added docs.
Per agreement, the metrics will be added in a followup PR.

2023-05-26 09:27 UTC, domodwyer approved these changes
Beautiful! 🎉

2023-05-26 09:40 UTC, merged