fix(iox, gc): delete files from table based on file age
influxdata/influxdb_iox pull request #7909
Opened 2023-06-01 21:00 UTC by philjb

This PR proposes to have the parquet file garbage collector remove files from the parquet_file table based on the to_delete column being non-null and the file's create time being older than the soft delete cutoff.

Because to_delete is filled with the timestamp of when the garbage collector (or compaction) marked the file as soft deleted, it is subject to the availability of the garbage collector running. If the GC is unavailable for a significant amount of time (approaching a day or more), the parquet files will have a to_delete timestamp of when the GC begins running again (or catches up if it is behind). This further delays removing files from the parquet table if only to_delete is used.

We know that if to_delete is not null, the file is soft deleted. We know that the created_at time is immutable so we can use the combination to determine that a file is available to be deleted from the table.

* helps with influxdata/idpe#17708

Closes #

Describe your proposed changes here.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-06-01 21:04 UTC, philjb commented on iox_catalog/src/postgres.rs
> +    AND created_at < $1
I already know an issue is that a file could not be soft deleted (to_delete != null) and then immediately eligible for deleting from the `parquet_files` table - say it is a very old parquet file that was still in use up until retention finally got it - queriers might still be referencing the file. 

The idea of using to_delete only allows a minimum delay from when it is soft deleted until removal from the table to allow queriers and other caches/uses to flush (just by passage of time + expected pod restarts). 

This PR breaks that potentially.

2023-06-01 21:05 UTC, philjb commented
I posted a flaw in this approach so if it doesn't pass muster, that's ok. Useful exercise for me.

2023-06-02 08:25 UTC, crepererum requested changes
I think we're confusing two things here:

1. **backup retention:** retain a file after it was created for a while because we wanna have a backup. This is what you PR gets right.
2. **cache invalidation retention:** after a file was marked for deletion, keep it for a while so that other nodes (esp. querier) can invalidate their caches on time so you don't delete a file while they are actively using it (see example below). This is what worked prior to your PR.

I think doing both w/ a single duration/age cutoff is wrong (or at least leads to suboptimal results, see https://github.com/influxdata/idpe/issues/17708 ). I think the condition for HARD deletion should be:

```sql
WHERE to_delete < cache_cutoff AND created_at < backup_cutoff
```

where:

- `cache_cutoff ~ now() - 1d`
- `backup_cutoff ~ now() - 30d` (or whatever was agreed on, don't remember.

# Example of breaking the querier
All you tests pass because race conditions are hard to test (if you have an idea on how to do it, please come forward!). You PR here will lead to the following bug:

1. file is created
2. 60d pass
3. querier plans query (contacts ingester, fetches catalog data), including that file, starts execution (and keeps executing during the following steps)
4. compactor does cold compaction, marks that file for deletion
5. GC is like "nice, file is marked for deletion, and it was created a long time ago, let me delete it from the catalog"
6. GC is like "this file is not part of the catalog anymore, let me remove this from S3"
7. querier is like "WTH, where's my file?! internal server error"

So sure this is not overly likely, but on a very busy cluster and long running analytic queries, this can happen. This is actually the reason WHY `to_delete` is a timestamp that marks the soft deletion time.
9.

2023-06-02 19:01 UTC, philjb commented
> I think we're confusing two things here:

100% I agree - I spotted this too in my [comment](https://github.com/influxdata/influxdb_iox/pull/7909#discussion_r1213678788), but I didn't get to conclusion of using two cutoffs as the solution. Nice and thanks.

```
WHERE to_delete < cache_cutoff AND created_at < backup_cutoff
```

I believe will work as discussed in slack. 

I will do this.

2023-06-06 22:02 UTC, philjb commented
> I believe will work as discussed in slack.

```
WHERE to_delete < cache_cutoff AND created_at < backup_cutoff
```


This doesn't work because a file may live longer than the backup_cutoff (100 days). For example, a compacted file for a namespace that has a retention of 150 days. That file will likely be >100days old when it is marked to be deleted (let to_delete = now()) for retention. Since `created_at < backup_cutoff` is already true on account of the file's age, the file will only live for the cache_cutoff time now (e.g. 1 day or 20 days). After that, the file may be hard deleted (removed from the catalog and from object store). This means any catalog backup older than the cache_cutoff is no longer viable - the 50 day old backup that references this retention-expired file don't work as at least one needed file is missing.

Unfortunately, this is not much better than just setting the backup_cutoff to something much shorter than 100 days.

Back to the drawing board. The team has a few other ideas to improve parquet file cleanup while maintaining backups for (influx's) DR.

2023-06-06 22:02 UTC, closed without merging