refactor: replace namespace with database for flight proto
influxdata/influxdb_iox pull request #7910
Opened 2023-06-01 21:23 UTC by NGA-TRAN

Closes #https://github.com/influxdata/idpe/issues/17607

I think this one would work to use `database`  in flightsql to run query instead of namespace but I have in-line  questions for @alamb and @mhilton

Describe your proposed changes here.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-06-01 21:36 UTC, NGA-TRAN commented on generated_types/protos/influxdata/iox/querier/v1/flight.proto
> +  string database = 1;
@mhilton : usually when we change the name, we make it field reserved and use new filed for it. But from your comment [here](https://github.com/influxdata/idpe/issues/17607#issuecomment-1550011849), I keep the field 1. I am not sure if we should do it though

2023-06-01 21:36 UTC, NGA-TRAN commented on service_grpc_flight/src/request.rs
> +            database: String,
Since this is now `database`, I remove the `database` alias but I think I may need to add `namespace_name` alias in case someone still using namespace_name. What do you think @alamb and @mhilton?

2023-06-01 21:36 UTC, NGA-TRAN commented on service_grpc_flight/src/lib.rs
> +        let namespace_name = request.database();
There are a lot of `namespace` in this file but it sounds to me I should not change them (yet). They are used in log messages and also `get_flightsql_namespace` that it seems we do not want to rename it yet. Let me know what you think @alamb

2023-06-01 21:36 UTC, NGA-TRAN commented on service_grpc_flight/src/lib.rs
> +/// Ask the team: when to rename this?
From the comment above, I do not rename this yet but not sure when we should do it

2023-06-02 05:06 UTC, mhilton requested changes
We need to ensure that `namespace_name` can still be used in the JSON token format. Otherwise this is looking good.

2023-06-02 05:06 UTC, mhilton commented on service_grpc_flight/src/lib.rs
> +            ticket: br#"{"database": "my_db", "sql_query": "SELECT 1;"}"#.to_vec().into(),
I think we need to keep this as it was to ensure the `namespace_name` will still work. There are other tests that check that `database` works as an alias.

2023-06-02 05:06 UTC, mhilton commented on service_grpc_flight/src/request.rs
> +            database: String,
Definitely. As currently written this will break the `influxqlbridge` and probably a number of other clients. I would probably elect not to change the JSON ticket code at all, @gavincabbage's recent changes mean that it works well enough from a client perspective. That does mean that the code would be a little messier with `database` and `namespace` being used interchangably, so tisying it up is a laudable goal.

2023-06-02 05:18 UTC, mhilton commented on generated_types/protos/influxdata/iox/querier/v1/flight.proto
> +  string database = 1;
I will note though that if you go the way of adding a new field it will require an intricate dance to enable.

1. Add the field and make IOx understand it, but not generate tickets that use it.
2. Update `queryrouterd` to understand the new field in tickets coming from clients and IOx.
3. Update IOx to generate tickets that use the new field in preference to the old one.

2023-06-02 17:06 UTC, NGA-TRAN reviewed
@mhilton : I have addressed your comment. In summary, this PR does:
1. Rename `string namespace_name = 1;` to `string database = 1;` for `ReadInfo` protobuf message   (purpose of this PR)
2. As a consequence, rename `alias = "database"` to `alias = "namespace_name"` to ensure `namespace_name` still works.
3. Add tests to fully cover these 4 aliases.

The other changes are just to make code compiles due to the change in number 1

2023-06-02 17:06 UTC, NGA-TRAN commented on service_grpc_flight/src/request.rs
>          let cases = vec![
Since the test does cover all alias (database, namespace_name, bucket, bucket-name), I add them in. Also, a few tests were duplicates rather than doing what they were meant to do so I fixed them (e.g: meta is "Show DataBases" rather than "SELECT 1"). I also add mover coverage for influxsql.

2023-06-02 17:07 UTC, NGA-TRAN commented on service_grpc_flight/src/lib.rs
> +            ticket: br#"{"database": "my_db", "sql_query": "SELECT 1;"}"#.to_vec().into(),
Done. Keep the original `namespace_name`

2023-06-05 16:47 UTC, mhilton approved these changes
LGTM

2023-06-05 16:53 UTC, merged