refactor: (WIP) separate compactor scheduler
influxdata/influxdb_iox pull request #7912
Opened 2023-06-01 23:15 UTC by wiedld

**WIP: not yet ready for review.**

Still need to finish the grpc service API, and connect through the service. Will need help on this part.

Plus lots of likely revisions, and/or a complete change in approach. We needed this work to get started, so I took a shot at it (with lots of team check-ins along the way).

---

* feat: skeleton of grpc service for compactor_scheduler (e7e12eddb)
    ```
    * grpc service will be consumed by the compactor 
    * will return the scheduled job for the compactor 
    * trait Scheduler -- define the functionality used by the service 
    * LocalScheduler -- will include the functionality for the local scheduler (per each compactor) for how it should behave. This will initial be a part of the of the current per-compactor decision-making logic.
    ```
    

* feat: expose scheduler to compactor config (20e4763cb)
    ```
    * create CompactorSchedulerConfig 
    * consume this config in the generation of the compactor config 
    * provide clap flags 
    * integrate into all-in-one mode 
    * set to default scheduler in test utils
    ```

* refactor: remove cold compactions (4c7f9c834)

* refactor: remove compaction_type (260f82693)

* refactor: move PartitionsSource into data_types. (040363df0)
     ```
      This commit is a refactoring to enable us to delineate between these two utilizations of the PartitionsSource trait. The prepartion of PartitionsSource is effectively what will be moved into the scheduler.

      The compactor currently uses PartitionsSource in two ways:
      * for the preparation of PartitionIds prior to the compactor pipeline.
      * for the abstraction which utilize the PartitionIds during the IO pipeline.
     ```

* refactor: separate scheduler logic from compactor (06dccf8de)
     ```
      Moved into the scheduler (will be exclusively used by the LocalScheduler):
      * mod id_only_partition_filter
      * implementations of PartitionsSource which can be applied prior to the IO pipeline
          * e.g. this means we can use these for PartitionsSource.fetch() --> return Vec<PartitionId> from the scheduler

      Temporary mod, within the scheduler:
      * contains the PartitionsSourceConfig, whose purpose will be fulfilled by the LocalScheduler.
      * figure out handling of ShardConfig, when in LocalScheduler mode.

      Proposed next steps:
      1. confirm logical boundary
      2. remove the temp mod code, into the LocalScheduler
      3. have the grpc service (using dyn LocalScheduler) return the needed schedule (Vec<PartitionId>)
      4. entirely delete/remove PartitionsSourceConfig. Will only have: (a) LocalScheduler mode, or (b) RemoteScheduler mode
     ```

* refactor: clean up dependency tree (97b602d73)
     ```
     * clap_blocks should not have any added dependencies
     * move creation of scheduler service into the scheduler crate itself 
     * scheduler should only require the scheduler config and the catalog service
     ```

* refactor: ShardConfig is part of the LocalScheduler 
     ```
     * remove from compactor awareness 
     * perform all validation, and usage, within the scheduler and scheduler config 
     * for the report, update the display fmt from the scheduler to include the shard config info 
     * missing CLI arg (for shard config) now gives more explicit feedback -- update test to match (ed1a7ab5f)
     ```

* refactor: PartitionsSourceConfig is part of local scheduler (105001a10)
      ```
      This is specifically about a configuration only used during the scheduling process. It is later used in the seeding of the initial Vec<PartitionIds> provided into the PartitionsSource trait implementations.
      ```

## Checklist:
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-06-02 04:58 UTC, wiedld commented on compactor/src/components/hardcoded.rs
>          partition_info_source: make_partition_info_source(config),
We chatted a bit offline about this one, as it could also be a way to reduce hits to the catalog. I think(?) the decisions was to wait until follow up iterations -- in which case, will remove this comment prior to merge.

2023-06-03 04:00 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +    fn from(value: proto::CompactionJob) -> Self {
Eventually, this will need to be a TryFrom. But didn't want to decide the error handling path for the remote stuff yet.

2023-06-13 21:54 UTC, wiedld commented on clap_blocks/src/compactor_scheduler.rs
> +    pub hostname: Option<String>,
Cannot `requires("shard_count")` for HOSTNAME, since that env var is set automatically by other things (e.g. circleci).

2023-06-14 15:15 UTC, crepererum commented on clap_blocks/src/compactor_scheduler.rs
> +    pub hostname: Option<String>,
Please don't try to parse the hostname. This should come solely from a dedicates env variable (the above one). We can get this to work in our K8s deploys (we had a similar setup for the ingest tier for a while and it used multiple 1-size statefulsets)

2023-06-14 15:15 UTC, crepererum commented on compactor_scheduler/src/scheduler.rs
> +    async fn get_job(&self) -> Vec<CompactionJob>;
How are jobs marked as completed, i.e. how does the scheduler know it was done?

2023-06-14 15:15 UTC, crepererum commented on compactor_scheduler/src/scheduler.rs
> +    fn from(value: proto::CompactionJob) -> Self {
`Box<dyn std::error::Error + Send + Sync>` will normally do, esp. for `TryFrom` which nobody really dissects anyways.

2023-06-14 15:15 UTC, crepererum commented on data_types/Cargo.toml
> +async-trait = "0.1.68"
`data_types` is a crate for simple structs, not for trait interfaces. the `PartitionsSource` is not an IOx-wide concept but only relevant for the compactor.

Doesn't the `compactor` depend on `compactor-scheduler` anyways? So could you place this in the former crate?

2023-06-14 16:10 UTC, wiedld commented on data_types/Cargo.toml
> +async-trait = "0.1.68"
good idea.

2023-06-14 18:17 UTC, wiedld commented on clap_blocks/src/compactor_scheduler.rs
> +    pub hostname: Option<String>,
Agreed, but I had trouble attempting another solution.

This `ShardConfig.hostname` is only used to get the unique ordinal index of each compactor in the StatefulSet. Such that when sharding, each compactor uses this unique id. I tried to instead set an explicit env var for the `INFLUXDB_IOX_COMPACTION_ORDINAL` in the [k8s compactor deployment config here](https://github.com/influxdata/k8s-idpe/blob/master/apps/iox/components/iox/compactor.libsonnet), but I could not find a way to access this unique ordinal.

Tried:
* looking at the k8s [stateful set docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) and the [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)
* looking at the [querier configs dynamic construction of these hostnames based upon ordinals](https://github.com/influxdata/k8s-idpe/blob/c85f80cb585435159dff5ce05546a7dd992e2338/apps/iox/components/iox/querier.libsonnet#L26-L30)
   * but it only counts 1 --> numReplicas and knows what ordinals exist.
   * not a current ordinal assignment 

Am I missing something? Or was there an alternative approach?

2023-06-14 18:54 UTC, wiedld commented on clap_blocks/src/compactor_scheduler.rs
> +    pub hostname: Option<String>,
Change made -- please let me know if it's not matching your request.

2023-06-14 19:03 UTC, Joe-Blount commented on compactor_scheduler/src/scheduler.rs
> +    async fn get_job(&self) -> Vec<CompactionJob>;
I suggest this be a followon PR, and probably not an immediate one.  I don't think it hurts to let the compactor continue writing its updates to the catalog until we have a reason for the scheduler to do it.

Moving this to the scheduler would shift work from the compactor to the scheduler.  If too much work is shifted over, the scheduler could become a bottleneck as we create more compactors.  I think there is a good chance we'll eventually want this moved to the scheduler, but I'm not certain of that.  So I lean towards postponing the decision until we have a need to.

unless I'm overlooking a reason we need to now?

2023-06-14 19:27 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +    async fn get_job(&self) -> Vec<CompactionJob>;
I think this also gets to the idea of doneness, when leases expire versus pipelining compactions, and whether the scheduler will notify of the catalog of intermediate updates (during pipeline). Which leads us back to the question of the division of responsibilities (scheduler-vs-compactor) for the end state updates.

2023-06-14 21:14 UTC, Joe-Blount approved these changes
LGTM

2023-06-15 15:33 UTC, carols10cents requested changes
Some suggestions that can be resolved with changes or clarification comments :)

2023-06-15 15:33 UTC, carols10cents commented on clap_blocks/src/compactor_scheduler.rs
> +    pub hostname: Option<String>,
I'm not sure, but I _think_ what @crepererum was saying was that this `HOSTNAME` env var shouldn't exist at all? That the shard ID should only come from `INFLUXDB_IOX_COMPACTION_SHARD_ID`?

If that is what Marco means, I think that change can be deferred to a future PR as this PR isn't introducing this behavior, only moving it around-- this is how the compactor works today.

2023-06-15 15:33 UTC, carols10cents commented on generated_types/protos/influxdata/iox/compactor_scheduler/v1/service.proto
> +  repeated CompactionJob compaction_jobs = 1;
Nit, if this service can return multiple compaction jobs, should the rpc API be named `GetJobs` (plural) rather than `GetJob` (singular)?

2023-06-15 15:33 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +        let partitions_source: Arc<dyn PartitionsSource> = match &self.partitions_source_config {
It surprised me that `LocalScheduler` is creating an instance of `Arc<dyn PartitionsSource>` on every call to `get_job`. I would have expected `LocalScheduler` to have a field called `partitions_source` that held the `Arc<dyn PartitionsSource>` instead of the field that holds the `partitions_source_config, and then `get_job` would call `self.partitions_source.fetch()`.

Is there something I'm missing about why this is being done the way it is?

2023-06-15 19:53 UTC, wiedld commented on clap_blocks/src/compactor_scheduler.rs
> +pub enum Error {}
🤦🏼‍♀️  Nice catch. Deleting.

2023-06-15 19:55 UTC, wiedld commented on generated_types/protos/influxdata/iox/compactor_scheduler/v1/service.proto
> +  repeated CompactionJob compaction_jobs = 1;
This terminology is part of a discussion with @Joe-Blount . From my understanding, the canonical terminology is a single job containing multiple tasks -- each task being a partition. Then the compactor can autonomously decide to further break a task into multiple subtasks (a.k.a. pipeline on a partition).

Please feel free to correct any terminology, and/or we can decide to switch it to whatever makes more sense to us?

2023-06-15 20:56 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +        let partitions_source: Arc<dyn PartitionsSource> = match &self.partitions_source_config {
That's definitely the better approach. The partition_source is the same per LocalScheduler (a.k.a. per compactor), so can construct once only --> then repeated fetch().

Change made.

2023-06-15 21:08 UTC, wiedld commented
** TO REVIEWERS:**

Pushed a few commits with changes based on feedback.
Next will be breaking these commits into separate, independent PRs (when/where possible) -- and have continued review based on there.

2023-06-20 16:59 UTC, wiedld commented
Converting this to a draft.
So it's explicit that this PR is not merging. It's merely a source of code/commits being broken up into smaller PRs.

2023-07-10 22:42 UTC, wiedld commented
This code has already been broken up, and merged in separate PRs.

2023-07-10 22:42 UTC, closed without merging