feat: Allow passing service protection limits in create db gRPC call
influxdata/influxdb_iox pull request #7941
Opened 2023-06-06 16:54 UTC by mkmik

Closes #7940

This PR adds a `ServiceProtectionLimits` proto message encapsulating the service protection limits.
It then adds a `service_protection_limits` field in the `CreateNamespaceRequest` proto and the necessary code in the namespace server and client to handle the service protection parameters during creation.

It also adds the CLI flags to the `namespace create` command and tests.

----

Future:

consolidate all uses of the service protection parameters to use that one proto message instead of scattering the bare fields around. Also, there is no real reason to use a `oneof` when updating the fields and we can thus make the create and update API *and* CLI share the same structures by not making update use a mutually-exclusive construct.

2023-06-06 17:54 UTC, domodwyer requested changes
If we need atomic creates with limit setting, we can push the operation down to the catalog level.

I think it's probably "good enough" for most cases to simulate it in the client though? If not, let us know :+1:

I'd prefer we don't change the API in a way that makes currently-atomic operations not atomic if possible.

2023-06-06 17:54 UTC, domodwyer commented on service_grpc_namespace/src/lib.rs
> +
I'm not sure this is the right way to achieve create time limit setting as it's not atomic - the currently exposed API correctly reflects the atomicity of the individual operations.

If this is merged, then the create operation may partially fail - currently it is an atomic operation, which either succeeds or fails entirely. I think this is a good property to preserve! This is no different from wrapping the calls up in a client:


```rust
fn create(name: &str, table_limit: usize, column_limit: usize) -> Result<...> {
    client.create(...)?;
    client.update_table_limit(...)?;
    client.update_namespace_limit(...)?;
}
```

Which allows the behaviour you're after, without impacting the atomicity of the API operations :+1:

2023-06-07 10:30 UTC, mkmik commented on service_grpc_namespace/src/lib.rs
> +
fair enough; I was just lazy. I'm not happy with the current update_* API which requires multiple calls to make changes; I guess the best thing to do is to just bite the bullet and push down the parameters to the namespace repo trait

2023-06-07 11:53 UTC, mkmik commented on service_grpc_namespace/src/lib.rs
> +
moved to `NamespaceRepo::create` impls, PTAL

2023-06-08 09:11 UTC, domodwyer approved these changes
Looking good! Thanks 🙏

2023-06-08 09:11 UTC, domodwyer commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
Can you remove this TODO? I don't think we'd want to _make_ the user specify both at once - if you only want to update one, then you have to fetch the other so you can specify it, and then it becomes a race between reading and writing, when you want to not update that number in the first place, and then you start building version clocks to track causality and then ... you're just updating a number m8 🔥 

I realise there are various different "update mask" and things, but I'm not really sure it's worth the complexity either for our current uses - either way, comments like this just confuse people who come to use it - feel free to make a ticket though :+1:

2023-06-08 09:11 UTC, domodwyer commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +async fn namespace_create_service_limits() {
Nice tests :+1:

2023-06-08 09:15 UTC, savage-engineer approved these changes

2023-06-08 09:15 UTC, savage-engineer commented on iox_catalog/src/postgres.rs
> +    name, topic_id, query_pool_id, retention_period_ns, max_tables, max_columns_per_table, partition_template
👌

2023-06-08 09:38 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
No that's not how I intend to change the update API.

I want the update to accept both fields but allow each field to be optional. If you only want to set one you just pass the value for one field. If you want to set both you pass both. No read+modify

2023-06-08 09:38 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
That said yeah the comment without a ticket is confusing I'll remove jt

2023-06-08 09:47 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
(Just for clarity, field masks are not necessary for scalars. By design protobuf doesn't allow you to distinguish an unset from a default (zero) value.)

2023-06-08 10:13 UTC, domodwyer commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
> I want the update to accept both fields but allow each field to be optional.

I'm hard yes for explicitly optional proto fields - it came up a long time ago, but we decided the answer was universally "never optional". This seems to have changed as of late - I'm all for it :+1:

2023-06-08 10:47 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
The "optional" keyword is just a hint for code generators (e.g. Prost generates an Option<T> for a scalar if it's optional)

The semantics for proto3 (and the wire protocol) are clear: all fields are optional in that it doesn't distinguish an unset value from a set but default/zero value.

2023-06-08 11:23 UTC, domodwyer commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
Optional makes the field "nullable", so that you can see if the default was materialised or a 0 was explicitly set - that's certainly a useful distinction for values that might want to be 0 :+1:

2023-06-08 11:49 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
Except it doesn't work like that. If you pass `Some(0)` you'll read it back as `None`

2023-06-08 11:51 UTC, domodwyer commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
That's not what the docs suggest: https://protobuf.dev/programming-guides/proto3/#field-labels

2023-06-08 12:21 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
Ah I keep forgetting the recent experimental support for optional scalars: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.1.4

Anyway even better if we can deal with 0 (although in our case both fields are meant to be non-zero anyway)

2023-06-08 12:26 UTC, mkmik commented on generated_types/protos/influxdata/iox/namespace/v1/service.proto
> +  // TODO: consider deprecating this and switching to ServiceProtectionLimits.
Ah I keep forgetting the recent experimental support for optional scalars: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.1.4

Anyway even better if we can deal with 0 (although in our case both fields are meant to be non-zero anyway)

2023-06-08 14:28 UTC, merged