feat: bound partition key size
influxdata/influxdb_iox pull request #7961
Opened 2023-06-09 11:49 UTC by domodwyer

This PR bounds both the individual parts within a partition key, and the number of parts allowed in a key - this effectively bounds the overall size of the key to 1,607 bytes (1.57 KiB).

The reversal function that reconstructs the tag column values from the partition key now emits a tuple of `(column_name, column_value_enum)` which encodes the valid operations (equality/prefix-match) into the type system.

Closes #7900.

---

* feat: truncate partition key parts at 200 bytes (050093df1)
      
      This commit ensures all partition key parts are less than or equal to
      200 bytes long.
      
      If a string exceeds the 200 byte limit, it is truncated (avoiding
      splitting unicode code-points or graphemes) and then a single "#"
      sentinel value is appended. When reversed from the string, these column
      values are indicated to be suitable for prefix-matching only - a
      property that is encoded into the type system.
      
      This commit takes a conservative approach of not splitting graphemes as
      outlined in the module documentation, but this could be relaxed in the
      future if needed.

* refactor: expose partition part count (39c22a2c2)
      
      Allow a table template override to report the number of template parts
      within it.
      
      This ignores the lint wanting an "is_empty()" method too, because it's
      misleading and redundant - a template MUST never be empty.

* feat: restrict partition template length (fc49b3ec1)
      
      Partition templates should not contain more than 8 parts, which when
      combined with a per-part byte limit, bounds the maximum size of a
      partition key.
      
      This commit causes the router to refuse to service a write request that
      contains > 8 parts in the template - this causes a panic, as it's a
      broken system invariant and should be an unreachable state. Templates
      are pre-validated at creation time to contain no more than 8 parts, and
      are immutable:
      
          https://github.com/influxdata/influxdb_iox/pull/7930

2023-06-09 11:56 UTC, domodwyer commented on data_types/src/partition_template.rs
> +//!
This block describes how partition key part truncation is applied, particularly the considerations made for unicode strings.

TL;DR: a truncated value is at most 200 bytes long, but has a variable length below that - it's possible to see a truncated value that is 195 bytes long. This is an implementation detail and encoded into the type system; the user of these types is not expected to make any special effort with these truncated strings.

2023-06-09 11:56 UTC, domodwyer commented on data_types/src/partition_template.rs
> +}
A rebuilt column value is now emitted wrapped in this enum.

2023-06-09 11:56 UTC, domodwyer commented on data_types/src/partition_template.rs
> +}
This type can only be used for equality matching of strings when it is the "identity" variant...

2023-06-09 11:56 UTC, domodwyer commented on data_types/src/partition_template.rs
> +    }
...however both variants can be used to prefix-match against a string.

2023-06-09 11:56 UTC, domodwyer commented on mutable_batch/src/payload/partition.rs
> +        }
This is the truncation logic, which accounts for both unicode code-points and graphemes when splitting.

This encoding is optimised for <200 character values, expecting >200 character values to be the unusual case.

2023-06-12 09:59 UTC, savage-engineer approved these changes
🎩

2023-06-12 14:35 UTC, carols10cents requested changes
A bunch of nits; I'd definitely like to see the `len` method changed or its documentation changed before merging.

2023-06-12 14:35 UTC, carols10cents commented on data_types/src/partition_template.rs
> +        want = [("a", prefix("(ノಠ益ಠ)ノ彡┻━┻"))]
😹

2023-06-12 14:35 UTC, carols10cents commented on mutable_batch/src/payload/partition.rs
> +                    ColumnValue::Prefix(_) => assert!(got.1.is_prefix_match_of(&want.1), "prefix mismatch"),
Thinking about debugging these tests if they fail, for the two `assert!`s here it'd be nice if the args to `is_prefix_match_of` were included in the failure message, something like:

```suggestion
                        assert!(got.1.is_prefix_match_of(&want.1), "prefix mismatch; {} is not a prefix of {}", got.1, want.1);
                    },
                    ColumnValue::Prefix(_) => assert!(got.1.is_prefix_match_of(&want.1), "prefix mismatch; {} is not a prefix of {}", got.1, want.1),
```

2023-06-12 14:35 UTC, carols10cents commented on data_types/src/partition_template.rs
> +
As written, this function *will* currently return 0 in this case (this test currently passes):

```
    #[test]
    fn table_partition_template_none() {
        let ns = NamespacePartitionTemplateOverride::default();
        let t = TablePartitionTemplateOverride::try_new(None, &ns).unwrap();

        assert_eq!(t.len(), 0);
    }
```

Which seems to contradict the comment "there must always be >0 parts"?

If `len` instead uses `parts`, then it will get the default partition template and indeed never return 0 (at the cost of iterating through all the parts):

```suggestion
    /// Returns the number of parts in this template.
    #[allow(clippy::len_without_is_empty)] // Senseless - there must always be >0 parts.
    pub fn len(&self) -> usize {
        self.parts().count()
    }
```

That is, the test that will pass now is:

```
    #[test]
    fn table_partition_template_none() {
        let ns = NamespacePartitionTemplateOverride::default();
        let t = TablePartitionTemplateOverride::try_new(None, &ns).unwrap();

        assert_eq!(t.len(), 1);
    }
```

because the hardcoded default template has 1 part.

I see the `len` method is only used to check the invariant of the upper bound of number of parts, so I'm not sure how important this is. If you want to keep the code the way it is, then I think this case/assumption should be documented at least?

2023-06-12 14:35 UTC, carols10cents commented on mutable_batch/src/payload/partition.rs
> +            "partition template contains {}, which exceeds the maximum of {}",
For clarity for the person theoretically getting paged over this, I'd change the message to include the word "parts" so that someone doesn't start wondering why a literal 9 isn't allowed in a partition template:

```suggestion
            "partition template contains {} parts, which exceeds the maximum of {} parts",
```

2023-06-12 15:37 UTC, domodwyer commented on data_types/src/partition_template.rs
> +                );
I like it!

2023-06-12 15:39 UTC, domodwyer commented on mutable_batch/src/payload/partition.rs
> +                let got = &reversed[idx];
I like it too! Indexing I think will always add an implicit range check too (unless it can be proven to exist some other way), so this will probably be faster too!

2023-06-12 16:22 UTC, carols10cents approved these changes

2023-06-12 16:23 UTC, carols10cents commented
I fixed all my issues with this PR, but @domodwyer should review the commits I added before merging :)

2023-06-13 13:02 UTC, domodwyer commented
Thank you @carols10cents! Super helpful 🙏

2023-06-13 13:08 UTC, merged