WIP trying only changing the partition table/type
influxdata/influxdb_iox pull request #7963
Opened 2023-06-09 20:24 UTC by carols10cents

2023-06-16 16:46 UTC, carols10cents commented on arrow_util/src/test_util.rs
> +    Lazy::new(|| Regex::new(r#"[0-9]+/[0-9]+/[0-9a-f]+/"#).expect("directory regex"));
There are 2 regexes in this PR that needed to be updated and that took me a while to figure out; I've opened https://github.com/influxdata/influxdb_iox/issues/8017 for consolidating those to one place.

2023-06-16 16:46 UTC, carols10cents commented on querier/src/cache/parquet_file.rs
> +        let two_file_size = 384;
These sizes are the memory used in the cache for the `ParquetFile` instances, which now have an extra field containing `Option<PartitionHashId>`.

2023-06-16 16:46 UTC, carols10cents commented on test_helpers_end_to_end/src/snapshot_comparison.rs
> +    Lazy::new(|| Regex::new(r#"([0-9]+)/([0-9]+)/([0-9a-f]{64})"#).expect("directory regex"));
This regex was actually incorrect, and was only grabbing the first character in each path part. Thus each capture group was length 1, and the replace below would always replace `15/232/5` with `1/1/1`.

I want to unify this with the other regex in arrow_util which does that replacement purposefully (as opposed to by coincidence with a bug here).

2023-06-21 10:41 UTC, domodwyer requested changes
So to summarise the effect of this change:

* Newly created partitions will have a hash ID in addition to their autoinc-assigned catalog row ID
* Old partitions existing before this merge will have only the latter
* These two cases will always be true - an old partition will never gain a hash ID, and a new one will never lose it
* The catalog will always address by row ID as the foreign key
* New partitions upload to an object store path that includes the hash ID instead of the row ID
* The ingester sends the hash ID in query responses (for new partitions with it only)
* Queries will continue on the hot path, as we need to know if a partition is one of the "old" or "new" varieties described above

Is the latter point the only reason we need to keep the queries on the hot path? What if we built a bloom filter at startup that contained every "old" partition, so we would very quickly only have to query for partitions when we see a false positive? We should be able to remove ~99% of queries that way without too much memory use once the workload shifts to new partitions (a day later).

We'd have to be smart about adding a bloom filter - we'd need to deploy this PR everywhere, then later deploy the bloom filter, to ensure there's no race with new partitions in the "old" style being added by another ingester after the local ingester build "the list" of old style partitions - we can only use a local cached list once we're certain no more "old style" partitions will be added.

Need to double check the INSERT query :+1:

2023-06-21 10:41 UTC, domodwyer commented on data_types/src/partition.rs
> +    pub fn new(
I think this could be annotated with `#[cfg(test)]`? A valid `Partition` instance should only ever come via the catalog's `create_or_get()` method right? It looks like all calls to this are probably in test code.

That way this shouldn't be possible:

```rust
// I need a partition to upload this file, and I have all the bits laying around 
// at hand already, so be a super optimiser and don't do a catalog query.
let p = Partition::new(id, table_id, etc...);
upload_file(file, p);
```

Where for "old" partitions with the autoinc ID, the above would put the file in the wrong place.

I think it's unlikely, but annotating the constructor takes it out the game entirely :+1:

2023-06-21 10:41 UTC, domodwyer commented on data_types/src/partition.rs
> +    fn display_partition_hash_id_in_hex() {
```suggestion
    /// A fixture test asserting the deterministic partition ID generation
    /// algorithm outputs a fixed value, preventing accidental changes to the
    /// derived ID.
    /// 
    /// This hash byte value MUST NOT change for the lifetime of a cluster
    /// (though the encoding used in this test can).
    #[test]
    fn display_partition_hash_id_in_hex() {
```

2023-06-21 10:41 UTC, domodwyer commented on data_types/src/partition.rs
> +    }
I love it!

2023-06-21 10:41 UTC, domodwyer commented on data_types/src/partition.rs
> +            let partition_hash_id = PartitionHashId::new(table_id, &partition_key);
How about throwing this in:

```suggestion
            let partition_hash_id = PartitionHashId::new(table_id, &partition_key);
            
            // ID generation MUST be deterministic.
            {
                let partition_hash_id2 = PartitionHashId::new(table_id, &partition_key);
                assert_eq!(partition_hash_id, partition_hash_id2);
            }
```

If you're feeling spicy, you _could_ also do:

```rust
// ID generation MUST be collision resistant; different inputs -> different IDs
{
    let other_table_id = TableId::new(table_id.get().wrapping_add(1));
    let partition_hash_id3 = PartitionHashId::new(other_table_id, &partition_key);
    assert_ne!(partition_hash_id, partition_hash_id3);
}
```

Which whilst being a useful property assert of its own, also ensures we're not just returning `bananas` as every ID.

2023-06-21 10:41 UTC, domodwyer commented on ingester/src/buffer_tree/partition/resolver/cache.rs
> +            HashMap::<PartitionKey, HashMap<TableId, (PartitionId, Option<PartitionHashId>)>>::new(
Could you add the byte size of the new hash ID to the maths in the description type?

2023-06-21 10:41 UTC, domodwyer commented on ingester/src/buffer_tree/partition/resolver/cache.rs
> +    entries: Mutex<HashMap<PartitionKey, HashMap<TableId, (PartitionId, Option<PartitionHashId>)>>>,
So we have to store this hash because we need to know of the _presence_ of this value in the catalog record right? So that old, cached partitions without the hash don't suddenly have a hash when read from this cache.

Otherwise we could re-compute it on the fly and pay no memory overhead. We could store a bool instead of the full hash, but I think it's probably overkill...

2023-06-21 10:41 UTC, domodwyer commented on iox_catalog/migrations/20230417173102_deterministic_partition_id.sql
> +  ADD COLUMN hash_id bytea;
Having raw bytes in the catalog is going to be annoying when looking for specific partitions by ID, but I think the overhead of a string representation is too much... We'll just have to SELECT with a hex representation or something :+1:

2023-06-21 10:41 UTC, domodwyer commented on iox_catalog/src/postgres.rs
> +    shard_id, table_id, partition_id, partition_hash_id, object_store_id, min_time, max_time,
This `INSERT` still references `partition_hash_id` - there's 14 column names, but only 13 bound vars - there's no `partition_hash_id` bound - something is amiss!

It's very strange it's not accepting an `Option<T>` as nullable? Is that why we need this duplication?

2023-06-21 10:41 UTC, domodwyer commented on iox_catalog/src/sqlite.rs
> +        if let Some(hash_id) = value.hash_id.as_ref() {
Nice check :+1:

2023-06-21 14:09 UTC, carols10cents commented
>   -  Queries will continue on the hot path, as we need to know if a partition is one of the "old" or "new" varieties described above
> 
> Is the latter point the only reason we need to keep the queries on the hot path? What if we built a bloom filter at startup that contained every "old" partition, so we would very quickly only have to query for partitions when we see a false positive? We should be able to remove ~99% of queries that way without too much memory use once the workload shifts to new partitions (a day later).
> 
> We'd have to be smart about adding a bloom filter - we'd need to deploy this PR everywhere, then later deploy the bloom filter, to ensure there's no race with new partitions in the "old" style being added by another ingester after the local ingester build "the list" of old style partitions - we can only use a local cached list once we're certain no more "old style" partitions will be added.

I'm still paging all this back into my brain, so I might misremember some things.

I *think* the reason we need the catalog queries in the ingester is to know whether we're ingesting data that goes with an "old" variety partition, because when a querier needs to collate Parquet files for that partition with ingester in-memory data for that partition, it needs to get the sequential database partition ID from the ingester with the data to be able to match that data with the catalog record that doesn't have a partition hash ID.

I think there could also be cases of incorrect query results during the deploy if the ingesters and queriers get the new code at different times. Say this happens:

- an ingester gets the new code and starts inserting partitions into the catalog with hash ids
- a querier still running the old code refreshes its catalog cache, but doesn't even know to ask for for hash ids in its catalog queries, so it has no way to match up new partitions using hash IDs, so the ingester needs to continue sending the database ids (hmm, i think this means it won't be able to find Parquet files for these partitions either? is this a problem, or should it be a short-lived scenario?)

Could you spell out for me what data you're thinking goes in the bloom filter, exactly, while I check wikipedia to remind myself what a bloom filter is? 😅 Also what do you mean by "false positive" in this context?

2023-06-21 14:16 UTC, carols10cents commented on ingester/src/buffer_tree/partition/resolver/cache.rs
> +    entries: Mutex<HashMap<PartitionKey, HashMap<TableId, (PartitionId, Option<PartitionHashId>)>>>,
Yep, exactly!

2023-06-21 14:43 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +    shard_id, table_id, partition_id, partition_hash_id, object_store_id, min_time, max_time,
Oops. Yeah the tests are probably not covering adding new parquet files to old-style partitions... I should fix that.

When I try to insert an `Option<T>`, I get:

```
error[E0277]: the trait bound `std::option::Option<PartitionHashId>: Encode<'_, _>` is not satisfied
    --> iox_catalog/src/postgres.rs:1581:15
     |
1581 |         .bind(partition_hash_id) // $4
     |          ---- ^^^^^^^^^^^^^^^^^ the trait `Encode<'_, _>` is not implemented for `std::option::Option<PartitionHashId>``
```

and I can't just go implement that because orphan rule. 



WAIITTTTTT i think this is because I've only implemented `Encode` for `&PartitionHashId` and this has `Option<PartitionHashId>` and sqlx only implements `Encode` for `Option<T: Encode>` hmmmmmmmmmmmm trying to fix this....

2023-06-21 17:36 UTC, carols10cents commented on data_types/src/partition.rs
> +    pub fn new(
Ok, I decided to change `new` to be called `new_in_memory_only` (used by the in-memory catalog and tests) and also added a function `new_with_hash_id_from_sqlite_catalog_only` used by the sqlite catalog, which used to use `new` and get an instance with a hash ID even if the database returned a partition without a hash ID. See what you think!

2023-06-21 18:13 UTC, carols10cents commented
@domodwyer I think this is ready for re-review! 5 new commits on the end for you.

2023-06-22 12:29 UTC, domodwyer commented on data_types/src/partition.rs
> +    pub fn new(
Ahh makes sense - I didn't spot that with a quick `rg` - thank you for the scary names 🙏

2023-06-22 12:33 UTC, domodwyer approved these changes
Perfect! 🎉

2023-06-22 12:33 UTC, domodwyer commented on iox_catalog/src/postgres.rs
> +    .bind(partition_hash_id_ref) // $4
I'm glad you managed to get it working! Much easier to work with 🙏

2023-06-22 12:33 UTC, domodwyer commented on iox_catalog/src/postgres.rs
> +        assert!(parquet_file.partition_hash_id.is_none());
This is the additional testing that would have caught the [`INSERT` column mismatch](https://github.com/influxdata/influxdb_iox/pull/7963#discussion_r1236772481) right?

2023-06-22 12:49 UTC, domodwyer commented
> I think there could also be cases of incorrect query results during the deploy

Sounds legit - however I think that the new ingesters will deploy, and there will be a (big enough) gap before they start persisting new partitions - during this time, the queriers should deploy and by the time persistence happens, they'll be speaking hash IDs so should be able to find the files.

It's a great call! Definitely worth thinking about up front - I think we should be OK?


> I think the reason we need the catalog queries in the ingester is to know whether we're ingesting data that goes with an "old" variety partition, because when a querier needs to collate Parquet files for that partition with ingester in-memory data for that partition, it needs to get the sequential database partition ID from the ingester with the data to be able to match that data with the catalog record that doesn't have a partition hash ID.

Yeah that makes sense - I think we can use the bloom filter trick then!

A bloom filter is just a magical memory efficient set - you can put things into it, and later ask it "is this thing in the set?".

When asked, it can answer "definitely not" or "maybe" - the key is the definitely not is always correct, and the "maybe" has a high probability of being "yes", and a low probability of being "I said maybe but it actually isn't soz".

So we can use this to eliminate most queries for new partitions, so the pessimistic approach is to query for every partition in the hot path:

* Write comes into ingester
* This ingester hasn't seen this partition before
* Ingester does a catalog query to find out if it is new/old
  * If old: use partition row ID
  * If new: `hash(table, namespace)` and use that for the ID

Instead if we build a bloom filter containing the generated hash ID of all old partitions (that don't have hash IDs in the catalog!), then we can do this:


* Write comes into ingester
* This ingester hasn't seen this partition before
* Ingester generates `hash(table, namespace)` as the hash ID
* Look up hash ID in the bloom filter
  * Answer: definitely not - it's definitely a new-style partition, use the hash ID!
  * Answer: maybe - do a query to check if it is old/new like the pessimistic approach

The trick is to configure the bloom filter so that it has a low probability of answering "maybe". For example, if we construct it such that it has a 1% chance of saying "maybe" when the answer should be "definitely not", then we stop doing queries for 99% of new partitions. We wind up doing queries for all old partitions + the 1% false positive rate.

This will let us immediately chop out almost all unnecessary queries, and quickly move towards almost no queries at all once the workload shifts to writing new-style partitions after the midnight rollover (using the above numbers, and ignoring "backfill" / writes to days-old partitions, we'd be doing ~1% of the queries we do today).

I think we should pursue this for the reasons outlined in the design document - I'm happy to do help with this too :+1:

2023-06-22 13:06 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +        assert!(parquet_file.partition_hash_id.is_none());
Yup!

2023-06-22 13:08 UTC, merged