feat(garbage-collector): batch parquet existence checks to catalog
influxdata/influxdb_iox pull request #7964
Opened 2023-06-09 21:13 UTC by philjb

---

    feat(garbage-collector): batch parquet existence checks to catalog
    
    The core feature of this PR is batching the existence checks of parquet
    files in object store against the catalog. Before, there was 1 catalog
    query per each parquet file in object store. This can be a lot of
    requests.
    
    This PR can perform one query of at most 100 parquet file uuids against
    the catalog in one query. A hundred seems like a decent starting place.
    
    The batch may not reach 100 because there is also a timeout on receiving
    object store meta objects from the object store lister thread. That
    timeout is set to 100 milliseconds. If more than 100 are received, they
    are batched into 100 for the catalog.
    
    Additionally, this PR includes surrounding code changes to make it more
    idiomatic (but not perfect). It follows up some suggested work from
     #7652 for watching for shutdown on the threads.
    
* fixes #7784

2023-06-09 21:13 UTC, philjb commented on compactor/src/components/skipped_compactions_source/mod.rs
> +    /// Get skipped partition record for a given partition
driveby

2023-06-09 21:14 UTC, philjb commented on garbage_collector/src/lib.rs
> +            select! {
Like what was done over here but not for all the spawned threads yet. (I haven't forgotten!)

https://github.com/influxdata/influxdb_iox/pull/7652/files#r1179156749

2023-06-09 21:16 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +const RECEIVE_TIMEOUT_MS: u64 = 100; // This may not be long enough to collect many objects.
These values are guess...

I don't see any metrics registry in the garbage collector or at least I don't know where to find it to see how these numbers will work out - phase 2 I guess.

2023-06-09 21:17 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +                timedout = true;
Is there another idiom that is clearer for this sort of scenario?

2023-06-09 21:35 UTC, Joe-Blount commented on garbage_collector/src/objectstore/checker.rs
> +const RECEIVE_TIMEOUT_MS: u64 = 100; // This may not be long enough to collect many objects.
I like these values as a starting place.  Specifically, I like having both criteria.  

To me, this works out to:
// group everything you can for 100ms, because that's not so much of a delay that it would cause issues,
// but if you manage to get a huge number of file ids, stop accumulating at 100.

We may tweak the numbers, but that sentiment feels reasonable for how to think about them.

2023-06-12 09:27 UTC, crepererum requested changes

2023-06-12 09:27 UTC, crepererum commented on data_types/src/lib.rs
> +#[derive(Debug, Copy, Clone, PartialEq, Eq, sqlx::FromRow)]
If you only need this for the PG impl, this should to to `iox_catalog::postgres`.

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
> +const RECEIVE_TIMEOUT_MS: u64 = 100; // This may not be long enough to collect many objects.
Instead of `_MS: u64`, I think this should be `: Duration`. `Duration::from_millis` is `const` and can be used to create constants.

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
>  pub(crate) async fn perform(
If you don't wanna deal with the `select!` and the actual impl. in one method, you can also pull the actual code into its own method (e.g. `perform_impl`) and ahve the `perform` just call the `select!` macro and the impl method.

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
> +                timedout = true;
Yes:

```rust
let timeout = match maybe_item {
    Ok(res) => {
        ...
        false
    }
    Err(_) => {
        true
    }
};
```

or

```rust
let timeout = maybe_item.is_err();
```

(`is_err` is not consuming)

2023-06-12 09:27 UTC, crepererum commented on iox_catalog/src/postgres.rs
> +    async fn exists_by_object_store_id_batch(
Can we just make the `exists_by_object_store_id` batched and not add yet another method? I think the non-batch method is only used by tests and they can easily use a 1-batch.

Also your new interface is not covered by a test (should be done in `interface.rs`, there are generic tests).

Also I think the method should just return a `ParquetFileID` or something, not a struct w/ a single element (this is just an implementation detail of the SQL wrapper).

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
> +        .filter(|c| !present_in_catalog.iter().any(|existing| *existing == c.0))
`O(n^2)`? Maybe make `present_in_catalog` a `HashSet`.

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
> +    // to_delete is the vector we will return to the caller containing ObjectMeta we think should be deleted.
I'm not a big fan of mutable state since it is hard to follow and a pain to refactor. It's not a blocker for this PR, but if I may suggest a slightly more Rusty way (half pseudo-code):


```rust
let (to_delete, to_check_in_catalog): (Vec<_>, Vec<_>) = items.into_iter()
  .filter(/* cutoff filter */)
  .filter(/* file suffix filter */)
  .partition(/* three-state if block starting w/ `if let Some(uuid) = file_name.unwrap()...` */);
```

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
> +    let mut present_in_catalog = Vec::with_capacity(to_check_in_catalog.len());
Similar to my mutable state comment above, for futures:

```rust
let present_in_catalog: HashSet<_> = futures::stream::iter(to_check_in_catalog.chunks(CATALOG_BATCH_SIZE))
    .then(|...| async move {})
    .flat_map(|ids| futures::stream::iter(ids))
    .collect()
    .await;
```

2023-06-12 09:27 UTC, crepererum commented on garbage_collector/src/objectstore/checker.rs
> +            Err(e) => {
I think this is wrong: if you have a catalog error (maybe IO?) then you just treat the whole batch as absent and wipe it? Like whenever you loose the connection to PG for a short while you delete the file?

2023-06-12 16:19 UTC, philjb commented on data_types/src/lib.rs
> +#[derive(Debug, Copy, Clone, PartialEq, Eq, sqlx::FromRow)]
> need this

Which is this? The derive? A part of the derive?

2023-06-12 16:21 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +const RECEIVE_TIMEOUT_MS: u64 = 100; // This may not be long enough to collect many objects.
done.

2023-06-12 16:22 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
>  pub(crate) async fn perform(
good point. I pulled the select up a layer where i think it wants to be anyway.

2023-06-12 16:26 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +                timedout = true;
thanks!

2023-06-12 16:45 UTC, crepererum commented on data_types/src/lib.rs
> +#[derive(Debug, Copy, Clone, PartialEq, Eq, sqlx::FromRow)]
The entire type. See my other comment: I think the affected catalog method should not contain the struct but the plain ID.

2023-06-12 16:49 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +        .filter(|c| !present_in_catalog.iter().any(|existing| *existing == c.0))
good call. thanks.

` .filter(|c| !present_in_catalog.contains(&c.0))`

2023-06-12 17:19 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +            Err(e) => {
yup - you're right. I'll see about adding the missing test for the negative/failure path.

2023-06-12 20:35 UTC, carols10cents commented on garbage_collector/src/lib.rs
> -        let checker_perform =  async || {
Unfortunately async closures are unstable :(

2023-06-12 20:43 UTC, carols10cents commented on garbage_collector/src/objectstore/checker.rs
> +    impl ParquetFileRepo for MockParquetFileRepo {
I wanted to make sure this actually worked, so I started a trait impl for you... but I did leave all the unused parameter warnings as an exercise for the reader ;)

2023-06-13 01:00 UTC, philjb commented on iox_catalog/src/sqlite.rs
> +            .map(|id| format!("uuid_blob('{}')", id.hyphenated()))
this works for me in `sqlite3` cli but doesn't in the tests, saying the function does not exist.

```
called `Result::unwrap()` on an `Err` value: SqlxError { source: Database(SqliteError { code: 1, message: "no such function: uuid_blob" }) }
thread 'sqlite::tests::test_catalog' panicked at 'called `Result::unwrap()` on an `Err` value: SqlxError { source: Database(SqliteError { code: 1, message: "no such function: uuid_blob" }) }', iox_catalog/src/interface.rs:2167:14
stack backtrace:
```

I know that there needs to be some conversion of the string to the uuid blob type. Since I can't use binding that was doing this previously, I'm not sure how for sqlite (or sql in general) I can specify the type I want sqlite to interpret the string as. I also got `uuid_str(object_store_id)` in the where clause to work as well in the cli. I suspect that is the slower method (convert all objectstoreids to strings first).

2023-06-13 01:02 UTC, philjb commented on iox_catalog/src/postgres.rs
> +    async fn exists_by_object_store_id_batch(
> Can we just make the exists_by_object_store_id batched and not add yet another method? I think the non-batch method is only used by tests and they can easily use a 1-batch.

Yes. done.

> Also your new interface is not covered by a test (should be done in interface.rs, there are generic tests).

Yes. done. But I'm struggling to get the uuid casted/converted for sqlite.

> Also I think the method should just return a ParquetFileID or something, not a struct w/ a single element (this is just an implementation detail of the SQL wrapper).

It needs to return the object_store_id because that's what I have. Instead of the struct, just a Vec<Uuid> should be ok. I will convert.

2023-06-13 01:04 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +    // to_delete is the vector we will return to the caller containing ObjectMeta we think should be deleted.
That's fair. I first tried to do it with the fluet filtering and mapping but couldn't manage it and switched to what you see here. I didn't know about `partition` so perhaps I will try again after this pr to get it back into that style.

2023-06-13 01:04 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +            Err(e) => {
test added.

2023-06-13 08:37 UTC, crepererum commented on iox_catalog/src/sqlite.rs
> +            .map(|id| format!("uuid_blob('{}')", id.hyphenated()))
We're not really using the latest sqlite:

https://github.com/influxdata/influxdb_iox/blob/614ff35998623026bd78b682dbce79827942e639/Cargo.lock#L3370-L3372

We cannot upgrade it due to sqlx (the abstraction layer that we use) has a somewhat messed up release policy.

2023-06-13 16:52 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> -        tokio::select! {
pulled up above `checker:: perform` - see earlier comment.

2023-06-13 17:42 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +const RECEIVE_TIMEOUT_MS: u64 = 100; // This may not be long enough to collect many objects.
added into a comment.

2023-06-13 17:42 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +                timedout = true;
done.

2023-06-13 17:59 UTC, philjb commented on data_types/src/lib.rs
> +#[derive(Debug, Copy, Clone, PartialEq, Eq, sqlx::FromRow)]
removed the struct type, switching to an explicit map (instead of leveraging FromRow)

2023-06-13 23:31 UTC, philjb commented on iox_catalog/src/sqlite.rs
> +            .map(|id| format!("uuid_blob('{}')", id.hyphenated()))
addressed this with the sqlite blob literal syntax: https://www.sqlite.org/lang_expr.html#literal_values_constants_

BLOB literals are string literals containing hexadecimal data and preceded by a single "x" or "X" character. Example: X'53514C697465'

2023-06-13 23:31 UTC, philjb commented on data_types/src/lib.rs
> -pub struct ParquetFileExists {
This was for the non-batching sql query version, which has been removed.

2023-06-13 23:33 UTC, philjb commented on garbage_collector/src/objectstore/checker.rs
> +    impl ParquetFileRepo for MockParquetFileRepo<'_> {
thanks to @carols10cents!

2023-06-14 07:58 UTC, crepererum approved these changes
As agreed in the comments, further clean-ups CAN be done in future PRs. Let's ship it!

2023-06-14 10:47 UTC, domodwyer approved these changes
Love it! Thanks for getting this in! 🙏

2023-06-14 14:59 UTC, merged