chore(catalog): Remove kafkaless transition tables and columns
influxdata/influxdb_iox pull request #8001
Opened 2023-06-15 11:00 UTC by savage-engineer

This PR removes the catalog code for the kafkaless transition, as well as including migrations to remove the various tables and columns associated with it. This should close #6217.

---

* chore(catalog): Remove unused parquet file indices from sqlite as well (43d50179d)

      These indexes were previously removed for Postgres in #7859 and #7905.
      They reference a Kafka IOx columns so should be removed from SQLite as
      well in order to have both schema migrate.

* chore(catalog): Remove kafkaless transition tables and columns (1c35c63b4)

      IOx has been Kafkaless for a while now and there's not any benefit for
      keeping around this transitionary table and all the workarounds. This
      simplifies the catalog layout. This adds a migration for both Postgres
      and SQLite, although the SQLite migration is a bit painful due to lack
      of support for many `ALTER TABLE` queries.

2023-06-21 12:05 UTC, domodwyer requested changes
This is a very tricky thing to take on and orchestrate!

Changes to the catalog (especially non-additive changes) are _tricky_ because they run within a live cluster, so stuff like this pops up!

2023-06-21 12:05 UTC, domodwyer commented on iox_catalog/migrations/20230614133225_complete_kafkaless_transition.sql
> +DROP SEQUENCE IF EXISTS query_pool_id_seq, sequencer_id_seq, sharding_rule_override_id_seq, kafka_topic_id_seq;
I think we're going to have to be a little more nuanced about this - as is, I think the following will happen:

* PR merges, image built
* Deploy starts
* First router is removed from the pool
* Replacement starts up and runs this migration
* All N other IOx pods suddenly can't do anything with the catalog, because they're running old code and doing queries like `SELECT ..., query_pool_id FROM ...` and now that column doesn't exist so it errors
* Rollout stops, because some pods crash
* Wedge! All clusters get stuck, panic ensues, confusion masses, the world economy collapses, 🥔 is awarded

I admit I might have gone a bit hyperbolic in that last bit, I would expect only a few operations/services to be affected, but it's definitely A Bit Bad(tm).

---

Instead I think we'll probably have to do the following:

* PR 1: Make all columns NULL-able or set sensible default values
* PR 2: Remove the columns from queries/data types (so now in the catalog they're always NULL/default value)
* PR 3: Drop foreign key constraints
* PR 4: Drop everything else? Perhaps can be in 3.

PR 1 will involve investigating what foreign key constraints are in place, and what is needed to satisfy the requirements. Maybe we have to drop the FK first. I can help look into this if I can dig out a little time - we could do it together!

First though, reproduce the problem so we can be somewhat confident we worked around it:

* Stand up a pair of routers + an ingester running code from master
* Send a bunch of writes, make sure the ingester is configured to persist files somewhat frequently (10s is decent for local tests)
* Build code from this PR, stop one router, start this one (running the migrations via `influxdb_iox catalog setup` which is always run first before the main command in k8s)
* Write some data for a new namespace via the old (master branch) router

I'd expect the write to go error when the router tries to create the new namespace, because it will try to set the topic & query pool IDs. There's similar problems with the ingester persisting and writing to the `parquet` table, etc.

Unfortunately there's no good way to reliably drive this in a test that I can think of, except for smoke tests in a staging environment (@jacobmarble)

2023-06-21 13:46 UTC, savage-engineer commented on iox_catalog/migrations/20230614133225_complete_kafkaless_transition.sql
> +DROP SEQUENCE IF EXISTS query_pool_id_seq, sequencer_id_seq, sharding_rule_override_id_seq, kafka_topic_id_seq;
Hmm I see. Alright, I'll give that scenario a test whirl!

2023-06-22 11:53 UTC, savage-engineer commented
Closing this PR in order to do the change more piecemeal.

2023-06-22 11:53 UTC, closed without merging