refactor: restore partition key generation dedupe
influxdata/influxdb_iox pull request #8003
Opened 2023-06-15 14:34 UTC by domodwyer

This restores #7953, now containing a fix (2acbaefa1) to an issue causing a limited number of rows to be partitioned incorrectly as described in influxdata/idpe#17765.

I also added a few extra tests (in addition to the reproducer) and added a bit of defensive checking to a code path that currently can't be reached - it's better to be robust!

---

* revert: revert: "Merge pull request #7953 from influxdata/dom/partition-key-dedupe" (df88b542f)
      
      This reverts commit 3c0388fdea805a6794a52b1a1844ae712fb06bf3.

* fix: correct dedupe of strftime values (2acbaefa1)
      
      This fixes the root cause of influxdata/idpe#17765; the code was
      performing a "is this the last value you saw" check by comparing it to
      the last generated partition key which is not the same thing - a cache
      hit would not generate a new key, and therefore would not return the
      correct answer after.
      
      The end result is that for a subset of writes with a problematic
      sequence of timestamps would cause the wrong partition key to be
      assigned. Because all users are using the default YYYY-MM-DD
      partitioning scheme, the impact was relatively low, as most of the time
      that partition key had the same YYYY-MM-DD representation as the last.

* test: stftime integration (018bf7962)
      
      This property test generates randomised inputs and validates that all
      rows with the ranges emitted by the partitioner render to the expected
      timestamp-derived partition key when using a known-good implementation.
      
      This includes generating timestamps that bypass the YYYY-MM-DD precision
      reduction optimisation to increase coverage of cache miss code paths.

* test: router partition handler (5388e4973)
      
      Asserts the partitioning code within the router (that drives the
      low-level partitioning logic) generates partitions with rows with
      timestamps that belong in those partitions.

* chore: update hakari (8f0088ab2)
      
      Update workspace hack.

* fix: clean up buffer after error (b28a65c37)
      
      When rendering a timestamp fails, remove the "timestamp -> generated
      key" mapping from the cache.
      
      I'm certain this is impossible to reach for multiple reasons, but it
      should do the right thing anyway, in case those reasons change.

2023-06-15 15:45 UTC, carols10cents commented
So I reverted the "fix: correct dedupe of strftime values" commit and ran the prop tests added in the other commits, and they all passed, I think because they're _too random_. The bug only occurred when there were times that went in the same partition interspersed with times that went to a different partition, which is the common case in the data.

Can we insert some repeats and shuffles in the proptest generated data to get coverage of that scenario?

2023-06-15 15:46 UTC, carols10cents requested changes
Should have made my comment a review; I'd like to make sure we're covering this case with the proptests by making sure they fail without the fix

2023-06-16 10:21 UTC, domodwyer commented
Yeah these were the tests I was fuzzing with to try and find the problem black-box style - they failed miserably! I included them because they were already wrote really, knowing they weren't finding this specific problem. You're spot on though - it's the pure _randomness_ of random numbers that's hobbling it.

I've changed the timestamp input generation from pure random, to something that more accurately models the distribution of timestamps found in real-world requests like you suggest - it hit the bug first run! Thanks for the suggestion! It'll be a much better safety net now.

2023-06-16 14:47 UTC, carols10cents commented on mutable_batch/src/payload/partition.rs
> +        proptest::collection::vec(arbitrary_timestamp_run(6), 10..100)
I verified that this test does indeed fail now when the fix commit is reverted! 🎉 

However, the "minimal failing input" that proptest came back with had 60 points, because of this `10` here. I don't think it actually requires 60 points to trigger this bug (I bet it could be done with 3), so I tried changing this:

```suggestion
        proptest::collection::vec(arbitrary_timestamp_run(6), 0..100)
```

and now I'm getting "minimal failing input" of 18 points (I'm guessing now we're hitting the limit of how many times proptest tries to minimize the input? not sure). I'd rather get a test case of 18 than 60, is there a reason 10 is important here?

2023-06-16 14:50 UTC, carols10cents commented on mutable_batch/src/payload/partition.rs
> +            x.resize(max_run_len, v);
WAIT this line is always resizing the vec to have 6 elements, so that's why there's that lower bound! I think this should be:



```suggestion
            x.resize(run_len, v);
```

2023-06-16 14:51 UTC, carols10cents requested changes
Ok yeah with those two changes I get minimal failing input down to 7 or 8 points sometimes. What do you think?

2023-06-16 14:55 UTC, domodwyer commented on mutable_batch/src/payload/partition.rs
> +        proptest::collection::vec(arbitrary_timestamp_run(6), 10..100)
The intent is to drive a meaningful number of rows through the partitioner in tests - it shouldn't affect shrinking, but you already figured that out!

2023-06-16 14:55 UTC, domodwyer commented
Good eyes! 🔎

2023-06-16 15:14 UTC, carols10cents approved these changes
Looks great now, thank you!

2023-06-20 13:22 UTC, merged