chore(7899): wal disk protection
influxdata/influxdb_iox pull request #8006
Opened 2023-06-15 18:35 UTC by wiedld

Part of #7899 

Three goals:
* provide a primitive which can be dropped into various structs
* easy extensibility as broaden the definition of disk protection (a.k.a. more metrics + actions)
* separation of concerns. `DiskProtectionMetrics` versus `DiskProtectionAction`
    * we can add metrics as we choose
    * we can then have each metric_threshold trigger the same callback action
              * check_available_disk_space => action
              * check_memory => action, etc

---

* feat(7899): add InstrumentedDiskProtection primitive for reuse across codebase (f4cd46d72)

* chore(7899): add InstrumentedDiskProtection to the WAL (a8e3420e6)
     ```
       * this requires providing the metrics registry to the wal 
     ```

* test(7899): add tests for InstrumentedDiskProtection (e8df9304d)

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-06-20 11:56 UTC, domodwyer requested changes
We definitely fell into some pitfalls we tried to avoid by having a conversation first!

2023-06-20 11:56 UTC, domodwyer commented on wal/src/lib.rs
> +        let disk_protection = InstrumentedDiskProtection::new(
We definitely spoke about not modifying the WAL crate/type - the metrics should not be part of the WAL layer! 

There's no reason for the WAL type to have to know about disk metrics, callbacks, limits, etc - the WAL type is responsible for writing operations to the write ahead log, or reading them back. This now forces tooling such as the "wal inspect" which only reads WAL files to export disk metrics, usually on a developers machine, just to read what's in the WAL file. Later it'd need to specify limits, callbacks, etc - this should be a big red flag!

2023-06-20 11:56 UTC, domodwyer commented on tracker/src/disk_protection.rs
> +            .set(available_disk_percentage);
This sums all the free space across all disks in the host to calculate how much space is left for the WAL directory to use - including the free space in C:\ to calculate the amount of bytes we can write in D:\ doesn't make sense! We can't use the free space in C:\ when writing WAL entries in D:\ so it shouldn't be part of this calculation.

We definitely spoke about this - we need to check the free space **in the WAL directory** to make sure that we check the right disk (which may be mounted onto the WAL directory only).

2023-06-20 11:56 UTC, domodwyer commented on tracker/src/disk_protection.rs
> +pub struct InstrumentedDiskProtection {
Can we rescope this PR to just exporting the metric? I wanted us to do this in stages so we could iterate with less friction / have smaller PRs / discuss how we'll compose functionality before we start implementing it.

2023-06-21 16:53 UTC, wiedld commented on wal/src/lib.rs
> +        let disk_protection = InstrumentedDiskProtection::new(
fixed

2023-06-21 17:11 UTC, wiedld commented on tracker/src/disk_protection.rs
> +            .set(available_disk_percentage);
One of the emphasized goals was to make a reusable struct for disk protection, which could be dropped in anywhere. Based upon that requirement, would we perhaps need the following?
```
InstrumentedDiskProtection::new(
        registry: &metric::Registry,
        attributes: impl Into<Attributes> + Send,
        interval_duration: Duration,    // because metric recording interval could differ per use
        directory_to_track: impl Into<String>,
    )
```

Is the re-usability still a requirement? Or is the attributes and interval_duration to be hardcoded?

2023-06-22 09:46 UTC, domodwyer commented on tracker/src/disk_protection.rs
> +            .set(available_disk_percentage);
My references to reusability were more part of my "build small, reusable, decoupled components" rant and not a statement of "we need to use this in multiple places" - there's only one place we use disks today! 

An example of this would be calling the metric (and types, etc) `disk_free_disk_space` (general) and not `disk_protection_free_disk_space` (use-specific) - this whole thing should be "just" be a metric that emits disk free values. Later _we use that_ to build something more complex, but this is **just a disk free metric** right now!

The interval can be hard coded, and the attributes can be this:

```
("path", directory_to_track.to_string())
```

Which ensures each instance of disk free metrics has a unique and non-overlapping label (unless you for some reason start two in the same dir, in which case, it still works!)

2023-06-22 10:01 UTC, domodwyer reviewed
Looking better!

Can we make this not a "protection" metric, but just a disk space metric? From the perspective of a metric user, it just says how much disk space is free - the metric itself has no concept of protection - that'll come later! (see https://github.com/influxdata/influxdb_iox/pull/8006#discussion_r1238281109)

Ideally we'd emit two metrics:

* Free space in the dir
* Total capacity in the dir

These raw numbers are more flexible than emitting a percentage (the caller can do the maths if they need a percentage) - it's more common to emit raw values for this reason, and not aggregated values 👍

2023-07-05 19:52 UTC, wiedld commented on tracker/src/disk_protection.rs
> +            .set(available_disk_percentage);
Made change. Here are the other updates done in order to make it work:
```
refactor: make struct signature be (path, registry)

    * the metric attributes are hardcoded to the path
    * the duration (frequency) of the background task is hardcoded
    * the tick.await now occurs after the first metric recording, such that the test doesn't have to wait 15 seconds.
```

2023-07-05 20:14 UTC, wiedld commented on tracker/src/disk_protection.rs
> +pub struct InstrumentedDiskProtection {
> As we discussed before, this should follow the established pattern for [spawning background tasks in the ingester](https://github.com/influxdata/influxdb_iox/blob/d1cbbd27b149fe7800910c4271b4f56a95a73aa5/ingester/src/init.rs#L365-L371) and retaining a handle to them for shutdown - this impl leaks the spawned task and will never stop (it's also impossible to actually call stop()).

Made change to match other pattern.

```
refactor: move the background task handler onto the parent IngesterGuard

    * follow the pattern of the periodic wal rotation
    * do NOT follow the pattern of the wal.flusher_task
```

2023-07-05 20:27 UTC, wiedld commented
> Ideally we'd emit two metrics:
>
>    Free space in the dir
>    Total capacity in the dir
>
> These raw numbers are more flexible than emitting a percentage

Made changes per request.

```
refactor: calculate raw metrics, not percentage
     * remove calculation of percentage available
     * only record raw numbers
```

2023-07-05 20:48 UTC, wiedld commented on tracker/src/disk_protection.rs
> +pub struct InstrumentedDiskProtection {
> Either way I don't think this type is needed? I was expecting it to go too - we just need the DiskProtectionMetrics (or rather, DiskSpaceMetrics) that can update a metric value - we don't need the two types.

Did as follows, in two different commits:
```
refactor: make into single struct

chore: rename disk protection to DiskSpaceMetric
```

2023-07-06 12:47 UTC, domodwyer commented
Looking great! Thanks @wiedld!

I'm going to push a commmit to tweak a couple things and merge this - I need it ASAP to unblock something 👍

2023-07-06 13:19 UTC, domodwyer commented on tracker/src/disk_metric.rs
> +        tokio::time::sleep(2 * Duration::from_secs(2)).await;
Just worth mentioning - please don't sleep in tests - if you think it's necessary there's probably something that needs to change, or a at worst, a busy-poll would be better.

It only takes a few tests like this to add minutes to the test time, which affects local development, CI runs, and ultimately deployments - it's something we try to avoid :+1:

2023-07-06 13:40 UTC, domodwyer approved these changes
(I'd like someone else to validate my changes too)

2023-07-06 14:02 UTC, savage-engineer approved these changes

2023-07-06 14:02 UTC, savage-engineer commented on tracker/src/disk_metric.rs
> +    disk_idx: usize,
How come you don't just take ownership of the relevant `Disk` and store it on the struct?

2023-07-06 14:04 UTC, merged

2023-07-06 14:04 UTC, domodwyer commented on tracker/src/disk_metric.rs
> +    disk_idx: usize,
It's by-ref only: https://docs.rs/sysinfo/0.29.2/sysinfo/struct.System.html#method.disks

There's no way I could find to take ownership of it - I don't like the indexing either 🤷

2023-07-06 14:07 UTC, savage-engineer commented on tracker/src/disk_metric.rs
> +    disk_idx: usize,
Ah I see, I assumed there would be something like `to_owned()` or `clone()` but I didn't check that far. That's awkward.