feat: add environment variables for max tables per namespace and max columns per table
influxdata/influxdb_iox pull request #8040
Opened 2023-06-21 19:32 UTC by NGA-TRAN

Closes #https://github.com/influxdata/idpe/issues/17796

If namespace is created through service gRPC which I think used by IOx client, these 2 new environment variables can be used to set default value for them:

- INFLUXDB_IOX_NAMESPACE_MAX_TABLE  (default 500)
- INFLUXDB_IOX_NAMESPACE_MAX_COLUMNS_PER_TABLE (default 200)

2023-06-21 20:38 UTC, alamb commented on influxdb_iox/src/commands/namespace/create.rs
> +    #[clap(action,
it might make sense to explain what service (querier, ingester, router, etc) need these set -- I can't remember which service actually creates the entries in the catalog for tables and columns

2023-06-21 20:43 UTC, lukebond commented
I think this updates the default value used by the cli if the args are not given. Which I think is useful if we think that 500 is a reasonable default. However I don't believe that this is how the namespaces are being created. They would be created on write (at least that's how I recall the write path working when I last worked on it) or somehow via granite when setting them up. I'm pretty sure it's the former because I don't believe sales ask the customer what namespaces they need in advance for cst.

2023-06-21 20:54 UTC, lukebond commented
Here is where the router auto creates the namespace: https://github.com/influxdata/influxdb_iox/blob/main/router/src/namespace_resolver/ns_autocreation.rs#LL110C30-L110C30

It's just a catalog function call. Here is the postgres impl: https://github.com/influxdata/influxdb_iox/blob/main/iox_catalog/src/postgres.rs#L568

I think the fix we want for Senec and other such situations in the future is instead of passing None as the last arg here we pass in a service protection block that we set from cli args of the router, much like you've done for the cli here. Then for cst we can set that as 500 in an envvar and cloud 2 iox can stay as it is.

2023-06-21 20:58 UTC, NGA-TRAN commented
@lukebond While I first worked on this PR this morning, I actually made the environments in the router where the namespace is automatically created. But then I see this and I asked myself, "hmm, which one should I provide environment variables? One of them or both?" Then I chose this.

Let us ask Dom before making decision.

@domodwyer : Do we often create namespace or customers create them? If I understand correctly, for Serverless, we will create the namespace automatically for `org_bucket` but for CST, I am not sure. How users of the same CST cluster create their namespace, @lukebond.

2023-06-21 21:00 UTC, NGA-TRAN commented
@lukebond 

> I think the fix we want for Senec and other such situations in the future is instead of passing None as the last arg here we pass in a service protection block that we set from cli args of the router, much like you've done for the cli here. Then for cst we can set that as 500 in an envvar and cloud 2 iox can stay as it is.

Yes, that is the point of this PR. You will set the `INFLUXDB_IOX_NAMESPACE_MAX_COLUMNS_PER_TABLE` created in this PR to 500 in CST. We will keep Serverless 200 intact which is the default value.

SO this PR is good for you?

2023-06-21 21:15 UTC, NGA-TRAN commented on influxdb_iox/src/commands/namespace/create.rs
> +    #[clap(action,
This namespace service is tricky. It will be created in both router and queriers so we might need to set in both if we want to it to work in both places.  However, there are 2 places to change this as Luke and I are discussing. I went with auto create namespace in router at first but then decided it was not the right place for CST and go with CLI in this PR. With this CLI changes, the environment variables will be set where the CLI is used.

I am waiting for @domodwyer and @lukebond to confirm how namespaces are created in Serverless and CST and will go with the right solution for it https://github.com/influxdata/influxdb_iox/pull/8040#issuecomment-1601668269

2023-06-21 21:21 UTC, philjb commented
in c3/serverless, the database (bucket aka namespace) is made in advance of writes (as writes are validated against existing buckets at write time by gateway). 

In cst, there is no gateway - customers write directly(ish) to iox routers. The namespaces are created on demand by the customer when they write. We (Luke/CST) want a feature where any namespaces created by a dedicated customer get a preconfigured limit set - e.g. dedicated customer A gets 350 columns per table for all namespaces they create implicitly. 

I think this pr is useful for the `influxdb_iox namespaces create` cli but it isn't what we would like to have for CST customers. 

I think an env var (or a couple) for the router would do the trick. (I'm repeating what Luke has said.)

2023-06-21 21:28 UTC, lukebond commented
I'm reviewing on my phone so might have missed something but sounds like Phil agrees. I'll check this thread again tomorrow at my desk

2023-06-21 21:34 UTC, NGA-TRAN commented
There seems to be different answer. This [slack conversation](https://influxdata.slack.com/archives/CRK9M8L5Q/p1687382572635979) says CST namespace is created manually

2023-06-21 23:48 UTC, philjb commented
> @lukebond and @philjb From this [slack conversation](https://influxdata.slack.com/archives/CRK9M8L5Q/p1687382572635979), CST namespace are created manually thru this gRPC call. So this PR provide the right environment variables

You're right Nga! sounds good. thanks for double checking.

2023-06-21 23:49 UTC, philjb approved these changes

2023-06-22 09:35 UTC, domodwyer requested changes
In production a user creates a bucket by writing to it (impilict creation) or via granite making an RPC request to create the namespace (explicit creation) depending where we're running.

This changes the arguments when running the CLI tool like this:

```shellsession
% influxdb_iox namespace create <name> --max-tables=42
```

Which isn't used by the end user. It also **doesn't really have any effect**, before this change the CLI user:

* Can not specify anything - the default value `DEFAULT_MAX_TABLES` will be used in the server
* Can either pass `--max-tables=1234` to use a different value

After this change the CLI user:

* Can not specify anything - the default value `DEFAULT_MAX_TABLES` will be used 
* Can either pass `--max-tables=1234` to use a different value

The only difference is where the default is assigned - previously it was done on the server (and still will be for all other clients) but now this CLI (and only this CLI!) will set it on the client side.

I think we shouldn't merge this - it makes no user-facing difference, but does make this CLI work differently from everything else w.r.t where defaults are applied (which the user doesn't benefit from either!)

---

It sounds like you want to change the default value on the granite client and not IOx? so it defaults to saying "X max tables" please. I think this is what we've done before.

2023-06-22 14:40 UTC, closed without merging