feat(idpe 17789): provide scheduler interface
influxdata/influxdb_iox pull request #8057
Opened 2023-06-22 22:57 UTC by wiedld

Part of https://github.com/influxdata/idpe/issues/17789

This PR is where things started getting added, as we officially start defining the boundary through the Scheduler interface. General approach was to only expose the minimum needed to the compactor, and try keeping all scheduler bits (config, specific `Scheduler` implementations, etc) as crate private.

## In followon PRs:
* decide how to define "done"|"complete" through the `Scheduler` interface
* decide what responsibilities should be within the `Scheduler` interface, versus without only the RemoteScheduler implementation
  * here is an example commit, demonstrate how the distributed coordination work could be encapsulated within the RemoteScheduler
  * note: this^^ is only a rough example. There are likely much better approaches. 😅 

## Checklist:
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-06-22 23:02 UTC, wiedld commented on compactor/src/components/partition_filter/mod.rs
> -/// which usually runs earlier in the pipeline and hence is more efficient.
This was the only remaining external reference (outside the compactor_scheduler) to `IdOnlyPartitionFilter`. 

Since it's only a comment, and nothing else in the compactor can reference this `compactor_scheduler::IdOnlyPartitionFilter` struct now --> it did not make sense to keep.

2023-06-22 23:04 UTC, wiedld commented on compactor/src/components/report.rs
> -    };
Only the scheduler should have any awareness of sharding etc.

The scheduler `Display` now includes this information.
And the compactor report (the code here) calls this scheduler `Display`.

2023-06-22 23:12 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
Not sure if the `Scheduler` trait should return a PartitionsSource? Or a `Vec<CompactionJob>`?

Because for the LocalScheduler implementation, we are:
1. creating a partitions_source
2. calling fetch(), then to convert `Vec<PartitionId>` into the trait contract `Vec<CompactionJob>`
3. then [in the compacto](https://github.com/influxdata/influxdb_iox/blob/1a6bb4469747760442c986e71ffb8c2deacbd692/compactor/src/components/partitions_source/scheduled.rs#L19-L24)r we have to once again convert back to `Vec<PartitionId>.

The followon PR will introduce doneness|completeness. If doneness is assigned per PartitionId, then it'll likely be within the CompactionJob. Thereby making this conversion/handling more worthwhile.

2023-06-23 18:37 UTC, carols10cents requested changes
I think some of this rearranging needs to go in slightly different spots to be consistent with the other crates.

2023-06-23 18:37 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
I agree with Marco about the names.

I was thinking about the conversion from PartitionId to CompactionJob and back again, and I think I like it because what constitutes the information on a compaction job might change (for instance, i don't know, we might change from identifying partitions by `PartitionId` to identifying them by `PartitionHashId` perhaps 😇 ) and having the type passed around be `CompactionJob` might mean there are fewer places to change. Maybe.

2023-06-23 22:01 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
This is an excellent conversation. 😻 

There was a chat a while back with @Joe-Blount , about what is a "CompactionJob". IIRC (joe please feel free to correct here), there is at minimum three options:
* Is it multiple partitions and a singular definition of doneness?
     * `struct CompactionJob { partitions: Vec<PartitionId>, doneness }`
     * singular get_job()
* Or should doneness be per PartitonId? And the CompactionJob be per partition?
     * `struct CompactionJob { partition: PartitionId, doneness }`
     * multiple get_jobs()
* Or should doneness be per PartitonId, but the CompactionJob is multiple partitions?
     * `struct CompactionSubJob { partition: PartitionId, doneness }`
     * singular get_job()
  
Then I researched a little and found CS definitions of: "Job" is the whole unit of work, "Task" is the execution unit within a job (multiple tasks per job). So maybe it's singular get_job() returning multiple CompactionTasks? 🤷🏼‍♀️  And then we still have to decide if the idea of doneness is per partition, or per whole job.

But I may have this wrong, or am proposing a path too confusing to our future selves. 😅

2023-06-23 22:07 UTC, wiedld commented on compactor/src/components/partitions_source/scheduled.rs
> +            "scheduled_partitions_source(local_compaction_scheduler(shard_cfg_n_shards=None,shard_cfg_shard_id=None))",
Thank you for explaining. Makes sense, will do!

2023-06-26 10:43 UTC, crepererum commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
So does the worker then call `get_job` and gets multiple tasks/partitions? Like a "unit of work" can for sure be a batch of tasks/partitions, I'm just wondering if we really wanna implement batching in this interface because then you quickly get into the pickle that a batch size might be too large or it is not well distributed (e.g. a job contains multiple "heavy" partitions), like all the issues that you also get with sharding.

2023-06-26 18:16 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
It sounds like while the scheduler might only ever send back one `CompactionJob` containing one `PartitionId` right now, you want to reserve the right to send more in the future, is that an accurate summary?

If so, that's fine, then I think: 

- this function's signature should be `async fn get_jobs(&self) -> Vec<CompactionJob>`
- `CompactionJob`'s definition should be:
    ```
    pub struct CompactionJob {
        /// Leased partition.
        pub partition_id: PartitionId,
    }
    ```

Then all code will need to iterate over both, but if we change from sending 1 to sending many in either place, no code will need to change. So that seems like the most flexible thing to me...

2023-06-26 19:48 UTC, wiedld commented on influxdb_iox/src/commands/run/compactor.rs
> +    );
Thank you for taking the time to write an excellent explanation. Did almost exactly the same, but with only slight differences. The outcome meets the goals of crate decoupling; the only crate now consuming both compactor_scheduler and clap_blocks is ioxd_compactor.

The differences are: 
* the ScheduledPartitionsSource also has a reference to the scheduler (in addition to the `compactor::Components`) for the fetching of source partitions
* assumed that we could keep the `clap_blocks::CompactorSchedulerConfig` as an entity set separately for the run all-in-one command, to aid development and testing of the remote scheduler.

2023-06-26 19:51 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +    /// The shard config used for generating the PartitionsSoruce.
🤦🏼 😆

2023-06-26 20:01 UTC, wiedld commented on compactor/src/components/mod.rs
> +    pub scheduler: Arc<dyn Scheduler>,
Currently only used in partitions_source, but will (in followon PR) be used the end_job() phase too.

2023-06-26 20:55 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
Making the change suggested by Carol.

2023-06-27 07:53 UTC, crepererum commented
I wrote that in slack but I'm somewhat afraid that this will get lost:

A follow-up PR (maybe the one that implements the "done/complete" interface part) also needs to clarify how scheduler and the workers ensure that only a single workers is processing a given partition.

2023-06-27 07:55 UTC, crepererum commented on compactor_scheduler/src/scheduler.rs
> +    /// Leased partitions.
So in the follow-up done/complete PR, we also need to clarify the expiration of that lease.

2023-06-27 07:58 UTC, crepererum approved these changes
I think this is a good minimum increment, even though we need follow-up PRs. So let's merge this to keep the PRs reviewable

2023-06-27 17:26 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +    /// Leased partitions.
Agreed. Have updated [the epic tracking here](https://github.com/influxdata/idpe/issues/17789#issuecomment-1599301745), to include both the "doneness" and worker coordination (only 1 worker per partition) question.

Part of what I'm unclear on, is how much of this logic fits into the Scheduler trait interface (a.k.a. included for both LocalScheduler and RemoteScheduler), and how much fits into the RemoteScheduler trait implementation -- which is code that still run locals on the compactor (before making the rpc call). May end up doing another PoC draft PR which includes both the end_jobs() and RemoteScheduler bit => then break that up into reviewable chunks.

2023-06-27 18:23 UTC, Joe-Blount commented on compactor_scheduler/src/scheduler.rs
> +    /// Leased partitions.
on worker coordination: I think the local scheduler still does a query for all active partitions then iterates through them...  That will continue to protect against dual assignment as well as it ever has.  The remote scheduler will need more sophisticated worker tracking though.  I think this is the big task before we can have a remote scheduler.

for doneness: as the remote scheduler gets smarter and wants to specify doneness, there may be some simple corresponding changes to the local scheduler.  For example, the remote scheduler may pass varying criteria for doneness and the local can always pass the same values.  But this can be deferred until after have a functioning remote scheduler.

2023-06-28 14:49 UTC, carols10cents requested changes
This is getting closer!!! Just a few more little things, here's a checklist that should correspond to my comments of what I'd like to see addressed:

- [ ] Create and use a `MockScheduler` in `compactor/src/components/partitions_source/scheduled.rs` for the display test
- [x] Put back the `let` that destructures `ShardConfig` in its `Display` impl so that we don't forget to handle new fields in the future
- [x] The `Compactor.scheduler` field-- either remove it or tell me you definitely have concrete plans for it that I'm not seeing

2023-06-28 14:49 UTC, carols10cents commented on compactor/src/components/mod.rs
> +    pub scheduler: Arc<dyn Scheduler>,
Will it be used as `components.scheduler` (from the top level) or will it become part of the `partition_done_sink`, do you think? To me, it seems more likely that it'll be part of the `partition_done_sink` so this top level field isn't really needed? How concrete is the future design plan?

2023-06-28 19:33 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            .collect()
Heads up to @carols10cents . Had a call this morning where the consensus (w/ Joe & Marco) moved to this:
```
pub struct CompactionJob {
    #[allow(dead_code)]
    /// Unique identifier for this job.
    /// Should not be the same as the partition id.
    uuid: Uuid,
    /// Leased partition.
    pub partition_id: PartitionId,
}
```
The uuid will be used in the next/followon PR for the job end API.
Please 🙏🏼 let us know if this^^ feels like a bad idea to you.

2023-06-28 19:37 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +    /// Leased partitions.
As per excellent conversation this morning (w/ Joe, Marco, Andrew, Nga, etc): the partition uniqueness tracking and throttling will be moved to the scheduler within the next done/complete PR. The commit will also be moved to the scheduler, as that will allow us to have a single location (scheduler) enforcing the partition uniqueness guarantees without needing to add additional consensus coordination between the compactors.

2023-06-28 19:58 UTC, wiedld commented on compactor/src/components/mod.rs
> +    pub scheduler: Arc<dyn Scheduler>,
We now have a concrete design plan for end_jobs(), which will not need scheduler as a top level component. Removing.

2023-06-28 21:03 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/shard_config.rs
> +            self.n_shards, self.shard_id
Done!

2023-06-28 21:22 UTC, carols10cents commented on compactor_scheduler/src/lib.rs
> +            partitions.into_iter().collect::<HashSet<PartitionId>>(),
Hm, I believe this test would pass if the test scheduler for some reason was creating two jobs per partition, such that if you collected `jobs`' partition IDs into a `Vec` instead of a `HashSet`, you'd have `vec![PartitionId::new(0), PartitionId::new(0), PartitionId::new(1234242), PartitionId::new(1234242)];`. Is that ok or is that the sort of bug you'd want this test to fail on? 

If the latter, I think an easy fix would be to add `assert_eq!(jobs.len(), 2);` in here.

2023-06-28 21:39 UTC, wiedld commented on compactor_scheduler/src/lib.rs
> +            partitions.into_iter().collect::<HashSet<PartitionId>>(),
Wanted to confirm completeness (both present), with no sort order sensitivity. The set (dedupe) was the wrong idea. I just added the sort. Sry!

2023-06-28 21:43 UTC, carols10cents approved these changes
Thank you!! This looks much better now :)

2023-06-28 22:04 UTC, merged