feat: Query the catalog with PartitionHashId if you have it, otherwise with PartitionId
influxdata/influxdb_iox pull request #8083
Opened 2023-06-26 20:34 UTC by carols10cents

Connects to https://github.com/influxdata/idpe/issues/17476.

Extracted from https://github.com/influxdata/influxdb_iox/pull/8068 if you're interested to see the direction in which this work is heading.

This PR changes these three catalog methods to accept a [`TransitionPartitionId`](https://github.com/influxdata/influxdb_iox/blob/7e30c91cebc32be665b360c5ab0feed09c038882/data_types/src/partition.rs#L10-L20) (which is a `PartitionHashId` if it's available and a `PartitionId` if not) instead of always a `PartitionId` as a means of identifying a partition. Each method change has its own commit in this PR:

- Looking up a partition by ID (done with a new function `partition_lookup` because there are methods `PartitionRepo::get_by_id` and `PartitionRepo::get_by_hash_id` already implemented per catalog impl and the `partition_lookup` logic doesn't depend on what catalog impl you're using
- `PartitionRepo::.cas_sort_key`
- `ParquetFileRepo::.list_by_partition_not_to_delete`

2023-07-06 08:53 UTC, crepererum requested changes
Needs PG index. Otherwise the PR looks pretty straight forward.

2023-07-06 08:53 UTC, crepererum commented on iox_catalog/src/postgres.rs
> +WHERE parquet_file.partition_hash_id = $1
We need a new partial index. See

https://github.com/influxdata/influxdb_iox/blob/main/iox_catalog/migrations/20230530132809_add_parquet_file_partition_and_deleted_index.sql

Please add this in an extra PR prior to merging this PR here so the perf impact isn't too harsh.

2023-07-07 14:44 UTC, domodwyer approved these changes
Ditto on the index, but looks good! 

Might be worth adding the index `CONCURRENTLY` now that it's do-able - we've had a few weeks of populating this column now.

2023-07-10 14:43 UTC, carols10cents commented
Index added, ready for re-review! ❤️

2023-07-10 17:47 UTC, carols10cents commented
Ok *now* this is ready for re-review.

2023-07-11 09:47 UTC, domodwyer approved these changes

2023-07-12 14:56 UTC, merged