fix(8191): directory path resolve
influxdata/influxdb_iox pull request #8205
Opened 2023-07-10 22:33 UTC by wiedld

Closes #8191 

Need to resolve for all pathing use cases.

---

* fix(8191): resolve canonical, absolute form of the path (61710b118)

* test(8191): update test to cover path resolution (6c3427124)

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-07-10 22:37 UTC, wiedld commented on tracker/src/disk_metric.rs
> +        // The directory path may be `/path/to/dir` and the mount point is `/`.
Want to explicitly highlight that the metric measurement is performed at a different path as the attributes label. This was part of the requirements/request at the time -- I leave others to decide whether or not to leave as is. 😄

2023-07-11 09:10 UTC, domodwyer approved these changes

2023-07-11 09:10 UTC, domodwyer commented on tracker/src/disk_metric.rs
> +        // The directory path may be `/path/to/dir` and the mount point is `/`.
I don't think there's any point emitting the mount point, it's not really something people can correlate - I don't know what the mount point of the WAL dir is in prod, and I bet neither do you! You wouldn't probably recognise the WAL directory path though.

2023-07-11 09:12 UTC, domodwyer requested changes
I think we should avoid creating a mess in the work directory :+1:

Normally we'd create a temporary directory for tests that touch the filesystem, I think tempfile is somewhat standard usage.

2023-07-11 09:12 UTC, domodwyer commented on tracker/src/disk_metric.rs
> +        std::fs::create_dir(unique_dir.clone()).ok();
Can we do this in `tmp` or something? Otherwise every time you run the test, you'll create a new directory in your working dir which is _annoying_ to say the least.

2023-07-11 10:22 UTC, alamb commented on tracker/src/disk_metric.rs
> +        std::fs::create_dir(unique_dir.clone()).ok();
Perhaps https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html would be a good choice (it is used widely in other tests)

2023-07-11 10:33 UTC, alamb approved these changes
I tested this out locally and it resolves the error I was seeing. Thank you @wiedld  🙏

2023-07-11 10:33 UTC, alamb commented on tracker/src/disk_metric.rs
> +        let mut directory = directory.canonicalize().ok()?;
Is this the bug fix (to canonicalize the directory?)

2023-07-11 10:33 UTC, alamb commented on tracker/src/disk_metric.rs
> +        let metric_label: Cow<'static, str> = unique_dir.clone().into();
I verified that this test covers the behavior by reverting the code change 

```diff
diff --git a/tracker/src/disk_metric.rs b/tracker/src/disk_metric.rs
index 0ee395227..75b213347 100644
--- a/tracker/src/disk_metric.rs
+++ b/tracker/src/disk_metric.rs
@@ -27,10 +27,8 @@ pub struct DiskSpaceMetrics {
 impl DiskSpaceMetrics {
     /// Create a new [`DiskSpaceMetrics`], returning [`None`] if no disk can be
     /// found for the specified `directory`.
-    pub fn new(directory: PathBuf, registry: &metric::Registry) -> Option<Self> {
+    pub fn new(mut directory: PathBuf, registry: &metric::Registry) -> Option<Self> {
         let path: Cow<'static, str> = Cow::from(directory.display().to_string());
-        let mut directory = directory.canonicalize().ok()?;
-
         let attributes = Attributes::from([("path", path)]);
 
         let available_disk_space = registry

```

And then verifying that the test fails:

```
---- disk_metric::tests::test_metrics stdout ----
thread 'disk_metric::tests::test_metrics' panicked at 'root always exists', tracker/src/disk_metric.rs:119:18
stack backtrace:
   0: rust_begin_unwind
```

👍

2023-07-11 15:58 UTC, wiedld commented on tracker/src/disk_metric.rs
> +        let mut directory = directory.canonicalize().ok()?;
Yes, and it handles various other use cases as well (path sym links, etc). Figured would fix it once.

2023-07-11 16:47 UTC, wiedld commented on tracker/src/disk_metric.rs
> +        std::fs::create_dir(unique_dir.clone()).ok();
TempDir was super useful. TY!

2023-07-11 19:36 UTC, wiedld commented
Made the changes requested by @dom, and already have a re-approval from @alamb . To get this in more quickly, will merge now. But please let me know if I should include additional changes in another PR!

2023-07-12 09:22 UTC, domodwyer approved these changes

2023-07-12 20:50 UTC, merged