feat(idpe 17789): scheduler `job_status()`
influxdata/influxdb_iox pull request #8216
Opened 2023-07-12 01:28 UTC by wiedld

Part of https://github.com/influxdata/idpe/issues/17789

This PR has:
* the initial changes (the original PR) is a single merge commit
* integration tests for `get_status()`
* integration test for the uniqueness abstraction, which uses feedback from `get_status()`
   * this test fails. Is the found bug which was stalling the compactors.
* the fix

--- 

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-07-12 15:38 UTC, carols10cents reviewed
I don't feel like I'm done reviewing this completely, but I have some high-level questions first (and I'm going to take a break so I wanted to send these in the meantime).

2023-07-12 15:38 UTC, carols10cents commented on compactor_scheduler/src/scheduler.rs
> +}
When I see a type that ends in the name `Result`, I assume it's going to have variants similar to `std::result::Result`'s `Ok` or `Err`, probably a type alias for `std::result::Result` with a default of a specialized `E` type. 

I know that's not the general meaning of "result" in English, but it's a fairly consistent convention in Rust :) 

What do you think about changing the name to something like `CompactionJobStatusResponse`? And actually, this is what the scheduler is going to send back to the compactors to say that the scheduler has processed the job status update that the compactor sent the scheduler, right? So I think the docs need to be updated here too, because it's not the actual status of the compaction job, it's the status of the status update 🧟‍♀️ 

So how about something like...

```suggestion
/// Responses sent from the scheduler to the compactor when the compactor sends an updated job status.
#[derive(Debug)]
pub enum JobStatusUpdateResponse {
    /// Ack only.
    Ack,
    /// Updates which were processed.
    UpdatedParquetFiles(Vec<ParquetFileId>),
}
```

2023-07-12 16:10 UTC, carols10cents commented on compactor/src/components/commit.rs
> +            _ => panic!("commit failed"),
Yeah, I would think in case of a transient network error, that we'd want to do a backoff retry? Also what if one compactor is working on multiple jobs, and sending a commit status fails for one of them-- this would stop all of them immediately, I think? Is that the desired behavior?

2023-07-12 16:13 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +    async fn job_status(
I like this suggested change.
Btwn this feedback, and the feedback to add comments to the test -- it's clear that we need to use better namings. Doing so.

2023-07-12 16:30 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +}
Yeah, better words are definitely needed! 🤦🏼‍♀️

2023-07-12 18:25 UTC, carols10cents requested changes
Ok, I feel like I've done a thorough review now, and I would like to see some changes (some of which you're already working on ❤️ )

2023-07-12 18:25 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +    async fn test_status_update_none_should_panic() {
I agree, and I highly recommend adding `expected` to the `should_panic` annotation, otherwise this test could be passing because something is panicking for a different reason than we were trying to verify :)

(This is moot if we decide not to panic though)

2023-07-12 18:25 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +            .is_ok());
I think it would be valuable to test here and in the other tests that send `CompactionJobStatusVariant::Update` that the `created` IDs come back in the response. [The `assert_matches!` macro](https://docs.rs/assert_matches/latest/assert_matches/macro.assert_matches.html) should make this nice! Something like:

```suggestion
        assert_matches!(scheduler
            .job_status(CompactionJobStatus {
                job,
                status: CompactionJobStatusVariant::Update(commit_update),
            })
            .await,
            Ok(CompactionJobStatusResult::UpdatedParquetFiles(result)) if result == &[created.id]
        );
```

2023-07-12 18:25 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +                .is_ok());
And likewise, in tests that send something other than `CompactionJobStatusVariant::Update`, I think it would be worthwhile to ensure we're getting an `Ack`:

```suggestion
            assert_matches!(scheduler
                .job_status(CompactionJobStatus {
                    job,
                    status: CompactionJobStatusVariant::RequestToSkip(SkipReason::CompactionError(
                        "some error".into()
                    )),
                })
                .await,
                Ok(CompactionJobStatusResult::Ack),
            );
```

2023-07-12 18:25 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +                self.partition_done_sink
Checking my understanding-- `partition_done_sink.record` should *not* be called for the `Update` case, because `commit` is currently called during each round of compaction rather than only when a partition is done, and ultimately this PR is aiming to keep the current behavior, right?

Current code path I'm basing this comment on:

- `try_compact_partition` has this `loop` https://github.com/influxdata/influxdb_iox/blob/c3788ee2b88c285511bedef4d5876d2d8a290e1d/compactor/src/driver.rs#L186-L201
- that calls `execute_branch` multiple times within each `loop` iteration https://github.com/influxdata/influxdb_iox/blob/c3788ee2b88c285511bedef4d5876d2d8a290e1d/compactor/src/driver.rs#L244
- `execute_branch` calls `update_catalog` https://github.com/influxdata/influxdb_iox/blob/c3788ee2b88c285511bedef4d5876d2d8a290e1d/compactor/src/driver.rs#L359
- `update_catalog` calls `Commit::commit` https://github.com/influxdata/influxdb_iox/blob/c3788ee2b88c285511bedef4d5876d2d8a290e1d/compactor/src/driver.rs#L552

2023-07-12 22:06 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +                self.partition_done_sink
This dialogue is very helpful, and made me realize that the test suite itself needs to be done a little differently. Here are the updated tests:

`test_display`
`test_display_with_sharding`
`test_empty_commits_should_panic`
`test_replacement_commit`  (note: let me know if terminology should be different)
`test_replacement_commit_args_incomplete`
`test_upgrade_commit`
`test_can_replace_and_upgrade_commit_at_once`
`test_partition_uniqueness`
`test_partition_throttling`
`test_partition_skipping`
`test_cannot_commit_to_skipped_partition`
`test_cannot_complete_a_skipped_partition`
`test_skipped_partition_can_still_send_errors`
`test_error_send_any_time`
`test_can_commit_then_complete` (this has a commit, then another commit, then a complete --> which covers the use case method in @carols10cents 's comment above).
`test_cannot_commit_after_complete`

2023-07-12 22:29 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +    UpdatedParquetFiles(Vec<ParquetFileId>),
changed.

2023-07-12 22:32 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            .is_ok());
This is me being impatient. Should have slowed down and did this test suite properly. Thanks for pointing out -- fixing!

2023-07-13 01:31 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +                .is_ok());
Done

2023-07-13 02:43 UTC, wiedld commented on compactor/src/components/commit.rs
> +            _ => panic!("commit failed"),
The attempt to reach the catalog (from the local scheduler) is [already using the backoff and retry logic](https://github.com/influxdata/influxdb_iox/blob/9103560f9507bb8732e2860c9b8eee82cc72baf0/compactor_scheduler/src/local_scheduler/catalog_commit.rs#L47-L48). So there should not be a use case in which it fails => so we should always be returning a `CompactionJobStatusResponse`.

The match here is checking the proper variant of CompactionJobStatusResponse and the Ok.
* Ok/Err from the Scheduler trait, which is both for the remote and local scheduler. 
  * yes, we will have backoff and retry on the remote scheduler connection. So should we remove the Ok/Err result?
* The proper CompactionJobStatusResponse enum variant is returned.
  * if not --> then we have a code bug.

2023-07-13 02:44 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +    async fn test_status_update_none_should_panic() {
I added the explicit panic message to the 2 `should_panic` annotations.

Are panics moved from the compactors. We can decide to make it into something else.

2023-07-13 03:07 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            PANIC_CALLED_0.store(true, Ordering::SeqCst);
I do not like this code pattern at all. The problem is that I can only detect the panic using the global panic hook, as the panic was thrown downstream of a future (which never returns) on another thread in the [ThrottlePartitionDoneSinkWrapper](https://github.com/influxdata/influxdb_iox/blob/9103560f9507bb8732e2860c9b8eee82cc72baf0/compactor_scheduler/src/local_scheduler/combos/throttle_partition.rs#L287-L290). Panic is from calling `scheduler.partition_done_sink` twice.

I made a whole bunch of test to document what is the current behavior of the scheduler API, with the understanding that we are likely to change these panics. So this code pattern is only temporary (as the current documented API contract).

2023-07-13 13:15 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
> +            PANIC_CALLED_0.store(true, Ordering::SeqCst);
Yeah no we definitely shouldn't be doing anything with the panic hook. This is more evidence that we should be returning an `Err` instead of panicking, imo.

2023-07-13 13:24 UTC, carols10cents commented on compactor/src/components/partition_done_sink/mod.rs
> -    async fn record(&self, partition: PartitionId, res: Result<(), DynError>);
So previously, `PartitionDoneSink::record` returned nothing because it was expected to handle retries of the catalog internally and retry forever. But now we're potentially splitting this call across services, which introduces the possibility of failure.

So I see 2 possibilities:

1. Change this method to return a `Result`
2. Keep this trait as-is and make it private to the scheduler-- instead, change the `Scheduler` trait and have the `compactor` only use `update_job_status`. I haven't worked through all the implications of this, nor am I sure that this is what we want with regards to logging and metrics, etc.

2023-07-13 14:50 UTC, Joe-Blount commented on compactor_scheduler/src/scheduler.rs
> +}
I think its useful to eventually have a manual request to skip a partition.  
So we can manually make the compactor skip a partition to get past whatever unhandled situation that may come up.

2023-07-13 15:56 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +            PANIC_CALLED_0.store(true, Ordering::SeqCst);
Will do.

2023-07-18 18:29 UTC, wiedld commented on compactor/src/components/partition_done_sink/mod.rs
> -    async fn record(&self, partition: PartitionId, res: Result<(), DynError>);
I ended up doing both, since the PartitionDoneSink trait needs further compactor vs scheduler specialization in the follow up PR (where the compactor starts passing CompactionJob around). So we now have 2 separated traits.

Both traits now have an Result returned, with a well-typed error on the scheduler side.

2023-07-18 22:44 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +    async fn test_status_update_none_should_panic() {
all code panics (in existing code moved from the compactor) are converted to proper error handling.

2023-07-18 22:44 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
> +                self.partition_done_sink
Integration test cases are now existing under `compactor_scheduler/tests/**`. Makes the contract much more explicit.

2023-07-18 22:45 UTC, wiedld commented on compactor_scheduler/src/scheduler.rs
> +}
Made the change to `pub struct SkipReason(String);`

2023-07-18 22:50 UTC, wiedld commented on compactor/src/components/mod.rs
> +    pub commit: Arc<CommitToScheduler>,
We only had 1 `Commit` implementation left in the compactor, which will need a type signature change in the next PR anyways (when compactor starts consuming `CompactionJob`.

Therefore, made this into the struct `CommitToScheduler`.

2023-07-18 22:51 UTC, wiedld commented on compactor/src/driver.rs
> +            .await // errors detected in the CompactionJob update_job_status(), will be handled in the timeout_with_progress_checking
This is where the commit errors finish propagating up.

2023-07-18 22:54 UTC, wiedld commented on compactor/src/components/commit.rs
> +            CompactionJobStatusResponse::Ack => unreachable!("scheduler should not ack"),
Wasn't sure about this `unreachable!()`. Thoughts?

2023-07-18 22:56 UTC, wiedld commented on compactor/src/components/partition_done_sink/mock.rs
> +pub struct MockPartitionDoneSink {
The `PartitionDoneSink` trait now differs btwn the scheduler and compactor. (And will differ further once the CompactionJob is consumed in the compactor.)

Therefore, each needs their own mocks.

2023-07-18 22:57 UTC, wiedld commented on compactor/src/components/partition_done_sink/logging.rs
> +                // log compactor errors, classified by compactor ErrorKind
This is the reason I elected not to move this abstraction behind the scheduler. what do you think?

2023-07-18 22:57 UTC, wiedld commented on compactor/src/components/partition_done_sink/metrics.rs
> +                // classify and track counts of compactor ErrorKind
This is the reason I elected not to move this abstraction behind the scheduler. what do you think?

2023-07-18 23:15 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/combos/throttle_partition.rs
> +    // Requires change of Scheduler.get_jobs() API to a Result<Vec<CompactionJob>>
Note: this is the only remaining possible panic in the scheduler code (I think 🤞🏼 ), which can occur during the uniqueness tracking in the `get_jobs()` request.

Your call on whether or not this work also gets done now.

2023-07-18 23:19 UTC, wiedld commented on compactor/src/components/partition_done_sink/error_kind.rs
> +                Err(e)
This behavior is the same as [existing in the prod](https://github.com/influxdata/influxdb_iox/blob/b79009b128ee52fd4b43be8120d05989c0a077aa/compactor/src/components/partition_done_sink/error_kind.rs#L44-L51) (compactor `ErrorKindPartitionDoneSinkWrapper`).

2023-07-18 23:20 UTC, wiedld commented on compactor/src/driver.rs
> +    let _ = components
This is the final point to which the `end_job()` errors get propagated up.

2023-07-19 14:49 UTC, carols10cents commented on compactor/src/components/commit.rs
> +            CompactionJobStatusResponse::Ack => unreachable!("scheduler should not ack"),
Hm. It feels a bit weird to me, like we're not using the type system as effectively as we could be. But the only solution I can think of is splitting `update_job_status` again, into `report_job_update` and `report_job_error`, that each have a more specific signature. That might complicate other things, such as using these messages (of either type) as a heartbeat of sorts to determine if the compactor is working or not. 

Ultimately, what this is attempting to do is enforce the contract between the compactor and the scheduler. This `unreachable` would ideally cause a panic in tests before getting to production, since we're controlling both sides of the contract..... so I think this is ok for now, we can revisit as this code evolves, I think.

2023-07-19 15:08 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler/catalog_commit.rs
> +        }
All these negatives and logical operators are making my head hurt :( I think this is saying:

- Either there must be files to upgrade, or 
- there must be both files to delete and create

is that right?

If so, I think this would be better as something like:

```suggestion
        if upgrade.is_empty() {
            match (delete.is_empty(), create.is_empty()) {
                (true, true) => return Err(Error::BadRequest("Commit was missing files to upgrade, files to delete, and files to create")),
                (true, false) => return Err(Error::BadRequest("Commit was missing files to upgrade and files to delete")),
                (false, true) => return Err(Error::BadRequest("Commit was missing files to upgrade and files to create")),
                _ => {},
            }
        }
```

What do you think?

2023-07-19 15:13 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler/combos/throttle_partition.rs
> +    Lock,
I missed this before, but this commit makes it clearer-- if we change the `Mutex` used in the compactor scheduler to [`parking_lot::Mutex`](https://docs.rs/parking_lot/latest/parking_lot/type.Mutex.html) (used elsewhere in iox), then we don't need this error case as `parking_lot::Mutex`es don't have poisoning.

2023-07-19 15:25 UTC, carols10cents commented on compactor/src/components/partition_done_sink/logging.rs
> +                // log compactor errors, classified by compactor ErrorKind
Yeah, I was wondering whether this was needed or not, ultimately I don't know whether it will be useful to have these logs on the compactor side as well as on the scheduler side. I also notice that `compactor::partition_done_sink::PartitionDoneSinkToScheduler` is only doing a bit of transformation and then calling `Scheduler::end_job`, so perhaps we can get rid of the `compactor::partition_done_sink::PartitionDoneSink` trait entirely and call `Scheduler::end_job` directly, and have logging/metricts/etc wrappers around `Scheduler`? That could be a future PR though.

2023-07-19 16:02 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler/combos/throttle_partition.rs
> +    // Requires change of Scheduler.get_jobs() API to a Result<Vec<CompactionJob>>
This PR is already big enough, let's do a future one :)

2023-07-19 16:17 UTC, carols10cents commented on compactor_scheduler/tests/helpers.rs
> +macro_rules! can_do_upgrade_commit {
Why do these need to be macros rather than regular functions? I'm not seeing any reason immediately.

2023-07-19 16:26 UTC, carols10cents commented on compactor_scheduler/tests/local_scheduler/get_jobs.rs
> +    );
Yeah this would be a lot clearer as

```suggestion
    let jobs = scheduler.get_jobs().await;
    assert!(jobs.is_empty(), "Expected empty, got {:?}, jobs);
```

2023-07-19 16:43 UTC, carols10cents commented on compactor_scheduler/tests/local_scheduler/get_jobs.rs
> +        "no partitions found in next get_jobs() call"
Yeah so a general comment, the final argument(s) to `assert_matches!` is like the final argument(s) to `assert!`, `assert_eq!`, etc-- it's a message to be printed when the assertion fails, to give more context or information. 

So the message here is backwards-- "no partitions" is what we want to see, but if we're seeing this message, we didn't see that.

In some of these cases where there's a failure message specified, I think leaving the custom message out would be appropriate, as the output from the `assert_matches!` macro that says something like `[whatever value it got] does not match []` is enough. 

In this case, however, when we're expecting to get nothing and we got something, (and another comment I made suggested changing this to, essentially, `assert!(scheduler.get_jobs().is_empty())`), I think having the custom failure message print out what we did get is useful.

2023-07-19 16:48 UTC, carols10cents commented on compactor_scheduler/tests/local_scheduler/end_job.rs
> +    );
Wait, what? A compactor says "hey scheduler, mark this partition as skipped", and then we're asserting that the next call to `scheduler.get_jobs` returns that skipped partition...? That seems wrong...? What am I missing?

2023-07-19 16:51 UTC, carols10cents requested changes
Ok, I'm done with this pass, I still have some changes I'd like to see :)

2023-07-19 17:10 UTC, wiedld commented on compactor_scheduler/tests/local_scheduler/end_job.rs
> +    );
Yeah, this surprised me too. It appears that partition skipping is not enforced until part of the partition filtering (during IO) in the compactor. (Specifically in SkippedCompactionsSource.) Definitely think this could be moved into the scheduler -- do we want to make this as a followup ticket?

2023-07-19 19:16 UTC, Joe-Blount commented on compactor_scheduler/tests/local_scheduler/end_job.rs
> +        "cannot commit after complete"
shouldn't this assert message be something about completing it twice?  I don't think `end_job` does a commit?

2023-07-19 20:43 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/combos/throttle_partition.rs
> +    Lock,
Ah, I didn't understand why we were using this mutex before. TY!

2023-07-19 21:45 UTC, wiedld commented on compactor_scheduler/tests/local_scheduler/get_jobs.rs
> +        "no partitions found in next get_jobs() call"
Yeah, this is my brain getting it's wires crossed. I knew it was an expect message -- but failed to properly think about the messages. 🤦🏼‍♀️  (I kept having to over-ride my tendencies.) Will go review and fix all of the expect messages. TY!

2023-07-20 21:16 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/catalog_commit.rs
> +        }
Used a match, but did it slightly different to make more explicit. See [here](https://github.com/influxdata/influxdb_iox/pull/8216/commits/e0081d7289e632fc66b4b97eb6516cf2c343c664) and tell me what you think, please!

2023-07-20 21:19 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/combos/throttle_partition.rs
> +    Lock,
[Changed to using parking_lot mutex](https://github.com/influxdata/influxdb_iox/pull/8216/commits/27b40cb04effa2685d61555143d32b22315fe3ad) in almost all locations in scheduler.

Last location will be switched in separate PR (because paranoid, and want to isolate any behavioral change). Is noted on the [cleanup task list](https://github.com/influxdata/idpe/issues/17789#issuecomment-1599301745).

2023-07-20 21:20 UTC, wiedld commented on compactor/src/components/partition_done_sink/outcome.rs
> +        };
[Done](https://github.com/influxdata/influxdb_iox/pull/8216/commits/568d12a68f8af38f96c0a4f22f64b149890a3e3c). TY.

2023-07-20 21:21 UTC, wiedld commented on compactor_scheduler/tests/helpers.rs
> +macro_rules! can_do_upgrade_commit {
No reason. It's not variable length args, is function-like, and doesn't utilize the control flow of the callee function. Therefore, can move to using functions. [Done here](https://github.com/influxdata/influxdb_iox/pull/8216/commits/4d45970fe44ce5a7d59dc6c6103f1ad13c2a86db).

2023-07-20 21:27 UTC, wiedld commented on compactor_scheduler/tests/local_scheduler/get_jobs.rs
> +    );
This feedback, along with a few others, made me realize that the test setup could be done a lot cleaner. Made [this change](https://github.com/influxdata/influxdb_iox/pull/8216/commits/fd9cb8ae1428ea1835d18c6ef00ef6e63d2da249) which introduced the `TestLocalScheduler` struct. Then [these two tests](https://github.com/influxdata/influxdb_iox/blob/fd9cb8ae1428ea1835d18c6ef00ef6e63d2da249/compactor_scheduler/tests/local_scheduler/get_jobs.rs#L36-L57) confirm the starting/seeded hot partitions.

Please let me know if this is a better approach!

2023-07-20 21:28 UTC, wiedld commented on compactor_scheduler/tests/local_scheduler/get_jobs.rs
> +    );
The expected terms were cleaned up, across the integration test suite. TY for highlighting this need!

2023-07-20 21:28 UTC, wiedld commented on compactor_scheduler/tests/local_scheduler/get_jobs.rs
> +        "no partitions found in next get_jobs() call"
The expected terms were cleaned up, across the integration test suite. TY for highlighting this need!

2023-07-20 21:28 UTC, wiedld commented on compactor_scheduler/tests/local_scheduler/end_job.rs
> +        "cannot commit after complete"
The expected terms were cleaned up, across the integration test suite. TY for highlighting this need!

2023-07-24 15:58 UTC, carols10cents approved these changes
Phew, I think this is ready to go now! Ship it!

2023-07-24 15:58 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler/catalog_commit.rs
> +        let replacement_commit_is_ok = !delete.is_empty() && !create.is_empty();
Much clearer, thank you!!

2023-07-24 15:58 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler/combos/unique_partitions.rs
> -    Lock,
Love it!

2023-07-24 15:58 UTC, carols10cents commented on compactor_scheduler/tests/local_scheduler/end_job.rs
> +    );
👍🏻 Good call on documenting this surprising behavior with a test. Yeah, I think it would be better to filter out partitions marked as skipped before having the scheduler potentially sending them as jobs that can't be done. 

I'm trying to think if there's a potential race condition we'd introduce by moving the check (if so, we might need to have both checks) but I think that's a question for the followup ticket (that I do think would be worthwhile to file for prioritization).

2023-07-24 15:58 UTC, carols10cents commented on compactor_scheduler/tests/local_scheduler/mod.rs
> +pub struct TestLocalScheduler {
Lots cleaner, thank you! I love how this struct names everything it creates, and tests that don't need all the pieces don't have to explicitly ignore them. I also love the `get_partition_id` method that gives one place to get the partition id and the `assert_matches_seeded_hot_partition` method that gives a name to what you're testing.

2023-07-24 19:01 UTC, merged