feat: create table CLI
influxdata/influxdb_iox pull request #8307
Opened 2023-07-21 18:22 UTC by NGA-TRAN

Closes https://github.com/influxdata/influxdb_iox/issues/8250

1. Add `PartitionTemplateConfig` that is used by this PR to `create table CLI`  and for [create namespace](https://github.com/influxdata/influxdb_iox/issues/8251)2. 
2. Add `create table CLI`

Describe your proposed changes here.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-07-21 18:33 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +pub struct PartitionTemplateConfig {
@appletreeisyellow : I put this Config in a separate module for you to use without refactoring when you work on https://github.com/influxdata/influxdb_iox/issues/8251

2023-07-21 18:33 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
@carols10cents and @domodwyer : Are the format we want to support for time format? Are there available parser that I should use instead?

2023-07-21 18:33 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            "time" => return Err(Error::TimeAsTag()),
@carols10cents and @domodwyer : When I allowed `time`, it will be added as a `tag` column of the table. Later on, when I inserted data, I got error. This means the table is useless. Thus, I think it is better not to let user create `time` as tag in the first place

2023-07-21 19:27 UTC, NGA-TRAN commented
@appletreeisyellow If you find the command lines to play with IOx from create server to create database, tables to write data to read data and to access catalog locally useful, feel free to document them in a runbook

2023-07-21 21:09 UTC, appletreeisyellow commented
I tried to run the CLI in my local machine. I was looking into this command to start all-in-one server:

> ./target/debug/influxdb_iox -vv run all-in-one --object-store=file  --data-dir ~/iox_data3 --catalog-dsn=postgres:iox3 --wal-rotation-period-seconds=1

What kind of data do you have in `~/iox_data3`? Are they parquet files?

2023-07-21 21:27 UTC, NGA-TRAN commented
> I tried to run the CLI in my local machine. I was looking into this command to start all-in-one server:

>> ./target/debug/influxdb_iox -vv run all-in-one --object-store=file --data-dir ~/iox_data3 --catalog-dsn=postgres:iox3 --wal-rotation-period-seconds=1

> What kind of data do you have in ~/iox_data3? Are they parquet files?

Yes,  ~/iox_data3 is there we store data locally. They are parquet files. Also there is a `wal` folder inside it which I think ingester uses to store data before processing them to persist. You need to to create the `iox_data3` before running the command

2023-07-24 10:22 UTC, domodwyer reviewed
Looks great!

I think we can do less validation / be more permissive in the CLI and rely on the server doing the validation. Having one place where validation is performed it'll make it easier to work on in the future.

We should definitely have an e2e test that covers the default partition template :+1:

2023-07-24 10:22 UTC, domodwyer commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
Any arbitrary combination of formatters is allowed - we shouldn't validate in the CLI, but instead let the server return an error if it is invalid (and the CLI should show it).

That way we can change things on the server and not worry about old CLI users being broken.

Lets just accept a string and pass it to the server without validation :+1:

It'd be great to add an e2e test that tries to set an invalid formatter!

2023-07-24 10:22 UTC, domodwyer commented on influxdb_iox/src/commands/partition_template.rs
> +                    part: Some(proto::template_part::Part::TimeFormat(part.to_string())),
Technically there's no reason why not, but lets not add it unless we actually need it - it's kinda not useful, and just adds needless complexity.

I like keeping it at one :+1:

2023-07-24 10:22 UTC, domodwyer commented on influxdb_iox/src/commands/partition_template.rs
> +            "time" => return Err(Error::TimeAsTag()),
This should be unnecessary - the server should not allow you to do what you describe in this comment.

I created https://github.com/influxdata/influxdb_iox/issues/8320 to track it, but I don't think there's any harm keeping this check - `time` will **never** be allowed as a tag!

2023-07-24 10:22 UTC, domodwyer commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +async fn create_tables_write_and_query() {
It'd be great to include a test that asserts what **the default** partition template is as an e2e case when not specified by the user - so when the user does `influxdb_iox table create bananas`, assert the correct default partition template is assigned (the time-based `YYYY-MM-DD` one)

2023-07-24 10:22 UTC, domodwyer commented on influxdb_iox/src/commands/partition_template.rs
> +    TimeAsTag(),
There's no need for these suffixes `()` - you can just use `TimeAsTag`! 🚀

2023-07-24 15:52 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +async fn create_tables_write_and_query() {
@domodwyer : Oh, do you mean you want us to **explicitly** add default partition template `TimeFormat(%Y-%m-%d)` for this case? Currently, it is empty.

2023-07-24 16:00 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +async fn create_tables_write_and_query() {
I just chatted with Dom. I would probably does not change anything in the code (and keep the table's partition template empty). But I will verify in the e-2-e tests that this table partition will be understood as the day partition.

2023-07-24 16:40 UTC, carols10cents requested changes
Some suggestions and questions!

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +/// Partition template: a string of columns or time ofrmat each separated by a comma
Typo:

```suggestion
/// Partition template: a string of columns or time format each separated by a comma
```

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +    let mut parts = Vec::with_capacity(MAXIMUM_NUMBER_OF_TEMPLATE_PARTS);
I think it'd be better if it's possible to rewrite this as iterator transformations? That way, the `collect` will take care of allocating the correct size `Vec`.

I know there are other changes to be made to this, but I think the end result should look something like:

```
let mut time_format_count = 0;
let parts: Vec<_> = s.split(',')
    .filter(|part| !part.is_empty()) // Ignore empty parts
    .map(|part| {
        match part {
            // however you determine time vs tag, this should return `proto::TemplatePart`s
        }
    }
    .collect();
```

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
Will the determination of what's a time and what's a tag be whether there's a `%` in the string then?

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +                    part: Some(proto::template_part::Part::TimeFormat(part.to_string())),
Is there any concern about having different validations in the CLI vs on the server? Will, say, support people find it unreliable if they can create a partition template by sending a gRPC request directly but trying to do it through the CLI gets rejected?

I think that would be weird, and I would vote for removing this extra restriction in the CLI, but ultimately yinz know better than me :)

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +/// Partition template: a string of columns or time ofrmat each separated by a comma
Also I think this means commas can't be used as, say, part of the time format or the tag name? Is that consistent with the rest of the system? I forget.

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +        assert!(error.contains("error: invalid value '' for '--partition-template <PART_TEMPLATE>': Client Error: Invalid partition template"));
Are these `print`s deliberate? If they're for debugging purposes because this `assert!` will only return "expected true, got false", the [`assert_contains!` macro](https://github.com/influxdata/influxdb_iox/blob/acf9da233699ad7664645c078d83b7bc67e65f8f/test_helpers/src/lib.rs#L132-L141) takes care of making the failure messages better!

2023-07-24 16:40 UTC, carols10cents commented on influxdb_iox/src/commands/table/create.rs
> +    println!("{}", serde_json::to_string_pretty(&table)?);
Is leaving in this `println!` deliberate?

2023-07-24 17:37 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +/// Partition template: a string of columns or time ofrmat each separated by a comma
This is an example of a line in LP:
`t1,col1=nga,Col1=duy f1=17.5 160075616043434343`
This means commas are used to 
- separate measure/table with tags 
- separate between different tags
- separate between different fields.

Asked the same question and I did some tests last week and if you want commas as part of a table name, tag name or field name, you can easily do that by adding double quotes around.

So I would say it is consistent with the rest of the system

2023-07-24 17:37 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
Let me try to play with this and see what the best solution for us is.

2023-07-24 17:37 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +                    part: Some(proto::template_part::Part::TimeFormat(part.to_string())),
Hah, both are good idea. Let me do some both CLI and server testings. We may just simply remove restriction here

2023-07-24 17:37 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +        assert!(error.contains("error: invalid value '' for '--partition-template <PART_TEMPLATE>': Client Error: Invalid partition template"));
Good catch, I will remove the `print!`

2023-07-24 17:37 UTC, NGA-TRAN commented on influxdb_iox/src/commands/table/create.rs
> +    println!("{}", serde_json::to_string_pretty(&table)?);
I will be likely convert this into `info`

2023-07-24 18:05 UTC, wiedld commented
Still going through the commands, but have a few differences so far:
* get a parsing arg error, instead of the descriptive error:
     * `./target/debug/influxdb_iox -vv table create ns_3 t2 col1  --host http://localhost:8081`
        * expected: `error: should specify -p or --partition-template`
        * got: `error: unexpected argument 'col1' found`
     * `./target/debug/influxdb_iox -vv table create ns_3 t2 time col1  --host http://localhost:8081`
        * expected: `error: should specify -p or --partition-template`
        * got: `error: unexpected argument 'time' found`
     * `./target/debug/influxdb_iox -vv table create ns_3 t3 -p col1 col2  --host http://localhost:8081`
        * expected: `error: it must be col1,col2`
        * got: `error: unexpected argument 'col2' found`

2023-07-24 18:17 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
@domodwyer and @carols10cents : We need some discussion here.
We have an available [create_table](https://github.com/influxdata/influxdb_iox/blob/acf9da233699ad7664645c078d83b7bc67e65f8f/influxdb_iox_client/src/client/table.rs#L31) in `influx_iox_client` for creating a table that I just simply invoke. This function currently takes `PartitionTemplate` as input. In order for me to pass in `PartitionTemplate`, I need to parse the string into this format. This means I need to distinguish `TagValue` with `TimeFormat`.  I have just played with LPs write and  found that we do allow `%` in the name of a tag. For example, this line `t2,"col2%more"=aaa f2=30.3 1600223756160` will create a tag column named `col2%more`. This mean `%` should not be the only signal to say this is a time format.

So if we do not want to parse `TimeFormat` here, there is no way for me to know which one is `TimeFormat` and which one is `TagValue`.

So I guess we need to parse and validate it here. A solution maybe we use the same function in server and client to determine time format?

2023-07-24 18:20 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
A different solution is I will ask for 2 arguments, one is for time format and the other is for tag value. In that case, I can pass string to time format

2023-07-24 18:26 UTC, wiedld commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
I like the solution of keeping it separate. Otherwise we can silently create tags whenever we meant to create a timeFormat, but it didn't specifically match our expected time formatting (and therefore defaulted to a tag).

example:
`{"parts": [{"tagValue": "col1"}, {"tagValue": "%j.%Y"}]}`

2023-07-24 18:35 UTC, NGA-TRAN commented
@wiedld : Regarding your comment in https://github.com/influxdata/influxdb_iox/pull/8307#issuecomment-1648366250, The comments I put in the examples  are for us to see why they got errors, the expected errors are actually the ones you see. We use clap for the parsing job and they are consistent with all other commands.

2023-07-24 19:51 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
Having the time format and tags in different arguments constrains the partition template more than the protobuf does (I'm assuming you'd make the template be something like time format followed by the tags or vice versa, whereas the server would let you do something like `tag1, time format, tag2, tag3` if you wanted). I don't know enough about real-world partition templates to know whether this would be acceptable or not.

Also not sure if this is an option, but we store the partition templates in the catalog as JSON, so we do have a JSON deserializer. [Here's an example of a partition template in JSON format](https://github.com/influxdata/influxdb_iox/blob/02088995b2e5059bd8a227ff6c5790cb5fe28248/data_types/src/partition_template.rs#L1068-L1071).

2023-07-24 19:58 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +/// Partition template: a string of columns or time ofrmat each separated by a comma
> Asked the same question and I did some tests last week and if you want commas as part of a table name, tag name or field name, you can easily do that by adding double quotes around.

Ok, so if you wanted to make a partition template using a tag name that contained a comma, how would you do that via the CLI?

2023-07-24 20:40 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
>  tag1, time format, tag2, tag3

This is a good example. We need to support this.

> Also not sure if this is an option, but we store the partition templates in the catalog as JSON, so we do have a JSON deserializer, if users of this CLI could specify a JSON string. [Here's an example of a partition template in JSON format](https://github.com/influxdata/influxdb_iox/blob/02088995b2e5059bd8a227ff6c5790cb5fe28248/data_types/src/partition_template.rs#L1068-L1071).

```
let expected_json_str = "{\"parts\":[\
            {\"tagValue\":\"region\"},\
            {\"timeFormat\":\"year-%Y\"}\
        ]}";
```

This makes me think we should do the same for the CLI parser to avoid all kind of headache here and below. I think the input should be

`--partition-template {"tagValue": "col1"}, {"timeFormat": "%Y.%j"}, {"tagValue": "col3,col2"}`

One part will be in between {} and `"tagValue"` or "timeFormat" will distinguish them. The "" will help us to allow all kinds of tag names and time format

2023-07-24 20:45 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +/// Partition template: a string of columns or time ofrmat each separated by a comma
Great point, the new format here https://github.com/influxdata/influxdb_iox/pull/8307/files#r1272733429 will solve this problem. Hope you won't find any other corner cases 😆

2023-07-25 00:21 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
😬 I'd rather we lean on serde's JSON parsing and validation rather than trying to handle something that's sort-of-but-not-really JSON and all the ways a user could mess that up. Any reason the CLI couldn't be something like 

```
--partition-template '{"parts":[{"tagValue":"col1"},{"timeFormat":"%Y.%j"},{"tagValue":"col3,col2"]}'
```

with single quotes around the one, full JSON string? Or escaped double quotes inside one double-quoted full JSON string?

2023-07-25 03:55 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
OK, I successfully use serge_json to parse `{"parts":[{"tagValue":"col1"},{"timeFormat":"%Y.%j"},{"tagValue":"col3,col2"]}'`
Will update the PR to use it

2023-07-25 08:51 UTC, domodwyer commented on influxdb_iox/src/commands/partition_template.rs
> +                    part: Some(proto::template_part::Part::TimeFormat(part.to_string())),
Now we have the more expressive JSON format as the CLI arg, this restriction can definitely go away :+1:

2023-07-25 14:22 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +                    part: Some(proto::template_part::Part::TimeFormat(part.to_string())),
Exactly 👍

2023-07-25 20:54 UTC, NGA-TRAN commented on influxdb_iox/src/commands/table/create.rs
> +    println!("{}", serde_json::to_string_pretty(&table)?);
I have checked and tested. This is here on purpose to return the content of created table

2023-07-25 20:54 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +async fn create_tables_write_and_query() {
Added test to verify the sort key that use the right partition template after loading data

2023-07-25 20:55 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            | "%Y-%m-%dT%H:%M:%S%:z" => {
So much fun working on this. See the unit and end-to-end tests

2023-07-25 20:56 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            "time" => return Err(Error::TimeAsTag()),
Nice. I have verified it was fixed on main and merged to this branch. I have a test to verify this in this PR, too

2023-07-25 21:13 UTC, NGA-TRAN commented
@carols10cents and @domodwyer : I have addressed all the comments. It is fun to work on this feature. So much end-to-end tests 😄

2023-07-25 21:17 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/table.rs
> +            // TODO:  ask write team if we allow time format `whatever` (see partition key below)
@domodwyer and @savage-engineer : I think this should fail but it pass and the partition key has `whatever` instead of time. You may want to look into it

2023-07-25 21:17 UTC, NGA-TRAN commented on influxdb_iox/tests/end_to_end_cases/table.rs
> +        expected: vec!["whatever"],
@domodwyer and @savage-engineer : And this is the value of the partition key of the `{"TimeFormat": "whatever"}` which does not mean anything

2023-07-26 11:36 UTC, savage-engineer commented on influxdb_iox/tests/end_to_end_cases/table.rs
> +            // TODO:  ask write team if we allow time format `whatever` (see partition key below)
If I my understanding of strftime formatting is good, then this would be a valid formatter, just one that reformats every date-time to `"whatever"` (and that's why it doens't throw an error). The underlying `chrono::datetime::DateTime` formatter processes this without error. Whether we want to impose some extra constraints is probably a good question, but I don't know if this has already been discussed somewhere else.

2023-07-26 11:50 UTC, domodwyer approved these changes

2023-07-26 11:50 UTC, domodwyer commented on influxdb_iox/tests/end_to_end_cases/table.rs
> +            // TODO:  ask write team if we allow time format `whatever` (see partition key below)
You can include static strings in arbitrary time formatters: `%Y-bananas` is a perfectly valid formatter, as is `bananas`, it's just not very time-ful! 

If you want an invalid time formatter for testing, try a meaningless formatter like `%42`

2023-07-26 11:50 UTC, domodwyer commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +                        ));
This is nice - relying on the server for validation is 👌

2023-07-26 11:50 UTC, domodwyer commented on influxdb_iox/tests/end_to_end_cases/cli.rs
> +            Step::PartitionKeys{table_name: "m0".to_string(), namespace_name: Some(namespace.to_string()), expected: vec!["2021.116"]},
Nice! :+1:

2023-07-26 17:04 UTC, carols10cents commented
Sorry, I think I was unclear-- the `proto::PartitionTemplate` type _already_ supports JSON serialization that we use when serializing them to the database, so there wasn't a need to define new types to add serialization support onto. I've added a commit since that seemed easier to show what I mean!

2023-07-26 17:19 UTC, NGA-TRAN commented
@carols10cents Nice. Thanks. I will take care of the test failures

2023-07-26 17:20 UTC, carols10cents requested changes
A few more cleanups I'd like to see :) Thank you for the previous changes!

2023-07-26 17:20 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +        assert!(error.contains(
Could you change these to use `assert_contains!` please, as I mentioned in a previous comment? The error messages that macro gives are so much nicer :)

2023-07-26 17:20 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +        let partition_templat = PartitionTemplateConfig::try_parse_from([
Nit, for searchability of code: there are a bunch of instances after this point of variables named `partition_templat` that should be `partition_template`

2023-07-26 17:20 UTC, carols10cents commented on influxdb_iox/src/commands/partition_template.rs
> +            Some(generated_types::influxdata::iox::partition_template::v1::template_part::Part::TimeFormat(
These types make the tests harder to read; could you please add `use generated_types::influxdata::iox::partition_template::v1::template_part::Part` at the top of the tests module, so that this and similar places could be `Part::TimeFormat` and `Part::TagValue`?

2023-07-26 17:20 UTC, carols10cents commented on influxdb_iox/src/commands/table/create.rs
> +        assert_eq!(config.table, "table");
I think this part of the test that doesn't send a partition template would be better as its own test, and with this assertion: `assert!(config.partition_template_config.partition_template.is_none())`

2023-07-26 17:20 UTC, carols10cents commented on influxdb_iox/src/commands/table/create.rs
> +                },
This section here would also be a lot easier to read if the test module had more imports :)

2023-07-26 17:20 UTC, carols10cents commented on influxdb_iox/src/commands/table/create.rs
> +    use influxdb_iox_client::table::generated_types::PartitionTemplate;
So `influxdb_iox_client` re-exports `generated_types` types -- here's [what `influxdb_iox_cilent::namespace` re-exports](https://github.com/influxdata/influxdb_iox/blob/1a6aa1a8dc5ab8ea4a4dbc8a0aac2dfd304e6a7d/influxdb_iox_client/src/client/namespace.rs#L8-L14), and here's [what `influxdb_iox_client::table` re-exports](https://github.com/influxdata/influxdb_iox/blob/1a6aa1a8dc5ab8ea4a4dbc8a0aac2dfd304e6a7d/influxdb_iox_client/src/client/table.rs#L8-L14).

Because they're the same type, this doesn't really matter--except that we should be importing the types here from either `influxdb_iox_client` or `generated_types`, not both :)

And because this is the "create table" command, I think these types should all come from `influxdb_iox_client::table` (below in this module are some that are using `influxdb_iox_client::namespace`).

2023-07-26 17:21 UTC, carols10cents commented
Whoops, sorry about that, should just be case differences in the tag names!

2023-07-26 20:42 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +        let partition_templat = PartitionTemplateConfig::try_parse_from([
great catch

2023-07-26 20:43 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +        assert!(error.contains(
Done

2023-07-26 20:43 UTC, NGA-TRAN commented on influxdb_iox/src/commands/partition_template.rs
> +            Some(generated_types::influxdata::iox::partition_template::v1::template_part::Part::TimeFormat(
Done

2023-07-26 20:43 UTC, NGA-TRAN commented on influxdb_iox/src/commands/table/create.rs
> +                },
Done

2023-07-26 20:44 UTC, NGA-TRAN commented
Thanks @carols10cents for great catches and suggestions

2023-07-27 14:20 UTC, carols10cents approved these changes
Looks great now, thank you so much!

2023-07-27 15:03 UTC, merged