feat(idpe-17935): move filtering of skipped partitions to the scheduler
influxdata/influxdb_iox pull request #8358
Opened 2023-07-27 23:53 UTC by wiedld

Closes https://github.com/influxdata/idpe/issues/17935

Scheduler get_jobs() should not return skipped partitions.
Also, the catalog querying (to determine which are skipped) should be in a batch.

## Done in these steps:
1. catalog method to should accept multiple partitions. (commits 1-2)
1. provide scheduler ability to filter out skipped partitions, based in a batched catalog query. (commits 3-5)
1. make all tests pass. (commits 6-7)
     * only changes was file numbering. No other outcome changes.
1. remove skipped filtering from compactor (commit 8)
     * compactor was doing 1x catalog query per 1 partition id
1. make all tests pass. (commits 9-11)

---

* feat(idpe-17935): get_in_skipped_compaction() should perform for multiple partitions (52bac22f8)

* test(17935): add testing for the multiple get_in_skipped_compactions() (e52b9dccc)

* feat(idpe-17935): add the ability to perform transformation on sets of partitions (rather than filtering one  by one). Start with the transformation to remove skipped partitions. (35398a0fb)

      * new partitions_source implementation, which does the exclusion of skipped.
      * new mod/trait to enable catalog requests to find subsets of sets (e.g. find the subset which is skipped)

* feat(idpe-17935): skipped partitions are removed with the scheduler get_jobs() paritions_source (ed152c8be)

* refactor(idpe-17935): move the env var and cli flag setting, for when to ignore skipped partitions, to the scheduler config. Have the local scheduler setup adher to this setting. (5a506fb9a)

* test(idpe-17935): all_overlapping_l0_max_input_bytes_per_partition() has all the same output files, but the L0.# designation may have a different number (4bcd0cfe1)

* test(idpe-17935): update all_overlapping_l0_max_input_bytes_per_partition_small_max_desired_file_size() for change in numbering/naming of L0 files (5e531fd8d)

* feat(idpe-17935): remove partition skipping (and catalog query 1x per 1 partition) from the compactor (80a069222)

* test(idpe-17935): updates to random_backfill_over_l2s(), which results in same outcome of compaction (a470a4347)

* test(idpe-17935): update file numbering on all_overlapping_l0_max_input_bytes_per_partition() (3c32a2dc6)

* test(idpe-17935): update file numbering/names on all_overlapping_l0_max_input_bytes_per_partition_small_max_desired_file_size() (6c7fe2319)

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-07-27 23:56 UTC, wiedld commented on compactor/tests/layouts/backfill.rs
> -    - "L1.?[900,922] 1.05us 13mb                                                                               |--L1.?--| "
Slightly different outcome from first 18 runs: 3 files output with 100mb total, slightly more evenly distributed file sizes (with this change).

Note that the final compacted outcome, of this entire test, was the same.

2023-07-28 00:05 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/partitions_source/never_skipped.rs
> +            MockInclusionPartitionsSubsetSource::new(skipped),
Note the use of `set_transformer` variable naming. The `NeverSkippedPartitionsSource` implements PartitionsSource and is one of the pipelined abstractions in `scheduler.partitions_source`. However, it works a bit differently in that it effectively does set transformation (difference of partitions vs skipped).

We can choose to later apply this pattern to other partitions_source abstractions, with the goal of further batching up catalog queries used for partition filtering.

2023-07-28 00:06 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/partitions_subset_source/mock.rs
> +            .filter(|p| self.partitions.contains(p))
This mock is for an inclusion `PartitionsSubsetSource`.
If we continue with this pattern, we can make another generic mock for exclusion `PartitionsSubsetSource`.

2023-07-28 00:48 UTC, wiedld commented on compactor/tests/layouts/backfill.rs
> +    - "L2.589[150,165] 342ns 218mb                                       |L2.589|                                           "
All the other test cases only had changes based on file numbers (e.g. `L0.105` --> `L0.101`).

But for this test case `actual_case_from_catalog_1`, there was a slight difference in the ordering of the stdout of output files.

2023-07-28 19:12 UTC, Joe-Blount commented on compactor_scheduler/src/local_scheduler/partitions_source/never_skipped.rs
> +        let skipped = self.skipped_source.fetch(&partitions).await;
This gets all the skipped the partitions, right?  So it assumes that the number of skipped partition is small enough that we can get all of them at once...  That's probably true right now, but may not always be true :thinking:

2023-07-28 21:16 UTC, Joe-Blount commented on compactor/tests/layouts/backfill.rs
> +    - "L2.589[150,165] 342ns 218mb                                       |L2.589|                                           "
they're ordered by number, so when the number changes, the order can change :+1:

2023-07-28 21:27 UTC, wiedld commented on compactor/tests/layouts/backfill.rs
> +    - "L2.589[150,165] 342ns 218mb                                       |L2.589|                                           "
TY!

2023-07-28 21:33 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/partitions_source/never_skipped.rs
> +        let skipped = self.skipped_source.fetch(&partitions).await;
It does not get all of the skipped partitions; instead it uses the subset query.

This never_skipped abstraction 
 => uses the [subset abstraction](https://github.com/influxdata/influxdb_iox/blob/02ced805a2a3ee811947dd6d71ef8b61317f637f/compactor_scheduler/src/local_scheduler/partitions_subset_source/skipped.rs#L41) 
=> which then makes a SQL query of [SELECT * FROM skipped_compactions WHERE partition_id = ANY($1);](https://github.com/influxdata/influxdb_iox/blob/02ced805a2a3ee811947dd6d71ef8b61317f637f/iox_catalog/src/postgres.rs#L1421).

2023-08-02 15:04 UTC, carols10cents requested changes
Some questions and suggestions that can be resolved with changes or explanations!

2023-08-02 15:04 UTC, carols10cents commented on compactor_scheduler/src/local_scheduler.rs
>          };
This `match` is introducing some duplication -- there's now 2 calls to `CatalogToCompactPartitionsSource::new` that look the same (and would need to be updated should we change that), 2 calls to `CatalogAllPartitionsSource::new`, and 2 calls to `NeverSkippedPartitionsSource::new`/`SkippedPartitionsSource::new`. 

Could this be refactored to something like:

```
let mut partitions_source = match &config.partitions_source_config {
   // contents of the `match` that was here before this PR
};

if !config.ignore_partition_skip_marker {
    partitions_source = Arc::new(NeverSkippedPartitionsSource::new(
        partitions_source,  
        SkippedPartitionsSource::new(backoff_config, Arc::clone(&catalog)),
    ))
}
```

In other words, create the partitions source as usual, then if directed, wrap that partitions source in the `NeverSkippedPartitionsSource`? 

This is more like what the compactor did in compactor/src/components/hardcoded.rs.

Please let me know if I'm missing a reason this couldn't be done that way!

2023-08-02 15:06 UTC, carols10cents commented on compactor/tests/layouts/backfill.rs
> +    - "L2.589[150,165] 342ns 218mb                                       |L2.589|                                           "
I don't really understand why the file numbers changed though? This is a more general question for these snapshot tests than I'm expecting this PR to resolve, but are these tests really useful if they change frequently with irrelevant changes? If the numbers aren't important/relevant to the correctness, should they appear in the snapshot at all? @Joe-Blount @wiedld

2023-08-02 15:55 UTC, wiedld commented on iox_catalog/src/postgres.rs
>          let skipped_partition_record = rec.map_err(|e| Error::SqlxError { source: e })?;
Doing so in all locations. TY!

2023-08-02 16:11 UTC, Joe-Blount commented on compactor/tests/layouts/backfill.rs
> +    - "L2.589[150,165] 342ns 218mb                                       |L2.589|                                           "
I look at them a lot for following a file through the compaction.

2023-08-02 16:55 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/partitions_subset_source/skipped.rs
> +    #[allow(dead_code)]
Since I was getting all tests/clippy to pass per commit, was adding this annotation only temporarily. Then it was not needed after the subsequent commits, but I forgot to remove.

To prevent this occurring in the future, I tried to find a linter rule about unused dead_code annotations. But I couldn't find one.
(note: looked [here](https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint_defs/builtin/index.html), [here](https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint/builtin/index.html), [here](https://doc.rust-lang.org/clippy/lint_configuration.html) and [here](https://rust-lang.github.io/rust-clippy/master/index.html). 😅 )

2023-08-02 16:55 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/partitions_source/never_skipped.rs
> +    #[allow(dead_code)]
fixed.

2023-08-02 16:58 UTC, wiedld commented on compactor_scheduler/src/local_scheduler/partitions_source/never_skipped.rs
> +        );
No good reason. Should be assert_eq. Changed.

2023-08-02 17:16 UTC, wiedld commented on iox_catalog/src/mem.rs
> +        let find: HashSet<PartitionId> = partition_ids.iter().map(|p| p.to_owned()).collect();
Changed.

2023-08-02 19:46 UTC, wiedld commented on iox_catalog/src/interface.rs
>              .get_in_skipped_compactions(&[other_partition.id])
Adding more comprehensive test coverage was a good idea, since it helped uncover a bug in the sqlite code. Pushed the [(failing) commit with the more comprehensive test coverage](https://github.com/influxdata/influxdb_iox/pull/8358/commits/de6733868fba5bf3e4389c394f21e65c363428c6), and then pushed the [sqlite fix](https://github.com/influxdata/influxdb_iox/pull/8358/commits/b4277b9183f915a08e54549352abb30ab90f9dc8).

2023-08-02 20:04 UTC, wiedld commented on compactor_scheduler/src/local_scheduler.rs
>          };
Can be done that way. Fixing.

2023-08-03 18:01 UTC, carols10cents approved these changes
Just one more little change please! (I hit approve, I trust you to apply the change)

2023-08-03 18:01 UTC, carols10cents commented on iox_catalog/src/interface.rs
> +            .unwrap();
I'm glad this test is useful! Can we add one more value here that should *not* be returned (and also not cause any errors), the [`non_existing_partition_id`](https://github.com/influxdata/influxdb_iox/blob/1138a5907c449b595b35d3fb6da7b078de552b97/iox_catalog/src/interface.rs#L1523)? So change this call to:

```suggestion
        // confirm can fetch both skipped compactions, and not the unskipped one
        let skipped_partition_records = repos
            .partitions()
            .get_in_skipped_compactions(&[
                partition.id,
                to_skip_partition.id,
                to_skip_partition_too.id,
                non_existing_partition_id,
            ])
            .await
            .unwrap();
```

but leave the assertions as-is.

2023-08-03 18:43 UTC, merged