fix(influxql): FILL(linear) for selectors
influxdata/influxdb_iox pull request #8396
Opened 2023-08-02 16:24 UTC by mhilton

Closes #8302 

Ensure that selector functions such as FIRST, LAST, MIN and MAX can use LINEAR filling in the same way as influxdb 1.8. This is done by explanding the arrays in a StructArray and filling each one individually. For linear filling only the "value" array is filled linearly all other arrays are filled with null. This is consistent with influxdb 1.8.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-08-02 16:38 UTC, wolffcm requested changes
Thank you Martin!

This looks nice, but I think some more tests are required:
- an end-to-end test using `date_bin_gapfill` in SQL would be good
- add a test to `iox_query/src/exec/gapfill/exec_tests.rs` that also varies input and output batch sizes. This will exercise code that needs to keep state across record batches which will not happen in the end-to-end tests.

2023-08-02 16:38 UTC, wolffcm commented on iox_query/src/exec/gapfill/algo.rs
> +#[derive(Debug, Clone)]
Rather than implement `Clone` here, can you use the `clone_for_aggr_col` method instead? Values of this type should not be cloned willy-nilly, I don't think, and there are prior uses of this method for similar reasons that you are doing now.

2023-08-02 16:38 UTC, wolffcm commented on iox_query/src/exec/gapfill/algo/interpolate.rs
> +                    })
I think that you want to ensure that the state of cursor reflects what `build_aggr_fill_interpolate` does, so it would be good to null-fill all the other columns first with a cloned cursor, and then finish with the `value` column, without cloning.

2023-08-04 15:19 UTC, mhilton commented on iox_query/src/exec/gapfill/algo.rs
> +#[derive(Debug, Clone)]
Done

2023-08-04 19:14 UTC, wolffcm reviewed
This is looking very close. I had one remaining concern. Happy to chat on Monday about if you like as I think parts of this might be kind of subtle.

2023-08-04 19:14 UTC, wolffcm commented on iox_query/src/exec/gapfill/exec_tests.rs
> +}
These tests are looking very nice. Thanks for writing them.

I have one more concern and I'm not sure you've covered it here.

The code that does the gap filling makes the assumption that we will have buffered enough input to produce one complete output batch. For most fill strategies we can just look at the number of input rows, but linear interpolation is different. If an aggregate column is sparsely populated (lots of nulls), we need to keep reading input until we find a value in there that can serve as the endpoint of an interpolated segment, or until the series keys change. The logic for that is here:
https://github.com/influxdata/influxdb_iox/blob/f5b5bc9c53f9498f48ad2b56959b1444af27a637/iox_query/src/exec/gapfill/buffered_input.rs#L122

If we are interpolating a struct column, then we need to be specifically looking at the `value` field within the struct. So I think that will need to be updated, and there also should probably be an accompanying test.

2023-08-24 15:25 UTC, mhilton commented on iox_query/src/exec/gapfill/exec_tests.rs
> +                - +----+--------------------------+------------------------+
Yes the struct array has null values and the primitive array can also be null. The reason there are no blank rows is that the way the test generates the struct array it always makes the struct non-null, only making the internal arrays null as appropriate.

2023-08-24 19:12 UTC, alamb approved these changes
I reviewed this code and past comments and I think we should proceed with merging this after adding the additional  test that @wolffcm 
 describes here: https://github.com/influxdata/influxdb_iox/pull/8396#discussion_r1284757060 

Once that test is written (and any code fixes required to get it to pass) then all comments will have been addressed (and I also think the code and tests are looking quite nice -- great job @mhilton )

2023-08-24 19:12 UTC, alamb commented on influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
> +| 2022-10-31T02:00:02 | 99.0  | 99.0         |
I don't know how influxql works, but it as an outsider it is somewhat strange to see these examples where  `FILL(linear)` applies only to columns with aggregates / selectors but `FILL(99)` applies to all the selected columns.

2023-08-24 19:12 UTC, alamb commented on iox_query/src/exec/gapfill/exec_tests.rs
> +}
I think this kind of test could be achieved using a dataset similar to what is in this PR with a few more sequential time/struct cols that are `None` /`Null`--  

And then perhaps sets the input / output batch sizes to small values to force the boundary logic:

```
        for output_batch_size in [7,5,1] {
            let input_batch_size = 3;
            let records = TestRecords {
```

2023-08-25 07:06 UTC, mhilton commented on influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected
> +| 2022-10-31T02:00:02 | 99.0  | 99.0         |
This is consistent with influxql's existing behaviour. I agree it is confusing though.

2023-08-25 07:07 UTC, mhilton commented on iox_query/src/exec/gapfill/buffered_input.rs
>  }
@alamb This test was intended to cover the case suggested by @wolffcm in [#8396 (comment)](https://github.com/influxdata/influxdb_iox/pull/8396#discussion_r1284757060).

Is there something about it that I've missed?

2023-08-25 18:54 UTC, alamb commented on iox_query/src/exec/gapfill/buffered_input.rs
>  }
I think think this is good go go!

2023-09-06 09:44 UTC, merged