feat: gRPC interface for ingester->querier v2
influxdata/influxdb_iox pull request #8443
Opened 2023-08-07 14:37 UTC by crepererum

Note that the actual "to/from bytes" conversion for the schema and batches will be implemented in #8347.

Closes #8346.

2023-08-07 15:00 UTC, alamb commented on generated_types/protos/influxdata/iox/ingester/v1/query.proto
> +syntax = "proto3";
There appears to already be a Ingester / Querier gRPC proto file here: 

https://github.com/influxdata/influxdb_iox/blob/main/ingester_query_grpc/protos/influxdata/iox/ingester/v1/query.proto

Perhaps we should add the new requests / responses to the same location to keep things easier to discover?

It appears to have been done in https://github.com/influxdata/influxdb_iox/pull/7789 -- Perhaps @carols10cents  has more thoughts on the matter

2023-08-07 16:25 UTC, carols10cents commented on generated_types/protos/influxdata/iox/ingester/v1/query.proto
> +syntax = "proto3";
The `generated_types` crate is for *external* gRPCs; the `ingester_query_grpc` crate is for *internal* gRPC APIs that external clients don't need to know about/pull in the dependencies for.

> why do we have two crates for this now?

Answered in the PR Andrew linked to: https://github.com/influxdata/influxdb_iox/pull/7789#discussion_r1193843684

2023-08-09 14:42 UTC, carols10cents requested changes
Two spots that need to be updated to reflect recent changes to partition identification that v2 will need as well; one question that I'm not sure matters or not.

2023-08-09 14:42 UTC, carols10cents commented on ingester_query_grpc/protos/influxdata/iox/ingester/v2/query.proto
> +    int64 id = 1;
This needs to be `oneof` `catalog_id` or `hash_id` now, like it is in v1: https://github.com/influxdata/influxdb_iox/blob/7a462754e4123c76244ec9df571e6d923cbd06d2/ingester_query_grpc/protos/influxdata/iox/ingester/v1/query.proto#L83-L104

2023-08-09 14:42 UTC, carols10cents commented on ingester_query_grpc/protos/influxdata/iox/ingester/v2/query.proto
> +  int64 partition_id = 1;
And here needs to be `oneof` `catalog_id` or `hash_id` too

2023-08-09 14:42 UTC, carols10cents commented on ingester_query_grpc/src/lib.rs
> +        if field_columns.is_some() {
Is it ever possible that the querier would send `Some([])` (`Some` empty set) for `field_columns`? I suppose it's our own fault if it does. 

I wonder if these checks are pointing to a need for a new `Predicate` type that doesn't have `field_columns`, `range`, `value_expr` at all?

2023-08-09 15:01 UTC, crepererum commented on ingester_query_grpc/src/lib.rs
> +        if field_columns.is_some() {
yeah, we should probably not use `Predicate` here AT ALL but `Vec<Expr>` directly. `Predicate` is a leftover from the InfluxRPC storage API and I plan to remove it from the querier internals anyways: #8097. I'll adjust the gRPC interface...

2023-08-10 09:23 UTC, crepererum commented on ingester_query_grpc/src/lib.rs
> +        if field_columns.is_some() {
done

2023-08-10 09:23 UTC, crepererum commented on ingester_query_grpc/protos/influxdata/iox/ingester/v2/query.proto
> +  int64 partition_id = 1;
done

2023-08-10 09:24 UTC, crepererum commented on ingester_query_grpc/protos/influxdata/iox/ingester/v2/query.proto
> +    int64 id = 1;
done

2023-08-10 17:59 UTC, carols10cents approved these changes
A few tiny typos I trust you to resolve. Much better though, thanks!

2023-08-11 09:52 UTC, merged