fix: Garbage collect old, empty partition catalog records
influxdata/influxdb_iox pull request #8448
Opened 2023-08-07 20:08 UTC by carols10cents

Fixes https://github.com/influxdata/influxdb_iox/issues/8417

In the same manner as the garbage collector deletes old Parquet file catalog records.

Oldness of a partition is determined by its `new_file_at` field. Emptiness is determined by looking for any Parquet file records (without regard to whether they're marked `to_delete` or not, so that the partition record should never get deleted before all its parquet file records are)

Notably, this will NOT delete partitions that never had any Parquet files generated for them, as in that case we don't know how old the partition record is (its `new_file_at` field will be NULL, which is also the case for a new partition whose Parquet files haven't been persisted yet). I don't know how often that happens in production; hopefully not very often.

I'm mildly frightened by this change because it deletes stuff. If there's a lower risk way to evaluate whether this is working or not (don't actually delete, only log what IDs would be selected for deleting and someone with production access checks the correctness?), I'm very willing to make those changes.

This also isn't urgent, so waiting until @domodwyer is back and can review is fine (but the more eyes the better!

2023-08-07 20:26 UTC, philjb commented
> if there's a lower risk way to evaluate whether this is working or not (don't actually delete, only log what IDs would be selected for deleting and someone with production access checks the correctness?), I'm very willing to make those changes.

If you look in the adjacent directories, you'll see that retention flagger and objectstore deleter have a "dry run" flag option passed through that turns the GC it a "I'll just tell you want i'm going to do instead of doing it kinda mode" - you could implement that for the partition deleter - I think its a decent idea. Perhaps a separate/new dry-run mode so all the GC doesn't go into dry-run mode would be best: `--dry-run-parition-deleter` or some such.

2023-08-07 20:41 UTC, philjb commented
If i write to a day, say Aug 7th, and i'm partitioning by day with 30day retention and then I don't write to it for 150 days so it falls out of retention and backup retention and the parquet files and the partition are deleted, and then I write to Aug 7th again (say I've modified the retention now to 1 year), is there a problem with having to create a new partition with new ids? 

Does it matter?

I'm looking at the `partition` table schema and I'm not sure what all the fields are used for.

```
iox_catalog_prod=> \d partition
                                    Table "iox_catalog.partition"
          Column           |       Type        | Collation | Nullable |           Default
---------------------------+-------------------+-----------+----------+------------------------------
 id                        | bigint            |           | not null | generated always as identity
 shard_id                  | bigint            |           |          |
 table_id                  | bigint            |           | not null |
 partition_key             | character varying |           | not null |
 sort_key                  | text[]            |           | not null |
 persisted_sequence_number | bigint            |           |          |
 to_delete                 | bigint            |           |          |
 new_file_at               | bigint            |           |          |
 hash_id                   | bytea             |           |          |
 sort_key_ids              | bigint[]          |           |          |
Indexes:
    "partition_pkey" PRIMARY KEY, btree (id)
    "partition_hash_id_unique" UNIQUE CONSTRAINT, btree (hash_id)
    "partition_key_unique" UNIQUE CONSTRAINT, btree (table_id, partition_key)
    "partition_new_file_at_idx" btree (new_file_at)
Foreign-key constraints:
    "partition_table_id_fkey" FOREIGN KEY (table_id) REFERENCES table_name(id) ON DELETE CASCADE
Referenced by:
    TABLE "parquet_file" CONSTRAINT "parquet_file_partition_hash_id_fkey" FOREIGN KEY (partition_hash_id) REFERENCES partition(hash_id)
    TABLE "parquet_file" CONSTRAINT "parquet_file_partition_id_fkey" FOREIGN KEY (partition_id) REFERENCES partition(id) NOT VALID
    TABLE "skipped_compactions" CONSTRAINT "skipped_compactions_partition_id_fkey" FOREIGN KEY (partition_id) REFERENCES partition(id) ON DELETE CASCADE
```


Looks like @NGA-TRAN add the `to_delete` for `partition` table in late 2022, but I think as partitions can non-time based, implementing _retention_ on partitions becomes less general. BUT that field could be used to implement soft partition delete - but I'm not sure i see a need for that (unless other users of the `partition` table want to filter on `to_delete`).

btw, `new_file_at` is updated in a trigger for each row that is inserted into the `parquet_file` table.

2023-08-07 20:54 UTC, NGA-TRAN commented
If IIRC, Dom fixed a critical bug in delete partition to not let us delete it or something related to it. Delete partition is trickier than delete parquet files. I am not sure if we ever delete partition after that fix. the `to_delete` will depend on that fix/decision

2023-08-07 21:06 UTC, philjb commented on iox_catalog/src/sqlite.rs
> +        OR parquet_file.partition_hash_id = partition.hash_id
I'm not sure this query is going to perform. With a LIMIT of 5, it took about 2 minutes on a production region. Here's the explain
```
 Limit  (cost=0.00..4864750.62 rows=5 width=8)
   ->  Nested Loop Anti Join  (cost=0.00..213793141325.27 rows=219737 width=8)
         Join Filter: ((parquet_file.partition_id = partition.id) OR (parquet_file.partition_hash_id = partition.hash_id))
         ->  Seq Scan on partition  (cost=0.00..43507.66 rows=236701 width=41)
               Filter: (new_file_at < '1682665200000000000'::bigint)
         ->  Materialize  (cost=0.00..9146863.32 rows=36998288 width=41)
               ->  Seq Scan on parquet_file  (cost=0.00..8636690.88 rows=36998288 width=41)
```

I believe this is saying that it is sequential scanning `parquet_file` for each partition.id it finds. There are a lot of parquet file rows (37 million). (I'm not a postgres explain expert).

I think you're going to need a different way to verify there are no parquet files associated with a partition. 

or add an index on partition_id and partition_hash_id on parquet_file table (not a small index - 37 million rows too!). 
```
iox_catalog_prod=> select 1 from parquet_file where partition_id=37554701;
 ?column?
----------
        1
(1 row)

Time: 55077.094 ms (00:55.077)
```
is slow just to find one row with a specific partition id (not a real id).

I put some other information from the internal region into this internal ticket: https://github.com/influxdata/idpe/issues/17994

2023-08-07 21:08 UTC, philjb requested changes
We're gonna need a bigger boat. - the query isn't performant. 

I picked request changes to signal that it needs to be looked at carefully. I personally don't need to approve the final version of this pr (just dismiss by review if needed).

2023-08-08 08:53 UTC, crepererum commented
From a querier PoV this should be OK given that this only deletes "long gone" partitions for which the GC has already pruned the files.

2023-08-09 13:34 UTC, carols10cents commented on iox_catalog/src/sqlite.rs
> +        OR parquet_file.partition_hash_id = partition.hash_id
yikes, I thought there were indexes on here :(

> I think we should wait til the deterministic hash ID migration is finished,

This PR was intended to be part of the migration-- currently, there is nothing "aging out" old partitions without hash IDs. 

If we instead decide to add hash IDs to old partitions (which maybe we have to for the infinite retention partitions @philjb mentioned [over here](https://github.com/influxdata/influxdb_iox/issues/8417#issuecomment-1668583790)), then we either have to:

- Also copy the partitions' Parquet files to new locations in object storage (as partitions with hash IDs use those in their Parquet files' object store paths)
- Add a new boolean column (ex `legacy`) that determines where we look in object storage for that partition's Parquet files, to use instead of the absence of a hash ID

2023-08-28 17:04 UTC, carols10cents commented
Ok, given the feedback above and after chatting with Dom, it's no longer looking like this work is worth the trouble. It might be someday.

2023-08-28 17:04 UTC, closed without merging