feat: read null sort_key_ids
influxdata/influxdb_iox pull request #8489
Opened 2023-08-14 19:58 UTC by NGA-TRAN

Closes https://github.com/influxdata/influxdb_iox/issues/8486

Due to the incident last Friday https://github.com/influxdata/idpe/issues/18019 that lead to the revert https://github.com/influxdata/influxdb_iox/pull/8477, I want to be cautious this time. This PR is read NULL `sort_key_ids` and add a lot of tests to verify the values.

1. The tests can be more than needed but they will help in next few PRs to verify empty  array,`{}`,  for insert tests and has values for update tests.
2. I want to ask the reviewers about ColumnDecode of NULL array. I think it should wok since all tests work but I want to hear from others.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-08-14 20:31 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        assert!(partition.sort_key_ids.is_none());
For this PR, all test partitions will be verified with NULL (None) `sort_key_ids`. 
  . Next PR that modifies insert partitions, they will be empty array `{}` for both insert and update partition test cases.
  . A PR later that updates partition's `sort_key_ids`, the value of test sort_key_ids will be `{}` for insert partitions and have specific values for update partitions.

So all of verification NULL asserts in this PR will be valuable for verifying different values in the next few PRs. This is the key for NOT hitting sqlx's ColumnDecode issue that we hit last Friday

2023-08-14 21:13 UTC, carols10cents commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
So this is one way to handle the problem. Another way is to set this to `ColumnSet` but annotate the field with [`#[sqlx(default)]`](https://docs.rs/sqlx/latest/sqlx/trait.FromRow.html#default), and if `sort_key_ids` isn't present in the query results, it'll get the default `ColumnSet` (which is `ColumnSet(vec![])`).

Another solution could be to write a migration that does:

```
UPDATE partition
SET sort_key_ids = '{}';
```

and then in another deploy, after verifying that there are no partitions that have `NULL` `sort_key_ids`, run another migration that requires `sort_key_ids` not be NULL. 

Is there a reason for choosing this solution over the others?

2023-08-14 21:16 UTC, carols10cents commented on iox_catalog/src/interface.rs
> +        assert!(updated_other_partition.sort_key_ids.is_none());
I don't think adding these assertions everywhere is really providing much value or assurance that this isn't going to crash; we could assert lots of things that we don't expect to change all over the place, but that isn't really providing value. This seems like it's adding lots of places that will need to be updated, maintained, or deleted in the future....

2023-08-14 21:18 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +// TODO: ask Carol where persisted_sequence_number is stored because there is no such filed in Partition struct
It's not stored anywhere; it just gets ignored. `persisted_sequence_number` can probably be removed from this `SELECT` now, but in a separate PR.

2023-08-14 21:24 UTC, carols10cents commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Related: https://github.com/influxdata/influxdb_iox/pull/4801

2023-08-14 21:27 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +        // At later step, we will convert it to NOT NULL when we know that all existing data has been updated.
If we decide to go this direction rather than doing a migration that inserts empty array and then sets a NOT NULL constraint, take a look at some tests I've added for cases like this-- they have to be added to postgres/sqlite specifically, because the application won't let you create records in the old state so you have to put raw SQL in the tests. Here's one that makes a partition without a hash id: https://github.com/influxdata/influxdb_iox/blob/964b2f6b9737df75cd0f4e1cee96e03ce70a4d40/iox_catalog/src/postgres.rs#L2192-L2210

2023-08-14 21:33 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
So her are the option:
1. This PR solution `pub sort_key_ids: Option<ColumnSet>`
2. Carol's solution 1:  `pub sort_key_ids: ColumnSet>` plus [#[sqlx(default)]](https://docs.rs/sqlx/latest/sqlx/trait.FromRow.html#default), and if sort_key_ids isn't present in the query results, it'll get the default ColumnSet (which is ColumnSet(vec![])).
3.  `ALTER partition ALTER COLUM  sort_key_ids SET NOT NULL  default {}`. This won't affect catalog performance becasue the default won't get updated to the existing data at all. Postgres only do it when the data rows are used

I do not think the `UPDATE partition ...` is a choice because there are always new partitions created and sort_key_ids  end up to be NULL until a few more tickets we plan to do is done.

I vote for either first (this PR) or the third option.

2023-08-14 21:33 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +        assert!(updated_other_partition.sort_key_ids.is_none());
While I agree there are a lot of asserts and we may not need all, I do think we need at least 70% of these asserts for the next few PRs where the NULL will be either empty array `{}` or arrays with actual values. Thus they look redundant in this PR, they will be very valuable in the next few PRs. I would leave all of them here and I will remove the redundant ones in the next few PRs after they are converted to `{}` or arrays with actual values

2023-08-15 00:37 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Thinking more. NULLvalue is the trouble maker that has caused all trouble. **We should avoid that in the first place** if possible and this case we can because we have not used `sort_key_ids` yet. I propose we go with **option 3** above. 

I will

1.  Have a PR to do `ALTER partition ALTER COLUM  sort_key_ids SET NOT NULL  default {}`.
2. Then I will modify here to make it `pub sort_key_ids: ColumnSet,`
3. Then I can remove a lot of tests here. Only keep some representative tests.

2023-08-15 08:19 UTC, crepererum commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Please do NOT use `default`. There's a reason that NULL is THE postgres marker for missing data and using a sentinel value makes debugging, migrating and reading the data way harder. Please handle NULLs in the Rust code base.

2023-08-15 08:21 UTC, crepererum commented on data_types/src/columns.rs
> +        Self(ids.into_iter().map(ColumnId::new).collect())
This is invalid because it breaks Eq and Co. Internally the data is sorted, so please just use the `new` method that does this:

```suggestion
        Self::new(ids.into_iter().map(ColumnId::new).collect())
```

2023-08-15 13:59 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Let us stick with option 1 that handle NULL (this PR) then

2023-08-15 13:59 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +        // At later step, we will convert it to NOT NULL when we know that all existing data has been updated.
Let me explore @carols10cents's comment above to understand and use it

2023-08-15 15:33 UTC, NGA-TRAN reviewed
@carols10cents and @crepererum : I have addressed all your comments. Can you re-review this? If this is approved by by 2pm ET today, I will merge it and observe how it works on Serverless. Otherwise, I will merge it first thing tomorrow

2023-08-15 15:33 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +        // At later step, we will convert it to NOT NULL when we know that all existing data has been updated.
@carols10cents 2 tests with same name `existing_partitions_without_sort_key_ids` have been added for Postgres and sqlite

2023-08-16 08:52 UTC, crepererum requested changes

2023-08-16 08:52 UTC, crepererum commented on data_types/src/columns.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, sqlx::Type)]
Is `Defaults` actually needed here?

2023-08-16 08:52 UTC, crepererum commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
`ColumnSet` is the WRONG type here. It's a set (and internally normalizes the order), you want a "sorted set". Please introduce as new type `SortedColumnSet`.

Sorry, I should have caught this during the first round.

2023-08-16 14:45 UTC, carols10cents commented on iox_catalog/src/interface.rs
> +        assert!(updated_other_partition.sort_key_ids.is_none());
So the part I'm not understanding is, under what circumstances would, say, only 1 or 2 out of these assertions would fail but not all of them? Put another way, what problem(s) are these assertions guarding against?

If they're guarding against having an incorrect initial database state, then we only need one of these, because if one fails, then they'll all fail. 

Is it likely that a code change in the next few PRs will spuriously make, say, `PartitionRepo::get_by_id` but NOT `PartitionRepo::create_or_get` return partitions with non-`None` `sort_key_ids`? That doesn't seem very likely to me. I'm just having trouble imagining the failure scenarios here.

2023-08-16 14:48 UTC, carols10cents commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Why does `ColumnSet` hold a `Vec` rather than a `HashSet` actually? I was going to submit a PR to change its name when I saw it was a `Vec` because I didn't look closely at `ColumnSet::new` where the actual set implementation is.

2023-08-16 14:50 UTC, NGA-TRAN commented on data_types/src/columns.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, sqlx::Type)]
You eyes catch things better than auto clips 🙂 . Everything works after removing `Default`

2023-08-16 14:54 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
@crepererum `ColumnSet` is define as: `pub struct ColumnSet(Vec<ColumnId>);` which I think `ColumnIds` will stay in the order of `Vec<ColumnId>` and are sorted. In the PR that was reverted last Friday and I am working on it locally right now, I had tests that show their orders.

If you do not think the `pub struct ColumnSet(Vec<ColumnId>);` is the right way, what is the `SortColumnSet` looks like?

Actually, @carols10cents is the one who introduced `ColumnSet` in this case and I have agreed. What do you think Carol?

2023-08-16 14:56 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Haha, Carol and I added comment concurrently

2023-08-16 15:00 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +        assert!(updated_other_partition.sort_key_ids.is_none());
@carols10cents See [my second PR here](https://github.com/influxdata/influxdb_iox/pull/8494) that depends on this PR addressed your concern. I only keep necessary tests and also added comments for those tests. Actually this add-and-remove-with-comments exercise helps me a lot to understand the needed tests and available tests.

2023-08-16 15:01 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +        assert!(partition.hash_id().is_none());
The assertions on the hash_id aren't relevant here; those were only relevant for the `hash_id` migration tests.

2023-08-16 15:04 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +        assert!(partition.sort_key_ids.is_none());
And this`sort_key_ids` assertion isn't relevant for the `hash_id` test. These are more unit-style tests and should only be testing one thing. In fact, this test should probably be inserting an empty array for `sort_key_ids` to accurately test a partition that doesn't have a hash ID in the catalog but DOES have `sort_key_ids` set.

2023-08-16 15:05 UTC, crepererum commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
`ColumnSet` is a SET (as the type says) and the fact that it is internally using a `Vec` is irrelevant for its semantic. This type is already used for the parquet file entries and there the ordering doesn't matter (however Postgres doesn't have a set type, so the typical way to implement this is by using a sort-normalized vector/array).

2023-08-16 15:06 UTC, carols10cents commented on iox_catalog/src/postgres.rs
> +        assert!(table_partitions[0].sort_key_ids.is_none());
To me, this assertion here covers all the other assertions added after a call to `PartitionRepo::create_or_get` because if something is wrong in `create_or_get`, this test will fail. All the others seem redundant to this one, to me.

2023-08-16 15:28 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
@crepererum, @carols10cents and I have a quick chat and we agree on creating a new type `SortedColumnSet` for this that:
1. Type: pub struct SortedColumnSet(Vec<ColumnId>);
2. Its `new` function will keep the column order of the input

I am working on this

2023-08-16 18:07 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +        assert!(table_partitions[0].sort_key_ids.is_none());
Yeah, there should a few places for different purpose that I added in the comments

2023-08-16 18:08 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub sort_key_ids: Option<ColumnSet>,
Done

2023-08-16 18:09 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +        // todo: ask Carol/Dom/Andrew/Marco whether the note above (empty array `{}`) is a must becasue this PR does not follow this for `sort_key_ids`.
I also remove the no-longer-valid existing comments

2023-08-16 18:17 UTC, NGA-TRAN commented on iox_catalog/src/postgres.rs
> +        assert!(partition.sort_key_ids.is_none());
Since this PR does not yet insert anything into sort_key_ids, I will add empty sort_key_ids in this test in my next PR that implements empty sort_key_ids

2023-08-17 08:19 UTC, crepererum approved these changes
Small nitpick regarding the duplication check, this probably doesn't need another round of reviews after fixing.

2023-08-17 08:19 UTC, crepererum commented on data_types/src/columns.rs
> +        assert_eq!(len_pre_dedup, len_post_dedup, "set contains duplicates");
IIRC `Vec::dedup` only works on sort-normalized vectors. However you don't wanna mess with the sort order. I see two options: remove the check or make it slightly more advanced:

```rust
let mut columns_sorted = columns.clone();
columns_sorted.sort();
let len_pre_dedup = columns_sorted.len();
columns_sorted.dedup();
let len_post_dedup = columns_sorted.len();
assert_eq!(len_pre_dedup, len_post_dedup, "set contains duplicates");
```

and then continue with the normal `columns` (NOT w/ `columns_sorted`!):

```rust
columns.shrink_to_fit();
Self(columns)
```

2023-08-17 16:03 UTC, NGA-TRAN commented on data_types/src/columns.rs
> +        assert_eq!(len_pre_dedup, len_post_dedup, "set contains duplicates");
Used the advanced one and al added 2 tests for it according

2023-08-18 14:15 UTC, merged