feat: file sort_key_idsw when partition is inserted and updated
influxdata/influxdb_iox pull request #8517
Opened 2023-08-17 20:53 UTC by NGA-TRAN

Closes https://github.com/influxdata/influxdb_iox/issues/8486, https://github.com/influxdata/influxdb_iox/issues/8445

This PR depends on https://github.com/influxdata/influxdb_iox/pull/8489

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-08-18 08:27 UTC, crepererum requested changes
Couple of things that I would like to see fixed before merging.

Side note: the PR would have been easier to review if it wouldn't have included #8494.

2023-08-18 08:27 UTC, crepererum commented on iox_catalog/src/interface.rs
> +pub(crate) fn verify_sort_key_length(sort_key: &[&str], sort_key_ids: &SortedColumnSet) {
this should document what "verify" mean as part of the docstring, not inline within the method.

2023-08-18 08:27 UTC, crepererum commented on iox_catalog/src/interface.rs
> +        new_sort_key_ids: &SortedColumnSet,
please adjust the docstring to clearly state that the "compare" in CAS is currently ONLY implemented for the name-based sort key, NOT for the IDs. This needs to be fixed AFTER this PR and the PG migration are merged.

2023-08-18 08:27 UTC, crepererum commented on querier/src/parquet/mod.rs
> +            // verify the partition has the correct sort key and sort key ids
why is this assertion here? it has nothing to do w/ this specific test. I would expect that the `update_sort_key` call above that is part of `iox_tests` work. Tests get really hard to read, understand, and maintain if there are a bunch of irrelevant assertions scattered around.

2023-08-18 08:27 UTC, crepererum commented on querier/src/cache/partition.rs
> +        // verify the sort key
same comment as in `querier::parquet`: why is this assertion here?

2023-08-18 08:27 UTC, crepererum commented on querier/src/cache/parquet_file.rs
> +        // read the partition and check its sort key
why does this has a catalog test? This has nothing to do with the parquet file cache.

2023-08-18 10:02 UTC, domodwyer reviewed
Looking good! We'll have to be careful to clean things up. (especially the CAS stuff) after this is done.

2023-08-18 15:25 UTC, NGA-TRAN commented on querier/src/cache/parquet_file.rs
> +        // read the partition and check its sort key
This test calls [create_parquet_file](https://github.com/influxdata/influxdb_iox/blob/5d17a99dbb0e4a141aa1ad234cbf23f2585dca2e/querier/src/cache/parquet_file.rs#L302) which goes and update the partition. In general they are all tests and I tried to verify that the tests are setup well but from your comments, I rethink and I do not need to test the outer layer of tests that invokes `cas_sort_key ` that is already tested well

2023-08-18 15:25 UTC, NGA-TRAN commented on querier/src/cache/partition.rs
> +        // verify the sort key
Similar to the response above, I will remove this test because it actually just test of test

2023-08-18 15:25 UTC, NGA-TRAN commented on querier/src/parquet/mod.rs
> +            // verify the partition has the correct sort key and sort key ids
Ditto.

2023-08-18 20:51 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +    Deferred(Arc<DeferredLoad<(Option<SortKey>, Option<SortedColumnSet>)>>),
@domodwyer This is related to the change that the `fetch` function returns both SortKey and its columns IDs. I think it should store in here for the deferred load, too. Let me know if you think otherwise

2023-08-18 20:51 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +        new_sort_key_ids: &SortedColumnSet,
I have added a todo right below the docstring

2023-08-18 20:51 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +pub(crate) fn verify_sort_key_length(sort_key: &[&str], sort_key_ids: &SortedColumnSet) {
Done

2023-08-18 20:51 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +}
Done

2023-08-18 20:52 UTC, NGA-TRAN commented on querier/src/cache/parquet_file.rs
> +        // read the partition and check its sort key
I have removed the test of the test (aka the asserts)

2023-08-18 20:52 UTC, NGA-TRAN commented on querier/src/parquet/mod.rs
> +            // verify the partition has the correct sort key and sort key ids
Removed.

2023-08-18 20:53 UTC, NGA-TRAN commented on querier/src/cache/partition.rs
> +        // verify the sort key
Done

2023-08-18 20:54 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +    }
I have updated the existing `tech` function. As a result (yes, positive), the `Deferred(Arc<DeferredLoad<Option<SortKey>>>),` has become `Deferred(Arc<DeferredLoad<(Option<SortKey>, Option<SortedColumnSet>)>>),` which I did tagged you there

2023-08-18 20:54 UTC, NGA-TRAN commented on ingester/src/persist/worker.rs
> +{
Great suggestion. Done

2023-08-18 20:59 UTC, NGA-TRAN commented
@crepererum and @domodwyer : I have addressed all your comments

2023-08-21 08:54 UTC, crepererum approved these changes

2023-08-21 14:26 UTC, merged