feat: have ingester's SortKeyState include sort_key_ids
influxdata/influxdb_iox pull request #8556
Opened 2023-08-23 15:26 UTC by NGA-TRAN

The first PR of https://github.com/influxdata/influxdb_iox/issues/8555

This PR make the ingester's `SortKeyState` also include `sort_key_ids` which is the first step to fetch and use `sort_key_ids` instead of `sort_key`.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-08-23 15:35 UTC, NGA-TRAN commented on data_types/src/partition.rs
> +    pub fn sort_key_ids_none_if_empty(&self) -> Option<SortedColumnSet> {
This function plays the same role as `sort_key()` but for sort_key_ids. The ingester uses the function `sort_key()` a lot to get `None` when the sort key is empty. So I create this function to use in the corresponding places.

2023-08-24 15:42 UTC, savage-engineer commented on iox_catalog/src/interface.rs
> +    ValueMismatch(T, Q),
Why is `CasFailure` explicitly taking two generic arguments? I'd return a tuple `(Vec<String>, Option<SortedColumnSet>)` that can be a single `T` to avoid over specialising the error.

2023-08-24 15:42 UTC, savage-engineer commented on iox_catalog/src/sqlite.rs
> -                    crate::partition_lookup(self, partition_id)
I think this change wouldn't be needed if the pair was returned as a tuple.

2023-08-24 15:42 UTC, savage-engineer commented on ingester/src/persist/worker.rs
> +        }
Why is this clone & set needed if our update was accepted?

2023-08-24 16:10 UTC, NGA-TRAN commented on ingester/src/persist/mod.rs
> +            // assert_eq!(sort_key_ids, &SortedColumnSet::from([1, 3]));
I would say checking they are unique and the same length with sort_key_columns are adequate for now and I will use it. I would say in the future, we may want to have a way to verify they are IDs of `region` and `time`.

Thanks for this great suggestion when we have no other option to map IDs for now @savage-engineer

2023-08-24 16:10 UTC, NGA-TRAN commented on ingester/src/persist/worker.rs
> +        }
The original code below also use `clone` so I think it is the right way

2023-08-24 16:10 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +    ValueMismatch(T, Q),
Good idea. Let me make it only T of a tuple

2023-08-24 16:13 UTC, savage-engineer commented on ingester/src/persist/worker.rs
> +        }
Ah I completely missed that red block below 😆 

Thanks!

2023-08-24 16:15 UTC, savage-engineer commented on ingester/src/persist/worker.rs
> +        }
I wonder whether it's worth including the `new_sort_key_ids` in that `debug!` log line below. 🤔

2023-08-24 18:40 UTC, NGA-TRAN commented on iox_catalog/src/sqlite.rs
> -                    crate::partition_lookup(self, partition_id)
The change is still needed because we want to get 2 values `sort_key` and `sort_key_ids` from the partition

2023-08-24 18:49 UTC, NGA-TRAN commented on iox_catalog/src/interface.rs
> +    ValueMismatch(T, Q),
Done

2023-08-24 18:49 UTC, NGA-TRAN commented on ingester/src/persist/worker.rs
> +        }
Good idea. Added and need to move debug! up to that

2023-08-31 14:24 UTC, domodwyer requested changes
I only got half way through the review (I have a meeting but wanted to get us moving with a review)

We **need to test** the concurrent sort key update case - it's too dangerous to not have coverage for.

2023-08-31 14:24 UTC, domodwyer commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
Might be worth a defensive check to be sure we don't corrupt if things are broken:

```suggestion
        assert!(new_sort_key.is_some() ^ new_sort_key_ids.is_some());
        
        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
```

Please update the call documentation:

```
/// The caller MUST provide exactly one of the arguments as a Some, and the other MUST be a None.
```

That's how it should work right? We should include this in other function docs.

2023-08-31 14:24 UTC, domodwyer commented on ingester/src/buffer_tree/partition/resolver/catalog.rs
> +            SortKeyState::Provided(p.sort_key(), p.sort_key_ids_none_if_empty()),
Lets do the length/option assert on these too before calling this constructor - that way stop ourselves from using clearly broken sort keys before they touch any data.

2023-08-31 14:24 UTC, domodwyer commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +                    (partition.sort_key(), partition.sort_key_ids_none_if_empty());
More asserts! MORE! (we can put one here too, which has the same effect - catch bad input before it starts being used)

2023-08-31 14:24 UTC, domodwyer commented on ingester/src/persist/context.rs
> +    ) {
How is it that this function always has a sort key with names, and the other functions only sometimes have a sort key with names?

2023-08-31 14:24 UTC, domodwyer commented on ingester/src/persist/mod.rs
> +                // in test setup
Sorry Nga - this needs testing - we can't risk this happening because the impact is too severe - it's too easy to change the code and break this, and wind up with data corruption.

2023-08-31 19:58 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
I will add the assert.

Regarding the comment `The caller MUST provide exactly one of the arguments as a Some, and the other MUST be a None.` It is not like that. Both `new_sort_key` and `new_sort_key_ids` must be Some.  

To avoid changing so much in the code, the `SortKeyState` will store both `sort_key` and `sort_key_ids`. This PR is to add `sort_key_ids` into it.

2023-08-31 19:58 UTC, NGA-TRAN commented on ingester/src/persist/context.rs
> +    ) {
Can you point to the other functions, Dom? I have worked on many PRs at the same time and I am not sure what other functions are

2023-08-31 19:58 UTC, NGA-TRAN commented on ingester/src/persist/mod.rs
> +                // in test setup
I will chat with you to see how we change the test setup to get columnIDs of the could name here. Form @savage-engineer 's comment here https://github.com/influxdata/influxdb_iox/pull/8556#discussion_r1304460185, we currently verify the length only. I would love to have the columns IDs

2023-08-31 20:19 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
Added the assert.
I also updated the doc but a bit different from your comment

2023-08-31 20:19 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +                    (partition.sort_key(), partition.sort_key_ids_none_if_empty());
Added

2023-08-31 20:19 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/catalog.rs
> +            SortKeyState::Provided(p.sort_key(), p.sort_key_ids_none_if_empty()),
Added

2023-08-31 20:59 UTC, NGA-TRAN commented on ingester/src/persist/mod.rs
> +                // in test setup
Hah, actually it is very simply. Not sure why I could not find it before 😄 
Done

2023-09-01 09:17 UTC, savage-engineer commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
If both must be `Some`, why take two `Option`?

2023-09-01 10:07 UTC, savage-engineer commented on ingester/src/persist/handle.rs
> +        assert_matches!(loader.get_sort_key().await, None);
Should this test perhaps also test against the return value of `loader.get_sort_key_ids()`?

2023-09-01 11:46 UTC, domodwyer commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
> To avoid changing so much in the code, the SortKeyState will store both sort_key and sort_key_ids. This PR is to add sort_key_ids into it.

Yeah I think this is the correct thing to do 👌 

> @domodwyer is there a reason this originally took just an Option<SortKey> parameter?

I think it was a mistake on my part - @NGA-TRAN if it always must be `Some` (which I'm pretty sure it should be) then the signature should probably not have `Option` at all and just take the two types :+1:

2023-09-01 12:37 UTC, domodwyer reviewed
Thanks Nga! I think we should be good after this 👍

2023-09-01 12:37 UTC, domodwyer commented on ingester/src/persist/context.rs
> +        new_sort_key_ids: Option<SortedColumnSet>,
I guess this will become:

```suggestion
        new_sort_key_ids: SortedColumnSet,
```

When we remove the options in https://github.com/influxdata/influxdb_iox/pull/8556/files#r1312789990 :+1:

2023-09-01 12:37 UTC, domodwyer commented on ingester/src/persist/worker.rs
> +                    {
Lets make this a bit more robust - if the sort keys with column names is identical, the sort keys with IDs MUST be identical:

```suggestion
                    Err(CasFailure::ValueMismatch((observed_sort_key, observed_sort_key_ids)))
                        if observed_sort_key == new_sort_key_str =>
                    {
                        // Invariant: if the column name sort keys match, the sort
                        // key IDs must also match.
                        assert_eq!(&observed_sort_key_ids, Some(&new_sort_key_colids));
```

The way the code is currently wrote, if the catalog becomes corrupt, the ingester will use it. With this, at least we'll stop!

2023-09-01 15:51 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
@domodwyer and @savage-engineer :
I think removing `Option` here will need to do in  different PR. Here is the reason:

The argument `new_sort_key_ids: Option<SortedColumnSet>` is passed down all the way from reading the `sort_key_ids` from the partition catalog. And due to the needs of the migration process, this catalog `sort_key_ids` field was defined as NULL at first  and, as the result, it needs to return as Option<SortedColumnSet> in the `Partition` struct. Even though this catalog field it is NOT NULL now after last week migration, we need a different PR to make it  `SortedColumnSet` in the `Partition` struct instead of option first. This change will affect a lot of other code changes in all components, not only the Ingester.

So the proposal is we keep it as Option here and we check if of `Some` and in a future PR, where we replace partition's Option<SortedColumnSet> with SortedColumnSet, the option will be automatically removed here.

I know this is a bit pain but this is how things work for this migration so far. So many small steps to ensure things work correctly and the code changes for each PR are not too much

2023-09-01 16:25 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
Another option is I will remove the option here and `set_partition_sort_key` but I need to do `Some` check at a different place. Let me approach with that

2023-09-01 16:34 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
I also found another reason we do not want to remove Option here yet and should do it in a different PR.
If you look at the SortKeyState https://github.com/influxdata/influxdb_iox/blob/7a6de3d422e45db3d3cd7974d37e7e79134dbb48/ingester/src/buffer_tree/partition.rs#L30, they are all Options. If we remove Option here, we should remove option there, too and will lead to a lot of other code changes. I think let us keep them Option here and in a future PR in which the purpose is to remove Option only and everywhere, it will be a lot clearer

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/persist/handle.rs
> +        assert_matches!(loader.get_sort_key().await, None);
Added

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        self.sort_key = SortKeyState::Provided(new_sort_key, new_sort_key_ids);
So I ended up remove Options here and in set_partition_sort_key, too.
What I do not do is to remove Options from `SortKeyState` which will be done in a separate PR as stated above

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/persist/context.rs
> +    ) {
Ah, I have added ac comment for this function

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition.rs
> +        assert!(new_sort_key.is_some() & new_sort_key_ids.is_some());
Done

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/catalog.rs
> +        verify_matched_sort_key_andsort_key_ids(&p_sort_key, &p_sort_key_ids);
Done

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/persist/context.rs
> +        new_sort_key_ids: Option<SortedColumnSet>,
Done

2023-09-01 21:19 UTC, NGA-TRAN commented on ingester/src/persist/worker.rs
> +                    {
Done

2023-09-05 10:04 UTC, domodwyer approved these changes
Very nice - very clean change! 🎉 

The asserts should give us reasonable confidence that nothing is going wrong too 👌

2023-09-05 10:04 UTC, domodwyer commented on ingester/src/persist/context.rs
> +    /// remove the sort_key from the SortKeyState and remove it from this method, too
This is excellent - so helpful 👌

2023-09-05 19:05 UTC, NGA-TRAN commented
I will merge this PF after https://github.com/influxdata/influxdb_iox/pull/8674 is deployed for a few hours or a day

2023-09-05 20:40 UTC, NGA-TRAN commented
Merging this as the compactor PR above has run for a while without any incidents

2023-09-05 20:41 UTC, merged