feat: ingester reads `sort_key_ids` instead of `sort_key`
influxdata/influxdb_iox pull request #8588
Opened 2023-08-28 20:10 UTC by NGA-TRAN

Closes https://github.com/influxdata/influxdb_iox/issues/8555

This the third and final PR that [teaches ingester to use sort_key_ids](https://github.com/influxdata/influxdb_iox/issues/8555). The other 2 previous PRs are necessary pluming works: https://github.com/influxdata/influxdb_iox/pull/8556 and https://github.com/influxdata/influxdb_iox/pull/8579

This PR is blocked by https://github.com/influxdata/influxdb_iox/issues/8467

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-08-29 09:30 UTC, domodwyer commented
I thought we were pausing this work - does this need reviewing / is it ongoing?

2023-08-29 14:25 UTC, NGA-TRAN commented
@domodwyer 
> I thought we were pausing this work - does this need reviewing / is it ongoing?

Let us continue reviewing this and we will chat to see when we merge this later

2023-08-29 17:26 UTC, NGA-TRAN commented
@domodwyer 
> Can we decide first? it takes time to do proper reviews, and there's quite a few changes in this series of PRs - I don't want to waste everyone's time

Per our discussion [here](https://influxdata.slack.com/archives/CRK9M8L5Q/p1693323640211779?thread_ts=1693319741.731959&cid=CRK9M8L5Q) with @8none1 , let us move this forward. We will work with CST team to deploy the PRs in order

2023-09-12 18:33 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +        SortKey::from_columns(names.iter().map(|s| &**s))
@crepererum : I saw in recent PR you said this `from_columns` function is expensive. How about here?

2023-09-12 18:36 UTC, NGA-TRAN commented
@crepererum @domodwyer and @savage-engineer : This PR is ready for review. It is the third one in the series of `ingester consumes sort_key_ids`. This is the actual consumption one. The previous 2 PRs are pluming

2023-09-13 12:06 UTC, savage-engineer commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +}
This could probably be written to consume a column iterator and simplify the iterator chaining a little. Haven't measured this change performance-wise (or looked in Godbolt), but thought I'd leave it here for discussion.

```suggestion
// build sort_key from sort_key_ids and columns
// panic if the sort_key_ids are not found in the columns
pub(crate) fn build_sort_key_from_sort_key_ids_and_columns<I>(
    sort_key_ids: &Option<SortedColumnSet>,
    columns: I,
) -> Option<SortKey>
where
    I: Iterator<Item = Column>,
{
    let mut column_names = columns.map(|c| (c.id, c.name)).collect::<hashbrown::HashMap<_, _>>();
    sort_key_ids.as_ref().map(|ids| {
        SortKey::from_columns(ids.iter().map(|id| {
            column_names
                .remove(id)
                .expect(format!("cannot find column names for sort key id {}", id.get()).as_str())
        }))
    })
}
```

2023-09-13 12:06 UTC, savage-engineer commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +}
I think regardless it'd be good to include the missing ID in the panic message 👍

2023-09-13 13:36 UTC, domodwyer requested changes
Why are we keeping both sort keys?! I thought we were removing the column-based sort key, and using only the ID-based sort keys?

We shouldn't keep both - keeping two in memory forever is exactly the sort of "code risk" we've been discussing recently, and forces unnecessary catalog queries into the hot path.

2023-09-13 13:36 UTC, domodwyer commented on ingester/src/buffer_tree/partition/resolver/catalog.rs
> +                self.get_columns(table_id)
Why do we do this? We resolve the sort key columns at persist time right? You added it recently:

https://github.com/influxdata/influxdb_iox/blob/f02b17e52342c0c08b2ec42386e4b183d3922233/ingester/src/persist/worker.rs#L184

So why do we need to resolve it here as well?

2023-09-13 14:32 UTC, domodwyer reviewed
So this **isn't the final PR** - there will be one after this that removes the old sort key columns from the ingester ❤️ 

We should aim to merge that as soon as we're happy, to remove the extra query load :+1:

2023-09-13 14:32 UTC, domodwyer commented on ingester/src/buffer_tree/partition/resolver/catalog.rs
> +        assert_eq!(sort_key, p_sort_key);
This is awesome :+1:

2023-09-13 14:44 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/catalog.rs
> +                self.get_columns(table_id)
They are different, Dom. Over there is `writing`. We need to get columns before persisting. Here, we are `reading` and from now on, we only read `sort_key_ids` and hence need to read columns to convert `sort_key_ids` back into `sort_key`.

**For a clear context:**
In the design discussion with @crepererum and @alamb  before, we decided for now we still keep `sort_key` in the code to avoid too much changes. Hence the work will be:
1. At read time (this PR): we will read `sort_key_ids` and columns; and then use them to build `sort_key`. The code continues using `sort_key` as is.
2. At write time (PR a few weeks ago), we use columns to convert `sort_key` back to `sort_key_ids` and then store `sort_key_ids`
3. In the future, if we want to optimize using `sort_key_ids` only in the code, we will change it independently with this migration epic.

So this PR is the final of the series `reading (aka consuming) sort_key_ids`. There will be another PR that stops reading `sort_key` which I categorize it in a different series. Sorry for the confusion

2023-09-13 14:44 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +}
Thanks @savage-engineer . I will use it

2023-09-13 14:47 UTC, NGA-TRAN commented
> Why are we keeping both sort keys?! I thought we were removing the column-based sort key, and using only the ID-based sort keys?

> We shouldn't keep both - keeping two in memory forever is exactly the sort of "code risk" we've been discussing recently, and forces unnecessary catalog queries into the hot path.

@domodwyer and I have chatted and we have resolved this. Short answer, this is the final PR of this series of consumption. There will be another PR to stop reading `sort_key` and removing it from the `Partition struct`

2023-09-13 15:40 UTC, NGA-TRAN commented on ingester/src/buffer_tree/partition/resolver/sort_key.rs
> +}
Done

2023-09-14 09:50 UTC, domodwyer approved these changes

2023-09-14 14:06 UTC, merged