feat(ingester): Automatically recover from an incomplete WAL write
influxdata/influxdb_iox pull request #8666
Opened 2023-09-04 17:53 UTC by savage-engineer

Will close #8613.

I believe this covers our bases fairly well.

---

* docs(wal): Clearly document why `UnableToReadNextOps` is returned (b6e8b9cc5)

      Nothing currently relies on this public error variant, but for automatic
      recovery we need the WAL to provide a contract that this error is
      returned only when the next operation in the WAL is unsalvageable.

* refactor(ingester): Use generic `SequencedWalOp` batched reader for WAL replay (7d8cc83f2)

      This decouples the implementation of the `ClosedSegmentFileReader` from
      the ability to replay batches of `Vec<SequencedWalOp>`s, making it easy
      to test.

* refactor(ingester): Tie `SegmentId` to WAL op batch iter during WAL replay (c72b2412c)

* feat(ingester): WAL replay automatic recovery from incomplete WAL write (350d99377)

      When we come across an `UnableToReadNextOps` error during Ingester
      start-up it means that one of two things has happened:

        1. Ingester crashed mid-flush to WAL, so the write entry is incomplete
           and the user received an error.
        2. The WAL segment file has been corrupted in a way which cannot be
           recovered from. The format does not allow for recovery of a bad
           entry.

      In either case we can safely drop the WAL file after all good entries
      have been replayed and persisted so as not to block recovery.

      See https://github.com/influxdata/influxdb_iox/issues/8613 for more
      details.

2023-09-04 18:41 UTC, savage-engineer commented on ingester/src/init/wal_replay.rs
> +        if let Err(err @ wal::Error::UnableToReadNextOps { .. }) = batch {
I don't believe that there's any difference in our ability to recover from errors thrown from [this code](https://github.com/influxdata/influxdb_iox/blob/main/wal/src/blocking/reader.rs#L46-L103), so the inner error should be immaterial.

2023-09-04 18:41 UTC, savage-engineer commented on ingester/src/init/wal_replay.rs
> +        if let Err(err @ wal::Error::UnableToReadNextOps { .. }) = batch {
We could perhaps capture this case being hit through metrics like we do with `empty_op_count_metric`, but I'm not sure how much signal this will give us considering it reset on startup.

Let me know if it's be helpful to add!

2023-09-04 18:41 UTC, savage-engineer commented on ingester/src/init/wal_replay.rs
> +                    source: wal::blocking::ReaderError::LengthMismatch {
I had thought about wrapping the `Iterator` in a layer that converts from `wal::Error` to something defined in this module for decoupled testing, but not sure it is worth it.

2023-09-05 14:58 UTC, domodwyer requested changes
I think we need to be more selective with this - the case we want to recover from is **only** truncated files (early end-of-file errors) - any other error (such as checksum failures) should not result in us automating it into the ether.

It'd be good to make sure / add tests that assert checksum failures don't cause the WAL replay to be aborted (nor any other error you can think of that isn't early EOF related).

2023-09-06 13:33 UTC, savage-engineer commented on wal/src/blocking/reader.rs
> +        }?;
The WAL reader now disambiguates between an `UnexpectedEof` in the read of the data and other kinds of io error, by returning a new `IncompleteEntry` error up the stack.

2023-09-06 13:33 UTC, savage-engineer commented on ingester/src/init/wal_replay.rs
> +                source: wal::blocking::ReaderError::IncompleteEntry { .. },
With the new error disambiguation, WAL replay now only swallows the specific `IncompleteEntry` error. The tests below cover a set of `source` errors we wouldn't want to swallow when encountering `UnableToReadNextOps` to assert this behaviour.

2023-09-06 13:33 UTC, savage-engineer commented on wal/src/blocking/reader.rs
> +        assert_error!(read_fail, Error::IncompleteEntry { .. });
The two existing test cases here cover the return of the new error type. The underlying decompressing read seems to hit `UnexpectedEof` both when the compressed length is shorter than expected, or when the input is less than the expected compressed length.

This covers the kind of error we've previously seen and seems reasonable to me, but worth a double check @domodwyer - I'm less certain about [this test case for `too_long_len`](https://github.com/influxdata/influxdb_iox/pull/8666/files/350d99377488bf0011a56d6ca70a17dc973319e9..d05380db097af24567332145182b8bf13f3b11bf#diff-8232dfb5c6ff010b57358073593cb15f4a9c270c419e050503ed94e683ba633bR275), but I don't think there's any way to trivially disambiguate. They both fail with the same `ErrorKind`.

2023-09-12 12:31 UTC, domodwyer requested changes
Looking better! Lets keep closing that danger window :+1:

2023-09-12 12:31 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +            error!(%err, ?segment_id, "unable to recover further op batches from wal segment");
This sounds like something unexpected has happened that is fatal, when in fact we're handling it:

```suggestion
            warn!(%err, ?segment_id, "detected truncated WAL write, skipping replay for file");
```

2023-09-12 12:31 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +        match replay_sequenced_op_batches(reader, sink, &ok_op_count_metric, &empty_op_count_metric)
Can we keep this `replay_file()`? I know it's replaying an abstract type that is an iterator, but it's _replaying WAL files_ so it's good to keep that clear :+1:

2023-09-12 12:31 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +        }
I think this error handling should go up a level and live in the file-level driver loop as it's a problem with a file - this will let us track how many files we see this happen to.

We should only ever see one file that contains a truncated write - a server that crashes leaves a bunch of complete files, and exactly one active file laying around. Only that active file can contain a legitimate incomplete write. A server that starts up with those files replays them entirely and then deletes them, so there can never be >1 file that contains a truncated write.

Additionally it has to always be the _last file_, because the active file is always the latest file, so this logic should be applied **only to the last file** in the file processing loop :+1: Anything else is a fatal error.

This will help us avoid applying this logic to the incorrect cases, and minimise the probability of false-positives causing data loss.

2023-09-12 12:31 UTC, domodwyer commented on wal/src/blocking/reader.rs
> +        }?;
I'd suggest passing the IO error up in the original `UnableToRead` error and match on `UnableToRead(io::UnexepectedEof)` in the caller specifically - that way there's not two errors with overlapping concerns for callers to muddle up. Translating between errors often gets messy, and the WAL files will always _be_ files, so there will always be the possibility of IO errors, so it's totally legit to pass up/not abstract away.

2023-09-15 15:54 UTC, savage-engineer commented
I've moved the truncation check logic up to the file iteration loop as suggested, so that we can limit the behaviour to the most recent file.

I ended up turning the WAL methods into a trait so that the behaviour can be properly tested with _some_ level of abstraction from the WAL implementation itself. Feels a little bit gnarlier than it perhaps could be but it hopefully does the job.

2023-09-15 15:55 UTC, savage-engineer commented on ingester/src/init/wal_replay.rs
> +
This metric could be binned if you don't think it adds any value - I figured the visibility might be useful for quantifying how often we encounter this.

2023-09-18 12:38 UTC, domodwyer reviewed
I think we're nearly there :+1:

2023-09-18 12:38 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +    ReadEntry(wal::Error, Option<SequenceNumber>),
Would be good to comment on what the significance of the IDs is :+1:

2023-09-18 12:38 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +
It can't hurt :+1:

I'd maybe rejigger it to be expressed as success/failure:

* `result: success`
* `result: error, reason: truncated`

That makes aggregating easier, and "whole" might be a weird state if we introduce more failure modes that are tolerated (that have nothing to do with truncation). It'd be easy to add more failure modes this way :+1:

2023-09-18 12:38 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +        match replay_result? {
I think it might be easier to express these states in the match? That way we can see the various states that are picked out easily rather than spreading it across the iteration and the match, and we don't have to have a `map()` that doesn't map anything / non-pure fn.

Something like:

```rust
        match replay_result {
            Ok(v @ Some(_)) => max_sequence = max_sequence.max(v),
            Err(WalReplayError::ReadEntry(
                wal::Error::UnableToReadNextOps {
                    source: wal::blocking::ReaderError::UnableToReadData { source, .. },
                    ..
                },
                ..,
            )) if source.kind() == std::io::ErrorKind::UnexpectedEof => todo!(),
            // etc...
```

2023-09-18 12:38 UTC, domodwyer commented on wal/src/blocking/reader.rs
> +        other.context(UnableToReadDataSnafu)?;
Accidental change?

2023-09-18 12:40 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +        match replay_result? {
Or alternatively, you can move the match out into a function:

```rust
fn is_truncated_wal_error(e: &WalReplayError) -> bool {
    matches!(e, ...)
}
```

and then:

```rust
        match replay_result {
            Ok(v @ Some(_)) => max_sequence = max_sequence.max(v),
            Err(e) if is_truncated_wal_error(e) => todo!(),
            // etc...
```

2023-09-18 12:56 UTC, savage-engineer commented on wal/src/blocking/reader.rs
> +        other.context(UnableToReadDataSnafu)?;
Yes, oops 😅

2023-09-18 14:11 UTC, savage-engineer commented on ingester/src/init/wal_replay.rs
> +        match replay_result? {
Much nicer indeed!

2023-09-19 09:09 UTC, domodwyer commented on ingester/src/init/wal_replay.rs
> +        match replay_result? {
Yeah diff looks nice!

2023-09-19 09:11 UTC, domodwyer approved these changes
You beauty! Very nice 👏

2023-09-19 09:41 UTC, merged