feat: make column sort_key null before we can stop populating it
influxdata/influxdb_iox pull request #8728
Opened 2023-09-13 21:53 UTC by NGA-TRAN

Closes https://github.com/influxdata/influxdb_iox/issues/8726

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2023-09-13 21:53 UTC, NGA-TRAN commented on iox_catalog/migrations/20230913180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ALTER COLUMN sort_key DROP NOT NULL;
I have run this locally

2023-09-14 08:34 UTC, crepererum commented on iox_catalog/migrations/20230913180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ALTER COLUMN sort_key DROP NOT NULL;
Does `iox_catalog` work for NULLs, i.e. shouldn't this be an `Option`?

https://github.com/influxdata/influxdb_iox/blob/82c45a798c4ace2c0f607375e19d17b22147bf1e/data_types/src/partition.rs#L446

BTW: I think we should make

https://github.com/influxdata/influxdb_iox/blob/82c45a798c4ace2c0f607375e19d17b22147bf1e/data_types/src/partition.rs#L473

not an optional anymore because the underlying type cannot be NULL.

2023-09-14 09:43 UTC, domodwyer requested changes
Changing the types like @crepererum suggest will cause the compiler to check everything is correct :rocket:

I think we'll get panics if we deploy this because of the missing `Option` (we've done this before!)

2023-09-14 15:00 UTC, NGA-TRAN commented
I have different plan that is less complicated. Will start a discussion on slack

2023-09-14 16:39 UTC, NGA-TRAN commented
Close this PR because its resins of PRs  will be more complicated than the proposal [here](https://influxdata.slack.com/archives/CRK9M8L5Q/p1694708781255299)

2023-09-15 15:01 UTC, NGA-TRAN commented
Reopen this as it will be step 3 of [this list](https://influxdata.slack.com/archives/CRK9M8L5Q/p1694767426776219?thread_ts=1694708781.255299&cid=CRK9M8L5Q). But it is not ready for review yet

2023-09-21 17:28 UTC, NGA-TRAN commented on iox_catalog/migrations/20230913180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ALTER COLUMN sort_key DROP NOT NULL;
Done in https://github.com/influxdata/influxdb_iox/pull/8750 and https://github.com/influxdata/influxdb_iox/pull/8772

2023-09-22 12:43 UTC, domodwyer commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
Are we saying "we don't care about users that use sqlite"? because this will corrupt their catalogs. I believe it's used by default for all-in-one mode too.

I'm not saying we have to care, just that this is going to break anyone using sqlite catalogs.

2023-09-22 14:42 UTC, NGA-TRAN commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
@domodwyer Look at this 
https://github.com/influxdata/influxdb_iox/blob/main/iox_catalog/sqlite/migrations/20230822081728_sort_key_ids_not_null.sql

We created `sort_key_ids` on July 31, populate data for it and on August 22, we dropped  to and re-created it with not null.

This tells me so far no one cares and it has not broken anything. I remember @alamb told query team one time when things does not work, just remove the binary and rebuild it.

For future tests: Now we know very well sqlite does not support `alter column`, if we want to have tests that support migration and alter columns, we cannot use sqlite.

2023-09-22 15:04 UTC, domodwyer commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
But that ALTER is different - we weren't using that data at that time - we were still dependent on the `sort_key` column instead.

>  I remember @alamb told query team one time when things does not work, just remove the binary and rebuild it.

Si claro, but that's exactly why this is a problem - if they use a later binary, it won't work, because we'll have deleted the sort keys in all partitions that later binaries would use 🤷

2023-09-22 16:11 UTC, NGA-TRAN commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
I have no other solutions now. We can wait until @crepererum come back on Monday and decide how to proceed with this.  I am off Monday so it will work well for al of us.

2023-09-22 20:19 UTC, alamb commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
> Are we saying "we don't care about users that use sqlite"? because this will corrupt their catalogs. I believe it's used by default for all-in-one mode too.
> I'm not saying we have to care, just that this is going to break anyone using sqlite catalogs.

If this PR effectively renders existing sqlite backed catalogs unreadabe, I think that is "fine" in the sense that it has happened before and there is no paying customer who will be affected. 

It seems as if we haven't invested the extra work required to make catalog migrations work for sqlite backed catalogs. While this is inconvenient for all-in-one users, given they aren't customers and our focus is on production / postgres catalogs it seems a reasonable choice to me.

> This tells me so far no one cares and it has not broken anything. I remember @alamb told query team one time when things does not work, just remove the binary and rebuild it.

I believe I suggested deleting all the data and catalog (not the binary) -- eg `rm -rf ~/.influxdb_iox`

2023-09-25 09:32 UTC, domodwyer commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
I don't have strong feelings either way - I just want us to be explicit about the decision we're making here.

If we don't intend to maintain the sqlite catalog state such that it can be relied upon by end users, we should probably leave a comment to that effect in the CLI docs where it is an option :+1:

2023-09-25 10:13 UTC, crepererum commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
To give some context: sqlite is WAY weaker in terms of features compared to postgres, so some migrations are a PITA or close to impossible to write in sqlite. We could just have Rust code for the migrations, but that's additional effort for something that apparently is currently NOT a prod-ready feature but more of a development tool.

2023-09-25 10:13 UTC, crepererum approved these changes

2023-09-25 10:17 UTC, domodwyer approved these changes
I think the end result of this is "sqlite is for development only and not a supported persistent catalog store" and I'll make sure the documentation is updated accordingly :+1:

2023-09-25 10:38 UTC, alamb commented on iox_catalog/sqlite/migrations/20230921180000_set_partition_sort_key_to_null.sql
> +ALTER TABLE partition ADD COLUMN sort_key TEXT[];
I also filed https://github.com/influxdata/influxdb_iox/issues/8826 to track the current known issues with the sqlite catalog so we don't have to rediscover this as part of PRs

2023-09-26 14:09 UTC, NGA-TRAN commented
Thanks everyone. I am going to merge this and observe this behavior

2023-09-26 14:15 UTC, merged