Resolves issue 835 - wrong http code on write path
influxdata/influxdb_iox pull request #936
Opened 2021-03-06 04:57 UTC by mitch292

Closes #835

Sends a 400 for a database that doesn't exist rather than a 500. New to the project, let me know if any changes to the PR are needed!

Describe your proposed changes here.

- [X] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [X] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-03-06 10:36 UTC, e-dard requested changes
Hey @mitch292 thanks so much for the contribution! I can see you have signed the CLA.

I think it would be good to add a test case for this if possible? Let us know if you need help with that.

Finally, your PR title needs to be in the semantic commit format. Take a look at closed PRs for examples of that.

2021-03-13 20:51 UTC, mitch292 commented
Hi just wanted to bump this PR. I added a test and fixed the name of the pr and branch. Let me know if I need to make any other changes!

2021-03-15 09:41 UTC, tustvold commented on src/influxdb_ioxd/http.rs
> +            Self::WritingPoints { .. } => self.bad_request(),
`WritingPoints` is returned for any error writing lines, with this change genuine internal errors will be returned as bad requests.

It should be possible to match on the error within `influxdb_ioxd::http::write` and convert a `server::Error::DatabaseNotFound` into a `influxdb_ioxd::http::ApplicationError::DatabaseNotFound`

2021-03-15 23:41 UTC, mitch292 commented on src/influxdb_ioxd/http.rs
> +            Self::WritingPoints { .. } => self.bad_request(),
Ah of course. Took a stab at this and updated the tests!

2021-03-22 09:56 UTC, e-dard approved these changes
This LGTM now! 👍

2021-03-24 18:13 UTC, carols10cents approved these changes
LGTM too! Thanks!

2021-03-24 18:24 UTC, merged