feat: Add support for setup API to influxdb_client
influxdata/influxdb_iox pull request #998
Opened 2021-03-16 10:55 UTC by aakashhemadri

- Check if database has default user, org, bucket
- Set up initial user, org and bucket
- Set up a new user, org and bucket

- Add examples and test
- Add necessary models

Signed-off-by: Aakash Hemadri <aakashhemadri123@gmail.com>

Added necessary models, largely following the swagger template.
My module management seems off. I am not sure if I can improve it. Pointers on that would be helpful.
Currently my build will spit out missing documentation warnings, I decided to complete that after an intial review, this is mostly in the models/* 

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

2021-03-22 09:43 UTC, e-dard commented
Hey @aakashhemadri thanks for the contribution. We will get some feedback to you this week.

2021-03-22 18:32 UTC, carols10cents requested changes
Looking good! I have a few comments and questions inline, and I also have some overall thoughts. I'd also like @pauldix's opinion on these:

## Module management

The module organization looks ok to me. What about it feels off to you?

## Swagger

Should we be using [`openapi-generator`](https://github.com/OpenAPITools/openapi-generator) to do automated generation of the types and raw API calls, then add a Rustier API on top? I haven't used it before, so I don't know what the Rust code it generates is like.

## Naming

I think the names and signatures of the client functions should be consistent with other clients and consistent with Rust idioms, as much as possible. So currently this PR has:

- `fn setup` that takes no params and returns an `IsOnboarding` on success, to check whether the instance has been set up or not (`GET /setup`)
- `fn setup_init` that takes username/pw/org/etc params and returns an `OnboardingResponse` on success, to perform the initial setup operation (`POST /setup`)
- `fn setup_new` that takes username/pw/org/etc params and returns an `OnboardingResponse` on success, to add subsequent new user/org/buckets (`POST /setup/user`)

Taking a look at the Go, C#, and Java clients, these are called:

| Request | Go | C# | Java |
|---------|----|----|------|
| `GET /setup` | [`GetSetup`](https://github.com/influxdata/influxdb-client-go/blob/a5a90d8ebb66b532f92a909b4f6a9b512f50b831/domain/client.gen.go#L2381-L2388) (autogenerated only) | [`IsOnboardingAllowed` returning `bool`](https://github.com/influxdata/influxdb-client-csharp/blob/847c5bedf23735dafde18bf2483353c5e4f8d975/Client/InfluxDBClient.cs#L435-L440) | [`IsOnboardingAllowed` returning `bool`](https://github.com/influxdata/influxdb-client-java/blob/d495d25fe0b6af6a7a6cbe7b49f26025b310a8f8/client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java#L267-L272) |
| `POST /setup` | [`Setup`](https://github.com/influxdata/influxdb-client-go/blob/a5a90d8ebb66b532f92a909b4f6a9b512f50b831/client.go#L147-L170) | [`Onboarding`](https://github.com/influxdata/influxdb-client-csharp/blob/847c5bedf23735dafde18bf2483353c5e4f8d975/Client/InfluxDBClient.cs#L424-L429) | [`onBoarding`](https://github.com/influxdata/influxdb-client-java/blob/d495d25fe0b6af6a7a6cbe7b49f26025b310a8f8/client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java#L255-L263) |
| `POST /setup/user` | [`PostSetupUser`](https://github.com/influxdata/influxdb-client-go/blob/a5a90d8ebb66b532f92a909b4f6a9b512f50b831/domain/client.gen.go#L2417-L2424) (autogenerated only) | [`PostSetupUser`](https://github.com/influxdata/influxdb-client-csharp/blob/847c5bedf23735dafde18bf2483353c5e4f8d975/Client/InfluxDB.Client.Api/Service/SetupService.cs#L922-L933) (autogenerated only) | [`postSetupUser`](https://github.com/influxdata/influxdb-client-java/blob/d495d25fe0b6af6a7a6cbe7b49f26025b310a8f8/client/src/generated/java/com/influxdb/client/service/SetupService.java#L47-L62) (autogenerated only) | 

So with that in mind, I think: 

- `fn setup` should be renamed to `fn is_onboarding_allowed` that returns a `Result` of `bool`
- `fn setup_init` should be renamed to `fn setup` or `fn onboarding`
- `fn setup_new` should be renamed to `fn setup_user` or `fn post_setup_user`

What do you think?

2021-03-22 18:32 UTC, carols10cents commented on influxdb2_client/src/models/authorization.rs
> +    }
It looks like `Authorization` can derive `Default` and then this could be:

```suggestion
    pub fn new(org_id: String, permissions: Vec<crate::models::Permission>) -> Authorization {
        Authorization {
            org_id,
            permissions,
            ..Default::default()
        }
    }
```

which I think makes it clearer what's being set. This applies to a lot of these types, I think.

2021-03-22 18:32 UTC, carols10cents commented on influxdb2_client/src/models/authorization.rs
> +    pub _self: Option<String>,
I'm used to fields and variables starting with underscore meaning that they're never used. I know `self` can't be used with the raw keyword syntax, but how about `self_` instead?

2021-03-22 18:32 UTC, carols10cents commented on influxdb2_client/src/models/authorization.rs
> +    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
Hm it looks like a lot of these fields have `#[serde(rename = "")` specified on them even when the rename specified is the same as the field name? Why is that?

2021-03-22 18:32 UTC, carols10cents commented on influxdb2_client/src/models/bucket.rs
> +    pub _type: Option<Type>,
For `type` we could use the raw identifier `r#type` syntax.

2021-03-22 18:32 UTC, carols10cents commented on influxdb2_client/src/models/authorization.rs
> +    /// URI of resource.
I'm assuming this is documentation copy-pasted that will get fixed when you're finishing the documentation?

2021-03-22 18:32 UTC, carols10cents commented on influxdb2_client/src/models/onboarding.rs
> +    /// `retentionPeriodSeconds`
Hm so I see this comment now, but I don't see this in the InfluxDB 2.0 API docs? Are those behind as well? Where did this come from?

2021-03-23 03:46 UTC, aakashhemadri commented on influxdb2_client/src/api/setup.rs
> +                let status = response.status();
Oh! I didn't know this was possible, Thanks for the suggestion :)

2021-03-23 03:47 UTC, aakashhemadri commented on influxdb2_client/src/api/setup.rs
> +    async fn setup_init() -> Result {
Sure! I'll make the changes!

2021-03-23 03:48 UTC, aakashhemadri commented on influxdb2_client/src/models/authorization.rs
> +    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
This was largely the openapi-generator code, I didn't put much thought to it -- My bad. I'll fix these instances 👍🏽

2021-03-23 03:50 UTC, aakashhemadri commented on influxdb2_client/src/models/authorization.rs
> +    }
Ah I'll update these 😅

2021-03-23 03:53 UTC, aakashhemadri commented on influxdb2_client/src/models/authorization.rs
> +    pub _self: Option<String>,
Ah yes your suggestion would cause lesser confusion

2021-03-23 03:53 UTC, aakashhemadri commented on influxdb2_client/src/models/authorization.rs
> +    /// URI of resource.
Yep :)

2021-03-23 03:58 UTC, aakashhemadri commented on influxdb2_client/src/models/bucket.rs
> +    pub _type: Option<Type>,
Ah sure! I didn't know we could escape keyword tokens. Thanks for the suggestion :)

2021-03-23 04:01 UTC, aakashhemadri commented on influxdb2_client/src/models/onboarding.rs
> +    /// `retentionPeriodSeconds`
I initially like you only implemented retention_period_hrs. But the openapi-generator spat out models having this as an optional arg, so I decided to add it to the api as well. Not sure what is recommended though.

2021-03-23 04:10 UTC, aakashhemadri commented
I have query @carols10cents warnings spit out #![warn(missing_copy_implementations)] for certain models as specified in src/lib.rs, The question is it always ideal to implement Copy for all instances? Can I blindly implement them if so?

2021-03-23 12:13 UTC, aakashhemadri commented
> * `fn setup` should be renamed to `fn is_onboarding_allowed` that returns a `Result` of `bool`
> * `fn setup_init` should be renamed to `fn setup` or `fn onboarding`
> * `fn setup_new` should be renamed to `fn setup_user` or `fn post_setup_user`
> 
> What do you think?

This seems to be a better choice, most clients follow this.

2021-03-23 12:15 UTC, aakashhemadri commented
> ## Swagger
> Should we be using [`openapi-generator`](https://github.com/OpenAPITools/openapi-generator) to do automated generation of the types and raw API calls, then add a Rustier API on top? I haven't used it before, so I don't know what the Rust code it generates is like.

Honestly the swagger generated code is ugly and seems like a drag if we would ever have to put our hands on it. And it's quite possibly not performant.

2021-03-24 18:15 UTC, carols10cents commented
> I have a query @carols10cents warnings spit out #![warn(missing_copy_implementations)] for certain models as specified in src/lib.rs, The question; is it always ideal to implement Copy for all instances? Can I blindly implement them if so?

I prefer for `Copy` to be implemented if it can be, as long as there isn't a reason not to :)

2021-03-24 19:32 UTC, carols10cents requested changes
Thank you, this is getting closer!!

I chatted with some other folks on the team, and everyone is ok with not using code generated from the swagger directly. But since that's the case, I'm being a bit more picky in my code review of the types you've added that were semi-generated: I think we should clean them up as if a person wrote them :) So there are a few more places to fix! Thank you!

2021-03-24 19:32 UTC, carols10cents commented on influxdb2_client/src/models/resource.rs
> +pub enum Type {
Hm, I wonder if all of the enums added in this PR could be handled with [`#[serde(rename_all = "camelCase")]`](https://serde.rs/container-attrs.html#rename_all) on the `enum` rather than renaming each variant? Could you try that on all the enums and see if it works?

2021-03-24 19:32 UTC, carols10cents commented on influxdb2_client/src/models/bucket.rs
> +    pub labels: Option<Vec<crate::models::Label>>,
So `Option<Vec<T>>` is kind of a rarely used type in Rust because you can just have an empty `Vec`, as long as an empty `Vec` doesn't have a different meaning from `None`. Looking at the swagger definition of `Bucket` and some of the API calls that use `Bucket`, I don't think there is a difference? Do you know of any reason this and other places with `Option<Vec<T>>` couldn't be:

```suggestion
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub labels: Vec<crate::models::Label>,
```

2021-03-24 19:32 UTC, carols10cents commented on influxdb2_client/src/models/authorization.rs
> +    #[serde(rename = "orgID")]
So `orgID` isn't `camelCase`, but it looks like we can specify `#[serde(rename_all = "camelCase")]` on a struct and override that for individual fields like this one ([playground test](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fe4b2d355791b2bbcf9d64fabb184c17)), which would let us eliminate most of the renames on struct field levels? Could you make that change please?

2021-03-25 06:35 UTC, aakashhemadri commented on influxdb2_client/src/models/authorization.rs
> +    }
I didn't know this! Thanks for the suggestion :)

2021-03-25 06:36 UTC, aakashhemadri commented on influxdb2_client/src/models/bucket.rs
> +    #[serde(rename = "write", skip_serializing_if = "Option::is_none")]
Fixed!

2021-03-25 06:37 UTC, aakashhemadri commented on influxdb2_client/src/api/setup.rs
> +                .unwrap()),
I decided to go with #[serde(default)], But I guess either is fine by me. I don't know what the best practice is

2021-03-25 06:38 UTC, aakashhemadri commented on influxdb2_client/src/models/authorization.rs
> +    #[serde(rename = "orgID")]
Done!

2021-03-25 06:43 UTC, aakashhemadri commented on influxdb2_client/src/models/resource.rs
> +            org: None,
The issue here is that `Type` does not let me derive `Default`

2021-03-25 06:45 UTC, aakashhemadri commented on influxdb2_client/src/models/resource.rs
> +            org: None,
Here Type is an enum and cannot derive `Default`

2021-03-25 06:50 UTC, aakashhemadri commented on influxdb2_client/src/models/resource.rs
> +pub enum Type {
Done! and it works :)

2021-03-25 06:54 UTC, aakashhemadri commented on influxdb2_client/src/models/bucket.rs
> +    pub labels: Option<Vec<crate::models::Label>>,
I believe you are right, This looks to me like a better solution

2021-03-25 07:01 UTC, aakashhemadri commented on influxdb2_client/src/models/bucket.rs
> +    pub labels: Option<Vec<crate::models::Label>>,
I have updated all instances of Option<Vec<T>>

2021-03-25 07:02 UTC, aakashhemadri commented
> Thank you, this is getting closer!!
> 
> I chatted with some other folks on the team, and everyone is ok with not using code generated from the swagger directly. But since that's the case, I'm being a bit more picky in my code review of the types you've added that were semi-generated: I think we should clean them up as if a person wrote them :) So there are a few more places to fix! Thank you!

I love your reviews <3 I have learnt a lot from them :)

2021-03-25 14:49 UTC, carols10cents commented on influxdb2_client/src/models/resource.rs
> +            org: None,
Oops I see. 👍🏻

2021-03-25 14:53 UTC, carols10cents commented on influxdb2_client/src/models/onboarding.rs
> +    pub allowed: Option<bool>,
Actually I meant removing the `Option` here and using the default of `false`, so:

```suggestion
    pub allowed: bool,
```

and then we should be able to remove the `unwrap` in influxdb2_client/src/api/setup.rs right?

2021-03-26 04:13 UTC, aakashhemadri commented on influxdb2_client/src/models/onboarding.rs
> +    pub allowed: Option<bool>,
Ah right! I got it now :) Fixed!

2021-03-29 20:24 UTC, carols10cents approved these changes
Looks great now, thank you!!!

I'm currently working on setting up and adding in some integration tests that will run against an actual InfluxDB 2.0 OSS `influxd`; they'll be in `influxdb2_client/tests`. 

So if you end up doing more work on the influxdb2_client, check in there for examples of new kinds of tests to write!

2021-03-29 20:38 UTC, merged

2021-03-30 01:15 UTC, aakashhemadri commented
> Looks great now, thank you!!!
> 
> I'm currently working on setting up and adding in some integration tests that will run against an actual InfluxDB 2.0 OSS `influxd`; they'll be in `influxdb2_client/tests`.
> 
> So if you end up doing more work on the influxdb2_client, check in there for examples of new kinds of tests to write!

Will do! :)